### ISSUE TITLE
Errors in documentation

### ISSUE THREAD

**Issue by michaellaier** [pymor/pymor#101]
The 'Getting Started' chapter states that the parameter training set of the thermalblock demo will have the size (XBLOCKS x YBLOCKS)^SNAPSHOTS.
I think that should be SNAPSHOTS^(XBLOCKS * YBLOCKS) as in the documentation for the demo.

**Comment by sdrave** [comment]
Fixed in 0e3535a2765b1fff96b28c0c5cfb55fc10d2dec0.
