### ISSUE TITLE
Numpy master CI job failing

### ISSUE THREAD

**Issue by renefritze** [pymor/pymor#1010]
Apparently they've bumped their minimal cython to `0.29.11`. Since that's not what's in our pypi mirrors, the tests against numpy git currently fail. 
Our minimal cython as of now is `0.28`, so I see no reason against just matching the bumped requirement. Also considering that we get it implicitly anyhow with the next numpy release.

**Comment by sdrave** [comment]
Duplicate of #1011.

**Comment by renefritze** [comment]
Hah. Didn't even notice this posted twice during Github's outage this morning.
