### ISSUE TITLE
Numpy git CI failing

### ISSUE THREAD

**Issue by renefritze** [pymor/pymor#1011]
Apparently they've bumped their minimal cython to `0.29.11`. Since that's not what's in our pypi mirrors, the tests against numpy git currently fail. 
Our minimal cython as of now is `0.28`, so I see no reason against just matching the bumped requirement. Also considering that we get it implicitly anyhow with the next numpy release.

**Comment by sdrave** [comment]
@renefritze, where did you see a cython-related build failure? See #1012.

**Comment by renefritze** [comment]
> @renefritze, where did you see a cython-related build failure? See #1012.

Your own PR for example: https://zivgitlab.uni-muenster.de/pymor/pymor/-/jobs/368402

**Comment by sdrave** [comment]
Ok, so seems like we are facing two separate issues. Regarding the Cython version: buster ships 0.29.2 and there is no backport. So I would prefer to not hard depend on the newer version.

**Comment by renefritze** [comment]
I'm not convinced this policy is actually needed for a pure python package other than pip itself. 

Are you considering that a user might do a (super-user) system-wide install of pyMOR which installs a newer cython version which other debian packages then conflict against?

**Comment by renefritze** [comment]
[Sidenote](https://github.com/numpy/numpy/commit/fc9d862f0cec6d9dc83acef54a66732dfdb813a3)

**Comment by sdrave** [comment]
> Are you considering that a user might do a (super-user) system-wide install of pyMOR which installs a newer cython version which other debian packages then conflict against?

You never know what people are doing. One potential scenario would be that they have FEniCS somehow globally installed. I don't even know what will happen in a venv with system site-packages when you try to install a newer Cython. 

What speaks against installing a newer Cython in the numpy git builds, and changing the Cython minimal version only when we bump numpy?

**Comment by renefritze** [comment]
> You never know what people are doing.

That's not a good argument for anything if you ask me. 


> What speaks against installing a newer Cython in the numpy git builds

We do not do this ever and I really do not want to start now. 

I can additionally put the required cython version in the pypi mirror though. I'll push commit to #1012 when that's done.

**Comment by sdrave** [comment]
> I can additionally put the required cython version in the pypi mirror though.

This is probably what I meant ..

**Comment by sdrave** [comment]
Fixed in #1012.
