### ISSUE TITLE
Better default tolerances for method of snapshots?

### ISSUE THREAD

**Issue by sdrave** [pymor/pymor#1014]
See discussion in #1012.

@lbalicki, as I understand https://www.netlib.org/lapack/lug/node89.html, then every EV smaller than the largest eigenvalue times machine precision should be considered as potentially zero. Everything else should be guaranteed to be a non-zero EV. So maybe it would make sense to throw everything away below that threshold (or a fixed constant times this threshold) and trust that the corresponding eigenvectors are at least not linearly dependent?

**Comment by lbalicki** [comment]
> So maybe it would make sense to throw everything away below that threshold (or a fixed constant times this threshold) and trust that the corresponding eigenvectors are at least not linearly dependent?

I think that sounds like a good idea. However, I am not sure whether we should use a fixed constant or a value that depends on the dimensions of the input matrix  (I think @pmli suggested something like that in #1012). The error bound presented in https://www.netlib.org/lapack/lug/node90.html has this p(n) value, which indicates that it might be a good idea to consider the matrix dimensions. So maybe we could consider all eigenvalues to be zero if they are smaller than "largest EV * machine precision * matrix size"?

**Comment by pmli** [comment]
Thanks @lbalicki for the link. Somehow, I still can't find the result about p(n) in the referenced Parlett's book... But, regardless of the choice of the tolerances, I think it should be guaranteed that `pod` will not return more than `min(A.dim, len(A))` modes.

Just to show that the error does grow with the problem size:

```python
import numpy as np
import scipy.linalg as spla
import matplotlib.pyplot as plt

n_list = np.round(np.logspace(2, 4, 50)).astype(int)
ratios = []
for n in n_list:
    print(n)
    x = np.ones((n, 1))
    e = spla.eigvalsh(x @ x.T)
    ratios.append(e[-2] / e[-1])
bounds = n_list * np.finfo(np.float_).eps

fig, ax = plt.subplots()
ax.loglog(n_list, ratios, '.-', label=r'$\frac{\lambda_2}{\lambda_1}$')
ax.loglog(n_list, bounds, label=r'$n \epsilon$')
ax.set_xlabel('$n$')
ax.legend()
ax.grid()
fig.savefig('plot.png')
plt.show()
```
![plot](https://user-images.githubusercontent.com/1268421/87679079-0a3f1580-c77c-11ea-892d-68e011557bc0.png)

**Comment by renefritze** [comment]
Btw, we can also get rid of the `turbo=True` arg for the `eigh` call while we're at it I think. It's deprecated and only applies to generalized problems. Reads pretty cool though.

**Comment by sdrave** [comment]
Overall, I would vote for keeping the current default of `atol=0` and `rtol=1e-7` (corresponding to 1e-14 in the plot above) for the following reasons:

- The bound proposed in @pmli's experiment is quite pessimistic. (It overestimates by up to two orders of magnitude. Using this bound might lead to the truncation of singular vectors one might actually be interested in.)
- n in the experiment would be the size of the input `VectorArray` which should never be larger than 1e4 and usually is below 1e3. So at least for the tested matrices, the current rtol would be about fine. In view of the experiment, I could also live raising it a bit more to 2e-7, say, but I'm not sure if this is needed.
- A sharper p(n) is unknown to us.
- We cannot have a dependence on n without either changing the meaning of `rtol` or adding some additional parameter.

Other opinions, @pymor/all?

**Comment by pmli** [comment]
Please correct me if I'm wrong, but from what I remember, the issue is in `method_of_snapshots` that could return more modes than `A.dim` when `A.dim < len(A)`. Then, the solution would be to make sure that the number of returned modes is less than `min(A.dim, len(A))`, independent of the tolerances, right?

**Comment by sdrave** [comment]
> Please correct me if I'm wrong, but from what I remember, the issue is in `method_of_snapshots` that could return more modes than `A.dim` when `A.dim < len(A)`. Then, the solution would be to make sure that the number of returned modes is less than `min(A.dim, len(A))`, independent of the tolerances, right?

I'm not sure. This happens only if `atol`/`rtol` are so small that numerical garbage is included in the result. Your proposed change would remove that garbage in some cases where it might lead to subsequent failures, but it does not really resolve the underlying issue of choosing the right tolerances to not include data below the actual (unknown) numerical accuracy. I think I would prefer to not add some quirks which give the user the impression of an always working algorithm and leave it as their responsibility to choose the right tolerance. Also, our numerical evidence suggests that the current `rtol` (or maybe `2e-7`) should be good enough for most cases. Already with `1e-7` we haven't seen any more test failures.

However, if you are strongly convinced that this is the better options, I would be willing to add your suggested change, @pmli.

**Comment by pmli** [comment]
Ok, I see your point. Still, I don't think that just increasing `atol` or `rtol` would fix the issue. As the plot above would suggest, the error tends to grow linearly with the problem size, so for a big enough problem, `1e-7` or `2e-7` would not be high enough.

Another approach would be to change the meaning of `rtol` to what [`numpy.linalg.matrix_rank`](https://numpy.org/doc/stable/reference/generated/numpy.linalg.matrix_rank.html) uses, where `tol` depends on matrix size by default. What do you think about this?

**Comment by sdrave** [comment]
> Ok, I see your point. Still, I don't think that just increasing `atol` or `rtol` would fix the issue. As the plot above would suggest, the error tends to grow linearly with the problem size, so for a big enough problem, `1e-7` or `2e-7` would not be high enough.

As I said above, the problem size should not grow arbitrarily large. We are computing there SVDs for `VectorArrays` and the problem size equals the array length. VectorArrays are not designed to grow arbitrarily large.

> Another approach would be to change the meaning of `rtol` to what [`numpy.linalg.matrix_rank`](https://numpy.org/doc/stable/reference/generated/numpy.linalg.matrix_rank.html) uses, where `tol` depends on matrix size by default. What do you think about this?

I don't think it is a good idea to use some formula for which we don't have theoretical justification. Also, if I want to compute POD, I don't want to prescribe a relative tolerance that implicitly depends on the number input vectors.

**Comment by pmli** [comment]
> As I said above, the problem size should not grow arbitrarily large. We are computing there SVDs for `VectorArrays` and the problem size equals the array length. VectorArrays are not designed to grow arbitrarily large.

Ah, right. Now I'm wondering why we only looked at the symmetric eigenvalue problem and ignored the Gramian computation. Anyway, it looks like the error can also depend on the dimension of the vectors:

```python
import numpy as np
import scipy.linalg as spla
import matplotlib.pyplot as plt

d_list = np.round(np.logspace(2, 6, 50)).astype(int)
n = 100
ratios = []
for d in d_list:
    print(d)
    vec_arr = np.ones((d, n)) * np.logspace(-5, 0, n)[::-1]
    gramian = vec_arr.T @ vec_arr
    e = spla.eigvalsh(gramian)
    ratios.append(e[-2] / e[-1])
bounds = d_list * np.finfo(np.float_).eps

fig, ax = plt.subplots()
ax.loglog(d_list, ratios, '.-', label=r'$\frac{\lambda_2}{\lambda_1}$')
ax.loglog(d_list, bounds, label=r'$d \epsilon$')
ax.set_xlabel('$d$')
ax.legend()
ax.grid()
fig.savefig('plot.png')
plt.show()
```

![plot](https://user-images.githubusercontent.com/1268421/99410793-29e57680-28f3-11eb-8c64-c73038bfecdf.png)

**Comment by sdrave** [comment]
> Now I'm wondering why we only looked at the symmetric eigenvalue problem and ignored the Gramian computation.

Right. I guess it's not very surprising that the error depends on the dimension of the array in that way. Anyway, I still don't see a reasonable way to let the tolerance depend on the array dimension. In particular from your last plot, it's not even clear what the right bound should be.

What about raising an error when the number of computed modes is larger than the VA dimension or/and the length of the array? The error message could say something meaningful about too-low tolerances.

**Comment by pmli** [comment]
> What about raising an error when the number of computed modes is larger than the VA dimension or/and the length of the array? The error message could say something meaningful about too-low tolerances.

I'm not sure. At least in that situation, it's clear that the smallest nonzero singular values are just a numerical artifact and can be discarded.

**Comment by sdrave** [comment]
Yes that much is clear. It is also clear that the algorithm wasn't numerically accurate for the specified tolerances and that probably some of the non-truncated modes will contain garbage. So as we know that, we should let the user know that we can't seem to deliver what they asked for.

As a compromise: How about removing the modes and logging a warning?

**Comment by pmli** [comment]
Ok, that's fine with me.
