### ISSUE TITLE
Add automatic "try-on-binder" links in tutorials

### ISSUE THREAD

**Issue by renefritze** [pymor/pymor#1035]

**Comment by sdrave** [comment]
We missed this untagged issue at the last dev meeting. Is is realistic to have that for the next release? Would be very nice ..

**Comment by renefritze** [comment]
The TODO here is basically two parts:
 1. Sphinx code to inject the right link badge into tutorials. The right link has the branch/tag name and the notebook filename.
 1. The generated notebooks need to be deployed into a git repo with binder infra.

Maybe somebody wants to help with the first bit? I already have a lot on my plate.

**Comment by renefritze** [comment]
Ping @pymor/all

**Comment by renefritze** [comment]
No takers @pymor/all ?
