### ISSUE TITLE
Estimate the model error without having to care for the reduced solution U

### ISSUE THREAD

**Issue by TiKeil** [pymor/pymor#1042]
I would like to discuss whether it makes sense to enable to call the `Model.estimate_error` function only for a certain `mu` while hiding the need to have `U`. 

Sometimes, when I am only interested in the error of a certain `mu`, I have to do `rom.estimate_error(rom.solve(mu), mu)` where `U = rom.solve(mu)`. In this case, computing `U` could easily be hidden in the `estimate` function in case `U` has not been computed before. Despite the fact that I find the current way very counterintuitive, I also have two problems with it
  
1. The `error_estimator` of the model (at least in my cases) always requires that `U = rom.solve(mu)`. Do you have any example where these `U` and `mu` are not related at all and where one would rather have `rom.estimate(V, mu)` for any `V`? If not, Isn't there currently a high risk that the user puts the wrong U into the function? 
2. In case a dual solution `P` is needed for an estimate (which we want to have for an `estimate_output` in #575), the user also has to care for computing the dual solution although he only needs to have it for the estimation and for nothing else. If, for some reason, we would go for `P` being computed inside the `estimate_output` function instead, I find this a little bit inconsistent with the current state.

If the user does not want to care for `U` at all, I would like to implement the possibility to omit `U` in the `estimate_error` function, which probably results in having to change the arguments of the function such that we have

```
def estimate_error(mu=None, U=None):
     [...]
     U = self.solve(mu) if U is None
     [...]
```

Do you have any thoughts why this is a bad idea or what I have missed? 

I also want to emphasize that not only the dual case in 2. made me think about this.

**Comment by sdrave** [comment]
As discussed with @TiKeil offline, I think we should think about the right signature for `estimate` in general. Maybe at the next dev meeting?

**Comment by TiKeil** [comment]
In an offline discussion @sdrave and me figured out that it is probably a good idea to remove the `U` argument from the `estimate_error(U, mu)` function entirely and only have one argument `mu` instead. 

One drawback of this would be that there might happen a computational overlap. For instance, if the user first calls the standard `solve(mu)` method  to get the solution and then calls the `estimate_error(mu)` function would result in two identical `rom` solves for the same `mu`. Of course, with `enable_caching` this would not be a problem.   

While discussion this we thought that it would be good to have `return_error_estimate` argument for the `solve` method, similar to the `return_output` argument. This would not require caching for only having to perform one solve. 
For the best way of implementing these return arguments, I open a separate issue because it is not directly related to this issue. 

To conclude: We

- remove `U` from `estimate_error(U, mu)` and solve for `U` internally by calling `estimate_error(mu)` 
- add a `return_error_estimate` to `Model.solve(...)` for avoiding computational overlap of `solve()`

Any objections for this?

**Comment by sdrave** [comment]
See #1095, #1113.
