### ISSUE TITLE
pytest config warning about unknown config ini key

### ISSUE THREAD

**Issue by pmli** [pymor/pymor#1048]
When running `pytest` recently, I got `PytestConfigWarning: Unknown config ini key: python_class` in the warnings summary.

I guess the issue is in https://github.com/pymor/pymor/blob/6e283d03b413db5bb58e6d67ef467456d3a2bbf2/setup.cfg#L45

From the [documentation](https://docs.pytest.org/en/stable/reference.html#confval-python_classes), it seems it should be renamed to `python_classes`. Removing it might also be fine.

**Comment by renefritze** [comment]
Are you using pytest >= 6 already? I've never noticed this warning. I'd prefer changing the name rather than removing the option, since while we currently (AFAICR) have no class based tests, somebody might want to and should then not have to think about why her tests don't get picked up.

**Comment by pmli** [comment]
> Are you using pytest >= 6 already? I've never noticed this warning.

Right, I recently updated all the packages.

> I'd prefer changing the name rather than removing the option, since while we currently (AFAICR) have no class based tests, somebody might want to and should then not have to think about why her tests don't get picked up.

Ok, sounds good to me.
