### ISSUE TITLE
scipy.linalg.solve is slower than numpy.linalg.solve

### ISSUE THREAD

**Issue by pmli** [pymor/pymor#1052]
When running the following code (which uses [perfplot](https://github.com/nschloe/perfplot))

```python
import numpy as np
import numpy.linalg as npla
import scipy.linalg as spla
import perfplot

# setup
n = 5000
rng = np.random.RandomState(0)
A = rng.standard_normal((n, n))

# benchmarking
out = perfplot.bench(
    setup=np.random.rand,
    kernels=[
        lambda b: npla.solve(A[:len(b), :len(b)], b),
        lambda b: spla.solve(A[:len(b), :len(b)], b),
        lambda b: spla.solve(A[:len(b), :len(b)], b, check_finite=False),
    ],
    labels=['NumPy', 'SciPy', 'SciPy w/o check'],
    n_range=np.round(np.geomspace(1, n, 50)).astype(int),
    xlabel='Problem size',
)

# plotting
plot_opts = dict(logx=True, relative_to=0)
out.save('numpy_vs_scipy.png', bbox_inches='tight', transparent=False, **plot_opts)
out.show(**plot_opts)

```

if NumPy and SciPy are installed via wheel (`pip install numpy scipy`), I get

![numpy_vs_scipy_wheel](https://user-images.githubusercontent.com/1268421/89648318-584cc200-d8bf-11ea-96f1-3844e9d59b45.png)

and if NumPy and SciPy are installed from source (`pip install --no-binary :all: numpy scipy`), I get

![numpy_vs_scipy_source](https://user-images.githubusercontent.com/1268421/89648423-77e3ea80-d8bf-11ea-92c7-34962b978e44.png)

I'm not sure how to interpret these results. Do others get similar figures?

I guess we could set `check_finite=False` which would speed up `scipy.linalg.solve` for very small problems and recommend installing NumPy and SciPy from source in general.

**Comment by lbalicki** [comment]
For me the results are similar, especially i also get the result that Scipy without the check is much faster than the regular Scipy solve. However, in my results i could not see a significant difference between the figures when installing via `pip install --no-binary :all: numpy scipy`  and `pip install numpy scipy`.

> I guess we could set check_finite=False which would speed up scipy.linalg.solve for very small problems and recommend installing NumPy and SciPy from source in general.

Regarding the recommendation to install NumPy and SciPy from source in general: What are the absolute timings that you get on these benchmarks?

**Comment by pmli** [comment]
Ok, it looks like the issue was not that SciPy got better when installing from source, but that NumPy got worse :confused: I guess there is an issue with my BLAS...

![comparison_wheel_source](https://user-images.githubusercontent.com/1268421/89663108-57268f80-d8d5-11ea-8ca2-3305919121dd.png)

**Comment by sdrave** [comment]
The change from numpy to scipy was introduced due to #417. If we also want the NumPy-Version for performance reasons, we might consider adding corresponding `solver_options` to support both. In general I would prefer the more robust method over the faster one ..

**Comment by pmli** [comment]
[numpy.linalg.solve](https://github.com/numpy/numpy/blob/67c7066353534eeac8054f0deb75dc5923c6dc20/numpy/linalg/umath_linalg.c.src#L1559) uses [`_gesv`](http://www.netlib.org/lapack/explore-html/d7/d3b/group__double_g_esolve_ga5ee879032a8365897c3ba91e3dc8d512.html#ga5ee879032a8365897c3ba91e3dc8d512), while [scipy.linalg.solve](https://github.com/scipy/scipy/blob/7dd0cd0365b2eda4484efed798000309e7649c77/scipy/linalg/basic.py#L209-L218) directly uses `_getrf` and `_getrs` for LU decomposition and triangular solves, and additionally `_gecon` to estimate the condition number from the LU decomposition. So, as far as I see, SciPy uses the same algorithm and adds some checks.

Adding support for both through `solver_options` sounds good to me.

**Comment by sdrave** [comment]
We didn't discuss this issue at yesterday's dev meeting. I will tag it for next year's release.

**Comment by renefritze** [comment]
Lets recheck for the release @pymor/main

**Comment by pmli** [comment]
I ran it again, but without the `relative_to` part (and on a different computer):

- wheels (`pip install numpy scipy`):
![numpy_vs_scipy_wheel](https://user-images.githubusercontent.com/1268421/133687019-5d92625b-579e-405b-9ac8-bbeebb1da0b5.png)
- source (`pip install --no-binary :all: numpy scipy`):
![numpy_vs_scipy_binary](https://user-images.githubusercontent.com/1268421/133687039-49e96a84-b242-417e-b061-b877f2bced20.png)

As before, the major difference is that NumPy gets slower when installed from source.

**Comment by sdrave** [comment]
On my machine I also see a factor of 1.5 to 2 for dimensions between 10 and 100. Since we solve many equations systems of this size in the ROMs, it seems like a good idea to be able to use numpy. However, time is running out for 2021.1, so I set the milestone to 2021.2.

**Comment by ilayn** [comment]
I ended up here by accident but happy to be here. Always nice to have direct users of things that are on the roadmap. You are right that to inject condition number warnings ala matlab we had to separate gesv calls to factorization and solve steps. So that created a bit of overhead. But when and if https://github.com/scipy/scipy/pull/12824 is done it will hopefully be faster than NumPy conclusively and will detect structure just backslash  way. But we are trying our best to fix certain plumbing to get there. 

In the meantime, we introduced, issymmetric, ishermitian, and bandwidth to scipy.linalg namespace for detection of structure. Hope that will also save some cpu cycles for you. 

Just wanted to ping this issue, so that I don't forget to ask for feedback 😃, cheers.

**Comment by pmli** [comment]
Hi @ilayn, thank you for the comment. It's good to see you here.

> But when and if [scipy/scipy#12824](https://github.com/scipy/scipy/pull/12824) is done it will hopefully be faster than NumPy conclusively and will detect structure just backslash way.

Indeed, this would help a lot and would close this issue.
It would be interesting for `lu_factor` to also have a condition number check, but that is a separate issue (#1603).

> In the meantime, we introduced, issymmetric, ishermitian, and bandwidth to scipy.linalg namespace for detection of structure. Hope that will also save some cpu cycles for you.

It is a bit tricky because of the Python and SciPy versions that pyMOR currently supports, but could be of interest to have (I'm not sure how often we have symmetric/Hermitian matrices).

**Comment by pmli** [comment]
I tried now also using `lu_factor` and `lu_solve`, and it seems that makes the difference.

![numpy_vs_scipy_wheel](https://github.com/pymor/pymor/assets/1268421/94016d27-a0c6-481f-8a58-48b9f524610b)

Here is the code (which was run with wheels and `OMP_NUM_THREADS=1`).

```python
import numpy as np
import numpy.linalg as npla
import scipy.linalg as spla
import perfplot

# setup
n = 5000
rng = np.random.RandomState(0)
A = rng.standard_normal((n, n))

# benchmarking
out = perfplot.bench(
    setup=np.random.rand,
    kernels=[
        lambda b: npla.solve(A[: len(b), : len(b)], b),
        lambda b: spla.solve(A[: len(b), : len(b)], b),
        lambda b: spla.solve(A[: len(b), : len(b)], b, check_finite=False),
        lambda b: spla.lu_solve(
            spla.lu_factor(A[: len(b), : len(b)], check_finite=False),
            b,
            check_finite=False,
        ),
    ],
    labels=[
        'NumPy',
        'SciPy',
        'SciPy no check_finite',
        'SciPy LU + no check_finite',
    ],
    n_range=np.unique(np.round(np.geomspace(1, n, 50)).astype(int)),
    xlabel='Problem size',
)

# plotting
plot_opts = dict(logx=True, logy=True)
out.save('numpy_vs_scipy.png', **plot_opts)
out.show(**plot_opts)
```

**Comment by pmli** [comment]
Here are also timings relative to NumPy.

![numpy_vs_scipy_rel](https://github.com/pymor/pymor/assets/1268421/b1beae8d-ed35-40bc-9cd8-40a56febf78b)

Updated plotting code:

```python
plot_opts = dict(logx=True)
out.save('numpy_vs_scipy_abs.png', **plot_opts)
out.save('numpy_vs_scipy_rel.png', relative_to=0, **plot_opts)
out.show(**plot_opts)
```
