### ISSUE TITLE
Mu.with_ method allows for changing the parameter type

### ISSUE THREAD

**Issue by TiKeil** [pymor/pymor#1058]
Let's say, I have a `Mu` instance `mu={ 'a': 0}`, which I want to change. Then, the `with_` method allows me to construct a completely different `Mu`, e.g. calling `mu.with_(a=[0,1])`. In my opinion, this is a little bit dangerous if this happens accidentally. I would rather expect that I can not construct a completely new `Mu` from `mu` or at least get a warning that I messed up the old `Mu` instance. 

What do you think ?

**Comment by HenKlei** [comment]
Just for my understanding: When would you expect the `with_` method to give a warning or so? I mean whenever you use `with_`, you add a new key to the dict or you change an existing one, right? The first should be fine without any warning I think. Changing the value of an existing key for instance occurs in different [time stepping algorithms](https://github.com/pymor/pymor/blob/2905801b89726dd7df4142d029476d3555ee7921/src/pymor/algorithms/timestepping.py#L168). Or do you have a different situation in mind?

**Comment by TiKeil** [comment]
Adding a key is fine, you are right.
My concern is about changing the shape of a key, like in the example above. Is that also the case in time stepping algorithms?

**Comment by HenKlei** [comment]
No, you are right, changing the shape might be problematic. That's also how I read your issue. Maybe this should indeed produce some sort of warning.

**Comment by sdrave** [comment]
> or at least get a warning that I messed up the old `Mu` instance.

What do you mean by that? `with_` never should modify the state of the original instance ...

Note that `InstationaryModel._solve` already uses `mu = mu.with_(t=0.)` where `t` might not be a key in the original dict, so adding a key really should not cause a warning. (It could still be a source of bugs, when there is a typo in the name of the parameter.)

Regarding changing the shape, I am fine with a warning. However, did you really have a case, where this would have saved you from a bug, @TiKeil?

**Comment by renefritze** [comment]
Please recheck if can be closed @TiKeil
