### ISSUE TITLE
pytest unknown config ini keys pep8ignore and pep8maxlinelength

### ISSUE THREAD

**Issue by pmli** [pymor/pymor#1061]
This is similar to #1048, but for some reason didn't show up before. It's visible when running, e.g., `pytest -h`.

I've been looking a bit at the [documentation](https://docs.pytest.org/en/stable/customize.html), which says that using `setup.cfg` is not recommended.

**Comment by renefritze** [comment]
Well, that recommendation has always been qualified, and up till release 6 of pytest  there was no alternative that didn't involve yet another file in the source tree. I'd be fine with moving to pyproject.toml, but really, there's no need for us.

**Comment by pmli** [comment]
It looks like the issue comes up with `pytest` 6.0 when `pytest-pep8` is not installed. The warning doesn't show up with `pytest` 6.1.

It might be interesting to set the [`required_plugins`](https://docs.pytest.org/en/stable/reference.html#confval-required_plugins) option. Otherwise, I guess this issue can be closed.

**Comment by renefritze** [comment]
Setting required plugins has little value for CI. And besides hypothesis, there's currently no plugin actually _required_ to run tests I think?

If the warnings are indeed gone with 6.1, I think we can just close this

**Comment by pmli** [comment]
Yeah, I guess nothing is required. I'm also not sure if `hypothesis` is considered a `pytest` plugin. Anyway, I'll close this.
