### ISSUE TITLE
Parameters.zeros() method?

### ISSUE THREAD

**Issue by TiKeil** [pymor/pymor#1062]
In some of my user code, I do not know the exact shape of a `Mu` which I want to construct as a starting point. 
By having access to `Model.parameters` I can just construct a zero `Mu` instance by calling 

```
mu_with_zeros = fom.parameters.parse( np.zeros(fom.parameters.dim) )   
``` 

Would it be interesting to wrap this code into a `Parameters.zeros()` method?

**Comment by sdrave** [comment]
> Would it be interesting to wrap this code into a `Parameters.zeros()` method?

I'm not convinced that this is useful in many cases. If you add this method, you probably also want `ones` or `full`. Could you give some example where you use this?

**Comment by sdrave** [comment]
I'm still not convinced, and nobody commented since august, so I will close the issue for now. Feel free to re-open it when you have anything more to say.
