### ISSUE TITLE
LTIModel.__sub__ and H2 error issues

### ISSUE THREAD

**Issue by pmli** [pymor/pymor#1063]
In the beginning, `LTIModel.__sub__` only relied on `__add__` and `__neg__`. I then changed it to check if the `D` operators are identical ([link](https://github.com/pymor/pymor/blob/ba3e62c93c29c291e9d4f8bc12b4f7130d6e8a7c/src/pymor/models/iosys.py#L482-L485)), assuming that comparison using `==` could be expensive and motivated by H2 error computation (if `D` is nonzero, H2 norm is infinite/undefined). The issue is that the identity comparison `self.D is other.D` does not work for [`TFBHIReductor`](https://github.com/pymor/pymor/blob/ba3e62c93c29c291e9d4f8bc12b4f7130d6e8a7c/src/pymor/reductors/interpolation.py#L421) (or any other data-driven reductor) which builds a new `D` operator. For this reason, [`LTIModel.h2_norm`](https://github.com/pymor/pymor/blob/ba3e62c93c29c291e9d4f8bc12b4f7130d6e8a7c/src/pymor/models/iosys.py#L753) actually does not check that `D` is zero, which also might be expensive.

Are there any opinions about this? Should `__sub__` be simpler and `h2_norm` just assume `D` is zero? Or should `h2_norm` be more strict?

**Comment by sdrave** [comment]
How about checking

```python
self.D.as_range_array(mu).norm()
```

for being close to zero in `h2_norm`? That should be relatively cheap. (`==` won't work, will be the same as using `is`).

**Comment by sdrave** [comment]
@pmli, do you plan to work on this in the foreseeable future?

**Comment by pmli** [comment]
I would be for making `__sub__` depend only on `__add__` and `__neg__`, and it should not take much time.

It is a bit more tricky checking if a floating-point number such as `self.D.as_range_array(mu).norm()` is close to zero. How about logging a warning if it is not exactly zero?

**Comment by sdrave** [comment]
Sounds reasonable. Do you want to do it for the next release?

**Comment by pmli** [comment]
Ok. I would go for the next release.
