### ISSUE TITLE
jupyter-sphinx build failures cause rebuild of entire documentation

### ISSUE THREAD

**Issue by sdrave** [pymor/pymor#1083]
If the docs build process fails due to an exception in a `jupyter-execute` cell, the entire documentation is rebuilt the next time sphinx runs.

This is super annoying when working on a tutorial document. For instance, a normal run of `sphinx-build` after changing the tutorial I am currently working on takes 59s on my machine. The entire documentation takes 394s. This is way to long to still have a decent editing experience.

I tried to specify the source file that is supposed to be built by manually invoking `sphinx-build` (you can provide a list of these files as optional arguments), but still the entire documentation was built.

In any case, more unnecessary stuff happens. In particular, with every`sphinx-build` invocation the entire source code is highlighted even though no source code changes have been made.

**Comment by HenKlei** [comment]
Updating `jupyter-sphinx` to at least version v0.2.4 seems to solve the problem, according to [this comment](https://github.com/jupyter/jupyter-sphinx/issues/31#issuecomment-624889284). On my machine, `make docs` is much faster after the update.

**Comment by sdrave** [comment]
@HenKlei, I can't confirm that with the newest available sphinx (3.2.1) and jupyter-sphinx (0.3.2) I observe the following: After a successful `make docs` on current master, changing some text in `tutorial_bt.rst` will only rebuild this file, which will take around 95 seconds on my machine. If I introduce an error in one of the code cells, calling `make docs` and after that fixing the error again, a new `make docs` will take around 500 seconds. Can you check again? What do the others, @pymor/all experience?

**Comment by sdrave** [comment]
Ah, @pymor/all does not include all @pymor/pymor-devs devs yet, so i mention them again ...

**Comment by HenKlei** [comment]
Actually, I did not check what happens after fixing an error in a code cell. The speed up in building the docs was just a general impression I had after updating `jupyter-sphinx`.

**Comment by renefritze** [comment]
Current version of jupyter-sphinx is now `0.3.2` maybe you guys want to revisit this issue.

**Comment by HenKlei** [comment]
> Current version of jupyter-sphinx is now `0.3.2` maybe you guys want to revisit this issue.

Isn't that the version @sdrave is also referring to above?

**Comment by renefritze** [comment]
Oh, sorry, must've skipped over that after reading the version in your post.
