### ISSUE TITLE
split pymor package into pymor and pymordiscretizations?

### ISSUE THREAD

**Issue by sdrave** [pymor/pymor#109]

**Comment by sdrave** [comment]
Maybe pymormodels would be a nicer name.

**Comment by ftalbrecht** [comment]
pyMOR developer meeting: move everything out to a separate package, including analytical problems, domaindiscretizers, etc...

**Comment by sdrave** [comment]
Given the large changes that already went into 0.5, I would say we postpone this to 0.6 ..

**Comment by sdrave** [comment]
Superseded by  #847.
