### ISSUE TITLE
meshio 4

### ISSUE THREAD

**Issue by gdmcbain** [pymor/pymor#1092]
I notice that meshio #793 is pinned at [3.3.1](https://github.com/nschloe/meshio/releases/tag/3.3.1)

https://github.com/pymor/pymor/blob/4fc3893a3746da584aa006db24f9ec210f366cba/dependencies.py#L34

I was looking writing bindings for [scikit-fem](https://github.com/kinnala/scikit-fem) but it uses the [latest](https://github.com/nschloe/meshio/releases/latest), currently [4.2.0](https://github.com/nschloe/meshio/releases/tag/v4.2.0) so I can't easily install scikit-fem and pyMOR in the same env.   There were a number of backwardly incompatible changes introduced into meshio 4, so I don't think scikit-fem will work with meshio 3.3.1.

Would there be interest in a pull request to update pyMOR to meshio 4.2.0?  Are there particular reasons for sticking at 3.3.1?

**Comment by sdrave** [comment]
Hi @gdmcbain, I think there is no particular reason for pinning meshio to this particular version. We probably don't won't to support multiple versions, but I see no reason to not update to recent meshio. @renefritze might want to say something about this, but he's on vacation until next week.

> I was looking writing bindings for scikit-fem but it uses the latest, currently 4.2.0 so I can't easily install scikit-fem and pyMOR in the same env. There were a number of backwardly incompatible changes introduced into meshio 4, so I don't think scikit-fem will work with meshio 3.3.1.

scikit-fem looks very interesting! As you might have guessed from the package layout, our long-term goal is to have discretizers for different PDE backends based on the same problem definitions in pyMOR. While there are still open questions how to do this for FEniCS or NGSolve, in particular regarding the representation of coefficient functions, scikit-fem looks like it could be used as a drop-in replacement for most of our own discretization toolkit. Since we do not really have the time to work on this toolkit, adding official scikit-fem support to pyMOR would be very attractive. Maybe we can discuss this further after the pyMOR course?

**Comment by TiKeil** [comment]
I use gmsh file parsing quite a lot and for me, there is no particular reason to stay at 3.3.1. Updating to 4 would be quite nice.

**Comment by gdmcbain** [comment]
> Maybe we can discuss this further after the pyMOR course?

Let's.  I'll continue looking into writing the bindings on top of #1093 (which turned out to be small).

**Comment by ftalbrecht** [comment]
We (dune-gdt) are currently bound to gmsh 2 , since dune-grid can only handle old gmsh files. Not sure what this means for `meshio`, we currently use `meshio==3.3.1`. I will look into this ...

**Comment by gdmcbain** [comment]
Current meshio reads Gmsh's legacy MSH 2 format O. K.; there's no intention to drop support for that.

**Comment by ftalbrecht** [comment]
I think one of the reasons for a `meshio` version smaller than 4 is that older versions of `pygmsh` require `meshio<4`. Updating `meshio` and `pygmsh` to the most recent versions fails the following example (with `gmsh` 2.6 binary in PATH):
```python
from pymor.analyticalproblems.domaindescriptions import PolygonalDomain

L_shaped_domain = PolygonalDomain(points=[
    [0, 0],
    [0, 1],
    [-1, 1],
    [-1, -1],
    [1, -1],
    [1, 0],
], boundary_types={'dirichlet': [1, 2, 3, 4, 5, 6]})

from pymor.discretizers.builtin.domaindiscretizers.gmsh import discretize_gmsh

grid, bi = discretize_gmsh(L_shaped_domain, msh_file_path='L_shaped_domain.msh')
```

The failure is
```
Info    : Running 'gmsh /tmp/tmpiz10ndu5.geo -2 -algo del2d -clscale 1.0  -o L_shaped_domain.msh' [Gmsh 2.16.0, 1 node, max. 1 thread]
Info    : Started on Thu Sep 17 12:31:50 2020
Info    : Reading '/tmp/tmpiz10ndu5.geo'...
Info    : Done reading '/tmp/tmpiz10ndu5.geo'
Info    : Finalized high order topology of periodic connections
Info    : Meshing 1D...
Info    : Meshing curve 1 (Line)
Info    : Meshing curve 2 (Line)
Info    : Meshing curve 3 (Line)
Info    : Meshing curve 4 (Line)
Info    : Meshing curve 5 (Line)
Info    : Meshing curve 6 (Line)
Info    : Done meshing 1D (0.002094 s)
Info    : Meshing 2D...
Info    : Meshing surface 8 (Plane, Delaunay)
Info    : Done meshing 2D (0.00544405 s)
Info    : 81 vertices 166 elements
Info    : Writing 'L_shaped_domain.msh'...
Info    : Done writing 'L_shaped_domain.msh'
Info    : Stopped on Thu Sep 17 12:31:50 2020
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-ad4b8ee26bfa> in <module>
      1 from pymor.discretizers.builtin.domaindiscretizers.gmsh import discretize_gmsh
      2 
----> 3 grid, bi = discretize_gmsh(L_shaped_domain, msh_file_path='L_shaped_domain.msh')

~/dune-gdt-python-bindings/pymor/src/pymor/discretizers/builtin/domaindiscretizers/gmsh.py in discretize_gmsh(domain_description, geo_file, geo_file_path, msh_file_path, mesh_algorithm, clscale, options, refinement_steps)
    185 
    186         # Create |GmshGrid| and |GmshBoundaryInfo| form the just created MSH-file.
--> 187         grid, bi = load_gmsh(msh_file_path)
    188     finally:
    189         # delete tempfiles if they were created beforehand.

~/dune-gdt-python-bindings/pymor/src/pymor/discretizers/builtin/grids/gmsh.py in load_gmsh(filename)
     42     if data.gmsh_periodic:
     43         raise NotImplementedError
---> 44     if not data.cells.keys() <= {'line', 'triangle'}:
     45         raise NotImplementedError
     46     if not np.all(data.points[:, 2] == 0):

AttributeError: 'list' object has no attribute 'keys'
```

This is probably easily fixed. However, we might to adapt the code depending on the `pygmsh` version. So the real reason for pinning `meshio` is probably a pinned `pygmsh`.

**Comment by TiKeil** [comment]
These adaptations that would be required are done in #1093

**Comment by sdrave** [comment]
> This is probably easily fixed. However, we might to adapt the code depending on the `pygmsh` version. So the real reason for pinning `meshio` is probably a pinned `pygmsh`.

As far as I can see, `pygmsh` is actually nowhere used. We call `gmsh` manually in `domaindiscretizers.gmsh`. If I remember correctly, there might have been plans to replace our code by `pygmsh`, but is has never been done. @renefritze, do you remember why it appears in our dependencies?

**Comment by ftalbrecht** [comment]
> I think that these adaptations that would be required are done in #1093

Cherry-picking c408524b33889422c5b5c0cdad5a78327f540e9d indeed makes my above example work. In particular, the resulting `.msh` can be used by dune-grid just fine.

However, the resulting `grid` and/or `bi` results in a broken solution when discretizing with pyMORs discretizer, for instance by (continuing the example above)

```python
from pymor.analyticalproblems.functions import ConstantFunction
from pymor.analyticalproblems.elliptic import StationaryProblem

problem = StationaryProblem(
    domain=L_shaped_domain,
    rhs=ConstantFunction(1, dim_domain=2),
    diffusion=ConstantFunction(1, dim_domain=2),
)

from pymor.discretizers.builtin import discretize_stationary_cg

fom, fom_data = discretize_stationary_cg(problem, grid=grid, boundary_info=bi)

print(fom.solve().sup_norm())
```
which gives `array([3.03613458e+14])`.

**Comment by gdmcbain** [comment]
> I think one of the reasons for a meshio version smaller than 4 is that older versions of pygmsh require meshio<4.
 
This is correct; pygmsh is pretty much built on top of meshio (by the many of the same people, both being projects of Nico Schlömer).  

It is possible to use pygmsh without meshio, just to generate Gmsh GEO code ([`pygmsh.built_in.Geometry.get_code`](https://github.com/nschloe/pygmsh/blob/9b57acdabe35355c87b5fa0bbce50a1f4a3c6e35/pygmsh/built_in/geometry.py#L45)), but the usual workflow ([`pygmsh.generate_mesh`](https://github.com/nschloe/pygmsh/blob/9b57acdabe35355c87b5fa0bbce50a1f4a3c6e35/pygmsh/helpers.py#L89)) passes that GEO to Gmsh which writes MSH.  This is [MSH 4.1](https://gmsh.info/dev/doc/texinfo/gmsh.html#MSH-file-format) by default these days, though pygmsh allows this to be [overridden](https://github.com/nschloe/pygmsh/blob/9b57acdabe35355c87b5fa0bbce50a1f4a3c6e35/pygmsh/helpers.py#L97) to write legacy [MSH 2.2](https://gmsh.info/dev/doc/texinfo/gmsh.html#MSH-file-format-version-2-_0028Legacy_0029), which is occasionally a makework to resort to, e.g. in nschloe/pygmsh#209.

In short, if meshio is to be updated to meshio 4, and pygmsh is to be depended upon, pygmsh should be updated to something after nschloe/pygmsh#240 (2019-03-18); maybe [4.4.2](https://github.com/nschloe/pygmsh/releases/tag/v4.4.2) (2019-04-01).  The latest release is [6.1.1](https://github.com/nschloe/pygmsh/releases/tag/v6.1.1) (2020-04-24).  I'd aim for the latter; it's reasonably stable now.

I wouldn't have thought that there could be any reason to want to hang on to an older version of pygmsh, but I'll check the example of @ftalbrecht .  (Thanks for that.)

I'm not sure whether I'll be able to test 

> with `gmsh` 2.6 binary in `PATH`

though; [gmsh-2.6.0-Linux.tgz](https://gmsh.info/bin/Linux/gmsh-2.6.0-Linux.tgz) is over eight years old.

Here under either Ubuntu or MS-Windows, I typically use Python from Miniconda in a conda env and install pyMOR and Gmsh with 
```shell
conda install -c conda-forge pymor
pip install gmsh-sdk
```
The latter gives Gmsh 4.6.0.

**Comment by gdmcbain** [comment]
I confirm the brokenness reported by @ftalbrecht.  With
```shell
git checkout master
pip install meshio==3.3.1 meshio=4.6.0
```
(as per `dependencies.py`) the [mwe.py.txt](https://github.com/pymor/pymor/files/5242724/mwe.py.txt) successfully computes the sup. norm `[0.14457347]`.

With `pip install -U meshio pygmsh` (which brings `meshio==4.2.0` and `pygmsh==6.1.1`, respectively), the MWE raises the `AttributeError`.

Then with `git checkout 1092-meshio4`, the MWE completes but with the erroneously large sup. norm.

**Comment by gdmcbain** [comment]
Found it.  In meshio<4, the cell data looked like `{'line': {'gmsh:physical': <ndarray>, ...}, ...}`; in meshio 4, the variable is the first key, so it's `{'gmsh:physical': [<ndarray>, <ndarray>, ...], ...}`.  Hence the need to swap 'line' and 'gmsh:physical' when looking up `data.cell_data_dict`.  This is fixed in d0f950d and with that the MWE again correctly computes the sup. norm `[0.14457374]`.  Thank you for the tidy MWE.

**Comment by ftalbrecht** [comment]
> Thank you for the tidy MWE.

Thanks for looking into it! From my side I have no objections against merging this then, as long as the `meshio` dependency is pinned to be new enough (since our code no longer passes with older versions of `meshio`). Perhaps you could

* remove the `pygmsh` dependency (if there are no objections, @renefritze) and
* document somewhere in a comment in `src/pymor/discretizers/builtin/grids/gmsh.py` that our code relies on a certain `meshio` version

as well in this pr.

**Comment by ftalbrecht** [comment]
> I'm not sure whether I'll be able to test
> 
> > with `gmsh` 2.6 binary in `PATH`
> 
> though; [gmsh-2.6.0-Linux.tgz](https://gmsh.info/bin/Linux/gmsh-2.6.0-Linux.tgz) is over eight years old.

No need to test this now, I guess. Just for future reference: in the Dockerfile for my daily-work docker container I simply use

```bash
RUN cd /tmp && \
    wget https://gmsh.info/bin/Linux/gmsh-2.16.0-Linux64.tgz && \
    tar -xzf gmsh-2.16.0-Linux64.tgz && \
    chown root:root gmsh-2.16.0-Linux/bin/gmsh && \
    chmod 755 gmsh-2.16.0-Linux/bin/gmsh && \
    mv gmsh-2.16.0-Linux/bin/gmsh /usr/local/bin && \
    rm -rf gmsh-2.16.0-Linux*
```

to get the old `gmsh`.

**Comment by renefritze** [comment]
I do not remember why we introduced pygmsh. I support dropping it as a dependency and bumping meshio.
