### ISSUE TITLE
generalize return arguments in Model.solve

### ISSUE THREAD

**Issue by TiKeil** [pymor/pymor#1095]
While discussion #1042, @sdrave and me had an offline discussion about generalizing return arguments in the `model.solve(...)` method. Some reasons for this would be 

- the solve method can directly be used to estimate the error which was usually been done by `estimate_error` 
- If the user needs additional information from the `solve` method (for example some intermediate steps of a Newton), it would be easy to add a return argument for whatever should be returned. 
- potential more return arguments from more applications could be easily added. For example we could also have an `estimate_output_error` in the future. 
- it might also be that the user is actually not interested in the solution `U` at all and instead only wants the output. 

We already have a return functionality with the `return_output` argument. For a generalization, we had several ideas to do this. 

1. simply add all return arguments to the `solve` method, such that we would have calls like 

```
solve(mu, return_solution=True, return_output=True, return_error_estimate=True, return_output_error_estimate=True, .... )
```

2. use a tuple of strings with strings to specify the returns via

```
solve(mu, return= ('solution', 'output', 'error_estimate', 'output_error_estimate' ) )
```

3. any other ideas ?? 

Of course, it would also be a question of how to order the return arguments of the `solve` function, but in the case we would go for something similar to 2., we would already have an order for that.  

What do you think?

**Comment by sdrave** [comment]
How about:

```python
class Model:

    def compute(self, solution=False, output=False, 
                         solution_error_estimate=False, output_error_estimate=False,
                         mu=None, **kwargs):
        raise NotImplementedError

    def solve(self, mu=None, return_error_estimate=False, **kwargs):
        return self.compute(solution=True, error_estimate=return_error_estimate, mu=mu)

    def error_estimate(mu=None):
        return self.compute(solution_error_estimate=True, mu=mu)

    def output(self, mu=None, return_error_estimate=False):
        return self.compute(output=True, output_error_estimate=return_error_estimate, mu=mu)

    def output_error_estimate(self, mu=None):
        return self.compute(output_error_estimate=True, mu=mu)
```

The `kwargs` are there to support additional output data. Not sure if the other methods should get `kwargs` as well, and if there should be a convention that all additional output data should be returned in a dict as the last return value.

One might also consider to let `compute` always return a dict.

**Comment by TiKeil** [comment]
I like your idea with introducing the `compute` method. That makes it also easier to read.
The question of a return value really is something important.

What about returning the solution in case this is the only return value and returning a dict for all other cases?
Then, we do not lose the simplicity  of just calling e.g. `U = m.solve(mu)` but support all sorts of return values for the other cases with `return_data = m.compute(solution=True, output=True)`, where `return_data` would then be a dict with keys `solution` and `output`.

**Comment by sdrave** [comment]
> What about returning the solution in case this is the only return value and returning a dict for all other cases?
> Then, we do not lose the simplicity of just calling e.g. `U = m.solve(mu)` but support all sorts of return values for the other cases with `return_data = m.compute(solution=True, output=True)`, where `return_data` would then be a dict with keys `solution` and `output`.

I'm fine with returning a dict for `compute`, but I don't like it for `solve`. We could say that as soon as you want to have additional data returned, you need to call `compute`?

BTW, also note that in my proposal the `return_output` has been removed from `solve`. If you want to have the solution and the output, you need to call `compute`.

**Comment by TiKeil** [comment]
I agree. That would be a very good choice.
