### ISSUE TITLE
Watch Codecov Bot

### ISSUE THREAD

**Issue by renefritze** [pymor/pymor#1131]
We'll use this issue to keep track of weird bot interactions. 
[First one I noticed](https://github.com/pymor/pymor/pull/1130#issuecomment-712677637)

**Comment by renefritze** [comment]
[Now this one](https://github.com/pymor/pymor/pull/1110#issuecomment-712934027)
Has coverage delta in vec array list. Also the bot commented/edited its msg 4 times. Which is weird since that does not match the number of different coverage reports per CI pipeline.

**Comment by sdrave** [comment]
So something definitely is wrong [here](https://github.com/pymor/pymor/pull/1138#issuecomment-717395053). All new actions for `project_to_subbasis` are triggered by the new tests (I had to add these actions to make the tests pass), and there also isn't any parametrization via hypothesis happening AFAIK.

**Comment by renefritze** [comment]
> So something definitely is wrong [here](https://github.com/pymor/pymor/pull/1138#issuecomment-717395053). All new actions for `project_to_subbasis` are triggered by the new tests (I had to add these actions to make the tests pass), and there also isn't any parametrization via hypothesis happening AFAIK.

The problem isn't just with the bot comment btw. If you look at https://codecov.io/gh/pymor/pymor/pull/1138/changes the actions are also missing there.

I think I'll have to cross check the report with the actually recorded coverage file.

**Comment by renefritze** [comment]
I feel like this has stabilized now. If anybody @pymor/all sees weird stuff again, please re-open.
