### ISSUE TITLE
Memory cache corruption

### ISSUE THREAD

**Issue by sdrave** [pymor/pymor#1133]
I known I ran across this previously but do not really remember what we did or decided. I have a `fom` with a `numpy`-based solution space of about 10.000 DoFs and

```python
fom.enable_caching('memory')
```

that I solve for about a hundred different parameters using the usual

```python
mus = parameter_space.sample_uniformly(100) # imagine a 1d parameter space
U = fom.solution_space.empty()
for mu in mus:
    U.append(fom.solve(mu))
assert len(U) == len(mus)
```
which works as expected.
However, running the same code again, the assertion fails and I have `len(mus)=100` and `len(U)=61`.
When investigating, I find that for some of these `mu`s, the result of `fom.solve(mu)` is simply an empty vector array:
```python
NumpyVectorArray([], NumpyVectorSpace(10201, id='STATE'))
```

Disabling caching or changing the backend to `disk` resolves the issue. While it seems that the storage of the `memory` cache backend is simply depleted, I feel that we should handle the situation better. In particular, *the result of `fom.solve` should not depend on the caching*!

Am I missing something, @sdrave?

_Originally posted by @ftalbrecht in https://github.com/pymor/pymor/discussions/1132_

**Comment by sdrave** [comment]
Sorry, I cannot reproduce the bug. Also, the implementation of `MemoryRegion` is pretty straightforward, and I don't see where a bug should be. Can you give a complete failing example?

**Comment by ftalbrecht** [comment]
Certainly not a minimal WE, running the following at least triggers the assertion on my machine:

```python
import numpy as np
np.warnings.filterwarnings('ignore')

from matplotlib import pyplot as plt

from pymor.analyticalproblems.elliptic import StationaryProblem
from pymor.analyticalproblems.functions import (
    ConstantFunction,
    ExpressionFunction,
    GenericFunction,
    LincombFunction,
)
from pymor.analyticalproblems.domaindescriptions import RectDomain
from pymor.parameters.functionals import ProjectionParameterFunctional

problem = StationaryProblem(
    domain=RectDomain(([0, 0], [1, 1]),
                      left='dirichlet', top='neumann', right='neumann', bottom='neumann'),

    rhs=ConstantFunction(0, dim_domain=2),

    diffusion=LincombFunction(
        [ExpressionFunction('1.*(x[..., 1] < 0.1)', dim_domain=2),
         ExpressionFunction('1.*(x[..., 1] > 0.1)', dim_domain=2)],
        [ProjectionParameterFunctional('diffusion', 1, 0),
         1]
    ),

    advection=GenericFunction(
        mapping=lambda x: np.vstack([np.zeros(x.shape[0]), x[..., 0]]).T,
        dim_domain=2, shape_range=(2,)),

    reaction=LincombFunction(
        [ExpressionFunction('1.*(x[..., 1] > 0.9)', dim_domain=2),
         ExpressionFunction('1.*(x[..., 1] < 0.9)', dim_domain=2)],
        [ProjectionParameterFunctional('reaction', 1, 0),
         1]
    ),

    dirichlet_data=ConstantFunction(0, dim_domain=2),

    neumann_data=ExpressionFunction('-1.*(x[..., 0] > (1 - 1e-7))', dim_domain=2),

    outputs=(('l2', ExpressionFunction('20.*(x[..., 0] > 0.95)', dim_domain=2)),),

    parameter_ranges={'diffusion': (0.1, 1), 'reaction': (0, 10)},
)

from pymor.discretizers.builtin.grids.rect import RectGrid
from pymor.discretizers.builtin.cg import discretize_stationary_cg

fom, fom_data = discretize_stationary_cg(
    problem, diameter=np.sqrt(2)/100, grid_type=RectGrid)
fom.enable_caching('memory')

U = fom.solve(mu={'diffusion': [1], 'reaction': [0]})

U = fom.solution_space.empty()
for diff in (0.1, 1):
    for react in (0, 10):
        U.append(fom.solve(mu={'diffusion': [diff], 'reaction': [react]}))


def io_fom(mu):
    return fom.output(mu=mu).to_numpy()[0][0]

io_fom([1, 0])

for mu in problem.parameter_space.sample_uniformly(2):
    print(f'output({mu}) = {fom.output(mu=mu).to_numpy()[0][0]}')

timing_mus = problem.parameter_space.sample_randomly(10)

for mu in timing_mus:
    fom.solve(mu)

for mu in timing_mus:
      io_fom(mu)

from pymor.reductors.coercive import CoerciveRBReductor
from pymor.algorithms.greedy import rb_greedy
from pymor.parameters.functionals import ExpressionParameterFunctional

training_set = problem.parameter_space.sample_uniformly(10)

product = fom.h1_0_semi_product
rb_reductor = CoerciveRBReductor(
    fom,
    product=product,
    coercivity_estimator=ExpressionParameterFunctional('1', fom.parameters)
)

greedy_data = rb_greedy(fom, rb_reductor, training_set)

for mu in greedy_data['max_err_mus'][:4]:
    U = fom.solve(mu=mu)
    assert U
```

**Comment by renefritze** [comment]
Apparently there's no automagic linking from discussions that reference issues: https://github.com/pymor/pymor/discussions/1135

**Comment by sdrave** [comment]
So the real culprit here is not cache eviction but corruption of the values stored in `MemoryRegion`. `RBSurrogate.extend` causes the solution snapshot to be appended to the basis with `remove_from_other=True`. Hence, the array returned by `solve` is emptied. The returned arrays were supposed to be copied in `MemoryRegion` but that did not happen as the corresponding code never triggered. However, in this example. the corruption also happens the other way around: When the solution is newly added to the cache, then also while appending, the cache entry is corrupted. So also storing a copy is necessary.

In the end, I decided that probably the only safe option is to only make deep copies of everything. See #1136.
