### ISSUE TITLE
Codecov display of file coverage is broken

### ISSUE THREAD

**Issue by sdrave** [pymor/pymor#1134]
E.g.

https://codecov.io/gh/pymor/pymor/src/master/src/pymor/core/defaults.py

**Comment by renefritze** [comment]
How did you get to that URL?

**Comment by sdrave** [comment]
Just by browsing through the codecov ui, starting by clicking on the codecov badge and then selecting an individual file. I believe this worked at the last dev meeting.

**Comment by sdrave** [comment]
@renefritze, did you do anything? The ui seems to work again ..

**Comment by renefritze** [comment]
Nope. Nothing. Fitting though since I also didn't do anything before to break the UI :wink:

**Comment by sdrave** [comment]
Interesting. Let's see what the future holds ...
