### ISSUE TITLE
[algorithms.gram_schmidt] silence numpy warning

### ISSUE THREAD

**Issue by ftalbrecht** [pymor/pymor#115]
While benchmarking (and thus calling `gram_schmidt` with random vector arrays) I ran into a `RuntimeWarning` of numpy, triggered by https://github.com/pymor/pymor/blob/master/src/pymor/algorithms/gram_schmidt.py#L125 with `norm = 0.0`.
This is not really an issue, since this vector has been marked for removal earlier in line 122. The removal, however, takes place after the loop.
While this is not really a problem, it is nevertheless an undesirable situation since the user is left with a warning from numpy although it does not impact the computation. We could

* leave everything as it is
* remove the vectors within the loop (which we probably do not want to do)
* disable numpys warning behavior, only fir line 125.

Opinions?

**Comment by sdrave** [comment]
Fixed in 8b501212b8.
