### ISSUE TITLE
[readthedocs] Copyright outdated

### ISSUE THREAD

**Issue by ftalbrecht** [pymor/pymor#116]
When I visit `docs.pymor.org`, the Copyright statement at the bottom reads
```
© Copyright 2012-2013, the pyMOR AUTHORS. Last updated on Mar 19, 2015. Created using Sphinx 1.2.2. 
```
If the leading years are with respect to pymor (and not readthedocs), we should update this.

**Comment by sdrave** [comment]
Should be fixed with 6ddb7930dc.
