### ISSUE TITLE
Stop supporting python 3.6

### ISSUE THREAD

**Issue by renefritze** [pymor/pymor#1164]
3.6 will reach end of life in [december 2021](https://www.python.org/dev/peps/pep-0494/#id28), so I propose 2021.2 will be the last release with official 3.6 support and we stop testing on 3.6 right after that release.

**Comment by pmli** [comment]
Sounds good to me. [NumPy](https://mail.python.org/pipermail/numpy-discussion/2020-November/081179.html) will drop support in their next release.

**Comment by renefritze** [comment]
For reference, the [general roadmap](https://numpy.org/neps/nep-0029-deprecation_policy.html) for these things in numpy

**Comment by sdrave** [comment]
Agreed. Even debian stable is on 3.7.

**Comment by renefritze** [comment]
We decided to move up the 3.6 dropping to not complicate the introduction of type annotations. The feature branch already includes the necessary changes via https://github.com/pymor/pymor/commit/fc41b45c7548ef818d1897e6945aa61a7f01b2a4 and https://github.com/pymor/pymor/commit/386a0a0f671c4851c09f508b9db91cfcba4fb8fb
