### ISSUE TITLE
Demo tests don't check window drawing

### ISSUE THREAD

**Issue by renefritze** [pymor/pymor#1178]
Apparently monkeying the `plt.show()` function to do nothing, hides potential problems. 

I've only found out that https://github.com/pymor/pymor/pull/1170 introduced a regression
when I manually ran a demo. Which is also when I discovered that we use a broken `show(figure)` in a few places.

Both issues are fixed in #1177, but we need a way to catch these error in CI.

**Comment by sdrave** [comment]
Any idea how to do that? Maybe `matplotlib` has some infrastructure for unit testing that might be usable?

**Comment by renefritze** [comment]
This should actually not be very hard, I think. Instead of moneying `show` to nothing, we can rewire it to always `block=False` plus sleep reasonable amount of time. The demo tests already run in a xvfb. Anything with glx extensions (shader patch vis) might be a problem though.

**Comment by sdrave** [comment]
>  I think. Instead of moneying show to nothing, we can rewire it to always block=False plus sleep reasonable amount of time.

Does `block=False` work for you? It's been a while since I played with it, but if I remember correctly, it never really worked for me.

**Comment by renefritze** [comment]
> Does `block=False` work for you?

"work" as in does it really not block? Last time I was actively used it, it did indeed not block.

**Comment by sdrave** [comment]
Ok, then we might as well just use `block=False` everywhere in the demos, IMHO.

**Comment by pmli** [comment]
What about [`plt.ion()`](https://matplotlib.org/3.3.3/api/_as_gen/matplotlib.pyplot.ion.html#matplotlib.pyplot.ion)? Would that work, instead of writing `block=False` all over?

**Comment by renefritze** [comment]
> Ok, then we might as well just use `block=False` everywhere in the demos, IMHO.

I think that's just bad usability for the demos. It's a real turn-off if the user potentially only sees a blip of UI questioning whether something's wrong with pyMOR. 

> What about [`plt.ion()`](https://matplotlib.org/3.3.3/api/_as_gen/matplotlib.pyplot.ion.html#matplotlib.pyplot.ion)? Would that work, instead of writing `block=False` all over?

Sounds good, but reads a little fuzzy as to what it actually does. Definitely worth a try though using that instead of the `_test_demo` monkeying IMO.

**Comment by sdrave** [comment]
> > Ok, then we might as well just use `block=False` everywhere in the demos, IMHO.
> 
> I think that's just bad usability for the demos. It's a real turn-off if the user potentially only sees a blip of UI questioning whether something's wrong with pyMOR.

Probably, this is new behavior of `block=False`. In general, having the plot window open while the script continues to run is only possible if there is an event loop running, which, at least for some platforms/toolkits, has to be in the main thread. So there is now way of getting non-blocking plotting without the code running from IPython or something similar. I believe the old behavior was to just block in that case.

> > What about [`plt.ion()`](https://matplotlib.org/3.3.3/api/_as_gen/matplotlib.pyplot.ion.html#matplotlib.pyplot.ion)? Would that work, instead of writing `block=False` all over?
> 
> Sounds good, but reads a little fuzzy as to what it actually does. Definitely worth a try though using that instead of the `_test_demo` monkeying IMO.

Ok, so the idea is to replace the code in `_test_demo` by `plt.ion()`, but not to modify the demos, right?

**Comment by renefritze** [comment]
> Ok, so the idea is to replace the code in `_test_demo` by `plt.ion()`, but not to modify the demos, right?

I would've though `plt.ioff()`, but yes.

**Comment by sdrave** [comment]
> > Ok, so the idea is to replace the code in `_test_demo` by `plt.ion()`, but not to modify the demos, right?
> 
> I would've thought `plt.ioff()`, but yes.

`plt.ion()` seems to correspond to `block=False` ...

**Comment by renefritze** [comment]
> > > Ok, so the idea is to replace the code in `_test_demo` by `plt.ion()`, but not to modify the demos, right?
> > 
> > 
> > I would've thought `plt.ioff()`, but yes.
> 
> `plt.ion()` seems to correspond to `block=False` ...

:roll_eyes:  I really don't get Matplotlib sometimes.
