### ISSUE TITLE
`make docker_docs` breaks permissions for files. 

### ISSUE THREAD

**Issue by TiKeil** [pymor/pymor#1193]
After running `make docker_docs` it happens to me that the `make docs` doesn`t work anymore. So far I have not figured out how to fix this.

**Comment by renefritze** [comment]
Hey @TiKeil can you checkout my `issue_1193` branch? This should fix permission issues. 
Please note though that extensions have to be recompiled when switching environments.

**Comment by TiKeil** [comment]
yep, I confirm this branch is doing the job. Thank you.
