### ISSUE TITLE
Inconsistent description of the stationary problem

### ISSUE THREAD

**Issue by HenKlei** [pymor/pymor#1229]
In the equation of the `StationaryProblem` (see [here](https://github.com/pymor/pymor/blob/600bf30ba126d3d9e67b25dab49aa6a328bc7528/src/pymor/analyticalproblems/elliptic.py#L16)), the function name `f` shows up twice, once for the advection term and furthermore as right hand side. In addition, it might be a bit unclear how to use/define the advection respectively nonlinear advection term, since there is only one equation that is supposed to somehow capture both cases (although in the linear case the equation should include something like `nabla cdot (f(x, mu)*u)` for the advection if I got this correctly). Maybe this can be clarified a bit. The same holds for the reaction, however, in the reaction case the equation does not change substantially.

**Comment by sdrave** [comment]
Yes. I think it makes sense to rewrite the equation in tex and, to be precise, add the missing terms such that each parameter exactly corresponds to one term in the equation.
