### ISSUE TITLE
gram_schmidt: set default for copy parameter to True?

### ISSUE THREAD

**Issue by sdrave** [pymor/pymor#123]
Since gram_schmidt always returns the orthonormalized matrix and pyMOR usually copies data per default to be on the safe side, the current behaviour is unexpected.

@ftalbrecht, @andreasbuhr, any objections? (Of course, changing the default will break code which assumes that gram_schmidt is in-place by default.)

**Comment by ftalbrecht** [comment]
No objections.

On 18 June 2015 15:00:49 CEST, Stephan Rave <notifications@github.com> wrote:
>Since gram_schmidt always returns the orthonormalized matrix and pyMOR
>usually copies data per default to be on the safe side, the current
>behaviour is unexpected.
>
>@ftalbrecht, @andreasbuhr, any objections? (Of course, changing the
>default will break code which assumes that gram_schmidt is in-place by
>default.)
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/pymor/pymor/issues/123

-- 
 Felix Schindler (born Albrecht)
 Applied Mathematics Münster
 University of Münster
 Orleans-Ring 10, room 120.012
 D-48149 Münster, Germany

 Tel.: +49 251 83 35130
 Fax :  +49 251 83 32729
 Mail: felix.schindler@wwu.de
 WWW:  http://felixalbrecht.de

**Comment by andreasbuhr** [comment]
My code does not use gram_schmidt directly, only gram_schmidt_basis_extension, so  no objections.

**Comment by sdrave** [comment]
Done in 711393a3300aa00176fd70e662b17b2ed8bd7e29.
