### ISSUE TITLE
(some) GH Actions fail for forks

### ISSUE THREAD

**Issue by renefritze** [pymor/pymor#1235]
This is due to the execution model giving the omnipresent github token read-only access in these cases. There's a simple workaround, which I will deploy on monday. 

Currently this impacts #1234

**Comment by TiKeil** [comment]
can be closed?

**Comment by renefritze** [comment]
I've only started to convert the one action and that's also not done yet.

**Comment by renefritze** [comment]
This should be good now. At least we had no problems with PRs coming from @TiKeil or @HenKlei for a quite a while.
