### ISSUE TITLE
[wiki]

### ISSUE THREAD

**Issue by ftalbrecht** [pymor/pymor#125]
We should get the wiki in a shape so that it can be used again (e.g., to document the role of a core developer). There are several old articles that are probably outdated by now. We can only work on this while the wiki is enabled, which we might not want to have at all time. So perhaps each of us could take some time in the next days/weeks, enable the wiki and delete those pages that are not needed any more and update the others (or at least mark the as unfinished/in need to be updated).

**Comment by renemilk** [comment]
Is it really necessary to have it enabled? I thought I could clone and edit offline, no?

**Comment by ftalbrecht** [comment]
That I did not know of, but since this is github you are probably right! :)
Nevertheless, the whole point of editing the wiki is that we want it to be enabled at some point, so we will have to do that anyway (at some point in the future). In addition, editing the Wiki using githubs editors is much more convenient than locally editing text files (for me at least). But cleaning up and getting rid of of old files might be easier in a clone.

**Comment by sdrave** [comment]
To be honest, I do not see why we would want to enable the wiki again. Its just one more thing that has to be kept up to date, and we disabled it because no one did so. Regarding the contribution guidelines, I would prefer a CONTRIBUTING file which is referenced by the README.

Am 23. Juni 2015 12:53:28 MESZ, schrieb Felix Schindler <notifications@github.com>:

**Comment by ftalbrecht** [comment]
I agrre on the maintanence part. Would you then like to have our ideas
of what the rights and duties of a _Core Developer_ is all documented in
the `CONTRIBUTING.md`?

**Comment by sdrave** [comment]
I guess that would be fine. Shouldn't be too much text anyhow.
