### ISSUE TITLE
Add support for empirical interpolation of coefficient functions

### ISSUE THREAD

**Issue by sdrave** [pymor/pymor#1265]
Generally, function EI can be simply done by passing `VectorArrays` of function evaluations to `ei_greedy`. However, depending on the PDE solver backend, it is not clear how to build `Operators` from the basis `VectorArrays` returned by `ei_greedy`. [This code](https://github.com/pymor/pymor/discussions/1230#discussioncomment-311657) gives a basic example how to indirectly build a corresponding basis of `Operators` using the changes in #1240. There is still backend-specific code we should supply for the officially supported backends. We also need documentation.

**Comment by renefritze** [comment]
@sdrave rechecks what's still to be done

**Comment by sdrave** [comment]
Support for empirical interpolation of `Functions` has also been added in #1240 including a basic demo. What remains is to write a tutorial on EI with a section on dealing with external solvers. I rename the issue and move it to the next milestone.

**Comment by sdrave** [comment]
See #1407.
