### ISSUE TITLE
External PDE solver figure height too short

### ISSUE THREAD

**Issue by pmli** [pymor/pymor#1272]
At the end of the [PDE solver tutorial](https://docs.pymor.org/2020.2.0/tutorial_external_solver.html), figures are very short, especially for the error plot.

![figures](https://user-images.githubusercontent.com/1268421/111431553-38ef0080-86fc-11eb-9ccd-ee3ed06cbd31.png)

**Comment by renefritze** [comment]
CHeck again with current main @renefritze

**Comment by pmli** [comment]
The issue seems to persist: https://docs.pymor.org/main/tutorial_external_solver.html
The problem looks to be that the x and y axes are equally scaled.

**Comment by renefritze** [comment]
Wasn't this something you (thought had) fixed @HenKlei ?

**Comment by HenKlei** [comment]
I will check. If I remember correctly, @renefritze and I were at least discussing how to properly address this issue.

As @pmli said, the scaling is the problem. From my point of view, it would be nice to have the possibility to switch between equal scaling and "fit to figure size"-scaling. What do you think @renefritze, @pmli?

**Comment by renefritze** [comment]
Right

> I will check. If I remember correctly, @renefritze and I were at least discussing how to properly address this issue.

Right. But didn't you then add a minimal size for the y-axis?

> 
> As @pmli said, the scaling is the problem. From my point of view, it would be nice to have the possibility to switch between equal scaling and "fit to figure size"-scaling. What do you think @renefritze, @pmli?

Fit to figure would be nice, I agree. That could be difficult though, since that needs feedback/advance knowledge of the figure size, which is determined in the jupyter display on the frontend.
