### ISSUE TITLE
Add Python 3 support

### ISSUE THREAD

**Issue by sdrave** [pymor/pymor#128]
All our major dependencies support Python 3 by now. As we have nothing to do with string handling, porting should be quite straightforward.

**Comment by sdrave** [comment]
Question is, if and how we will support Python 2 in the future.

**Comment by renemilk** [comment]
I vote against parallel 2.7/3.x support. There's way more overhead than benefit imo. If python 3 is still scary for some potential user than he's probably just mis/uninformed.

**Comment by ftalbrecht** [comment]
I do not have a strong opinion in this apart from keeping the workload at a minimum. As a side note: the [Raspberry Pi supports and recommends Python 3](https://www.raspberrypi.org/documentation/usage/python/)

**Comment by sdrave** [comment]
Since we do not do a lot of string handling, automatic options like [3to2](https://bitbucket.org/amentajo/lib3to2) or [pasteurize](http://python-future.org/automatic_conversion.html#pasteurize-py3-to-py2-3) might work quite well. If these do not work, I would also vote for making pyMOR Python 3 only.

Right now, our only dependency which is not available for Python 3 is pyvtk. Sadly, the last time I looked I could not find any alternative. There is not too much code in pyvtk. So in case anyone wants to port it, or integrate the relevant code into pyMOR ...

@renemilk, @ftalbrecht, I still believe that switching to Python 3 may have negative consequences. Your typical user is more likely to sit in front of a RHEL machine than in front of a Raspberry Pi.

**Comment by renemilk** [comment]
Both supermuc and Cheops run RHEL derivatives and have usable python 3 modules. If you're in a desktop machine with RHEL 5 now and cannot get your admin to install python 3 you're f'ed anyway.

**Comment by sdrave** [comment]
@renemilk, you are probably right. If python 3 is not available, then python 2.7 is most likely missing as well, so you have to roll your own in any case.

**Comment by renemilk** [comment]
Next question would then be what's the minimal x in 3.x .

**Comment by sdrave** [comment]
From a quick look I would say at least 3.2. Maybe it is wiser to say 3.3 right from the start. 3.3. does not have any important new features, but its already three years old and having to support fewer versions is always a good thing. Python 3.4 is only a year old which is probably to young.

Type annotations as discussed in #56 will enter 3.5, but I believe changes involve only a new `typing` module which will probably be available via pip.

**Comment by renemilk** [comment]
Sounds very reasonable.

**Comment by renemilk** [comment]
I can now output vtr files with a patched pyEVTK that paraview cannot read ;-)
Also: https://i.imgur.com/u0Msda6.png

**Comment by sdrave** [comment]
Since there is still work to do and FEniCs (for which we have just added some support #146) is Python 2 only ATM, shall we postpone until the 0.5 release?

**Comment by renemilk** [comment]
I've been updating #134  since yesterday. Imo postponing for an optional feature with no clear roadmap or dedication to support python 3 is a bad idea. The branch will bit rot. Afaict the poisson demo in fenics was *reportedly* working a year ago on python 3, with no news since.

**Comment by sdrave** [comment]
So what do you suggest? Dropping FEniCS support again or supporting both Python 2 and 3?

**Comment by ftalbrecht** [comment]
Given that fenics is one of the most powerful discretization packages out there, and that via dolfin the bindings/usage is one of the easiest out there, and that a major goal of pyMOR is an easy coupling to powerful discretization backends, I would not drop the fenics support too lightly...

**Comment by renemilk** [comment]
Maybe try to get official word about python 3 status/plans first?

**Comment by sdrave** [comment]
I very much agree with @ftalbrecht. I think another possible route might be to move to Python 3 keeping Python 2.7 compatibility via 3to2. If there are only two or three places in pyMOR which might need special handling, this might be a viable option.

**Comment by renemilk** [comment]
I say we wait for python 3 support in fenics and continue with the prep for python_move in #134 
See [here](http://fenicsproject.org:8010/waterfall?category=dolfin.next&category=ferari.next&category=ffc.next&category=fiat.next&category=instant.next&category=ufc.next&category=ufl.next&category=uflacs.next) and search ```py3```

**Comment by sdrave** [comment]
Since 0.4 is nearing completion, I would say we defer this issue to the start of the 0.5 development cycle. Any objections?

**Comment by ftalbrecht** [comment]
Fine with me.

**Comment by renemilk** [comment]
Not from me.

**Comment by renemilk** [comment]
FYI, Landscape now support python 3, so I've re-enabled it. It tries to get python rev from setup.py classifiers, which seems to work.

**Comment by renemilk** [comment]
I now have functioning dolfing packages for python 3 on trusty and xenial in our ppa. Non-MPI Travis tests are green.

**Comment by sdrave** [comment]
@renemilk, if I remember correctly there are still some issues with vtk writing? Maybe we should close this issue and open another one?

**Comment by renemilk** [comment]
Sounds good. I'll check what (tris/cubes) was still misbehaving and open a more focused issue in a bit.

**Comment by renemilk** [comment]
Turns out both are OK. 

[tria_cube.zip](https://github.com/pymor/pymor/files/304397/tria_cube.zip)

**Comment by sdrave** [comment]
Was it just the grid or the combination with codim 0/2 data?

**Comment by renemilk** [comment]
Afaicr only the grid.
