### ISSUE TITLE
Non-blocking Qt-based visualization seems broken

### ISSUE THREAD

**Issue by renefritze** [pymor/pymor#1288]
Seems to hang in the GL colorbar widget super init, for unknown reasons.

**Comment by sdrave** [comment]
As I just wrote on gitter, I no longer see the related issues with pyMOR main. The following script works for me on Python 3.7 with PySide2==5.14.2.

```python3
from pymor.basic import *
p = burgers_problem_2d()
m, _ = discretize_instationary_fv(p, diameter=1/100, nt=400)
m.visualize(m.solve(1.), block=False)
m.visualize(m.solve(1.5), block=False)
```

**Comment by renefritze** [comment]
I can also no longer replicate this original issue. The problems in testing seem unrelated and entirely in matplotlib. For that the only current workaround is falling back on old behaviour: https://github.com/pymor/pymor/pull/1286/commits/627de8fa7f11115ee0b7ddec970ae782552ebe04
