### ISSUE TITLE
Speedup tests

### ISSUE THREAD

**Issue by sdrave** [pymor/pymor#130]
Right now our VectorArray tests (marked with 'slow') like to error on travis because they need more than 50 minutes to run.

**Comment by sdrave** [comment]
I have deactivated the DiskVectorArray tests on travis for now (84a4e55). The tests now run in 30 minutes.  DiskVectorArray is only in playground, so it can stay this way for now. I guess, we will need more fine-grained separation into jobs on travis for the future ...

**Comment by renemilk** [comment]
We could give this another try on travis. We've since moved to a different infrastructure type there. But yes, finer grained separation would be good.

**Comment by renemilk** [comment]
Is this still an issue? I've collected runtime data (mm:ss) from [build #2000](https://travis-ci.org/pymor/pymor/builds/185780728)

|        | slow  | not slow | MPI   | PIP   |
| ------- | ----- | -------- | ----- | ----- |
| py 2.7 | 07:46 | 22:28    | 15:04 | 25:22 |
| py 3.4 | 06:33 | 23:29    | 13:30 | 21:17 |
| py 3.5 | 07:25 | 24:53    | 13:10 | 20:44 |

Given these numbers we could actually forgo the slow/not slow splitting again. There's about 150 seconds of system setup time included at the start of each build (mainly ```docker pull```), so the combination of those two markers should come in between 27-30 minutes.

**Comment by sdrave** [comment]
How long are tests allowed to run on travis? Generally, I agree that slow/not slow is pretty useless right now and should be merged. - In general, it would be nice to either speedup the whole test suite or to have at least some "quick" subset which only does minimal testing. But this could also be done "some time in the future" ...

**Comment by renemilk** [comment]
A single step is allowed a max of ~48 minutes. I like the idea of a "quick" subset. How about I merge the slow/not slow now, and we'll consider that subset in a new ticket?

**Comment by sdrave** [comment]
Agreed.

**Comment by renemilk** [comment]
Closed by d136958416263e21506ad5b7abed4d414d46b32f
