### ISSUE TITLE
ERROR:No matching distribution found for pymor

### ISSUE THREAD

**Issue by ashrafulmazid** [pymor/pymor#1308]
unable to install pyMOR . please help .

**Comment by renefritze** [comment]
Dear @ashrafulmazid, in order to help we need to understand how exactly you tried to install pyMOR. Please be as precise and verbose as possible, thank you.

**Comment by ashrafulmazid** [comment]
Tried to install with pip command.

**Comment by ashrafulmazid** [comment]
I installed intellij...there I installed python as plugin..then I tried to install pymor as package...but the error occurs and the error message states ERROR: no matching distribution found for PyMOR . We even tried it using command prompt but still no luck

**Comment by ashrafulmazid** [comment]
Is there any other way to write codes in python for model order reduction?

**Comment by renefritze** [comment]
> We even tried it using command prompt but still no luck

Is that following the [README](https://github.com/pymor/pymor#installation-via-pip)? 

Which operating system are you working on? Which python version?

If you are on Windows or MacOSX, you can try this:

 1. Download the source archive: https://github.com/pymor/pymor/archive/refs/tags/2020.2.0.zip
 2. Extract it somewhere and open a terminal/command prompt in that directory.
 3. execute `pip install .` (make sure this is inside the extracted directory, probably named pymor-2020.2.0)

**Comment by ashrafulmazid** [comment]
yes, I have followed that.
working on windows 10. python version 3.9.5

**Comment by ashrafulmazid** [comment]
same problem
getting this message
ERROR: Could not find a version that satisfies the requirement pymor (from versions: 0.2.0rc2-15-g22475c4, 0.2.0, 0.2.1, 0.2.2, 0.3.0, 0.3.1, 0.3.2, 0.4.0, 0.4.1, 0.4.2, 0.5.1, 0.5.2, 2019.2.0, 2020.1.1, 2020.1.2, 2020.2.0)
ERROR: No matching distribution found for pymor

**Comment by renefritze** [comment]
We've just released pyMOR 2020.2.2 which fixes the underlying error on OSX and Windows.
