### ISSUE TITLE
hapod not usable in jupyter notebooks

### ISSUE THREAD

**Issue by ftalbrecht** [pymor/pymor#1310]
The following MWE fails in a Jupyter Notebook:
```python
from pymor.analyticalproblems.thermalblock import thermal_block_problem
from pymor.discretizers.builtin.fv import discretize_stationary_fv

fom, _ = discretize_stationary_fv(thermal_block_problem())

U = fom.solution_space.empty()
for mu in fom.parameters.space((0.1, 1)).sample_randomly(10):
    U.append(fom.solve(mu=mu))

from pymor.algorithms.hapod import inc_vectorarray_hapod

inc_vectorarray_hapod(2, U, 1e-4, 0.9)
```

The error is:
```python
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-9-0d578d07f599> in <module>
      1 from pymor.algorithms.hapod import inc_vectorarray_hapod
      2 
----> 3 inc_vectorarray_hapod(2, U, 1e-4, 0.9)

~/examples/pymor/src/pymor/algorithms/hapod.py in inc_vectorarray_hapod(steps, U, eps, omega, product, executor)
    288     return inc_hapod(len(slices),
    289                      lambda i: U[slices[i]: slices[i]+chunk_size],
--> 290                      eps, omega, product=product, executor=executor)
    291 
    292 

~/examples/pymor/src/pymor/algorithms/hapod.py in inc_hapod(steps, snapshots, eps, omega, product, executor, eval_snapshots_in_executor)
    206                  product=product,
    207                  executor=executor,
--> 208                  eval_snapshots_in_executor=eval_snapshots_in_executor)
    209 
    210 

~/examples/pymor/src/pymor/algorithms/hapod.py in hapod(tree, snapshots, local_eps, product, pod_method, executor, eval_snapshots_in_executor)
    157 
    158     # perform HAPOD
--> 159     result = loop.run_until_complete(hapod_step(tree.root))
    160 
    161     # shutdown event loop

/usr/lib/python3.7/asyncio/base_events.py in run_until_complete(self, future)
    569         future.add_done_callback(_run_until_complete_cb)
    570         try:
--> 571             self.run_forever()
    572         except:
    573             if new_task and future.done() and not future.cancelled():

/usr/lib/python3.7/asyncio/base_events.py in run_forever(self)
    524         self._check_closed()
    525         if self.is_running():
--> 526             raise RuntimeError('This event loop is already running')
    527         if events._get_running_loop() is not None:
    528             raise RuntimeError(

RuntimeError: This event loop is already running
```

A possible fix [due to ](https://stackoverflow.com/questions/46827007/runtimeerror-this-event-loop-is-already-running-in-python) is given by
```python
import nest_asyncio
nest_asyncio.apply()
```

**Comment by sdrave** [comment]
Ok, probably the right way to do this is to run the code in a separate thread which can have its own event loop. But maybe it is a better idea to ditch asyncio and manage the scheduling of task manually.

As discussed with @ftalbrecht, we also need some notion of dependency between leaf node computations, for instance when the leafs are associated with a time series. I think we should decide on this before revisiting the implementation.

One way to handle dependencies would be to explicitly specify for each leaf, which other leafs need to be computed before the given leaf. We could also try to derive the dependencies from the tree structure. One possible rule would be:

> For each node, all non-leaf children of the node have to be fully computed before the node's leaf children are computed.

@ftalbrecht, @tobiasleibner, @gramian, do you think this rule makes sense?

**Comment by gramian** [comment]
I think your rule would be a natural approach and sounds fine to me.

I just want to make one remark: As a node could have many children, the amount of data stored per node (even though probably negligible) is undetermined. If one would attach to each node/leaf who its parent is, only one piece of information has to be stored per node/leaf. However, the machinery necessary to coordinate this may not be worth it. On the other hand, the tree would only have to be traversed up, not down and up.

**Comment by tobiasleibner** [comment]
The rule also sounds good to me, though I am sure that there are cases where specifying the dependencies manually would be beneficial. So maybe the automatic derivation of the dependencies could be used unless the dependencies are given manually.
