### ISSUE TITLE
Add 'apply_adjoint_inverse' method to operators

### ISSUE THREAD

**Issue by pmli** [pymor/pymor#133]

**Comment by sdrave** [comment]
I will implement this, when #122 is closed.

**Comment by sdrave** [comment]
With #122 done, do we want to name the method 'apply_adjoint_inverse' or 'apply_inverse_adjoint'. I would vote for the second option.

**Comment by ftalbrecht** [comment]
I do not have a strong opinion here. So if you have one, let's go with
it...

**Comment by pmli** [comment]
I used the first option, but I'm fine with switching to the second. Also, in math we usually write A^{-T} or A^{-*} (or A^{-H}), so in that way it makes sense to use the second option.
