### ISSUE TITLE
Only first class in module is shown in documentation

### ISSUE THREAD

**Issue by HenKlei** [pymor/pymor#1343]
As discussed in #1282, there seems to be an issue where autoapi fails to include all classes of a module if they are defined in a conditional statement.

See for instance [here](https://docs.pymor.org/github-push-feature-ann-output-reductor/autoapi/pymor/models/neural_network/index.html).

**Comment by renefritze** [comment]
Since this is not really in our hands it seems, I'll defer it to next release to be checked again with the then current releases of astroid/autoapi.

**Comment by sdrave** [comment]
This also happens for `bindings.{fenics,ngsolve,pymess,slycot}` ..

**Comment by ftalbrecht** [comment]
Stupid idea: how about instead of
```python
if config.HAVE_X:
    import X

    class Foo:
        pass
```
we do something like
```python
if config.HAVE_X:
    import X

class Foo:
    def __init__(...):
    assert if config.HAVE_X
```

However, does not always work (i.e., when init default arguments com from `X`).

**Comment by renefritze** [comment]
A workaround that should always work is repeating the `if X` statement for each new class def.

**Comment by renefritze** [comment]
[Autoapi issue](https://github.com/readthedocs/sphinx-autoapi/issues/264#issuecomment-981884896) for reference

**Comment by sdrave** [comment]
If this is a viable workaround, then I guess we should implement this for the release.

Maybe a better approach for the future would be just to fail with a reasonable error message when a module is imported which has unresolved dependencies. So something like:

```python
from pymor.core.config import config
if not config.HAVE_FENICS:
    raise ImportError('Missing dependency: fenics')

import dolfin as df
...
```

With a bit of care I would expect that this might be a good solution. However, there might be some issues to fix, so we should maybe better do this after the release.

**Comment by ftalbrecht** [comment]
One could also think about
```
config.assert(HAVE_FENICS)
```
or something alike, to save some lines.
But don't we get the errors on module import in that case?

**Comment by sdrave** [comment]
> But don't we get the errors on module import in that case? 

Yes. The general idea would be that these modules should then only be imported when needed. Right now the import succeeds, but the module is empty. So you can't do anything with it anyway.
