### ISSUE TITLE
Remove slicing restrictions for vectorarray tests

### ISSUE THREAD

**Issue by renefritze** [pymor/pymor#1348]
Historically index tests were performed with a set of manually constructed `slice` objects. When rewriting the tests to instead draw slices from a hypothesis strategy it became necessary to add a filter to mimic the properties of the manual examples, or be drowned by test failures. Notably this filter excludes negative step sizes. It's unclear whether the assertions simply are defective or if real failures are among them. And I currently do not have time to look into this further. Anybody interested should check out the `vectorarray_tests_unrestricted_slicing` branch and run the tests there.

**Comment by sdrave** [comment]
@renefritze, I have just tried to run the vectorarray tests in the branch you mentioned. But all I get is failures inside the `valid_indices` strategy. So it seems like the problem does not seem to be with the actual code but only with the hypothesis strategy? In any case, all valid slice objects, e.g., with negative step sizes, should be allowed!
