### ISSUE TITLE
Conda package has wrong (package) version (info)

### ISSUE THREAD

**Issue by renefritze** [pymor/pymor#1354]
### Discussed in https://github.com/pymor/pymor/discussions/1353

It seems the generated versioneer file isn't properly packaged with the conda package. This results in ""0+unknown" being set for `pymor.__version__`.

**Comment by renefritze** [comment]
Could one of the @pymor/main @pymor/contributors who have a regular conda setup please check this out?

**Comment by renefritze** [comment]
> Could one of the @pymor/main @pymor/contributors who have a regular conda setup please check this out?

Is anyone actually using conda?

**Comment by sdrave** [comment]
I can confirm the issue in my Windows conda environment. The package comes with the following `version.py`:

```python

# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": null,
 "dirty": null,
 "error": "unable to compute version",
 "full-revisionid": null,
 "version": "0+unknown"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
```

**Comment by renefritze** [comment]
I think I've fixed the issue on the conda recipe side of things, but I can only check that after the release tag happened. 
So technically I'm moving this to the next release, but hope to be able to close it right after 2021.1

**Comment by renefritze** [comment]
The new conda package is done, maybe @sdrave can check if the issue is resolved

**Comment by sdrave** [comment]
Looking good!
