### ISSUE TITLE
ComplexifiedListVectorSpace.make_array behaves unexpectedly

### ISSUE THREAD

**Issue by ftalbrecht** [pymor/pymor#1386]
I think that `ComplexifiedListVectorSpace` is lacking its own `make_array` which ensures that each element of the array is a `ComplexifiedVector`. Let me elaborate: suppose you have some external PDE solver which only knows real numbers, and make use of pyMORs complexification within the bindings, say [the `DuneXTVectorSpace`](https://github.com/pymor/pymor/pull/1383/files#diff-5153dc94a4bc6e59e5a702be6113212d36737650fe86260254ba2e76d2e0536aR113), deriving from `ComplexifiedListVectorSpace`. Looking at
```python
from pymor.bindings.dunegdt import DuneXTVectorSpace
space = DuneXTVectorSpace(5)
space.ones()._list[0]
```
we obtain
```python
ComplexifiedDuneXTVector(DuneXTVector(IstlVector([1 1 1 1 1])), None)
```
which is exactly as expected. Now lets take an actual vector, as it might pop up as right hand side from the PDE solver, then
```python
v = space.ones()._list[0].real_part
v
```
gives
```python
DuneXTVector(IstlVector([1 1 1 1 1]))
```
as expected.

When trying to convert this `v` to an element of `space` by using
```python
space.make_vector(v)
```
we get back
```python
ComplexifiedDuneXTVector(DuneXTVector(DuneXTVector(IstlVector([1 1 1 1 1]))), None)
```
as expected. However, when calling
```python
V = space.make_array([v,])
V._list[0]
```
we have
```python
DuneXTVector(IstlVector([1 1 1 1 1]))
```
which is unexpected. This is probably attributed to [`ListVectorSpace`s implementation of `make_array`](https://github.com/pymor/pymor/blob/main/src/pymor/vectorarrays/list.py#L609), which only calls `ComplexifiedListVectorSpace`s `make_vector` in some circumstances.

I am not sure if its justified, @sdrave, but I am labeling this a bug for now. Care to take a look?

**Comment by sdrave** [comment]
> I am not sure if its justified, @sdrave, but I am labeling this a bug for now. Care to take a look?

So `DuneXTVector` is the wrapped vector, right? The thing is that you are actually not supposed to directly operate on `Vector` objects. They are internal to the `ListVectorArray` implementation. So the right way to call `make_array` would be

```python
space.make_array([IstlVector([1 1 1 1 1])])
```

In other words, `make_array` is supposed to receive a list of backend objects, which are then wrapped as vector objects and put into an internal list. The is actually no interface method to retreive the wrapped vector back from the array.

Apparently, at some point in time I found it useful to allow passing `Vector` objects. But I am wondering now, if this is the actual bug here .. - Note that it is not trivial how to check if a passed `Vector` object is really of the right type. @ftalbrecht do you really need the ability to call `make_array` with a list of wrapped objects?

**Comment by ftalbrecht** [comment]
> > I am not sure if its justified, @sdrave, but I am labeling this a bug for now. Care to take a look?
> 
> So `DuneXTVector` is the wrapped vector, right? The thing is that you are actually not supposed to directly operate on `Vector` objects. They are internal to the `ListVectorArray` implementation. So the right way to call `make_array` would be
> 
> ```python
> space.make_array([IstlVector([1 1 1 1 1])])
> ```
> 
> In other words, `make_array` is supposed to receive a list of backend objects, which are then wrapped as vector objects and put into an internal list.

Ah, thx for clarifying.

> The is actually no interface method to retreive the wrapped vector back from the array.
> 
> Apparently, at some point in time I found it useful to allow passing `Vector` objects. But I am wondering now, if this is the actual bug here .. - Note that it is not trivial how to check if a passed `Vector` object is really of the right type. @ftalbrecht do you really need the ability to call `make_array` with a list of wrapped objects?

No, actually I don't. It's just that it was in my discretizer code for some reason, and as long as I did not complexify my vectors it worked fine. That is due to the check in `ListVectorSpace.make_array`. The same code does not work anymore with complexified vectors, since the check behaves differently in `ComplexifiedListVectorSpace.make_array` (since there is no specialization, the one from the base is used and the wrong type of `Vector` is checked for). So I guess I rather than the difference between `make_vector` and `make_array`, I stumbled upon the difference between `ListVectorSpace.make_array` and `ComplexifiedListVectorSpace.make_array`. If, for instance, one would copy the `make_array` implementation from `ListVectorSpace` to `ComplexifiedListVectorSpace` and replace the check for `Vector` by a check for `ComplexifiedVector` (pseudocode here, sry), the two would at least behave similarly. But I don't have a strong opinion here.

**Comment by ftalbrecht** [comment]
> > ... @ftalbrecht do you really need the ability to call `make_array` with a list of wrapped objects?
> 
> No, actually I don't.

That is of course not true. I need to convert my backend vectors into something that lies in the source or range of the created oeprators. Thus, it needs to convert my backend vectors to vector arrays, not vectors...

**Comment by sdrave** [comment]
> > > ... @ftalbrecht do you really need the ability to call `make_array` with a list of wrapped objects?
> > 
> > 
> > No, actually I don't.
> 
> That is of course not true. I need to convert my backend vectors into something that lies in the source or range of the created oeprators. Thus, it needs to convert my backend vectors to vector arrays, not vectors...

And this is what `make_array([backend_vector1, backend_vector2, ...])` is for?

**Comment by ftalbrecht** [comment]
> > > > ... @ftalbrecht do you really need the ability to call `make_array` with a list of wrapped objects?
> > > 
> > > 
> > > No, actually I don't.
> > 
> > 
> > That is of course not true. I need to convert my backend vectors into something that lies in the source or range of the created oeprators. Thus, it needs to convert my backend vectors to vector arrays, not vectors...
> 
> And this is what `make_array([backend_vector1, backend_vector2, ...])` is for?

That does indeed work, *sigh*. Thx. What remains then is just the mismatch between `ListVectorSpace.make_array` and `ComplexifiedListVectorSpace.make_array`. The former accepts already wrapped vectors, while the latter does not.

**Comment by sdrave** [comment]
I think it is better to have clear semantics here as people already get easily confused when working with `ListVectorArrays`. So I have decided to remove the convenience functionality.

**Comment by ftalbrecht** [comment]
Fine with me.

**Comment by sdrave** [comment]
CI remembered me that things are not that easy. `make_array` is used on `Vector` objects in `ListVectorArrayOperatorBase` and `LinearComplexifiedListVectorArrayOperatorBase` and there is no obvious way around that.

**Comment by sdrave** [comment]
In #1408 I went into the other direction and added a `vector_type` to every `ListVectorSpace` which is used instead of `Vector` to decide whether or not pyMOR wrapping is necessary. Additionally, `ComplexifiedListVectorSpace` has gotten a `real_vector_type`.
