### ISSUE TITLE
add a parallelization framework to pyMOR

### ISSUE THREAD

**Issue by sdrave** [pymor/pymor#14]

**Comment by ftalbrecht** [comment]
Related to #119

**Comment by sdrave** [comment]
@ftalbrecht, not really: #119 is about adding tools which make creating bindings for MPI parallel solvers easier. This one is about parallelization of the algorithms in pyMOR.

**Comment by sdrave** [comment]
See #148.

**Comment by sdrave** [comment]
#148 has been merged. Closing this issue.
