### ISSUE TITLE
pyMOR AUR package

### ISSUE THREAD

**Issue by peoe** [pymor/pymor#1429]
I noticed that, so far, no packages are available for pyMOR on the Arch User Repository.

Is it okay to create (and maintain) an AUR package, in a similar fashion to, e.g. [bioPython](https://gitlab.archlinux.org/bot-test/community/python-biopython/-/tree/main)?

**Comment by peoe** [comment]
Ad 1) pacman and available AUR managers should be able to pull (optional) dependencies from the AUR. E.g. yaourt can search the AUR for packages via the `-a --aur` flags ([man page](https://linuxcommandlibrary.com/man/yaourt)).

I noticed, however, that some Python packages are not yet on either Arch Repository (official and user ones), so I'll have to add those as well.

Ad 2) The AUR supports multiple maintainers/contributors, which can be added via the packages build file. If anyone is willing to partake in maintenance I'll gladly put them on there.

Ad 3) Oops, fixed that!

**Comment by renefritze** [comment]
> Okay, that's something I could handle then.

Better hold off on that though for a little while. The jupyter visualization situation is (again) in flux and we're likely changing to something else soon. 
> 
> [Fenics](https://aur.archlinux.org/packages/dolfin/), [ngsolve](https://aur.archlinux.org/packages/ngsolve-git/), and [ngsolve](https://aur.archlinux.org/packages/deal-ii) are all available in the AUR.

Excellent. (second ngsolve is deal.II)

**Comment by renefritze** [comment]
What's the status of this?

**Comment by ftalbrecht** [comment]
I actually cannot recall if @peoe contacted me, or what the result was. I am still willing to step in as 2nd maintainer, but won't do any initial work on this.

**Comment by peoe** [comment]
I did some work on this (and thought I wrote an email to @ftalbrecht, but I apparently missed out on that):
https://aur.archlinux.org/packages/python-pymor

**Comment by renefritze** [comment]
Great. I assume rebuilding on new releases is not automatic, but easy?

Once @ftalbrecht is a co maintainer should we close this issue then?
