### ISSUE TITLE
Remove 'almost_equal' from 'VectorArrayInterface' ...

### ISSUE THREAD

**Issue by sdrave** [pymor/pymor#143]
... or provide a default implementation in terms of norms.

Right now, the semantics of `almost_equal` is to do a `float_cmp` for each component pair of the vectors. I see no reason, why it would not be ok to do

||u - v|| <= rtol * ||v|| + atol

instead, where the norm could be 'sup', 'l2', or 'l1'.

Right now, we only use `almost_equal` only in `trivial_basis_extension` and the tests, anyhow.

I would propose to completely remove `almost_equal` from the interface and add a free function `almost_equal` which can also be given a scalar product as norm.

**Comment by ftalbrecht** [comment]
Sounds reasonable. In a way, the old behaviour is more like a `float_cmp` extension for vectors.

How did you come across this? Do you have an application for an almost equal measured in a specific norm?

Anyway, I have no objections...
