### ISSUE TITLE
Remove Python fallbacks for Cython modules

### ISSUE THREAD

**Issue by sdrave** [pymor/pymor#145]
1. The Python versions have horrible performance, so they should never be used.
2. Newcomers might think that pyMOR is slow instead of learning how to properly install it.
3. Code duplication.
4. More or less unmaintained as nobody ever runs this code.

**Comment by ftalbrecht** [comment]
+1

**Comment by sdrave** [comment]
@renemilk, any objections from the packaging front?

**Comment by sdrave** [comment]
Done in b960c6ffa3d97bad5af6a8343423695ddc69127d.

**Comment by sdrave** [comment]
We still need to update the README!

**Comment by sdrave** [comment]
README updated in b3cefd705af1edef3755c3ee2fd2665520357b6e.
