### ISSUE TITLE
Overview of available MOR methods

### ISSUE THREAD

**Issue by lbalicki** [pymor/pymor#1458]
It would be nice to have an overview of available MOR methods in the documentation where it is made clear in which problem setting which methods can be used. Maybe even a decision tree which leads to the possible/ideal method for a problem.

**Comment by sdrave** [comment]
Since MOR methods work on specific types of `Models`, this should go along with an overview of the existing models in pyMOR.

**Comment by sdrave** [comment]
Implemented in #2266.
