### ISSUE TITLE
Improve 'Coding style' section in CONTRIBUTING.md

### ISSUE THREAD

**Issue by sdrave** [pymor/pymor#1468]

**Comment by renefritze** [comment]
Do you have concrete ideas what to improve?

**Comment by sdrave** [comment]
I opened the issue mainly to document that we discussed this in the last dev meeting. Some things that might be relevant:

- How to write which assertions.
- Naming conventions for tolerances and their meaning (e.g. when to fail and when to stop).
- When to use `warnings.warn` or to `logger.warning.
- Use of builtins as function parameters.
- Use of `__auto_init`.
- If and when to copy/paste API documentation in derived classes.
- Naming conventions for variables (e.g. use verbose names instead of letters).
