### ISSUE TITLE
AdvectionOperatorP1 with advection_function=None

### ISSUE THREAD

**Issue by moro1111** [pymor/pymor#1489]
**Describe the bug**
In the documentation of the `AdvectionOperatorP1` it is stated:

> advection_function

    The Function v(x) with shape_range = (grid.dim, ). If None, constant one is assumed.
But when calling the `AdvectionOperatorP1` with no `advection_function` (i.e. `advection_function=None`) the handling of the default option `None` is missing.

**To Reproduce**
```
from pymor.basic import *
from pymor.discretizers.builtin.cg import AdvectionOperatorP1

grid = OnedGrid()
boundary = EmptyBoundaryInfo(grid)
operator = AdvectionOperatorP1(grid,boundary)
operator.assemble()
```
The default option `None` is never checked, therefore, while trying to invoke the `advection_function` during `operator.assemble()`, the `advection_function` is still `None`, instead of the promised constant one function. Hence, the error `'NoneType' object is not callable` is thrown.

**Comment by ftalbrecht** [comment]
I stumbled upon something similar some time ago (without reporting). I for one do not find it completely obvious what a suitable default advective direction would be in the multi-dimensional case and propose to drop the default altogether.

**Comment by sdrave** [comment]
I would also be in favor of dropping the default. Would you agree @moro1111?

**Comment by moro1111** [comment]
I found the functions `L2ProductP1`, `DiffusionOperatorP1` and `AdvectionOperatorP1` with its default options a useful tool to get an easy access to the common inner L2 inner product matrices for the products `(u,v)`, `(grad u, grad v)` and `(grad u, v)` for an arbitrary grid. So i would argue, that the constant one function is a suitable default advection. But i would also agree, that accessing those matrices is most likely not a common use-case for people just working with pyMOR. 

And even if the default is dropped, one could still manually pass the constant function for the same result.

**Comment by sdrave** [comment]
Ok, if it's useful for you then I will prepare a PR to fix `advection_function=None` ..
