### ISSUE TITLE
Migrate to new Travis infrastructure

### ISSUE THREAD

**Issue by sdrave** [pymor/pymor#149]
@renemilk, Travis has a new build infrastructure which, of course, makes things more complicated for us:

http://docs.travis-ci.com/user/migrating-from-legacy/

**Comment by renemilk** [comment]
Yay us. Will tackle that soon.

**Comment by renemilk** [comment]
1. As is we need our ppa for build-deps
2. There's an approval process for additional deb sources
3. They have a three month backlog on that list.

I'll see if we can get away w/o our ppa for now, but otherwise this issue will involve a lot of waiting.

**Comment by renemilk** [comment]
With 38079e8b0ed054795ee1c4ad6b556e96b1a735a6 and 358335441d5575a0220909ffca0acf98cb186201 we're no longer dependent on our own ppa for "external" packages. We could just list the python-pymor-demos dependencies now instead of adding the ppa and installing that package. Will using the fenics ppa become necessary, @sdrave  or could we get away with the versions in travis' ubuntu? Or hope the fenics people get it whitelisted.

**Comment by sdrave** [comment]
Don't know. I have developed the bindings with the PPA version, i.e. 1.6.0. As far as I know, @ftalbrecht has used the current git HEAD. On 14.04, the available version seems to be 1.3.0. I havn't tested it, but I would not be surprised if this is too old. Do you know, which Ubuntu version the new travis workers are based on?

**Comment by renemilk** [comment]
It's not really documented, but http://blog.travis-ci.com/2015-08-19-using-docker-on-travis-ci/ mentions trusty.  I'll test with 1.4.0 in a bit. If that fails we can be almost certain 1.3 will also fail. I'd consider marking the respective array test xfail depending on the fenics version an ok interim measure.

**Comment by sdrave** [comment]
Marking with xfail is probably hard as we have no specific fenics tests, only fixtures. Right now, the tests simply will not be executed when fenics is not available. So not testing fenics on travis is an easy option. However, as we probably will not use the code ourselves very often, continuous integration would be very nice ...

On the other hand, I would assume that the old travis infrastructure will degrade pretty fast, so we probably cannot postpone migrating forever.

**Comment by ftalbrecht** [comment]
On a side note: I found [instructions on how to compile dolfin in a virtualenenv](https://bitbucket.org/fenics-project/fenics-web/pull-requests/9/added-python-virtualenv-installation/diff). But I do not think this will help too much, as compiling dolfin takes forever and uses up all your ram and a little more...

And yes, I was using the current head of dolfin.

**Comment by renemilk** [comment]
https://travis-ci.org/pymor/pymor/jobs/84081653
> Installing APT Packages (BETA)
Disallowing packages: python-pytest, python-pyside, cython, python-sympy, python-opengl, python-docopt, python-pyvtk

:disappointed:

**Comment by renemilk** [comment]
Travis was almost ready to switch to 14.04 a year ago.... https://github.com/travis-ci/travis-ci/issues/2046
The only way around 12.04 now seems docker images. Which I'm not willing to do atm.

**Comment by renemilk** [comment]
Even with extension ```travis_wait pip install pyside``` does not succeed. I'll disable it for for now to discover the problems coming after it.

**Comment by ftalbrecht** [comment]
Considering [their milestone](https://github.com/travis-ci/travis-ci/mi
lestones/Ubuntu%2014.04%20-%20Trusty%20Tahr), they seem to be ready for
14.04 roughly in April of 2016^^

**Comment by renemilk** [comment]
Not entirely sure what happened now: https://travis-ci.org/pymor/pymor/jobs/84104703

**Comment by ftalbrecht** [comment]
Looks like a wrong/missing `scipy` issue. Alas why...

**Comment by renemilk** [comment]
Maybe the new travis infra fails to allow system packages for virtualenv and it  wasn't mentioned in the migration guide. Checking with c4dadee39761fc5ec6fcf21a9dbb9446baefd12b

**Comment by renemilk** [comment]
Scipy won't build :smirk:  https://travis-ci.org/pymor/pymor/jobs/84112889

**Comment by renemilk** [comment]
Our tests do work with fenics 1.3.0 btw, I've check with a default Ubuntu 14.04 machine.

**Comment by ftalbrecht** [comment]
Very nice. Since you have this setup lying around :), could you also do a quick test of the `thermalblock_fenics.py` demo (e.g., with `-e 2 2 2 20` arguments) and compare the results to #146.

**Comment by sdrave** [comment]
@renemilk, since #168 is merged, I guess we can close this one?

**Comment by renemilk** [comment]
Indeed.
