### ISSUE TITLE
Automagic GUI construction for Models

### ISSUE THREAD

**Issue by renefritze** [pymor/pymor#1517]
### Discussed in https://github.com/pymor/pymor/discussions/1510

<div type='discussions-op-text'>

<sup>Originally posted by **renefritze** December 21, 2021</sup>
 - looking at the [thermalblock_gui demo](https://app.codecov.io/gh/pymor/pymor/blob/main/src/pymordemos/thermalblock_gui.py) we should investigate why `ReducedSim._first` seems to be called not even once. Also see how difficult clicking some buttons with pytest-qt would be.
 - Add case that also hits the bottom `detailed_data` [branch](https://app.codecov.io/gh/pymor/pymor/blob/main/src/pymordemos/analyze_pickle.py)
 - `src/pymor/scripts/*` basically have no relevant coverage
 - [jupyter stuff ](https://codecov.io/gh/pymor/pymor/tree/main/src/pymor/discretizers/builtin/gui/jupyter) show very little coverage. They're used in tutorial tests though that do upload coverage data. So there's something amiss there. </div>

**Comment by sdrave** [comment]
Implemented in #2061.
