### ISSUE TITLE
Move 'with_' from 'BasicInterface' to 'ImmutableInterface'?

### ISSUE THREAD

**Issue by sdrave** [pymor/pymor#154]
Right now we have a default implementation that calls `__init__` and tries to deduce the arguments from the attributes of the object. For mutable objects this does not seem reasonable, so we should not have such a default implementation and I do not see why each subclass of `BasicInterface` should be forced to implement `with_`.

**Comment by ftalbrecht** [comment]
Sounds reasonable to me.

**Comment by sdrave** [comment]
Has been implemented in #157.
