### ISSUE TITLE
`NumpyVectorSpace` is always real

### ISSUE THREAD

**Issue by artpelling** [pymor/pymor#1568]
The implementation of `NumpyVectorSpace` does not account for different types, which makes it real-valued per default.
This leads to unexpected behaviour, e.g. for `NumpyMatrixOperator` with complex-valued matrices.

MWE:

```
from pymor.operators.numpy import NumpyMatrixOperator
import numpy as np

A = NumpyMatrixOperator(np.array([1+1j]))
print(np.iscomplexobj(A.range.random(1)))
```

**Comment by sdrave** [comment]
This actually is not a bug but a design decision in pyMOR: `VectorArrays` in pyMOR are 'potentially complex' in the sense that, like with numpy, you can mutliply a real array with a complex number to get an array with complex entries. The `VectorSpace` does not differentiate between real and complex numbers, and `random` is assumed to produce real-valued arrays. This is why `adaptive_rrf` has an `is_complex` argument.

If you search for 'complex' you will find quite a few issues/PRs discussing complex numbers in pyMOR. To summarize the painful history: explicitly marking a `VectorSpace` as real or complex causes quite a few issues, and, so far, no real benefit has been found in doing so. I will close this issue, but feel free to open a discussion if you feel that the handling of complex numbers in pyMOR should be changed.

**Comment by artpelling** [comment]
Understood. Sorry about the noise :no_bell:
