### ISSUE TITLE
Remove 'add_attributes' from 'BasicInterface'

### ISSUE THREAD

**Issue by sdrave** [pymor/pymor#158]
`add_attributes` isn't currently used at all, and it is probably not a good idea to do so. (One can still call `unlock` on an immutable object, which also makes it more clear that you are doing dangerous business.)

**Comment by ftalbrecht** [comment]
agreed

**Comment by sdrave** [comment]
Done in 8f347788ecbdf80a24d3bbb93a2f9d6fb606e198.
