### ISSUE TITLE
More flexible sampling of parameter spaces

### ISSUE THREAD

**Issue by drittelhacker** [pymor/pymor#1598]
**Is your feature request related to a problem? Please describe.**
`ParameterSpace` objects seem to have downgraded in importance and are at the moment mainly used to generate sets of parameter samples in `parameter values` dicts. However, in doing so, they are little flexible, as only methods for uniform and random sampling exist.

**Describe the solution you'd like**
Common sampling techniques also include log-equispaced sampling, or sparse grid sampling, so at least these should be added. Also, currently a count or a dict of counts is passed to the methods, implying that all parameters are sampled in the same fashion. This should become more flexible. Maybe by a dict of sampling methods allowing to specify, e.g. linear equidistant sampling in one direction, log-equispaced in another direction, and, e.g., a sparse grid for the rest, could be passed to a master sample routine, making the existing ones merely convenience methods?  Alternatively, the latter could be realized by a dict of dicts, or so, that allows to group the parameters of the space into the available sampling methods, which might be beneficial, e.g., for sparse grids.

**Comment by ftalbrecht** [comment]
We often need to sample log-spaced, which we currently do by hand. We also need to sample using different distributions for different parameter components, so: yes, I fully agree!

**Comment by sdrave** [comment]
@ftalbrecht, if you currently use other sampling strategies, maybe you want to draft a pull request?

**Comment by ftalbrecht** [comment]
I might, but only after prs #1338, #1339, #1387, #1529, #1603 and discussion #1604 is done. So, someone else might go about this before me...

**Comment by Congpy** [comment]
Hello all,

Like others I am also from University of Stuttgart, so we are expected to make a contribution on GitHub and I am assigned with pyMOR. This will be the first contribution I've ever done, so I was looking for something light. 

This issue seemed reasonable to me. I guess after setting up a developer environment, I should just add some functions like log-equispaced on ```src\pymor\parameters\base.py``` is that right?

**Comment by sdrave** [comment]
Hi @Congpy! yes, you would simply add some additional methods to `ParameterSpace`.

**Comment by Congpy** [comment]
Okay, thank you!

**Comment by pmli** [comment]
Logarithmic sampling will be done in the PR, the rest should have separate issues.
