### ISSUE TITLE
add a dg discretization

### ISSUE THREAD

**Issue by sdrave** [pymor/pymor#16]

**Comment by sdrave** [comment]
@ftalbrecht has done some work on this. Looking forward to the pull request 😄

**Comment by ftalbrecht** [comment]
I guess it does not really count, but the dune-gdt bindings provide a DG discretization by now: https://github.com/dune-community/dune-gdt-pymor-interaction/blob/master/notebooks/linearelliptic_swipdg.ipynb

**Comment by sdrave** [comment]
I guess, this is not happening any time soon, and I think there is not much need for it. Closing.
