### ISSUE TITLE
Numpy + Python 3.7

### ISSUE THREAD

**Issue by renefritze** [pymor/pymor#1626]
I just learned that numpy has dropped supported for 3.7 way ahead of its EOL June **2023**. 
I think we do have to react to this, since the now current numpy release no longer has wheels for 3.7
IMO we basically have two options here:
1. Just drop 3.7 altogether
2. cap numpy/scipy versions (and whatever else will stop shipping wheels now) for python 3.7 only to last-version-with-wheel-available

Since our (inofficial) policy for the minimum python/pip version has been following debian stable (bullseye has 3.9) I'm strongly pro option 1. 
Plus 1. is _much_ less work in implementation and maintenance. 

Opinions @pymor/all ?

**Comment by sdrave** [comment]
I agree ...

**Comment by pmli** [comment]
Agreed.
