### ISSUE TITLE
readthedocs build failing [again]

### ISSUE THREAD

**Issue by sdrave** [pymor/pymor#166]
The readthedocs build fails again because of Cython missing. But only for 0.3.x. @renemilk, did we do anything in master to fix this?

**Comment by sdrave** [comment]
So the 0.3.x build is still failing due to missing Cython. Strangely, master does not seem to be affected.

**Comment by renemilk** [comment]
I've cherry-picked b291f2461991c6dd338959e96dbeed4a4c987580 into 0.3.x and all seems well now: https://readthedocs.org/projects/pymor/builds/3550763/
