### ISSUE TITLE
Handle Fenics/Dolfin dependency on travis

### ISSUE THREAD

**Issue by renemilk** [pymor/pymor#169]
We need at least 1.4.0, travis runs ubuntu 12.04 and even then fenics is not whitelisted for apt installation and at 1.0 w/o additional apt-source. Even if travis updates to 14.04 that fenics (1.3.0) will also be too old.
Refs #168 #167

**Comment by sdrave** [comment]
If I understand correctly, we can resolve this, once #181 is resolved, as we have root access there?

**Comment by renemilk** [comment]
Yeah.

**Comment by renemilk** [comment]
Travis now uses ```14.04``` and adds ```ppa:fenics-packages/fenics``` before
```sudo aptitude install -y -q dolfin-dev python-dolfin```
