### ISSUE TITLE
Numpy 1.24 incompatibility

### ISSUE THREAD

**Issue by renefritze** [pymor/pymor#1692]
With the (currently 2 days old) numpy commit https://github.com/numpy/numpy/commit/189eb6e38e78a06d86292b5d503de12fe2bebe38 our tests against [numpy git started failing](https://github.com/pymor/pymor/files/9138919/log.txt)

The first problem is in matplotlib and I haven't looked it further.

The second problem is somewhat bad, if I did not miss anything obvious. For a certain setup
`np.ndarray.__mul__(VectorArray)` throws a `ValueError`. So `VectorArray.__rmul__` is never even called.

Since the 2022.1.0 release is happening today and I have a slight hope that the numpy behaviour will still change I decided to
1. require `numpy < 1.24`. This should give us ~5 months time to get ahead of this.
2. disable the numpy git tests in gitlab

**Comment by renefritze** [comment]
The commit is https://github.com/pymor/pymor/pull/1693/commits/d8a81732b3310dfd4cb57277a73e7a570ac915da

**Comment by renefritze** [comment]
We still need to remove the pin and update images accordingly.

**Comment by pmli** [comment]
Indeed.

**Comment by pmli** [comment]
> We still need to remove the pin and update images accordingly.

Can we do that before the next release?
