### ISSUE TITLE
transition from ftalbrecht to ftschindler

### ISSUE THREAD

**Issue by ftalbrecht** [pymor/pymor#1714]
Dear @pymor/main,

I'd like to transition from @ftalbrecht to @ftschindler (for obvious reasons :P), and would like to use this issue to collect ideas/things we need to consider/take care of when doing so. How would we proceed?

* [x] add @ftschindler as owner
* [ ] update `.mailmap`?
* [ ] rewrite mentions/assignments
* [ ] remove @ftalbrecht as owner

**Comment by renefritze** [comment]
Add a mailmap entry for the autogenerated github user email for ftschindler. 

If you want to be fancy, use the python github api client and o through everything and switch mentions/assignements and so forth.

**Comment by ftalbrecht** [comment]
> Add a mailmap entry for the autogenerated github user email for ftschindler.
> 
> If you want to be fancy, use the python github api client and o through everything and switch mentions/assignements and so forth.

Do you have an example for the latter, a quick search yielded either too much or too little.

**Comment by ftalbrecht** [comment]
So, what I could come up with is roughly
```python
from github import Github
token = '...'
g = Github(token)
repo = g.get_repo('pymor/pymor')
issues = repo.get_issues(assignee='ftalbrecht', state='all')
page_id = 0
while True:
    page = issues.get_page(page_id)
    if len(page) == 0:
        break
    page_id += 1
    for issue in page:
        issue.add_to_assignees('ftschindler')
        issue.remove_from_assignees('ftalbrecht')
```
Tried this for a single issue, worked. But since I'm owner (and I could break everything), some feedback/approval would be welcome, @renefritze @sdrave

**Comment by renefritze** [comment]
That was actually way easier just using the web UI.

I was more thinking of subscriptions were you'd want to (also?) subscribe with your new username.

**Comment by ftalbrecht** [comment]
> That was actually way easier just using the web UI.

Where you can do this for more than one issue/pr?

**Comment by renefritze** [comment]
Filter issues by assignee -> Select all -> (in table header) Assign -> check new, uncheck old

**Comment by sdrave** [comment]
Can this be closed, @ftschindler?

**Comment by ftschindler** [comment]
> Can this be closed, @ftschindler?

Yes, thx for the reminder.
