### ISSUE TITLE
non-deterministic test failure

### ISSUE THREAD

**Issue by renemilk** [pymor/pymor#172]
There's only an empty diff between
https://travis-ci.org/pymor/pymor/builds/85542844
and
https://travis-ci.org/pymor/pymor/builds/85557805

Other than that the python 3 tests work btw. (#134)

**Comment by renemilk** [comment]
And then there's https://travis-ci.org/pymor/pymor/builds/85557812 which doesn't have the failure in either builder.

**Comment by sdrave** [comment]
This is somewhat disturbing. Have you checked if the same thing happens locally?

**Comment by renemilk** [comment]
Nope, cannot replicate locally.

**Comment by sdrave** [comment]
Have we already seen this in master or is this somehow related to Python 3?

**Comment by renemilk** [comment]
Haven't seen it with master, no.

**Comment by sdrave** [comment]
@renemilk, have you encountered this again, or should we assume that the problem has resolved itself?

**Comment by renemilk** [comment]
Nope, haven't seen it this year. Am ok with assuming self resolving bug.
