### ISSUE TITLE
Add a QuantifiedCode badge to README.md ? 

### ISSUE THREAD

**Issue by renemilk** [pymor/pymor#173]
In the wake of #137 I've setup QuantifiedCode with my pymor fork. You can see the [issue list](here). Which imo is a lot nicer and more helpful than what landscape got us. Sadly there does not seem to be time series evaluation of the findings as landscape had. On the upside, pretty much everything concerning the analysis is web-configurable. I've invited @sdrave and @ftalbrecht to be admins on the  QuantifiedCode project, so you can see better for yourselves. 

Lastly: badge code [![Code Issues](https://www.quantifiedcode.com/api/v1/project/6d1a61431d364c9db9155cbb53b01167/badge.svg)](https://www.quantifiedcode.com/app/project/6d1a61431d364c9db9155cbb53b01167)

**Comment by sdrave** [comment]
So I have to sign in to have a look at the issues, or did I miss something?

**Comment by renemilk** [comment]
Yeah, looks like. I didn't notice that when setting it up ofc. Was too nice of a service I guess to have no catch...

**Comment by sdrave** [comment]
Ok, it seems I no longer have to sign in to look at the issues.
I guess it will require some configuration, but overall it might be useful. Not sure, however, if we want to add a bade. I mean, 230 potential bugs ... Are we gonna advertise that?

**Comment by renemilk** [comment]
OTOH, If it's not in our face we won't bother checking them out.

**Comment by renemilk** [comment]
Either way, I did trigger the frst time analysis for pymor/pymor now

[![Code Issues](https://www.quantifiedcode.com/api/v1/project/6061c0c1dc2a43fda5319eea7ace3151/badge.svg)](https://www.quantifiedcode.com/app/project/6061c0c1dc2a43fda5319eea7ace3151)

**Comment by sdrave** [comment]
If we manage to configure it in a way s.t. the number of issues is not ridiculously high, I am ok with adding the badge. However, from looking at the issues, I doubt that this will be possible without deactivating many useful tests.
In general, I believe there would be enough noise, when QC posts to pull request and sends emails when commits increase the issue count.

**Comment by sdrave** [comment]
@renemilk, please take a look at #163. Every issue found is IMHO a non-issue. What I really don't like is that this marks the PR with a mean red x in the issue list ...

**Comment by renemilk** [comment]
I've merhged master into mpi_merge and pushed to trigger a rebuild/analysis after disabling the mentioned issues as a way to test if only bug/critical category issues will mark X

**Comment by renemilk** [comment]
Nope. Even minor issues produce a red X. This problem may however go away if the problems aren't "new" any longer.

**Comment by sdrave** [comment]
Maybe we should ask them if they change the behavior or make it configurable.

**Comment by renemilk** [comment]
https://github.com/quantifiedcode/issues/issues/33

**Comment by programmdesign** [comment]
@sdrave @renemilk: you can configure all checks and the badge will only show the issues you turned on in your analysis. We also fix issues automatically now, so we can help you fix quite a few of them with just a click of a button. Give it a try. It'll open a PR so you can review the changes before merging. Let me know if you got any questions.

**Comment by renemilk** [comment]
I did try that for two issue categories in this project about 6 hours ago, @programmdesign , but I haven't gotten an email nor is there a new pull request. Could that be tied to that we currently have "analyze PR" setting on "Off" for this repo?

**Comment by programmdesign** [comment]
Let me check. Which issue did you want to fix?

On 09.12.2015, at 19:42, Ren? Milk <notifications@github.com<mailto:notifications@github.com>> wrote:


I did try that for two issue categories in this project about 6 hours ago, @programmdesign<https://github.com/programmdesign> , but I haven't gotten an email nor is there a new pull request. Could that be tied to that we currently have "analyze PR" setting on "Off" for this repo?

-

**Comment by renemilk** [comment]
I'd say if python 3 enabled landscape is working we drop this. Anybody against that?

**Comment by sdrave** [comment]
Go ahead!

**Comment by renemilk** [comment]
Done
