### ISSUE TITLE
Missing eigenvectors in POD function's output 

### ISSUE THREAD

**Issue by vahid-nateghi** [pymor/pymor#1730]
In your POD method, you output the reduced order states and the corresponding eigenvalues but not the selected eigenvectors. So it is not possible to find the mapping of the reduced states back to the original space to control the reconstruction error.

**Comment by pmli** [comment]
Hi, thank you for opening an issue. Do the methods in [`pymor.algorithms.svd_va`](https://github.com/pymor/pymor/blob/f357630387d6fe3765f2911830283cafe65acd54/src/pymor/algorithms/svd_va.py) work for you?

**Comment by vahid-nateghi** [comment]
Yes, it works. It is only when you call "svd_va" in your "pod" script, you don't save singular vectors.

**Comment by pmli** [comment]
Yes, that is by design, and maybe the expectation for RB methods. @sdrave is more familiar with this.

**Comment by HenKlei** [comment]
The POD method in pyMOR actually returns the high-fidelity states and not the reduced coefficients, i.e. the left singular vectors of the snapshot matrix and not the right ones. So the elements returned by POD are in the original space. This makes sense in the RB world, because you use POD to create a reduced basis. To obtain the corresponding reduced coefficients, you can simply project your state onto the POD basis using `.inner`.

**Comment by sdrave** [comment]
> Yes, that is by design, and maybe the expectation for RB methods. @sdrave is more familiar with this.

At pyMOR school we discussed that it might be helpful to add something like a `return_reduced_coefficients` argument to `pod` which will then also return the right singular vectors. In effect, with this option `pod` would become equivalent to one of the `VectorArray` SVDs with an additional orthogonality check and an dispatch on the available `svd` methods. Regarding the latter, I discussed with @artpelling again that we also might want to have a global `svd` method which does this dispatch based on `defaults` and input data.

I think there are many POD use cases where the user wants access to the right singular vectors. Of course you can always directly call the svd method, but this might not be obvious to the user. So I think it would make sense to add this  an optional argument, which defaults to false.
