### ISSUE TITLE
Input-output selection in `bode_plot`

### ISSUE THREAD

**Issue by pmli** [pymor/pymor#1767]
Currently, [`TransferFunction.bode_plot`](https://github.com/pymor/pymor/blob/4866fa087df441be1ffc8ebb09bd6ee34bed6cf1/src/pymor/models/transfer_function.py#L172) plots all pairs of inputs and outputs. It could be useful to be able to select only some of them.

**Comment by MohamedAdelNaguib** [comment]
Hello @pmli ,
My name is Mohamed and I am a computer science master student at the university of Stuttgart. As a project for a course called [Simulation Software Engineering](https://simulation-software-engineering.github.io/homepage/) we should chose an open-source software and make a contribution to it to be familiar with the software development process.

I am interested in contributing into [pyMOR](https://pymor.org). As I can see this issue has a label of good first which make it more intersting. I want to ask if there is someone currently working on this issue ?
if no, can I start working on it? is there any hints or useful tips that can help me in this issue ?

if there is someone who is currently working on this issue, can you please recommend me another issue that I can work on it knowing that I have good knowledge of python but that is my first time in the Sofrware Engineering field. 

Thanks for your time.
Bests,
Mohamed Ahmed

**Comment by pmli** [comment]
Hi @MohamedAdelNaguib, I don't think anybody is working on this, so you can start. It would involve adding new parameters to `bode_plot`, e.g., `input_indices` and `output_indices` (names could be different), which would be `None` by default and can be set to a tuple of integers denoting the indices of interest. The `bode_plot` method would then check if the indices are valid and, if yes, plot only the corresponding plots. If you need more help, feel free to ask.

**Comment by MohamedAdelNaguib** [comment]
Hello @pmli , Than you for your answer. I understand the issue now and I will start setting the environment and working on it. should. I add unit test for this ?

**Comment by pmli** [comment]
Sounds good. I'm not sure how a unit test would work for this, so extending the [LTI tutorial](https://github.com/pymor/pymor/blob/0270147f584c2614d094215ef3073170953c6998/docs/source/tutorial_lti_systems.md) might be better (`bode_plot` is already called there, so a second call to `bode_plot` with restricted inputs and outputs could be added below).

**Comment by MohamedAdelNaguib** [comment]
perfect ! ,, Thanks for the explanation and for you time.

**Comment by pmli** [comment]
That's a good question. I think the idea is to be able to select a subset of inputs and a subset of outputs, i.e., the second option you described.
