### ISSUE TITLE
Use antijet as default colormap?

### ISSUE THREAD

**Issue by sdrave** [pymor/pymor#177]
[This](https://gist.github.com/gramian/67585e5f2e9a294c3aa6) seems to be a nice default colormap.
When #176 is merged, using it should be straightforward.

**Comment by renemilk** [comment]
:+1:

**Comment by ftalbrecht** [comment]
pyMOR developer meeting: use as default after _the_ green issue has been resolved.

**Comment by gramian** [comment]
I would currently suggest to use the "perceptually uniform sequential colormaps" from matplotlib: http://matplotlib.org/examples/color/colormaps_reference.html . They are safe for colorblind people, have good grayscale conversion and look "smooth" due to the "perceptually uniform" design.

**Comment by sdrave** [comment]
Speaking with @gramian again, we should be fine with using matplotlib's color maps, in particular with its new default 'viridis'. We should have that once #176 has been merged. Closing this one.
