### ISSUE TITLE
Disable caching for discretizations by default

### ISSUE THREAD

**Issue by sdrave** [pymor/pymor#178]
Currently, the default cache region for discretizations in `pymor.discretizations.basic` is `'disk'`. I propose to change this to `None`.  IMHO, pyMOR should behave as reproducible as possible by default. Having persistent cache entries on disk will change timings in subsequent runs. Moreover, first time users will probably be surprised that pyMOR dumps up to 1GB of data to disk. Re-enabling caching will be as simple as writing

```python
discretization.cache_region = 'disk'
```

Any objections?

**Comment by renemilk** [comment]
Sounds good. I'm  a little concerned if anybody new will do/find that though.

**Comment by sdrave** [comment]
At least, we could add an option to the demos ..

**Comment by renemilk** [comment]
That I like.

**Comment by ftalbrecht** [comment]
So, in view of #179, one would write
```python
discretization.enable_caching(region='disc')
```
to enable caching and
```python
discretization.disable_caching()
```
or
```python
discretization.enable_caching(region=None)
```
to disable caching again?

**Comment by sdrave** [comment]
Yes, but I would write:

```python
discretization.enable_caching('disk')
```

**Comment by sdrave** [comment]
Done in  4c67dd7.
