### ISSUE TITLE
Remove disable_caching, enable_caching from CacheableInterface

### ISSUE THREAD

**Issue by sdrave** [pymor/pymor#179]
`CacheableInterface` has the property `cache_region`. Since `disable_caching` just sets `cache_region` to `None`, whereas `enable_caching` sets `cache_region` to its given argument, I see no reason to keep these methods. (There should be one (and only one) obvious way to do it.)

**Comment by renemilk** [comment]
Agreed.

**Comment by sdrave** [comment]
Well, as it turns out, this is a bad idea, of course: The cache_region property cannot be modified directly on immutable objects, so we have to go through a method call.
Actually, `CacheableInterface.enable_caching` tried to directly set the property which I have just fixed in  8ce576f.
