### ISSUE TITLE
revisit CircleDomain

### ISSUE THREAD

**Issue by ftschindler** [pymor/pymor#1799]
Looking at the docs of [`CircleDomain`](https://github.com/pymor/pymor/blob/main/src/pymor/analyticalproblems/domaindescriptions.py#L253), I stumbled upon several things that look like a copy of the docs from `LineDomain`. In addition, the `dim` and `domain` properties don't seem to match the intent of a circle, as well as the computation of the `width`.

**Comment by sdrave** [comment]
The docs say

> Domain with the topology of a circle, i.e. a line with end points identified.

I'd say that it's relatively clear what that means: we take the geometry of a line and identify the endpoints, obtaining a circle. And, of course, a circle is a one-dimensional object. Note that none of pyMOR's domaindescriptions care about any embedding into a higher-dimensional space and non of pyMOR's discretizations would care about some extrinsic geometrical properties inferred from the embedding.

So I'm closing this as invalid. If you feel that further clarification is needed in the docstring, feel free to open a PR ..
