### ISSUE TITLE
Uniform Sample Test Breaks for Multidimensional Parameters

### ISSUE THREAD

**Issue by peoe** [pymor/pymor#1805]
**Describe the bug**
Multidimensional parameters causes the `test_uniform` test to fail. This is due to `sample_uniformly` now computing linspaces for every parameter, yielding `count**number_of_total_parameters` for `sample_uniformly(count)` - for the code in "To Reproduce" this equals 10000 samples instead of 100.

**To Reproduce**
In `src/pymortests/parameters/parameters.py` change
```python
@pytest.fixture(scope='module')
def space():
    return Parameters({'diffusionl': 1}).space(0.1, 1)
```
to
```python
@pytest.fixture(scope='module')
def space():
    return Parameters({'diffusionl': 2}).space(0.1, 1)
```

**Expected behavior**
I would expect `sample_uniformly` to either
 * yield `count` samples if I call `sample_uniformly(count)`, or
 * compute the correct amount of samples in `test_uniform`.

**Comment by renefritze** [comment]
Is this an issue for other sampling too? Do we need to document the behaviour somewhere so expectations get aligned?

**Comment by peoe** [comment]
As far as I can tell, the only sample methods for parameter spaces are `sample_uniformly` and `sample_randomly`. The second behaves as expected, and the first causes the bug mentioned here.

The amount of samples for `sample_uniformly` is properly documented, however the formulation `a single count that is taken for all |Parameters|` can be interpreted so that this then refers to `count` samples in total instead of `count` samples for each parameter. I'll add a change to the docstring to make this clearer.

There are however a handful of files that use `sample_randomly` (mostly demos) - I can't tell if they assume to get back `count` samples or the actual amount...
