### ISSUE TITLE
Add missing methods in operators.constructions

### ISSUE THREAD

**Issue by sdrave** [pymor/pymor#188]
We should add the following missing methods:
- `Concatenation`: ~~`jacobian`~~
- `ComponentProjection`: `apply_inverse`, `apply_inverse_adjoint`,
- `IdentityOperator`: ~~`apply_inverse`~~,  ~~`apply_inverse_adjoint`~~, ~~`restricted`~~
- `ConstantOperator`: ~~`apply_inverse`~~, ~~`apply_inverse_adjoint`~~, ~~`restricted`~~
- `ZeroOperator`: ~~`apply_inverse`~~, ~~`apply_inverse_adjoint`~~, ~~`restricted`~~, ~~`apply_adjoint`~~
- `VectorArrayOperator`: `apply_inverse`, `apply_inverse_adjoint`, ~~`restricted`~~
- `FixedParameterOperator`: ~~`apply_inverse_adjoint`~~, ~~`restricted`~~
- `AdjointOperator`: ~~`apply_inverse`~~, ~~`apply_inverse_adjoint`~~, ~~`restricted`~~
- `SelectionOperator`: ~~`assemble`~~, `restricted`

**Comment by sdrave** [comment]
I have set the 0.4 milestone for now, but most methods are not really needed very much, so I will defer most of it to a later release at some point.

**Comment by sdrave** [comment]
IdentityOperator: 00c7843, 214aee3
FixedParameterOperator: eae44e2
AdjointOperator: ba55bbc

**Comment by pmli** [comment]
What about `ZeroOperator.apply_adjoint`?

**Comment by sdrave** [comment]
`ZeroOperator.apply_adjoint` is now implemented in dfa475f.

**Comment by sdrave** [comment]
@pymor/pymor-devs, if nobody objects I will close this issue now.  Implementing the remaining methods would require some work and I do not really see a need for them in the near future.

**Comment by pmli** [comment]
@sdrave Sounds ok to me.
