### ISSUE TITLE
Move BitmapFunction out of the playground

### ISSUE THREAD

**Issue by sdrave** [pymor/pymor#194]
This should be an interesting `Function` for many users, so we should not hide it in the playground. Before moving, we should check again the implementation, though.

**Comment by sdrave** [comment]
@andreasbuhr, according to this [documentation](http://pillow.readthedocs.org/en/3.0.x/handbook/concepts.html), an image mode 'L' should imply 8 bit grayscale, so the additional check in `__init__` would not be necessary. I can also reproduce locally that an 16bit grayscale image has mode 'I'.

What version of PIL have you been using? According to [this](http://stackoverflow.com/questions/1996577/how-can-i-get-the-depth-of-a-jpg-file), there is supposed to be a `depth` attribute on the `Image` object which, however, is missing in my PIL version. If I remember correctly, you did not have it either?

**Comment by andreasbuhr** [comment]
I reproduced the problem I had. Indeed, it's sufficient to check for 'L' mode. The image I had problems with reports an 'I' mode.

**Comment by sdrave** [comment]
Done in 5f426dd.
