### ISSUE TITLE
BlockOperator.jacobian not implemented

### ISSUE THREAD

**Issue by peoe** [pymor/pymor#1942]
**Describe the bug**
When working with non-linear operators that produce linear jacobians, wrapping multiple operators into a `BlockOperator` (e.g. to represent a vector-valued output functional) results in `BlockOperator.jacobian()` to default to `Operator.jacobian()` which does not accept non-linear operators. In my opinion, `BlockOperator.jacobian()` should reference the `jacobian()` methods which the underlying operators implement.

**To Reproduce**
Create e.g. a FOM with a vector valued output including a `BilinearFunctional` operator. Calling `jacobian()` then fails due to non-linearity.

**Expected behavior**
`BlockOperator.jacobian()` should sequentially call `jacobian()` on the wrapped operators and not default to `Operator.jacobian()`.

**Additional context**
Fixing this will come in handy for writing a demo incorporating bilinear output functionals and the TR algorithm proposed in #1924. I'm currently working on a fix.

**Comment by sdrave** [comment]
This is not really a bug but a missing feature, IMHO. I updated the title and label accordingly ...
