### ISSUE TITLE
do not add uid to auto-generated name

### ISSUE THREAD

**Issue by sdrave** [pymor/pymor#198]
Right now, if not specified by the user, BasicInterface.name returns

```python
type(self).__name__ + '_' + self.uid
```

However, I never had a use case where adding the uid was helpful.
On the other hand, adding the uid to the name makes the name depend on global state (the uid depends on the order of object creation and the specific pyMOR run), which already broke caching for me (f5bc852de07d9a09cef50d4c1e98179ca66076be). I would propose to let the auto-generated name simply be the class name.

**Comment by ftalbrecht** [comment]
I agree. Never have had a use for this, either...

**Comment by sdrave** [comment]
Done in 5e33949.
