### ISSUE TITLE
handling of affinely decomposed data functions in analytical problems

### ISSUE THREAD

**Issue by sdrave** [pymor/pymor#205]
`EllipticProblem` currently has `diffusion_functions` and `diffusion_functionals` attributes for handling affinely decomposed diffusion tensors. The same would have to be done to allow affinely decomposed right hand sides or other data functions.

A more natural approach might be to chose `diffusion_function` as a `LincombFunction` and let the discretizer detect that case and to the right thing.

**Comment by ftalbrecht** [comment]
Without thinking too much about it I would opt for the latter...

**Comment by ftalbrecht** [comment]
pyMOR developer meeting: proceed
