### ISSUE TITLE
Casting VectorSpace/VectorArray dimensions to int

### ISSUE THREAD

**Issue by peoe** [pymor/pymor#2062]
**Is your feature request related to a problem? Please describe.**
I have been running scripts that at some point for some reason unintentionally set the dimension of the underlying `VectorSpace` as a `float`. Afterwards I'd like to use NumPy related methods such as `np.eye(<space>.dim)`. This fails because the `VectorSpace` returns a `float` which NumPy does not expect in the method call.

**Describe the solution you'd like**
I'd propose to cast the dimension as an integer in the `VectorSpace` constructor(s). Space dimensions can always be expected to be integers meaning this should be safe enough, but I'd like some feedback before I open a (admittedly simple) PR.

**Additional context**
To reproduce the behaviour try running

```python
import numpy as np
from pymor.vectorarrays.numpy import NumpyVectorSpace

dim = 5.
space = NumpyVectorSpace(dim)
data = np.eye(int(space.dim)) # this succeeds
data = np.eye(space.dim) # this fails
```

**Comment by pmli** [comment]
I think it would be better to raise an exception. Casting to `int` might hide some real issues.
