### ISSUE TITLE
Allow 'pip install pymor' to work even when numpy/scipy are not installed yet

### ISSUE THREAD

**Issue by sdrave** [pymor/pymor#209]
Current pip versions are able to install all dependencies without error. An option might be to issue a verbose warning (using `sleep`), when the missing dependencies are not installed yet. (We could then also warn that an appropriate toolchain is needed to compile the missing stuff.)

**Comment by sdrave** [comment]
The changes in the remove_dependency_check branch seem to resolve this issue, even with the ancient pip shipped with Ubuntu 14.04.
@renemilk, could you have a look if this is safe to merge?

**Comment by renemilk** [comment]
The branch works on my Ubuntu 15.10 box, but not on travis: https://travis-ci.org/pymor/pymor/jobs/109566378

**Comment by sdrave** [comment]
@renemilk, not sure if this is true: the log says that the wheel failed to build but it later on claims to have successfully built scipy, pyMOR among other packages. (I believe I have experienced  a similar behavior locally.)

**Comment by renemilk** [comment]
Uhm, right. I just got the mail for the restored build. 
The pip install test adds about 13 minutes to the build time. I'll see about separating this into its own entry in the build matrix which in turn does not run py.test.

**Comment by renemilk** [comment]
Yupp, works: https://travis-ci.org/pymor/pymor/builds/109575478
hence #218
