### ISSUE TITLE
Adding first how-to guides

### ISSUE THREAD

**Issue by pmli** [pymor/pymor#2107]
See #1990.

To start, a how-to guide about running demos could be moved from "Getting Started" (see also #2022). Another could be about converting NumPy arrays to `NumpyVectorArrays`.

**Comment by sdrave** [comment]
As discussed, I have cherry-picked the TOC changes into #2266. We will add an FAQ section similar to the howto-guides in this PR for the 2024.2.

**Comment by sdrave** [comment]
We decided to add FAQs instead of howto guides.
