### ISSUE TITLE
instantiating `Timer` without arguments raises error

### ISSUE THREAD

**Issue by artpelling** [pymor/pymor#2148]
**Describe the bug**
The docstring states:
```
    You can use me as a context manager, plain instance or decorator to time execution
    of a code scope::

        with Timer() as timer:
            do_some_stuff()
            do more stuff()
        #outputs time in (s)
```
which raises an error, because `section` is a mandatory argument.

**Comment by sdrave** [comment]
Actually, I'd like to resolve this issue by removing the code. It's used nowhere in pyMOR, and I don't think that it belongs into a library like pyMOR. @artpelling, would you agree?

**Comment by artpelling** [comment]
> Actually, I'd like to resolve this issue by removing the code. It's used nowhere in pyMOR, and I don't think that it belongs into a library like pyMOR. @artpelling, would you agree?

Well, I've jused it quite often but I see your point. I don't have any objections :)
