### ISSUE TITLE
Scalar Functions throw error with Parameters

### ISSUE THREAD

**Issue by artpelling** [pymor/pymor#2202]
Consider this snippet
```python
from pymor.analyticalproblems.functions import ConstantFunction
from pymor.parameters.base import Parameters


n = 1
f = ConstantFunction(np.ones(n))
mu = Parameters(x=n).parse(f)
```

 It works for `n>1` but `n=1` gives
```
ValueError: {x: [ConstantFunction()]} is incompatible with Parameters {x: 1} (parameter function x[0] not scalar-valued: ConstantFunction: x -> [1.])
```

Any ideas how to fix it?

I've tried setting
```python
f=ConstantFunction(1.)
```
but that leads to
```
AttributeError: 'ConstantFunction' object has no attribute 'expression_obj'
```

It would be nice if it would work for both cases!

**Comment by artpelling** [comment]
> What do you want to use this for? To create a constant time-dependent parameter?

Thanks for the snippets. I am using it [here](https://github.com/pymor/pymor/pull/2203/commits/bdb2eef38f2fed51aed44effbdf0a04a26da86be#diff-b56ee21111d202854acd814abdf6c4487b678d1e52a29dbd1b43041ef3cbac09R774) as an input to `compute` which only accepts a NumPy array or `Function`.

**Comment by sdrave** [comment]
> > What do you want to use this for? To create a constant time-dependent parameter?
> 
> Thanks for the snippets. I am using it [here](https://github.com/pymor/pymor/pull/2203/commits/bdb2eef38f2fed51aed44effbdf0a04a26da86be#diff-b56ee21111d202854acd814abdf6c4487b678d1e52a29dbd1b43041ef3cbac09R774) as an input to `compute` which only accepts a NumPy array or `Function`.

I'm confused. Wouldn't it be more straightforward (and efficient) to use `input = np.zeros(self.dim_input)`?

**Comment by artpelling** [comment]
> I'm confused. Wouldn't it be more straightforward (and efficient) to use `input = np.zeros(self.dim_input)`?

Good point. In this case yes. In `impulse_resp`, however, I need a `Function`.
