### ISSUE TITLE
Support NumPy 2.0

### ISSUE THREAD

**Issue by pmli** [pymor/pymor#2205]
See https://github.com/numpy/numpy/issues/24300#issue-1828940995, [release notes](https://numpy.org/devdocs/release/2.0.0-notes.html), and [migration guide](https://numpy.org/devdocs/numpy_2_0_migration_guide.html).

**Comment by sdrave** [comment]
So I don't really want to start testing unstable numpy in ci again. Should be add the proposed 'numpy<2' pin for now?

**Comment by pmli** [comment]
> Should be add the proposed 'numpy<2' pin for now?

Sounds good to me.
