### ISSUE TITLE
rename reductors

### ISSUE THREAD

**Issue by sdrave** [pymor/pymor#224]
@JuliaBru told me that `pymor.reductors.linear.reduce_stationary_affine_linear` and
`pymor.reductors.stationary.reduce_stationary_coercive` are not very intuitive names, and I agree. How should we name them (@ftalbrecht)?

**Comment by sdrave** [comment]
Maybe `reduce_coercive` and `reduce_coercive_simple` in `pymor.reductors.coercive`?

**Comment by ftalbrecht** [comment]
What you propose could do. I do not have a better name at the moment...

**Comment by sdrave** [comment]
Done in 16a56cb5b0212cd138b7cb64dabc29feffc4fb64.
