### ISSUE TITLE
merge fixes in python3 branch back to master

### ISSUE THREAD

**Issue by sdrave** [pymor/pymor#228]
Just to ensure we do not forget to do this before 0.4.

**Comment by renemilk** [comment]
Relevant were:
- 03c5a9166d4cfcd0bc191d6c0c095bf22a87f089
- 9e38162f4aa48efcb8811ad0e5081e6f17f37954
- 96aab259d1dbb705fbc71c0759cb8e260a2b0891

Only the last one was not already on master, which I've corrected just now.
