### ISSUE TITLE
eigs fails for operators on small dimensional spaces

### ISSUE THREAD

**Issue by sdrave** [pymor/pymor#2280]
```python
import numpy as np
from pymor.basic import NumpyMatrixOperator
from pymor.algorithms.eigs import eigs
eigs(NumpyMatrixOperator(np.eye(2)), k=1)
```

fails at `assert l > k`.

```python
import numpy as np
from pymor.basic import NumpyMatrixOperator
from pymor.algorithms.eigs import eigs
eigs(NumpyMatrixOperator(np.eye(3)), k=1)
```

fails in `_arnoldi` at `return V[:l], H, v * R[l, l]` with an `IndexError`.

**Comment by sdrave** [comment]
The issues does not seem to be restricted to very small dimensions. The same code also fails for `np.eye(90)`.

**Comment by sdrave** [comment]
Ok, so the issue seems to be that sometimes, like for the identity matrix above, `gram_schmidt` will throw out a vector despite setting `atol` and `rtol` to `0`. For this specific case, I would be willing to replace vectors with norm zero with something random in `gram_schmidt`. With the current VA interface, this would mean a lot of copying, as we cannot overwrite any vectors. (This needs fixing.) Also, I am not sure if that is what we want here. So, what would you expect to happen in `_arnoldi` in such a situation, @lbalicki, @pmli, @drittelhacker?

**Comment by drittelhacker** [comment]
Not sure if I understand this right, and I don't have time to check this carefully at the moment, but a zero vector in the Arnoldi sequence would represent a lucky breakdown, i.e. the (rare?) event when an exact solution has been found.  See, e.g., https://en.wikipedia.org/wiki/Arnoldi_iteration

**Comment by lbalicki** [comment]
The first step to deal with this would be to add a proper convergence check to `_arnoldi` and `_extend_arnoldi` and return a smaller basis if they break down. This should be enough to deal with the identity matrix if `k=1`. However, there would still be issues with the identity if `k>1`. Currently, the `eigs` implementation will only work properly if all eigenvalues have algebraic multiplicity 1. Taking care of multiplicities is a bit more involved and would require some digging into proper ways to deal with them.

**Comment by sdrave** [comment]
@lbalicki, so if one would let `_arnoldi`, `_extend_arnoldi` detect that `gram_schmidt` removed a vector and fix the return values (smaller `V`, `H` and `f = 0`), would that work for `k=1`? Could it somehow make things worse for `k > 1`?
