### ISSUE TITLE
Getting Started page gives installation instructions incompatible with `zsh`

### ISSUE THREAD

**Issue by dmitry-kabanov** [pymor/pymor#2326]
**Describe the bug**
In the Getting Started page, there are instructions like

    pip install pymor[gui]

that are not compatible with the `zsh` shell. This shell is default in Ubuntu 22.04, so it can be confusing for many users. It should be `pip install "pymor[full]"` (single quotes should work as well).

**To Reproduce**
- Install Ubuntu
- Try to execute `pip install pymor[gui]`
- See that zsh complains about this command: `zsh: no matches found: pymor[full]`, because in `zsh` brackets are special.

**Expected behavior**
N/A

**Screenshots**
N/A

**System information:**
N/A

**Additional context**
N/A

**Comment by sdrave** [comment]
Thanks for the bug report, @dmitry-kabanov, you are certainly right. Do you want to open a pull request?

**Comment by dmitry-kabanov** [comment]
omg, sure! 😉
