### ISSUE TITLE
Harmonize file encodings?

### ISSUE THREAD

**Issue by renemilk** [pymor/pymor#233]
Currently we seem to mostly have python files with ASCII and with a few UTF-8. Should we harmonize that? 

```
cd pymor
└───> findn "*.py" | xargs file | ack ASCII | wc -l 
189
└───> findn "*.py" | xargs file | ack UTF | wc -l 
14
└───> findn "*.py" | xargs file | wc -l 
206
└───> findn "*.py" | xargs file | ack -v ASCII | ack -v UTF 
./src/pymor/playground/discretizers/__init__.py:             empty
./src/pymor/playground/core/__init__.py:                     empty
./src/pymor/vectorarrays/__init__.py:                        empty
```

**Comment by sdrave** [comment]
What would you mean by "harmonizing"? The UTF files are those which contain mathematical symbols in their docstring. Would you want to remove these symbols?

**Comment by renemilk** [comment]
Didn't check _why_ those files were UTF. Wouldn't it be nicer to have just one encoding, UTF, across the repo?

**Comment by sdrave** [comment]
Yeah, but aren't files which only contain ASCII characters at the same time UTF-8 files?

**Comment by renemilk** [comment]
Not according to ```file```, no.

**Comment by sdrave** [comment]
Sorry, I don't get it. Do you want to forbid non-ASCII characters or do you want to add an UTF-8 character to each source file?

**Comment by renemilk** [comment]
Apparently I-ve jut mis-aasumed the workings of ```file```
