### ISSUE TITLE
Implement block Arnoldi

### ISSUE THREAD

**Issue by pmli** [pymor/pymor#2340]
Currently, [`arnoldi`](https://github.com/pymor/pymor/blob/225e12abfb5f0985187e041c832b9a4326e88eb3/src/pymor/algorithms/krylov.py#L10) works only with a single vector. Extending this to multiple vectors would be of interest.

**Comment by sdrave** [comment]
To implement this, does one only have to replace `scal` by `gram_schmidt` and fix the offsets in subsequent `gram_schmidt` and `apply` calls, or is there some floating-point stuff to be aware of @drittelhacker?
