### ISSUE TITLE
NumPy array to VectorArray

### ISSUE THREAD

**Issue by pmli** [pymor/pymor#235]
Wrapping methods (such as `scipy.sparse.linalg.eigs`) that can work with operators means that operators' `apply` methods need to be wrapped so that they accept and return NumPy vectors/arrays. For returning NumPy arrays, there is an optional `data` property in `VectorArray`s, but for accepting, only `NumpyVectorArray` has a constructor which accepts NumPy arrays.

@sdrave How about adding `from_numpy` class methods to other `VectorArray`s, e.g. `BlockVectorArray`?

**Comment by sdrave** [comment]
I guess, this should also be seen in view of #234. I am a bit more open to add methods the the array themselves since I feel that there are a lot of cases where you do not have direct access to matrix data but you can access the vectors.

However, how would `BlockVectorArray.from_numpy` look like? At least, you would have to specify the subtype, I guess?

**Comment by pmli** [comment]
Yes, you're right, `VectorArray` is not enough, `VectorSpace` is necessary. This is actually what I have, because I'm given an operator, and therefore also its source. So, maybe a function `VectorSpace.from_numpy(array)`, which would call `self.type.from_numpy(array, self.subtype)`?

**Comment by sdrave** [comment]
Sounds good to me. Thinking of the `data` property, maybe, we should better call it `from_data`? This would also give us the option to use the method in other situations (e.g. instantiating vectors in external solvers which have a more complicated data format).

@ftalbrecht, @renemilk, any objections?

**Comment by ftalbrecht** [comment]
No, `from_data` sounds good to me. As a class method on vector arrays, then?

**Comment by sdrave** [comment]
I would agree with @pmli to add it to `VectorSpace` and the `VectorArray` implementations.

**Comment by ftalbrecht** [comment]
agreed

**Comment by sdrave** [comment]
This is related to #252.

**Comment by sdrave** [comment]
and to #253 ...

**Comment by sdrave** [comment]
Implemented in #239.
