### ISSUE TITLE
pip install git+https://github.com/pymor/pymor@python3 fails under Python 2 in clean venv

### ISSUE THREAD

**Issue by sdrave** [pymor/pymor#241]
The command succeeds after numpy has been installed into the venv. master does not have this problem. Also, the command works when using a Python 3 venv.

**Comment by renemilk** [comment]
Cannot replicate with python 2.7.11, pip 8.1.2, virtualenv 15.0.1

**Comment by sdrave** [comment]
@renemilk, works for me when I upgrade setuptools from  5.5.1 to 21.2.1. What version do you have?

**Comment by renemilk** [comment]
20.7.0-1

**Comment by sdrave** [comment]
Ok, so I really do not understand why this makes much of a difference, but putting 3to2 at the beginning of the dependency list resolves the issue (see  4c95dc0).
