### ISSUE TITLE
Somehow dependency handling broken with python3

### ISSUE THREAD

**Issue by andreasbuhr** [pymor/pymor#244]
Hi,

with python3, I keep getting messages like 

    There are some suggested packages missing:
    
    ipyparallel:  required for pymor.parallel.ipython
    
    pyside:       solution visualization for builtin discretizations
    
    
    try: 'pip install ipyparallel pyside'
    
even though pyside is installed and importable.

**Comment by andreasbuhr** [comment]
It seems the import name was not set in dependencies.py. See pull request:
https://github.com/pymor/pymor/pull/245

How did this ever work? At least on my machine, the import name is "PySide" also in python 2.

**Comment by renemilk** [comment]
Not sure yet what happened here, but all in-source references also use PySide.

**Comment by renemilk** [comment]
Puzzling. IMO #245 is the correct fix.

**Comment by sdrave** [comment]
I have merged #245, what about ipyparallel? `import ipyparallel` is working in my venv ..

**Comment by sdrave** [comment]
I also do not get the error message ... @andreasbuhr, can you have a look what happens in `setup.py` on your machine? Should be easy to set a break point.

**Comment by andreasbuhr** [comment]
ipyparallel was not installed correctly. It worked after an "pip uninstall ipyparallel; pip install ipyparallel".
