### ISSUE TITLE
remove 'product' parameter from 'apply2'?

### ISSUE THREAD

**Issue by sdrave** [pymor/pymor#247]

**Comment by sdrave** [comment]
I guess the only reason to have it would be to allow specialized `apply2` implementations in the solver that are faster than an `apply` on the operator followed by `apply2` on the product. Right now, there is no code making use of it, and I do not see that this will change in the future.

**Comment by ftalbrecht** [comment]
No objections against dropping this...

**Comment by ftalbrecht** [comment]
pyMOR developer meeting: no objections.
