### ISSUE TITLE
license - not clear

### ISSUE THREAD

**Issue by denfromufa** [pymor/pymor#250]
What is pymor's license? Not clear - MIT, GPL, LPL, BSD, Apache?
I understand that some of dependencies are GPL.

**Comment by renemilk** [comment]
Hi there! You can view our license information here: https://github.com/pymor/pymor/blob/master/LICENSE.txt
which is to say we're using the BSD-2 Clause license.

**Comment by renemilk** [comment]
Does that answer your question @denfromufa ?

**Comment by denfromufa** [comment]
Thank you, the issue can be closed.
