### ISSUE TITLE
Define a policy on adding algorithms which directly operate on NumPy arrays

### ISSUE THREAD

**Issue by sdrave** [pymor/pymor#253]
While pyMOR's interface design has many benefits (e.g. allowing matrix free implementations, mpi distributed data without any additional work), there are many relevant MOR algorithms which directly need access to the data. They fall into two categories:
1. algorithms which only require access to vector data (e.g. interfacing with M.E.S.S.)
2. algorithms which require access to vector and matrix data

We need to decide how to move on with pyMOR regarding these algorithms. I see the following options:
1. Do not allow any such algorithms in pyMOR.
2. Allow these algorithms by introducing abstract functions/methods (e.g. solve a certain Lyapunov equation) which are then only specialized for numpy-based discretizations.
3. Allow only algorithms of the first kind and make `VectorArrayInterface.data` more prominent/well-defined. Maybe add some provisions for the MPI distributed case.
4. Add a numpy_algorithms (or a better name) sub-package of algorithms/external library bindings which directly operate on numpy arrays. Define clear ways for the transition between the interface-based domain and the numpy domain.
5. A combination of 3 and 4.

In general I believe that 1. is not really an option, since it closes the door to large parts of the model order reduction world ..

**Comment by ftalbrecht** [comment]
There shall be a seperate module for "bad" algorithms (with a better name). No need for anything in between, just algorithms which act on the interfaces and those with any requirement...

**Comment by sdrave** [comment]
@ftalbrecht, @pmli, @renemilk, anyone has any idea regarding the naming of the old and the new module? I guess 'numpy(_)algorithms' or might be an option? Or maybe 'algorithms.numpy.foo'? All of this is rather quite longish.

**Comment by sdrave** [comment]
Given the state of the sys-mor branch, there does not seem to be a need for this ATM. Closing.

**Comment by sdrave** [comment]
To make my last comment clearer: In the sys-mor branch, the code which requires direct access to the data has been moved to modules in the bindings package.
