### ISSUE TITLE
replace 'BoundaryTypes' by strings

### ISSUE THREAD

**Issue by sdrave** [pymor/pymor#257]
The only reason we have a `BoundaryType` class is to prevent difficult to track errors due to typos. `'dirichlet'` is much nicer to write than `BoundaryType('dirichlet')`. At relevant places (constructor of a `DomainDescription`) we could still check with a global boundary type registry if that is really desired.

**Comment by ftalbrecht** [comment]
pyMOR developer meeting: no objections
