### ISSUE TITLE
Provide wheels for pyMOR?

### ISSUE THREAD

**Issue by sdrave** [pymor/pymor#260]
See https://github.com/pypa/manylinux.

**Comment by renemilk** [comment]
Ongoing: https://github.com/pymor/pymor-wheels

**Comment by renemilk** [comment]
I've managed to get wheels for python 3.{
4,5} : [pymor-wheels.zip](https://github.com/pymor/pymor/files/525000/pymor-wheels.zip)
Wheeling 2.7 currently fails during building pyzmq due to too old glibc (I think)

**Comment by sdrave** [comment]
Have wheels only for Python3 seems fine. The Python3.5 wheel has worked nicely for me.

**Comment by renemilk** [comment]
As for having wheels for master there's the question of where to deploy them. Github releases only works in conjunction with tags. We could deploy to our own wheelhouse https://pymor.github.io/wheels/ or pypi, both raise the issue of versioning in a way pip understands as properly ordered, I think.

**Comment by sdrave** [comment]
I guess it would be nice to push to pypi as a develoment version. Do you remember what the accepted version format was?

**Comment by renemilk** [comment]
Had to look it up: https://www.python.org/dev/peps/pep-0440/#public-version-identifiers
So we'd probably need to change the versioneer setup to generate something using the '.devN'. However N needs to be an integer there.

**Comment by sdrave** [comment]
@renefritze, I guess this can be closed?

**Comment by renefritze** [comment]
Depends. We only deploy (non-release builds) to our [own site](http://wheels.pymor.org/) still.

**Comment by renefritze** [comment]
We will keep deploying non-release wheels to our own site for now. Release wheels go to pypi.
