### ISSUE TITLE
Jupyter notebooks for demos?

### ISSUE THREAD

**Issue by pmli** [pymor/pymor#271]

**Comment by sdrave** [comment]
Good idea! This could also free us from having to do the tedious command line parsing. Only issue is that we use the demos for system testing as well. Maybe one could use `nbconvert`? But how to test different variants as we are doing now using the command line arguments?

**Comment by pmli** [comment]
I was thinking of using notebooks purely for demos, something new users could play with. I'm not sure how to do system testing with them. Maybe they would be appropriate for a different repository?

**Comment by sdrave** [comment]
pyMOR surely needs better learning materials. And I agree that notebooks would be the best option.

**Comment by ftalbrecht** [comment]
pyMOR developer meeting: use notebooks as user examples, use current demos mainly for testing.

**Comment by sdrave** [comment]
[This](http://mybinder.org/) looks very interesting. Would be great if we could make this work for the notebooks.

**Comment by sdrave** [comment]
Superseded by #540.
