### ISSUE TITLE
Use table of transformation rules instead of inheritance to implement reduction algorithms

### ISSUE THREAD

**Issue by sdrave** [pymor/pymor#274]
Currently we mainly use inheritance to implement reduction algorithms. For instance, `LincombOperator` overrides `projected` by calling the method on each of the sub-operators. Thus, to modify the algorithm for a specific operator, one has the following options:
- Change the implementation of `projected` for the given Operator type.
  This is only possible when the user is able to modify the class, which is usually not the case for Operators implemented within pyMOR. Also, if the algorithm should depend not only on the type but also on the specific instance, things start to get messy.
- Subclass the given type and override `projected`.
  The difficulty here is to get instances of the new type at the places where they are needed. This may be problematic when the operator in question is part of a larger hierarchy which is created by another algorithm in pyMOR (think of `LincombOperator`).

The proposed alternative would be to let algorithms like `project`, `assemble`, `project_to_subbasis` search an ordered list of transformations (functions). The first transformation for which an associated criterion applies is then executed. Matching criteria might be the type of the `Operator` or its `name`. The user may modify this list by inserting additional transformations or removing existing ones.

Possible downsides:
- It is not clear where pyMOR's default transformations should be defined. For instance, defining a transformation for a specific `Operator` in the module where the operator is defined raises the question how the default ordering of the rules should be determined. (It should not depend on import order.)
- The rule tables would be modifiable global state.
- More difficult to understand than inheritance?

Before deciding it might be helpful to find and discuss some concrete examples.

**Comment by sdrave** [comment]
One example can be found in #103 where we discussed to default `InstationaryDiscretization.mass` to `IdentityOperator(d.solution_space)` instead of `None`. However, this would have lead to `NumpyMatrixOperators` as reduced mass `Operators` instead of a new `IdentityOperator` which would be the better result in case of an l2-orthonormal basis. In general, `IdentityOperator.projected` cannot now whether the given reduced basis is orthonormal and adding this as an additional flag to the signature of `projected` would be quite clumsy given the fact that the information is only needed at very few places. Using a rule tables, a possible solution would be to add an additional rule for the projection of `IdentityOperator` if one knows that the basis is orthonormal.

**Comment by ftalbrecht** [comment]
pyMOR developer meeting: lets gather more information and use cases and investigate further.
