### ISSUE TITLE
Infinite recursion in apply for IdentityOperator * scalar

### ISSUE THREAD

**Issue by pmli** [pymor/pymor#276]
```python
from pymor.operators.constructions import IdentityOperator
from pymor.vectorarrays.numpy import NumpyVectorArray
import numpy as np

v = NumpyVectorArray(np.array([1, 2, 3]))
A = IdentityOperator(v.space) * 3

A.apply(v)
```
causes `RuntimeError: maximum recursion depth exceeded in comparison`.

(Observed when replacing `LincombOperator((A, I), (1, p))` with `A + I * p`.)

**Comment by sdrave** [comment]
Hi, I have just pushed f562037334f5f4a37d82615fa8f6232bf0477b14 to master and the 0.4.x branch, which should make the above code work.
