### ISSUE TITLE
dependencies.py doesn't work

### ISSUE THREAD

**Issue by pmli** [pymor/pymor#283]
Currently, it raises `TypeError: can only concatenate list (not "dict") to list`.

**Comment by renemilk** [comment]
Could you please tell me how/when you ran into this? On master with python3? Thanks!

**Comment by pmli** [comment]
Yes, on current master, running with python3.

**Comment by sdrave** [comment]
I guess the error occurs when executing `dependencies.py` as main script. Is probably broken for quite a while.

**Comment by renemilk** [comment]
Yeah, I wasn't seeing how we'd get that error otherwise..

**Comment by sdrave** [comment]
Do we need the __main__ script for anything, or can we simply remove it?

**Comment by pmli** [comment]
How do you suggest to list dependencies, such that they can be easily installed using pip?

**Comment by sdrave** [comment]
@pmli, `pip install pymor` should install all required dependencies. However, if you feel this is useful, we can fix the current `__main__`, of course ..

**Comment by pmli** [comment]
Aha, ok, then `pip install pymor; pip uninstall pymor` will only install the dependencies (for "developer mode")?

**Comment by sdrave** [comment]
Yeah, thats the intention.
