### ISSUE TITLE
merge parameters of gram_schmidt algorithm?

### ISSUE THREAD

**Issue by sdrave** [pymor/pymor#290]
Setting `reiterate` to `False` is equivalent to setting `reiteration_threshold` to 0. Setting `check` to `False` is equivalent to setting `check_tol` to `np.inf`, and the implementation could be changed to only perform the check when `check_tol` is finite.

**Comment by renemilk** [comment]
I like the more explicit way.

**Comment by sdrave** [comment]
Ok, closing.
