### ISSUE TITLE
mpi4py broken on Ubuntu 16.04

### ISSUE THREAD

**Issue by sdrave** [pymor/pymor#293]
So, Ubuntu managed to ship a broken mpi4py package:

https://bugs.launchpad.net/ubuntu/+source/mpi4py/+bug/1583432

We need to take care of this when releasing pyMOR 0.4 ...

**Comment by renemilk** [comment]
One thing we can do ofc is ship a rebuilt package in our PPA. Other than that we can't do much about it, can we?

**Comment by sdrave** [comment]
Guess not. We now have packages in our PPA, so closing this one.
