### ISSUE TITLE
use hypothesis for unit testing?

### ISSUE THREAD

**Issue by sdrave** [pymor/pymor#295]
Maybe we could [this](http://hypothesis.works/) to make our unit tests somewhat simpler?

**Comment by renemilk** [comment]
I'm not convinced it's worth the effort rewriting existing tests from what little I've read about the tool. 
Is there much more to gain than data setup like here: http://hypothesis.readthedocs.io/en/latest/extras.html#hypothesis-numpy ?

**Comment by sdrave** [comment]
Well until now, I have not found a nice way to parametrize fixtures with pytest (see the VectorArray fixtures). Using hypothesis might improve the situation. However, I haven't really looked at it myself .. [This](http://hypothesis.readthedocs.io/en/latest/stateful.html) also looks quite interesting.

BTW, when the indexing stuff is ready, we will have to rewrite large parts of the tests, anyway.

**Comment by pmli** [comment]
This can be closed, right?

**Comment by renefritze** [comment]
Indeed
