### ISSUE TITLE
Resurrect DiskVectorArray from the graveyard

### ISSUE THREAD

**Issue by sdrave** [pymor/pymor#300]
With #299, `DiskVectorArray` is moved to the graveyard as updating the code seems to worth it.
For the next release it would be nice to have a new implementation. Two variants would be possible:
1. Write a `DiskVector` and use `ListVectorArray`
2. Write a new `DiskVectorArray` which wraps an arbitrary other array by serializing it.

Right now, I feel that the first approach is more useful. In any case we should provide algorithms for transforming Operators/Discretizations to work with a disk variant of the given array.

**Comment by sdrave** [comment]
Since there is probably no immediate use case (@pymor/pymor-devs?), I would defer this issue to the future.

Regarding implementation: It would also be an option to handle this transparently in `ListvectorArray` by providing a custom `_list` attr which fetches its items from memory/disk as needed. A global default could control the behavior. This way, operators would not need to be adapted.

**Comment by sdrave** [comment]
So the code is very old an nonfunctional. We should probably remove it or completely rewrite it.

**Comment by pmli** [comment]
I guess 'interfaces', or maybe 'operators' (for `SelectionOperator`) and 'vectorarrays' (for `DiskVectorArray`).

**Comment by sdrave** [comment]
This does not involve an interface change so 'interfaces' does not apply. Regarding 'vectorarrays' and 'operators': Bindings for external solvers also implement `Operators` and `VectorArrays` but I would prefer to only attach 'bindings' to such issues. The idea of 'constructions' was to address stuff, which builds new objects out of existing one, e.g. `DiskVectorArray` or `BlockOperator`. - I have to admit though, that `NumpyVectorArray` would remain uncovered.

**Comment by pmli** [comment]
Well, I'm not against adding many more labels, seeing which ones get used and maybe removing unused ones.

**Comment by sdrave** [comment]
@pmli, would 'generic objects' be acceptable for now? I would propose to go the other way around and have as few labels as possible and see which labels are over-used ...

**Comment by sdrave** [comment]
I think that *if* we want to have such a feature, it would be better to directly implement this in the existing VectorArray implementations instead of having to wrap each Operator to accept a DiskVectorArray. Is anybody opposed to removing the code and closing this issue, @pymor/pymor-devs?

**Comment by pmli** [comment]
No objections from me.
