### ISSUE TITLE
transform range to xrange in 3to2

### ISSUE THREAD

**Issue by sdrave** [pymor/pymor#301]
Currently, tests fail for Python 2 if we apply the range->xrange rule of 3to2. We should check why this is the case and if we can work around this issue.

**Comment by renemilk** [comment]
Which fixer is that that executes that transformation, if not ```range```? https://github.com/pymor/pymor/blob/master/setup.py#L120 (only the fallback, default is all fixers active)

**Comment by sdrave** [comment]
The relevant line is here: https://github.com/pymor/pymor/blob/master/setup.py#L123

**Comment by renemilk** [comment]
Yeah, sorry, did not see that.

**Comment by renemilk** [comment]
First failure is in gmsh writer of all places. Relevant build:https://travis-ci.org/pymor/pymor/builds/189226604
