### ISSUE TITLE
Add apply_adjoint to NumpyGenericOperator?

### ISSUE THREAD

**Issue by pmli** [pymor/pymor#303]
I want to use data sparse matrices (e.g. identity plus rank-1) as operators, but `NumpyGenericOperator` doesn't define `apply_adjoint`, which I need. Is there already a way to wrap some `apply` and `apply_adjoint` methods or is it better to modify `NumpyGenericOperator.__init__`?

**Comment by sdrave** [comment]
Hmm, i would probably add an optional `adjoint_mapping` and implement `apply_adjoint` to raise an error if `adjoint_mapping` has not been specified. Regarding your application: Maybe it would also be an option to have a generic `Rank1Operator` which computes `R.lincomb(S.dot(V))`? One could also use a `Concatenation` of a `VectorFunctional` and a `VectorOperator`. Then one could have a `LincombOperator` of this Operator and an `IdentityOperator`.

**Comment by pmli** [comment]
I would add an optional `adjoint_mapping` to `NumpyGenericOperator`, for the general case. For my application, after constructing identity plus rank-1 (`LincombOperator` of `IdentityOperator` and `Concatenation` of `VectorFunctional` and `VectorOperator` looks good to me), I would also need `ComponentProjection` and its adjoint to project it down. Maybe I can add `apply_adjoint` to `ComponentProjection`?

**Comment by sdrave** [comment]
Unfortunately, if I am not mistaken, its impossible to implement `apply_adoint` for `ComponentProjection`. Doing this would be equivalent to set certain DOFs of a given `VectorArray`, which is impossible with the current interface. However, I could imagine adding a `set_components` method to `VectorArrayInterface` if it's really needed ...

**Comment by pmli** [comment]
Isn't the adjoint of `ComponentProjection`, which is a linear operator, the one that adds zeros (and multiplies with `source_product` and `range_product`)?

**Comment by sdrave** [comment]
Not sure what you mean by 'add zeros' What is the behavior for `ComponentProjection([1,2], NumpyVectorSpace(4).apply_adjoint` when no products are specified?

**Comment by pmli** [comment]
If
```
A = ComponentProjection([1, 2], NumpyVectorSpace(4))
v = NumpyVectorArray([1, 2, 3, 4])
w = A.apply(v)
```
I would imagine the following are true statements:
```
w == NumpyVectorArray([2, 3])
A.apply_adjoint(w) == NumpyVectorArray([0, 2, 3, 0])
```

**Comment by sdrave** [comment]
Ok, so we're on the same page, and now I see what you mean by adding zeros. However, this is exactly what is not supported by the `VectorArrayInterface`.  What you want would be some code of the form:

~~~python
def apply_adjoint(self, V):
    U = self.source.zeros(len(V))
    U.set_components(self.indices, V.data)
    return U
~~~

Would it be an option in your case to replace the `ComponentProjection` multiplication with a (sparse?) matrix? I am somewhat hesitant to extend the interface just to enable `apply_adjoint` for `ComponentProjection`.
