### ISSUE TITLE
Should we have a 'bindings' package?

### ISSUE THREAD

**Issue by sdrave** [pymor/pymor#321]
pyMOR currently contains bindings for fenics and pyamg. Soon we will also have bindings in master for ngsolve, pymess and slycot. I think it would make sense to have a central place in pyMOR where all glue code for external PDE/equation solver libraries can be found.

Any opinions on this? This is also related to #317.

**Comment by renemilk** [comment]
I'm for it.

**Comment by sdrave** [comment]
Done in #353.
