### ISSUE TITLE
TestCase for BitmapFunction

### ISSUE THREAD

**Issue by renemilk** [pymor/pymor#327]
Does anybody have an easily extractable usage of it for a new testcase? I've added pillow to optional requirements so we can test it.

**Comment by andreasbuhr** [comment]
The issue just created:
https://github.com/pymor/pymor/issues/328
uses it. And a test for symmetry is included. Should work as a start.

**Comment by renemilk** [comment]
I'll have a look, thanks.

**Comment by sdrave** [comment]
Maybe we could use the code from [here](https://www.uni-muenster.de/AMM/num/Vorlesungen/MultiScale_SS17/uebungen/blatt03.html) and turn it into a demo (see the "Zusatzaufgabe")?

**Comment by sdrave** [comment]
See #401.

**Comment by sdrave** [comment]
With #401 merged, we now have a demo test which utilizes `BitmapFunction`. That would be sufficient for me to close this issue, @renemilk?
