### ISSUE TITLE
NumpyVectorArray.__iadd__ and complex numbers

### ISSUE THREAD

**Issue by pmli** [pymor/pymor#333]
Calling `v += w`, where `v.data` is real and `w.data` is complex, raises `TypeError: Cannot cast ufunc add output from dtype('complex128') to dtype('float64') with casting rule 'same_kind'`. This is due to using NumPy's `+=` in `NumpyVectorArray.__iadd__`, without promoting types.

@sdrave is this expected behavior?

**Comment by sdrave** [comment]
I wouldn't say this is expected, since I didn't think about this case when implementing `__iadd__`. Generally, I do not have a strong opinion on this. So I would say, this should be decided between you, @pmli, and @andreasbuhr.

**Comment by pmli** [comment]
I encountered this when using `BlockOperator.apply`, which uses `+=`. I guess we could make `v += w` behave like `v = v + w` when necessary, but maybe another option would be to add an `is_real` or `dtype` attribute to vector arrays. When implementing different method, I generally have an idea if a vector array is real (e.g. [`reductors.lti.interpolation`](https://github.com/pymor/pymor/blob/8a3625b5dc3f235f87f3e2551d494694107c5732/src/pymor/reductors/lti.py#L15)) or complex (e.g. [`algorithms.sylvester.solve_sylv_schur`](https://github.com/pymor/pymor/blob/2d9a5feba6b31c2a708455b49b5afbdba92990ef/src/pymor/algorithms/sylvester.py#L13)).

**Comment by andreasbuhr** [comment]
Hi,
I can think of situations where I'd like to treat a real vector as if it was complex. And I can think of situations where this would cover a bug, like you expect a real vector but get a complex, and then you don't notice because there is no error.

If we have automatic type promotion you have to add code at places where you want to make sure your vector stays real.
If we do not have automatic type promotion you have to add code at places where you want to treat a real vector as if it was complex.

So I don't have a strong opinion. I just think we should have a decision and then we should stick to it.
I'd propose to have automatic type promotion everywhere.

**Comment by pmli** [comment]
I've thought about this a bit more. Besides operations like `+=` and `append` (for which I'd agree to have automatic type promotion), there are also methods for creating vector arrays, like `zeros` and `empty`. Currently, it is not possible to specify the data type when using `zeros`. This means that combining `empty(reserve=n)` and `append`s would first allocate a real vector array, and than promote it to complex if one of the vectors is complex. Maybe if would be desirable to immediately allocate a complex array. I could also imagine somebody wanting to use single/half/quad precision numbers. Also, looking abstractly, to define a vector space one also needs to specify the field it is defined over.

**Comment by sdrave** [comment]
I guess, there are basically two options:

1. `dtype` is an attribute of `NumpyVectorSpace`. We completely remove all type promotion from real to complex for output data (e.g. applying a real NumpyMatrixOperator to a complex array is forbidden, but a complex NumpyMatrixOperator may be applied to a real array, yielding a complex output array). We provide some convenience methods for casting between real and complex spaces where appropriate.

2. `dtype` is not an attribute of `NumpyVectorSpace`. We do type promotion everywhere possible. In particular, `__iadd__` can change `dtype`. We add an optional `dtype` argument to `NumpyVectorSpace.zeros`, `NumpyVectorSpace.empty`.

I guess option 1 would be cleaner, but I have no idea how much annoyance this would add for the user. This is also related to #259.

**Comment by pmli** [comment]
I guess option 2 is ok. I would just add that type promotion is avoided when possible. For example, when a linear combination with complex coefficients has to be computed, but the coefficients have zero imaginary part. This is already the situation in some parts, e.g. `NumpyMatrixOperator.assemble_lincomb`.
