### ISSUE TITLE
Pull requests are marked as failing due to PIP_ONLY tests

### ISSUE THREAD

**Issue by sdrave** [pymor/pymor#340]
The lights on all pull requests are red again, since the PIP_ONLY tests on travis are failing. Maybe there is an environment variable we can use to disable the tests?

**Comment by renemilk** [comment]
There is one of course: https://github.com/pymor/pymor/blob/master/.travis.script.bash#L16
Otherwise that check could never have worked. I "fixed" that block a while back though: https://github.com/pymor/pymor/commit/9586c1df3124e2ce64a5eb202433ee7e0f460f59
