### ISSUE TITLE
Select a subset of tests for a 'quick' marker in py.test

### ISSUE THREAD

**Issue by renefritze** [pymor/pymor#351]
As touched upon in #130 , it would be a nice to have relevant subset to complete in significantly less time than the full suite.

Sidenote: https://github.com/pytest-dev/pytest/issues/920 is blocking pytest-xdist usage for us.

**Comment by sdrave** [comment]
I guess this is quite hard to achieve. In many cases, we would want to reduce the number of fixture realizations (i.e. omit larger VectorArrays) ...

**Comment by renemilk** [comment]
With the pytest plugin I'm adding in #354 we could figure out which fixture realizations those are. Then we'd need another, activated by marker or cli arg, plugin to skip every realization not in that list. That would probably mean keeping a pickle of the runtimes dict in git and occasionally updating it.

**Comment by renemilk** [comment]
With regards to pytest-xdist, I've just come across https://github.com/firedrakeproject/firedrake/commit/0aa80bcdabf478e85fece4ae03a7e708c8d7a7d8
I see no reason not to fix this seed in our travis test script.

**Comment by renemilk** [comment]
Actually, pytest-dev/pytest#920 was fixed recently, so we can just require pytest 3.2 and don't need the workaround.

**Comment by sdrave** [comment]
I am still not sure if we should not rewrite the whole test suite at some point. In particular, the realization of parametrized fixtures for VectorArrays and Operators is a mess. Thus, I would not put too much effort into this ATM.

**Comment by renemilk** [comment]
Well, I am at least very sure that _I_ should not be rewriting our test suite :wink: 
As for putting effort into subset selection, I'm thinking a generic pytest plugin where you can select the X percentile of previously fastest realizations. Not a priority though, yes.

**Comment by sdrave** [comment]
I guess there is no point in keeping this issue open. pyMOR's  test suite will get a major overhaul at some point. For now, the current state seems acceptable.
