### ISSUE TITLE
Incompatible with numpy 1.12

### ISSUE THREAD

**Issue by renemilk** [pymor/pymor#357]
It wasn't immediately clear what's wrong, so I've opted to make an issue instead. 
1.12 was released yesterday: https://github.com/numpy/numpy/releases

**Comment by renemilk** [comment]
Branch didn;t trigger the issue because of pre-installed numpy in the docker images. 
"Fixed": https://travis-ci.org/pymor/pymor/builds/192353859 
https://github.com/pymor/pymor/commit/21767dd7abc91a95da2dcd79c7d28a4a1056ca5d

**Comment by renemilk** [comment]
Will you pick 1434bb1130313dcb1f643ac32af1a6317ff2a06c into master and 0.4 branches, @sdrave ?

**Comment by sdrave** [comment]
Fixed in 36f0ac2028874ff1cb57e647fafb3633cf3784db.
