### ISSUE TITLE
"pip install pymor" does not show the list of suggested packages, as it used to

### ISSUE THREAD

**Issue by andreasbuhr** [pymor/pymor#360]
Hi,

I just installed pymor in a venv (on jacen). It did not show me the list of suggested packages. I had to manually search for this list in the source to install these packages.

I did a 
pip install git+https://github.com/pymor/pymor@0.4.x

**Comment by renemilk** [comment]
Same on master py 3.5 and pip 9

**Comment by sdrave** [comment]
My suggestion would be to remove this feature. Instead, printing `pymor.config` could give advice about installing additional packages. Also, there is #376.

**Comment by renemilk** [comment]
Potentially relevant: https://github.com/pypa/pip/issues/2933

**Comment by sdrave** [comment]
@renemilk, should we remove the relevant code and close this?

**Comment by renemilk** [comment]
Yes
