### ISSUE TITLE
Sparse operators to source/range arrays

### ISSUE THREAD

**Issue by pmli** [pymor/pymor#363]
Currently, `NumpyMatrixOperator.as_(source|range)_array` do not allow converting sparse operators to vectorarrays (see [here](https://github.com/pymor/pymor/blob/ffbff4046faef7d731857b585be727cbcd3ca64a/src/pymor/algorithms/genericsolvers.py#L341)). Is this necessary? Input and output operators are actually commonly sparse (imagine boundary control/measurement on a small part of the boundary) and for these operators I need those methods.

**Comment by sdrave** [comment]
(Your links seem to be pointing to the wrong location.) What matrix shapes are you thinking of? E.g. you most definitely do not want to convert a 1e6 DOF PDE system matrix to a VectorArray ...

**Comment by pmli** [comment]
(Woops. [Correct link](https://github.com/pymor/pymor/blob/ffbff4046faef7d731857b585be727cbcd3ca64a/src/pymor/tools/io.py#L40-L41)) I thinking of shapes expected in, for example, [`discretizations.iosys.LTISystem.eval_tf`](https://github.com/pymor/pymor/blob/a4e0cad36b818b9dc180776262602513791b0d79/src/pymor/discretizations/iosys.py#L402-L441), i.e. tall and skiny for `as_range_array` and short and fat for `as_source_array`.

**Comment by sdrave** [comment]
Ok, if you actually have tall and skinny sparse matrices, I see no reason to forbid calling `as_range_array` or `as_source_array`. I see that `NumpyVectorSpace.make_array` already automatically converts its input to dense, so we can simply remove the assertions.

**Comment by pmli** [comment]
Ok, great. Made the changes in 4803316eaca277db820c6a53197047c6609c4e01.
