### ISSUE TITLE
Loading dense matrix from Matrix Market format

### ISSUE THREAD

**Issue by pmli** [pymor/pymor#364]
`pymor.tools.io._mmread` assumes the matrix is stored in coordinate format (see [here](https://github.com/pymor/pymor/blob/ffbff4046faef7d731857b585be727cbcd3ca64a/src/pymor/tools/io.py#L40-L41)). This seems strange, when other functions in `pymor.tools.io` allow `np.ndarray` type matrices.

**Comment by sdrave** [comment]
I agree that there is no reason to not support dense as well ..

**Comment by pmli** [comment]
Fixed in 238e6229a3ec5773f46174960f96ffefc5592cdd.
