### ISSUE TITLE
Search on readthedocs.io seems broken

### ISSUE THREAD

**Issue by ftalbrecht** [pymor/pymor#372]
Using [the search feature on pymor.readthedocs.io](http://pymor.readthedocs.io/en/latest/search.html) does not give optimal results: searching for Foo gives all places where Foo is referenced or mentioned, but not the place where Foo is actually defined; search for instance for `LincombOperator`.

**Comment by sdrave** [comment]
Why do you believe its broken? Seems to be a full text search and `operators.constructions` is in the results. If you want to look up a class, you should use the index ...

**Comment by ftalbrecht** [comment]
True, although the link to `operators.constructions` leads to the source code defining `LincombOperator`, not the documentation of `LincombOperator`. There used to be a time when a full text search for a class would yield the class documentation as first result. But this could very well be a regression of readthedocs, an not in our hand.

**Comment by sdrave** [comment]
Right, you have to click on 'pymor.operators package'. Would be nice, to exlude the source from search results, however ..

**Comment by sdrave** [comment]
Ok, so I have looked a bit into this: RTD actually overrides the sphinx search feature (which is working nicely) with its own index. I could not find any way to configure this behavior. @ftalbrecht, you might want to ask the RTD guys about this issue ..

**Comment by sdrave** [comment]
I do not think it is possible to fix this on our side. Closing.
