### ISSUE TITLE
ngsolve not available on travis

### ISSUE THREAD

**Issue by sdrave** [pymor/pymor#380]
For some reason, ngsolve does not seem to be present on travis. I pulled `pymor/testing:3.4`, where, indeed, no ngsolve seemed to be installed ...

**Comment by renemilk** [comment]
Please check if it's the same for 2.7 and 3.5

**Comment by sdrave** [comment]
Same for 3.5. Haven't tested 2.7, but ngsolve is Python 3 only ..
