### ISSUE TITLE
Annoying SparseEfficiencyWarning from scipy.sparse.linalg.splu

### ISSUE THREAD

**Issue by pmli** [pymor/pymor#386]
MWE (using current master):
```python
>>> import numpy as np
>>> import scipy.sparse as sps
>>> import scipy.sparse.linalg as spsla
>>> from pymor.operators.numpy import NumpyMatrixOperator
>>> from pymor.vectorarrays.numpy import NumpyVectorSpace
>>> I = sps.eye(2, format='csc')
>>> v = np.ones((2,))
>>> Iop = NumpyMatrixOperator(I)
>>> vva = NumpyVectorSpace.from_data(v)
>>> Iop.apply_inverse(vva)
NumpyVectorArray([[ 1.  1.]], NumpyVectorSpace(2))
>>> Iop.apply_inverse_transpose(vva)
/some_path/.virtualenvs/py3.4.6/lib/python3.4/site-packages/scipy/sparse/linalg/dsolve/linsolve.py:253: SparseEfficiencyWarning: splu requires CSC matrix format
  warn('splu requires CSC matrix format', SparseEfficiencyWarning)
NumpyVectorArray([[ 1.  1.]], NumpyVectorSpace(2))
```

Compare to no warning when using pure SciPy:
```python
>>> spsla.spsolve(I, v)
array([ 1.,  1.])
>>> spsla.spsolve(I.T, v)
array([ 1.,  1.])
```

**Comment by sdrave** [comment]
The reason for the different behavior is that `pymor.bindings.scipy.apply_inverse` calls `splu` instead of `spsolve` when the `spsolve_keep_factorization` default is set to `True`. Which it is by default.

**Comment by pmli** [comment]
Is there a way to fix this? I often need to solve `A x = b` and `A^T x = b` for the same sparse `A`. Is there a way to turn this warning off? Probably a better way to fix this is to use `tocsc` before every `splu` call. Maybe also `'csr'` format can be allowed, since [`splu`](https://docs.scipy.org/doc/scipy-0.19.1/reference/generated/scipy.sparse.linalg.splu.html#scipy.sparse.linalg.splu)'s returned object has a [`trans` parameter in its `solve` method](https://docs.scipy.org/doc/scipy-0.19.1/reference/generated/scipy.sparse.linalg.SuperLU.solve.html#scipy.sparse.linalg.SuperLU.solve).

**Comment by sdrave** [comment]
I guess we should look first, what is happening inside SciPy when `spsolve`/`splu` are called.

**Comment by pmli** [comment]
It seems `spsolve` and `splu` are independent: `spsolve` calls [`_superlu.gssv`](https://github.com/scipy/scipy/blob/7511430b3641d716998e095cf7e43cc9dbbedbc5/scipy/sparse/linalg/dsolve/linsolve.py#L189-L190) (which can use CSC or CSR), `splu` calls [`_superlu.gstrf`](https://github.com/scipy/scipy/blob/7511430b3641d716998e095cf7e43cc9dbbedbc5/scipy/sparse/linalg/dsolve/linsolve.py#L308-L309) (which can only use CSC).

**Comment by pmli** [comment]
So, the easy thing would be to add `matrix = matrix.tocsc()` before every `splu` call. This is basically [what `splu` would do anyway](https://github.com/scipy/scipy/blob/73f723a6ec2e7fc93314b1407336e71bb9ab6de0/scipy/sparse/linalg/dsolve/linsolve.py#L294). A more clever thing would be to also allow CSR format, pass the transpose to `splu`, and somehow detect this when using the `solve` method of `matrix.factorization`.

BTW, what is [this comment](https://github.com/pymor/pymor/blob/ad9d31813c9a0f56a67d34196d19bbd9a13a2b6f/src/pymor/bindings/scipy.py#L179) referring to?

**Comment by sdrave** [comment]
I guess the format conversion should be cheap in comparison to the actual decomposition. Also, the decomposition will probably require significantly more memory than a copy of the original matrix, so it should be safe to simply perform the conversion?

**Comment by sdrave** [comment]
Regarding the comment, see #411.

**Comment by pmli** [comment]
How about adding the conversions to CSC and maybe open another issue about including CSR? This way, the performance should be exactly the same as it is now, since `splu` would do the conversion by itself, except there would be no more annoying warnings. Including CSR seems to me like it would take significant effort, since `apply_inverse` and `apply_inverse_transpose` should both be able to use the same factorization.

**Comment by sdrave** [comment]
Sounds good to me.
