### ISSUE TITLE
__str__ and __repr__ for discretizations

### ISSUE THREAD

**Issue by pmli** [pymor/pymor#392]
This would be helpful for `InputOutputSystem`s.
@sdrave Would it be useful in general for discretizations?

**Comment by sdrave** [comment]
Yes, this would also be nice for `StationaryDiscretization` and `InstationaryDiscretization` ...

**Comment by pmli** [comment]
Ok. Then I will think about a good implementation for `InputOutputSystems` and its derived classes, and open a pull request.

**Comment by sdrave** [comment]
I think at least some work in that direction should enter the next release, so I am adding the 2019.2 milestone for now.
