### ISSUE TITLE
Random segfaults on travis

### ISSUE THREAD

**Issue by sdrave** [pymor/pymor#398]
See for instance [here](https://travis-ci.org/pymor/pymor/jobs/286709787). Might be an issue with pytest-xdist?

**Comment by sdrave** [comment]
I have disabled xdist in da9167565aaf45e9cb8c7cc6b5e5435127f21974, but we still have segfaults:

https://travis-ci.org/pymor/pymor/jobs/289523433

My first guess would be that this is related to the recently added ngsolve support. @renemilk, any ideas how to debug this?

**Comment by renemilk** [comment]
If you suspect ngsolve (only 3.5 builders are affected?) I suggest you wait until after I've upgraded the docker infrastructure since then we will have full control over debug options and such.

**Comment by sdrave** [comment]
Haven't seen any segfaults since @renemilk's build infrastructure changes. Hoping for the best and closing for now.
