### ISSUE TITLE
Can we drop testing on python 3.4, start testing with 3.7-rc?

### ISSUE THREAD

**Issue by renemilk** [pymor/pymor#400]
Debian stretch has 3.5, Current Ubuntu LTS (16.04) has 3.5 and current RHEL has no python 3 at all. With Anaconda on win we have 3.5 and 3.6. 
Therefore I think there's little use in still testing on 3.4 although it's EOL is still 18 months away. 
Coincidentally this would also make my task of updating our docker infrastructure from ubuntu 16.04 to debian stretch a whole lot easier, since cpython 3.4 does not build against stretch's openssl. 

Anybody disagree @pymor/pymor-devs ?

**Comment by pmli** [comment]
If I remember correctly, I only used 3.4 so far because pyside wasn't available for 3.5. Has this changed, or do you use something else now (I guess pyqt5, looking at `requirements-optional.txt`)?

**Comment by renemilk** [comment]
Correct. @sdrave added an abstraction for pyqt/pyside called qtpy a while back.

**Comment by pmli** [comment]
Ok, then I should be fine.
Maybe one off-topic question: without 3.4, do we want to use the `@` operator for matrix multiplication or do we stick with `dot` (or does it not matter)?

**Comment by ftalbrecht** [comment]
I do not have a strong opinion there, but a slight bias towards sticking with `dot`...

**Comment by renemilk** [comment]
Awesome. Since @sdrave was also ok with dropping 3.4 I will do that. 

As for the operator question: I see no advantage of using it. We'd also lose (soo to be untested) 3.4 compat.

**Comment by sdrave** [comment]
Regarding `@`, I would be surprised if 3to2 can handle it. So we would probably loose Python 2 support as well.

**Comment by renemilk** [comment]
I just checked, 3to2 has no fixer for it, indeed. So that's definitely a no-go until we drop python 2 altogether.
