### ISSUE TITLE
Discretizations inheritance tree changes discussion

### ISSUE THREAD

**Issue by pmli** [pymor/pymor#409]
The current inheritance tree in sys-mor branch looks like this:
- `interface.DiscretizationInterface`
  - `basic.DiscretizationBase`
    - `basic.StationaryDiscretization`
    - `basic.InstationaryDiscretization`
    - `iosys.InputOutputSystem`
      - `iosys.LTISystem`
      - `iosys.TransferFunction`
      - `iosys.SecondOrderSystem`
      - `iosys.LinearDelaySystem`
      - `iosys.LinearStochasticSystem`
      - `iosys.BilinearSystem`

At least, this should be changed in a way that a reductor for `InstationaryDiscretization` can also work for `LTISystem`. An example of such a reductor would be `ParabolicRBReductor`.

Beyond this, we should probably see how to better fit "discretization" and "system" concepts together. Of course, from my perspective, I would say we should replace discretizations by systems (every discretization is a system, but not every large-scale system is a discretization of a PDE, e.g. electrical circuits and mass-spring-damper systems), but some @pymor/pymor-devs would probably disagree. For a less drastic suggestion, it would be enough to add an output equation to discretizations, as far as I see.

The `TransferFunction` class stands out. It is neither a discretization (since it can represent a PDE directly) or a system (although it is a representation of a linear time-invariant system which assumes zero initial condition).

We might consider adding "data" classes, which system identification/data-driven/non-intrusive model reduction methods could use. Issue #390 might be a better place to discuss.

We should probably rethink the inheritance tree with respect to system properties: 
1. parametric/non-parametric
1. linear/nonlinear/bilinear/quadratic/polynomial...
1. algebraic/differential/differential-algebraic
1. deterministic/stochastic
1. time-invariant/time-varying/parameter-varying
1. without/with delay
1. first-order/second-order/port-Hamiltonian/symmetric etc. structure

The difficulty is that a system can have almost any combination of above properties. Some properties are easier to deal with (e.g. we might not need to separate parametric from non-parametric systems), while others not so much (e.g. we have algebraic/stationary and differential/instationary systems, and would probably have to add more classes for differential-algebraic systems based on index).

**Comment by sdrave** [comment]
> Beyond this, we should probably see how to better fit "discretization" and "system" concepts together. Of course, from my perspective, I would say we should replace discretizations by systems (every discretization is a system, but not every large-scale system is a discretization of a PDE, e.g. electrical circuits and mass-spring-damper systems), but some @pymor/pymor-devs would probably disagree.

If we are mainly discussing terminology, I think renaming `Discretization` to `Model` would be a way to go. In retrospective, I am not sure why we didn't use `Model` in the first place, @ftalbrecht?

> For a less drastic suggestion, it would be enough to add an output equation to discretizations, as far as I see.

What exactly do you mean by that?

> We should probably rethink the inheritance tree with respect to system properties:
>
>  1.  parametric/non-parametric

Why have different classes for that? You can always ask a `Discretization` `d` if its parametric simply by looking at `d.parametric`.

In principle, I would agree that `LTISystem` should derive from `InstationaryDiscretization`. However, it is not quite clear to me how `InputOutputSystem` would fit into the picture. However, IMHO the class hierarchy isn't really that important. In particular, I see no need for the system theory classes to derive from `InstationaryDiscretization` to make the RB reductors usable for them.

I really have no opinion on `TransferFunction`. Everything so far in pyMOR is strictly related to projection-based methods, so I would say that this can be relatively independent from the rest.

**Comment by pmli** [comment]
> If we are mainly discussing terminology, I think renaming `Discretization` to `Model` would be a way to go.

`Model` sounds good to me.

>> For a less drastic suggestion, it would be enough to add an output equation to discretizations, as far as I see.
>
> What exactly do you mean by that?

For an algebraic equation A x = u or a differential equation x' = A x + B u, by "output equation" I mean something like y = C x + D u. It is possible that C = I and D = 0, but in general, the idea is to approximate the mapping from u to y (of course, with projection-based methods, one gets an approximation for x for free, but the primary goal is to approximate y well for any u).

> Why have different classes for that? You can always ask a `Discretization` `d` if its parametric simply by looking at `d.parametric`.

Ok, that's good.

> In principle, I would agree that `LTISystem` should derive from `InstationaryDiscretization`. However, it is not quite clear to me how `InputOutputSystem` would fit into the picture. However, IMHO the class hierarchy isn't really that important. In particular, I see no need for the system theory classes to derive from `InstationaryDiscretization` to make the RB reductors usable for them.

`ParabolicRBReductor` assumes the discretization has `operator` and `mass` attributes, so I'm not sure how it would be usable for system theory classes...

**Comment by sdrave** [comment]
Regarding adding the `output equation`: The mathematical side was clear to me. What's not clear to me is what you have in mind regarding the implementation ..

Regarding `ParabolicRBReductor`: In principle, `operator` is just `A` and `mass` is just `E`. This translation could also happen in the reductor. However, instead of source term we have the time-dependent input. Already for solving the discretization, its not quite clear to me, how this input should be specified. Currently, `DiscretizationInterface.solve` only accepts a `Parameter` as single argument. Would we provide the input as an `Parameter`, and if yes would it be time-discrete or some analytical function of time?
In any case, I would have to double-check whether the error estimator really works for time-dependent inputs. (I am quite sure, however.)

**Comment by pmli** [comment]
I just thought it would be a good idea to make discretizations and systems more similar. With the output equation, I guess RB could also use the adjoint system to estimate the error in the output.

I would be for time-dependent input to be a separate argument for `solve` and that it can be any Python function with proper signature (this is probably related to #389).

**Comment by sdrave** [comment]
Ok.
