### ISSUE TITLE
Infinite recurion in LincombOperator.apply_inverse

### ISSUE THREAD

**Issue by sdrave** [pymor/pymor#419]
As reported by @pmli in #272:

```python
from pymor.vectorarrays.numpy import NumpyVectorSpace
from pymor.operators.constructions import IdentityOperator
from pymor.operators.numpy import NumpyMatrixOperator
import numpy as np

v = NumpyVectorSpace.from_data(np.ones((1, 2)))
I = IdentityOperator(v.space)
A = NumpyMatrixOperator(np.eye(2))

(I * 2).apply_inverse(v)  # RuntimeError: maximum recursion depth exceeded in comparison
(I * 2 + A).apply_inverse(v)  # RuntimeError: maximum recursion depth exceeded in comparison
(A + I * 2).apply_inverse(v)  # RuntimeError: maximum recursion depth exceeded in comparison
```

**Comment by sdrave** [comment]
@pmli, I have fixed the three errors you have mentioned above in #420. Please check if there are any more instances where the problem occurs.

**Comment by sdrave** [comment]
Another issue in above situation is, however, that the constructed operators will never assemble into a matrix, so a generic iterative linear solve will be call. (Which is probably not what you want.) Instead, you would need to replace `IdentityOperator` by the corresponding `NumpyMatrixOperator`. Alternatively, one could try to extend `NumpyMatrixOperator.assemble_lincomb` for the second and third case and make `IdentityOperator` a `ScaledIdentityOperator` for the first case.

**Comment by pmli** [comment]
In the first case, instead of using `ScaledIdentityOperator`, would it make sense to check in `LincombOperator.apply_inverse` if `len(self.operators) == 1`, and if it is true, do `self.operators[0].apply_inverse(V).scal(1 / self.coefficients[0])`?

**Comment by sdrave** [comment]
Right this would be more generic as it would work as well with any `Operator` not only `IdentityOperator`. A generic version of my proposal would be to have a `ScaledOperator` to which `LincombOperator` assembles. But maybe you are right that its simpler to just extend `LincombOperator.apply_inverse`.

**Comment by pmli** [comment]
For the second and third case, as a first step in `NumpyMatrixOperator.assemble_lincomb`, would it be ok to "flatten" all `LincombOperators` in `operators`?

**Comment by sdrave** [comment]
`assemble_lincomb` is not intended to do any recursive operations. Its sole purpose is to handle the linear combination of matrices of a certain data type (and possible abstract operators like `ZeroOperator` or `IdentityOperator`). The recursion is already handled by `LincombOperator.assemble`. Also, with #421, the flattening should happen automatically.

**Comment by pmli** [comment]
Ok, I ran the code above on the current master and opaddmul branches. On master, all three cases fail, but on opaddmul only the first fails. So, it is enough to handle the `len(self.operators) == 1` case in `LincombOperator.apply_inverse`?

**Comment by sdrave** [comment]
There was still a small bug. Above code should now work with master as well as oppaddmul.

**Comment by pmli** [comment]
Yes, it's working and I see that `lgmres` is called in all cases on master, but only in the first case on opaddmul.
