### ISSUE TITLE
Supporting PEP 518

### ISSUE THREAD

**Issue by renefritze** [pymor/pymor#423]
This here describes how to properly declare build dependencies: https://www.python.org/dev/peps/pep-0518/
The idea is pip can read that file and install deps without having to execute setup.py. Which would help us a lot. 

OFC Pip does not respect this yet. It might in pip 10 (it's not in current git) , to be released sometime in the future. Relevant issues: https://github.com/pypa/pip/issues/4802 https://github.com/pypa/pip/issues/3691

Nevertheless I've setup a branch that should do what's described in the pep. 
https://github.com/pymor/pymor/commit/572c9953c31cae3702fa1efa3352f5a963333e32

**Comment by renemilk** [comment]
This works for our pip install CI testcase already: https://travis-ci.org/pymor/pymor/builds/308987673

**Comment by renefritze** [comment]
#524

**Comment by renefritze** [comment]
#524 is merged
