### ISSUE TITLE
Debian packages still needed?

### ISSUE THREAD

**Issue by renemilk** [pymor/pymor#427]
I for one would like to burn them with fire and since we've got wheels now, I think we can actually do without them. 
Anybody disagree, @pymor/pymor-devs ?

**Comment by ftalbrecht** [comment]
No opinion. In particular: no objections!

**Comment by pmli** [comment]
No objections here.

**Comment by sdrave** [comment]
I guess its nice to have them if you want to do a system-wide installation. I personally do not use them, however, and if it takes a nontrivial effort to maintain them, I am ok with dropping them.

**Comment by renemilk** [comment]
Definitely non-trivial. In fact I'm bringing this up because the daily-ppa builds broke again, for some unknown, external, reason.
