### ISSUE TITLE
Drop Python 2 support?

### ISSUE THREAD

**Issue by sdrave** [pymor/pymor#429]
The world is moving on, and many in the scientific computing world use Python 3 now. (In particular, FEniCS works well with Python 3 nowadays.) Are there any reasons to keep supporting Python 2, @pymor/pymor-devs?

**Comment by renemilk** [comment]
Nope.

**Comment by pmli** [comment]
I don't think so, especially with https://pythonclock.org/ and http://www.python3statement.org/.

**Comment by renemilk** [comment]
Done in #430
