### ISSUE TITLE
Skipping tests using external solvers

### ISSUE THREAD

**Issue by sdrave** [pymor/pymor#455]
The current situation is kind of messy. In general, all tests using FEnicS, NGSolve, slycot or pymess should be enforced in CI and should be skippable locally, IMHO. Right now there are only special provisions for NGSolve, which I have abused in `pymortests.lyapunov` and `pymortests.riccati`.

**Comment by renemilk** [comment]
By 'skippable' you mean auto-skipped if package missing, yes?

**Comment by sdrave** [comment]
Yep.
