### ISSUE TITLE
NumpyMatrixOperator.matrix is mutable

### ISSUE THREAD

**Issue by pmli** [pymor/pymor#457]
Example:
```python
import numpy as np
from pymor.operators.numpy import NumpyMatrixOperator
A = NumpyMatrixOperator(np.array([[0]]))
print(A.matrix)
A.matrix[0, 0] = 1
print(A.matrix)
```
Output:
```python
[[0]]
[[1]]
```

@sdrave Is this expected behavior?

**Comment by sdrave** [comment]
Hi, I am aware of this. One might consider making the matrix write-protected, but I never felt this to be necessary. Do you think we should do it?

**Comment by pmli** [comment]
Ok. I somehow assumed that the matrix is immutable because `NumpyMatrixOperator` derives from `ImmutableInterface`, which led to a bug in my code. Maybe a note somewhere (e.g. `core/interfaces.py`), saying that public attributes could still be mutable, would be enough?

**Comment by sdrave** [comment]
Well, since you ran into this, it might be reasonable to make at least numpy arrays readonly. I will prepare a pull request.
