### ISSUE TITLE
Make GenericRBReductor and GenericPGReductor more coherent

### ISSUE THREAD

**Issue by sdrave** [pymor/pymor#473]
`GenericPGReductor` is introduced in #464. In particular, we should look at the `product` and `biorthogonal_product` arguments.

**Comment by pmli** [comment]
The thing is that I don't understand what `orthogonal_projection` and `product` mean in `GenericRBReductor`.

How I see Petrov-Galerkin projection for LTI systems is:
- V and W are given matrices
- W<sup>T</sup> E V, W<sup>T</sup> A V, W<sup>T</sup> B, C V are reduced matrices
- exceptionally, if V and W are biorthogonal w.r.t. E, then W<sup>T</sup> E V doesn't have to be computed.

**Comment by sdrave** [comment]
For `GenericRBReductor` one would also have the case that the basis might be orthonormal w.r.t. a certain operator in the discretization (e.g. the mass (=E) matrix) which should reduce to an `IdentityOperator` or an `Operator` holding the identity matrix. Currently, there is no provision for this in `GenericRBReductor`. We had some related discussion in #103. Quite a few things have changed since then, so we might reconsider adding an analogue of `biorthogonal_product` to `GenericRBReductor`.

The `product` argument of `GenericRBReductor` is used in conjunction with the `orthogonal_projection` argument. This has to do with the fact that vectors need to be projected differently than functionals. From the systems perspective: consider an LTISystem with non-zero initial data. To obtain a ROM, you need the projection of the initial data into the space spanned by the range of `V`. Given W = V, you normally project in the range by multiplying with V^T, e.g. V^TAV. However, to project the initial state x_0 given by a `VectorOperator` you would need something like V^TEx_0, assuming that V is E-orthonormal. The `product` argument is to specify the E, the `orthogonal_projection` argument is to specify the operator corresponding to x_0.

**Comment by pmli** [comment]
Right, totally forgot about the initial condition! So, in general, the projected initial condition would be (W<sup>T</sup>EV)<sup>-1</sup>W<sup>T</sup>Ex<sub>0</sub>?

How would we handle this for `LTISystems`? Sometimes it makes sense to simulate the model for different initial conditions...

**Comment by pmli** [comment]
I sometimes see V(W<sup>T</sup>EV)<sup>-1</sup>W<sup>T</sup>E being refered to as the (Petrov-Galerkin) projector and how V(W<sup>T</sup>EV)<sup>-1</sup>W<sup>T</sup>Ex(t) should approximate x(t) (e.g., see section 9.1.2 in the [Antoulas book](https://doi.org/10.1137/1.9780898718713)). Also, [this](https://doi.org/10.1016/j.sysconle.2016.11.007) and [this](https://doi.org/10.1016/j.automatica.2010.12.002) paper both use W to project the initial condition.

**Comment by pmli** [comment]
I would prefer to have the option of projecting with V and W which are not necessarily biorthogonal. (I guess by setting `product=None`?) For example, `BTReductor` has three options for projection (and maybe even more one day), because it is a priori not clear which is numerically best. It might happen, if V and W are biorthogonalized w.r.t. E, that V and W become ill-conditioned, which would introduce errors in W^TAV. Instead, it _might_ be better to orthogonalize V and W individually w.r.t. Euclidian inner product.

**Comment by sdrave** [comment]
To simplify things: What would you think of completely removing the `biorthogonal_product` feature from `GenericPGReductor` and replace the the resulting reduced E-operator by `IdentityOperator` as an additional step in the derived reductors where the biorthogonality of the bases is known? I.e. in `GenericBTReductor` one could write

```python
rd = super().reduce.with_(E=None)
```

Of course, this would incur some additional costs of projecting E even though its thrown away afterwards.

**Comment by pmli** [comment]
Doing unnecessary computation hurts my soul.
How about adding a `mass` attribute to systems (`'E'` for `LTISystem`, `'M'` for `SecondOrderSystem`, etc.) and a bool argument `biorthogonal` to `GenericPGReductor.reduce` which would say if `W^TEV==I`? I guess a similar thing would work for `GenericRBReductor`?

**Comment by sdrave** [comment]
Ok, if this is important to you and we also want to support projecting vectors with non-orthonormal bases, I would propose the following:

- `GenericRBReductor` has attributes `product`, `basis_is_orthonormal`, `vector_ranged_operators`.
- `GenericPGReductor` has attributes `product`, `bases_are_biorthonormal`, `vector_ranged_operators`.
- In both cases, when the to-be-projected operator `is` `product` *and* `basis_is_orthonormal` resp. `bases_are_biorthonormal` is `True`, the operator is replaced by an `IdentityOperator`.
- If the key of a given Operator in the `operators` dict is contained in `vector_ranged_operators`, then the projection is performed with `product=product`. If, in addition, `basis_is_orthonormal` reps. `bases_are_biorthonormal` is `False`, the projected Operator `pop` is replaced by `Concatenation(InverseOperator(NumpyMatrixOperator(product.apply2(W/V,V))), pop)`.

**Comment by pmli** [comment]
I'm still confused with why `product` and `vector_ranged_operators` could not be specified by the discretization. Can they be something else besides mass and initial condition?

I'm also still unsure about initial conditions in `LTISystems`. Many sys-mor methods ignore them, with a few exceptions (e.g., the papers I mentioned [above](https://github.com/pymor/pymor/issues/473#issuecomment-443761485)). Because of this and also because someone might want to try many different initial conditions, it doesn't make sense to me to specify the initial condition for an `LTISystem` as it is done in `InstationaryDiscretization`, but as an argument of the `solve` method (when it eventually appears). Then it would be nice to have the "dual" method to `reconstruct` in `Generic(RB|PG)Reductor` for projecting the initial condition, which would be called before `rd.solve`.

**Comment by sdrave** [comment]
> I'm still confused with why product and vector_ranged_operators could not be specified by the 
> discretization. Can they be something else besides mass and initial condition?

`product` could be any inner product operator used to orthonormalize / biorthonormalize the basis. In particular, the operator does not have to be included in the `Discretization`. Regarding `vector_ranged_operators` I see your point. However, I would like to have a broader discussion about this topic after the next release. For instance, if we only have reductors that know the type of equation to be reduced, the argument would not be required at all. Another route to go would be to somehow attach the information to the `Operator` itself.

Regarding the inital conditions: For RB-Methods it makes sense to inlcude the initial conditions into the to-be-reduced model as the goal is a full offline-online spliiting. Thus, for non-fixed initial conditions, you would usually require these to be a linear combination of some fixed vectors. This does not mean that you should add initial conditions to `LTISystems`. However, the reductor should also be usable for other discretizations.

**Comment by pmli** [comment]
> - If the key of a given Operator in the `operators` dict is contained in `vector_ranged_operators`, then the projection is performed with `product=product`.

> `product` could be any inner product operator used to orthonormalize / biorthonormalize the basis.

Except, when projecting the initial condition, the `product` needs to be the mass matrix, right?

**Comment by sdrave** [comment]
What makes you think that?

**Comment by pmli** [comment]
Well, I'm only aware of (W<sup>T</sup>EV)<sup>-1</sup>W<sup>T</sup>Ex<sub>0</sub>. Do you have an RB reference explaining how to project the initial condition?

**Comment by sdrave** [comment]
I mean, you can do this with any inner product you like. In most cases, using the mass matrix will be the best thing to do. But if for some reason you wish to have a, say, H1-orhtonormal basis, the most natural thing would be to project w.r.t. that basis. Also, the point with these reductors is, that they actually make no assumption on the type of equation they are supposed to reduce ... (As I said, I am not sure if it is a good idea to have such reductors in the first place. However, for 0.5 we should stick to this plan.)

**Comment by pmli** [comment]
Ok, then let's go with the above plan for the 0.5 release and discuss later about future releases.

**Comment by sdrave** [comment]
Hi @pmli, I have started working on this in #501. Before proceeding: I noticed, that `extend_source_basis` and `extend_range_basis` isn't used anywhere. On the other hand, it is not possible to do a biorthogonal basis extension. I would suggest to replace both methods by a joint `extend_bases` method, which receives a `VectorArrays` for both bases and uses the biorthonormal Gram-Schmidt by default?

**Comment by pmli** [comment]
Hi @sdrave, I'm not familiar with any sys-mor method which would extend bases (although I've heard of a few adaptive methods), so I'm ok with anything you want to do.
