### ISSUE TITLE
Make solve_lyap and solve_ricc free functions

### ISSUE THREAD

**Issue by sdrave** [pymor/pymor#476]
After merging #464, `LTISystem.solve_lyap` and `LTISystem.solve_ricc` should become free functions. See discussion [here](https://github.com/pymor/pymor/pull/464#discussion_r235038473).

**Comment by pmli** [comment]
Maybe a summary of all the equations and solvers would be good.

---

Some terminology (more-or-less following [[Kürschner '16]](http://hdl.handle.net/11858/00-001M-0000-0029-CE18-2)):

- continuous-time algebraic Lyapunov equation
  - standard (CALE): A X + X A<sup>T</sup> + Q = 0
  - generalized (GCALE): A X E<sup>T</sup> + E X A<sup>T</sup> + Q = 0
- discrete-time algebraic Lyapunov equation (a.k.a. algebraic Stein equation)
  - standard (DALE): A X A<sup>T</sup> - X + Q = 0
  - generalized (GDALE): A X A<sup>T</sup> - E X E<sup>T</sup> + Q = 0
- continuous-time algebraic Riccati equation
  - standard (CARE): A<sup>T</sup> X + X A - X R X + Q = 0
  - generalized (GCARE): A<sup>T</sup> X E + E<sup>T</sup> X A - E<sup>T</sup> X R X E + Q = 0
- discrete-time algebraic Riccati equation
  - standard (DARE): A<sup>T</sup> X A - X - A<sup>T</sup> X B (R + B<sup>T</sup> X B)<sup>-1</sup> B<sup>T</sup> X A + Q = 0
  - generalized (GDARE): A<sup>T</sup> X A - E<sup>T</sup> X E - A<sup>T</sup> X B (R + B<sup>T</sup> X B)<sup>-1</sup> B<sup>T</sup> X A + Q = 0

(Differential versions are also interesting, e.g., they appear in MOR for linear time-varying (LTV) systems, but maybe its better to postpone their discussion.)
(I assume above that E is invertible, but there are also versions for differential-algebraic systems.)

---

Here are the solvers (**bold** for those available in pyMOR):

- SciPy (only for dense problems)
  - **`scipy.linalg.solve_continuous_lyapunov`**
    - CALE
  - `scipy.linalg.solve_discrete_lyapunov`
    - DALE
  - **`scipy.linalg.solve_continuous_are`**
    - A<sup>T</sup> X + X A - X B R<sup>-1</sup> B<sup>T</sup> X + Q = 0
    - A<sup>T</sup> X E + E<sup>T</sup> X A - (E<sup>T</sup> X B + S) R<sup>-1</sup> (E<sup>T</sup> X B + S)<sup>T</sup> + Q = 0
  - `scipy.linalg.solve_discrete_are`
    - DARE
    - A<sup>T</sup> X A - E<sup>T</sup> X E - (A<sup>T</sup> X B + S) (R + B<sup>T</sup> X B)<sup>-1</sup> (A<sup>T</sup> X B + S)<sup>T</sup> + Q = 0
- slycot v0.3.3 (only for dense problems)
  - **`slycot.sb03md`**
    - (C/D)ALE
  - `slycot.sb03od`
    - (C/D)ALE
    - for stable A
    - returns a Cholesky factor
  - **`slycot.sg03ad`**
    - G(C/D)ALE
  - `slycot.sg03bd`
    - G(C/D)ALE
    - for stable (A, E)
    - returns a Cholesky factor
  - **`slycot.sb02md`**
    - (C/D)ARE
  - `slycot.sb02od`
    - A<sup>T</sup> X + X A - (X B + S) R<sup>-1</sup> (X B + S)<sup>T</sup> + Q = 0
    - A<sup>T</sup> X A - X - (A<sup>T</sup> X B + S) (R + B<sup>T</sup> X B)<sup>-1</sup> (A<sup>T</sup> X B + S)<sup>T</sup> + Q = 0
  - **`slycot.sg02ad`**
    - A<sup>T</sup> X E + E<sup>T</sup> X A - (E<sup>T</sup> X B + S) R<sup>-1</sup> (E<sup>T</sup> X B + S)<sup>T</sup> + Q = 0
    - A<sup>T</sup> X A - E<sup>T</sup> X E - (A<sup>T</sup> X B + S) (R + B<sup>T</sup> X B)<sup>-1</sup> (A<sup>T</sup> X B + S)<sup>T</sup> + Q = 0
- pymess v1.0.0
  - **`pymess.lyap`**
    - (G)CALE
    - for stable A
    - returns a (low-rank) Cholesky factor
    - for dense and sparse problems, but needs access to matrix data
    - if A is dense, it calls `pymess.glyap`, otherwise a low-rank method
  - `pymess.glyap`
    - (G)CALE
    - for dense problems
  - `pymess.gstein`
    - (G)DALE
    - for dense problems
  - **`pymess.lradi`**
    - (G)CALE
    - for stable (A, E)
    - returns a low-rank Cholesky factor
    - for large problems, but needs access to vector data
  - **`pymess.care`**
    - A<sup>T</sup> X + X A - X B B<sup>T</sup> X + C<sup>T</sup> C = 0
    - A<sup>T</sup> X E + E<sup>T</sup> X A - E<sup>T</sup> X B B<sup>T</sup> X E + C<sup>T</sup> C = 0
    - for dense and sparse problems, but needs access to matrix data
    - if A is dense, it calls a dense method, otherwise a low-rank method
  - `pymess.dense_nm_gmpare`
    - (G)CARE
    - for dense problems
  - **`pymess.lrnm`**
    - same equations as `pymess.care`
    - returns a low-rank Cholesky factor
    - for large problems, but needs access to vector data
- pyMOR
  - **`pymor.algorithms.lyapunov.lradi`**
    - (G)CALE
    - returns a low-rank Cholesky factor
    - for large problems

---

Matrix equations we are solving now:

- continuous-time `LTISystem` Gramians (also used in Balanced Truncation (BT)):
  - A P E<sup>T</sup> + E P A<sup>T</sup> + B B<sup>T</sup> = 0
  - A<sup>T</sup> Q E + E<sup>T</sup> Q A + C<sup>T</sup> C = 0
- continuous-time LQGBT:
  - A P E<sup>T</sup> + E P A<sup>T</sup> - E P C<sup>T</sup> C P E<sup>T</sup> + B B<sup>T</sup> = 0
  - A<sup>T</sup> Q E + E<sup>T</sup> Q A - E<sup>T</sup> Q B B<sup>T</sup> Q E + C<sup>T</sup> C = 0
- continuous-time Bounded-Real BT (&gamma; > 0):
  - A P E<sup>T</sup> + E P A<sup>T</sup> + &gamma;<sup>-2</sup> E P C<sup>T</sup> C P E<sup>T</sup> + B B<sup>T</sup> = 0
  - A<sup>T</sup> Q E + E<sup>T</sup> Q A + &gamma;<sup>-2</sup> E<sup>T</sup> Q B B<sup>T</sup> Q E + C<sup>T</sup> C = 0

---

Some matrix equations we want to solve:

- discrete-time versions of the above
  - only dense solvers available
- variants of BT (only dense solvers available):
  - LQGBT with nonzero D
    - A P E<sup>T</sup> + E P A<sup>T</sup> - (E P C<sup>T</sup> + B D<sup>T</sup>) (I - D D<sup>T</sup>)<sup>-1</sup> (E P C<sup>T</sup> + B D<sup>T</sup>)<sup>T</sup> + B B<sup>T</sup> = 0
    - A<sup>T</sup> Q E + E<sup>T</sup> Q A - (E<sup>T</sup> Q B + C<sup>T</sup> D) (I - D<sup>T</sup> D)<sup>-1</sup> (E<sup>T</sup> Q B + C<sup>T</sup> D)<sup>T</sup> + C<sup>T</sup> C = 0
  - BRBT with nonzero D
    - A P E<sup>T</sup> + E P A<sup>T</sup> + (E P C<sup>T</sup> + B D<sup>T</sup>) (&gamma;<sup>2</sup> I - D D<sup>T</sup>)<sup>-1</sup> (E P C<sup>T</sup> + B D<sup>T</sup>)<sup>T</sup> + B B<sup>T</sup> = 0
    - A<sup>T</sup> Q E + E<sup>T</sup> Q A + (E<sup>T</sup> Q B + C<sup>T</sup> D) (&gamma;<sup>2</sup> I - D<sup>T</sup> D)<sup>-1</sup> (E<sup>T</sup> Q B + C<sup>T</sup> D)<sup>T</sup> + C<sup>T</sup> C = 0
  - Balanced Stochastic Truncation
    - A P E<sup>T</sup> + E P A<sup>T</sup> + B B<sup>T</sup> = 0
    - A<sub>2</sub><sup>T</sup> Q E + E<sup>T</sup> Q A<sub>2</sub> + E<sup>T</sup> Q B<sub>2</sub> (D<sup>T</sup> D)<sup>-1</sup> B<sub>2</sub><sup>T</sup> Q E + C<sup>T</sup> (D<sup>T</sup> D)<sup>-1</sup> C = 0
    - A<sub>2</sub> := A - B<sub>2</sub> (D<sup>T</sup> D)<sup>-1</sup> C, B<sub>2</sub> := B D<sup>T</sup> + P C<sup>T</sup>
  - Positive-Real BT
    - A<sub>2</sub> P E<sup>T</sup> + E P A<sub>2</sub><sup>T</sup> + E P C<sup>T</sup> (D + D<sup>T</sup>)<sup>-1</sup> C P E<sup>T</sup> + B (D + D<sup>T</sup>)<sup>-1</sup> B<sup>T</sup> = 0
    - A<sub>2</sub><sup>T</sup> Q E + E<sup>T</sup> Q A<sub>2</sub> + E<sup>T</sup> Q B (D + D<sup>T</sup>)<sup>-1</sup> B<sup>T</sup> Q E + C<sup>T</sup> (D + D<sup>T</sup>)<sup>-1</sup> C = 0
    - A<sub>2</sub> := A - B (D + D<sup>T</sup>)<sup>-1</sup> C
  - H<sub>&infin;</sub> BT
    - A P E<sup>T</sup> + E P A<sup>T</sup> - (1 - &gamma;<sup>-2</sup>) (E P C<sup>T</sup> + B D<sup>T</sup>) (I + D D<sup>T</sup>)<sup>-1</sup> (E P C<sup>T</sup> + B D<sup>T</sup>)<sup>T</sup> + B B<sup>T</sup> = 0
    - A<sup>T</sup> Q E + E<sup>T</sup> Q A - (1 - &gamma;<sup>-2</sup>) (E<sup>T</sup> Q B + C<sup>T</sup> D) (I + D<sup>T</sup> D)<sup>-1</sup> (E<sup>T</sup> Q B + C<sup>T</sup> D)<sup>T</sup> + C<sup>T</sup> C = 0
- `BilinearSystem` Gramians:
  - A P E<sup>T</sup> + E P A<sup>T</sup> + &Sigma;<sub>i</sub> N<sub>i</sub> P N<sub>i</sub><sup>T</sup> + B B<sup>T</sup> = 0
  - A<sup>T</sup> Q E + E<sup>T</sup> Q A + &Sigma;<sub>i</sub> N<sub>i</sub><sup>T</sup> Q N<sub>i</sub> + C<sup>T</sup> C = 0
  - no Python solvers available, one option is a fixed-point iteration with Lyapunov equations

---

Dispatch proposal which hopefully covers most cases (**bold** is already implemented, `chol = pymor.bindings.scipy.chol`):

- `solve_lyap(A, E, B, trans=False, cont_time=True, return_cholesky_factor=True, solver_options=None)`
  - continuous-time:
    - `trans == False`
      - A X E<sup>T</sup> + E X A<sup>T</sup> + B B<sup>T</sup> = 0 ((G)CALE)
    - `trans == True`
      - A<sup>T</sup> Y E + E<sup>T</sup> Y A + B<sup>T</sup> B = 0
    - for small problems:
      - return a Cholesky factor:
        - **`scipy.linalg.solve_continuous_lyapunov` + `chol`** (E = I)
        - **`slycot.sb03md` + `chol`** (E = I)
        - `slycot.sb03od` (E = I)
        - **`slycot.sg03ad` + `chol`**
        - `slycot.sg03bd`
        - **`pymess.lyap`**
        - `pymess.glyap` + `chol`
      - return full solution:
        - `scipy.linalg.solve_continuous_lyapunov`
        - `slycot.sb03md`
        - `slycot.sg03ad`
        - `pymess.glyap`
    - for large problems (always return a low-rank Cholesky factor `->` raise an exception if `return_cholesky_factor` is `False`):
      - **`pymess.lradi`**
      - **`pymor.algorithms.lyapunov.lradi`**
  - discrete-time:
    - return a Cholesky factor:
      - `scipy.linalg.solve_discrete_lyapunov` + `chol` (E = I)
      - `slycot.sb03md` + `chol` (E = I)
      - `slycot.sb03od` (E = I)
      - `slycot.sg03ad` + `chol`
      - `slycot.sg03bd`
      - `pymess.gstein` + `chol`
    - return full solution:
      - `scipy.linalg.solve_discrete_lyapunov` (E = I)
      - `slycot.sb03md` (E = I)
      - `slycot.sg03ad`
      - `pymess.gstein`
- `solve_care(A, E, B, C, R, S, trans=False, cont_time=True, return_cholesky_factor=True, solver_options=None)`
  - continuous-time:
    - `trans == False`
      - A<sup>T</sup> X E + E<sup>T</sup> X A - (E<sup>T</sup> X B + S) R<sup>-1</sup> (E<sup>T</sup> X B + S)<sup>T</sup> + C C<sup>T</sup> = 0
    - `trans == True`
      - A Y E<sup>T</sup> + E Y A<sup>T</sup> - (E Y C<sup>T</sup> + S<sup>T</sup>) R<sup>-1</sup> (E Y C<sup>T</sup> + S<sup>T</sup>)<sup>T</sup> + B<sup>T</sup> B = 0
    - for small problems:
      - return a Cholesky factor:
        - **`scipy.linalg.solve_continuous_are` + `chol`**
        - **`slycot.sb02md` + `chol`** (E = I, S = 0)
        - `slycot.sb02od` + `chol` (E = I)
        - **`slycot.sg02ad` + `chol`**
        - **`pymess.care`** (R = I, S = 0)
        - `pymess.dense_nm_gmpare` + `chol` (S = 0)
      - return full solution:
        - **`scipy.linalg.solve_continuous_are`**
        - **`slycot.sb02md`** (E = I, S = 0)
        - `slycot.sb02od` (E = I)
        - **`slycot.sg02ad`**
        - `pymess.dense_nm_gmpare` (S = 0)
    - for large problems (always return a low-rank Cholesky factor `->` raise an exception if `return_cholesky_factor` is `False`):
      - **`pymess.lrnm`** (R = I, S = 0)
  - discrete-time:
    - for small problems:
      - return a Cholesky factor:
        - `scipy.linalg.solve_discrete_are` + `chol`
        - `slycot.sb02md` + `chol` (E = I, S = 0)
        - `slycot.sb02od` + `chol` (E = I)
        - `slycot.sg02ad` + `chol`
      - return full solution:
        - `scipy.linalg.solve_discrete_are`
        - `slycot.sb02md` (E = I, S = 0)
        - `slycot.sb02od` (E = I)
        - `slycot.sg02ad`

---

Questions:

- Should we unify the meaning of `trans` between Lyapunov and Riccati equations? (Notice that in CALE, the first matrix is not transposed, but in CARE, it is.) Should `trans` be a reference to CALE/CARE, or rather to "is the first matrix transposed"? (I would prefer the second option.)
- Should solvers for dense, unstable systems (e.g., `slycot.sb03md` and `pymess.glyap`) have their separate dispatch function? (I do have a use-case for these functions.)

**Comment by sdrave** [comment]
In general, you are the expert and should decide what a reasonable interface is. My only remark would be that if there are currently no implementations in pyMOR for `cont_time=False`, it might make more sense to add the switch later. From the user perspective it might be frustrating to have an argument for which only one value is admissible.
