### ISSUE TITLE
Replace _is_like_identity_operator and _is_like_zero_operator

### ISSUE THREAD

**Issue by sdrave** [pymor/pymor#478]
After merging #464 we should either get rid of these helper methods or replace them by something better. These are used to check `E` for identity and `D` for zero-ness in `LTISystems`. Possible options that come to mind:

- Ensure that these operators are always exactly ZeroOperator or IdentityOperator by modifying `LTISystem.__add__` and `SecondOrderSystem.to_lti`.
- Move the methods to `pymor.algorithms` and base them on `RuleTables`.
- Add `pymor.algorithms.simplify` which replaces such operators by `IdentityOperator` or `ZeroOperator`.
- Add similar functionality to `pymor.algorithms.preassemble`.

**Comment by pmli** [comment]
Another possible option is
- Using `None` instead of `IdentityOperator` and `ZeroOperator` for `E` and `D`.

One issue with forcing `IdentityOperators` is that there should be a way to assemble `IdentityOperator + BlockOperator`, e.g., as with `E` and `A` in `LTISystem`.

**Comment by sdrave** [comment]
After fixing #485, special handling of `D` should no longer be necessary.
