### ISSUE TITLE
gram_schmidt doesn't return the R matrix

### ISSUE THREAD

**Issue by pmli** [pymor/pymor#491]
Currently, `gram_schmidt` only returns the Q matrix. The R matrix is used in the [shift selection for the LRADI method](https://github.com/pymor/pymor/blob/1aeccb428700fa140cb6faa7490bdaf87a9754a3/src/pymor/algorithms/lyapunov.py#L285-L287) and in the [rational Krylov subspace method for Lyapunov equations](http://www.dm.unibo.it/~simoncin/rksm.m) (related to #387).

It might also be useful for computing an SVD of a vectorarray (Q * svd(R)).

**Comment by sdrave** [comment]
Yeah, this would be nice to have. I guess, it's not required for the coming release?

**Comment by pmli** [comment]
> I guess, it's not required for the coming release?

Yes, I think it's fine for a later release.
