### ISSUE TITLE
Replace numpy.ascontiguousarray with numpy.asarray?

### ISSUE THREAD

**Issue by pmli** [pymor/pymor#494]
There is a discussion in the [NumPy mailing list](http://numpy-discussion.10968.n7.nabble.com/Depreciating-asfortranarray-and-ascontiguousarray-td46361.html) about deprecating `asfortranarray` and `ascontiguousarray`. In pyMOR, only `ascontiguousarray` is used, and it is only used [here](https://github.com/pymor/pymor/blob/1aeccb428700fa140cb6faa7490bdaf87a9754a3/src/pymor/gui/gl.py#L149). Should this be replaced?

**Comment by sdrave** [comment]
The discussion on the mailing list does not sound like `ascontiguousarray` is going to be removed. And I agree with the argument that using this method (instead of asarray) is easier to understand. So I do not think that we should replace the call.

**Comment by pmli** [comment]
Ok, good.
