### ISSUE TITLE
Reduce number of warnings in sys-mor demos

### ISSUE THREAD

**Issue by sdrave** [pymor/pymor#499]
The sys-mor demos produce a lot of warnings due to conversion into dense numpy arrays. It would be nice to silence those:

- In `LTISystem.poles` we could check if the sparse eigenvalue solver from SciPy would work.
- In the other cases, we might introduce a dimension threshold below which no warning is produced.

**Comment by sdrave** [comment]
Regarding `scipy.sparse.linalg.eigs`: There seems no way to specify the number of returned eigenvalues based on some tolerance. Thus, it is probably not clear how to use the method efficiently in `poles` (without changing its interface). So maybe we should leave that out for the coming release and just introduce a threshold for the dense conversion warning?

**Comment by renefritze** [comment]
FYI, with the next numpy release we will also get lots of ```PendingDeprecationWarning``` due to pymess' usage of ```np.matrix```
