### ISSUE TITLE
heat.py: Estimated forward relative error bound is large

### ISSUE THREAD

**Issue by sdrave** [pymor/pymor#516]
When pymess is not installed, executing the `heat.py` demo leads to the warning:

```sg03ad: Estimated forward relative error bound is large (ferr=3.776686e-08, sep=2.871767e-08). Result may not be accurate.```

This doesn't sound like good advertisement for pyMOR. Maybe we should detect missing pymess and explain what is happening?

**Comment by pmli** [comment]
I didn't expect this. The notebook is even worse. Should we remove [this](https://github.com/pymor/pymor/blob/473a14eb208037cd08d8ac5eb2ac3d37653c78c1/src/pymor/bindings/slycot.py#L146-L150), or maybe increase the tolerance (the largest `ferr` seems to be of order 1e-6)?

**Comment by sdrave** [comment]
Hmm, not sure. Is `ferr` an absolute or relative error. If it's an absolute error, than comparing against a fixed value probably does not make any sense?

**Comment by pmli** [comment]
It is relative, using Frobenius norm (see [here](https://github.com/python-control/Slycot/blob/7f5dc1c1eff862305788044d0bc033d2dac5ac21/slycot/synthesis.py#L2091-L2096)).

**Comment by sdrave** [comment]
Ok. I guess if half machine precision is expected, then the check in `_solve_check` is maybe a little too strict and it would be ok to loosen it by one order of magnitude? On the other hand, I am really no expert in these algorithms and really can't tell what to expect. If you can't as well, it would probably be more reasonable to leave out the check completely?

**Comment by pmli** [comment]
This is more related to the ill-conditioning of the problem then the solver itself, so it's similar to #417. I checked now, and `scipy.linalg.solve` uses the machine epsilon as a tolerance for the reciprocial condition number (see [here](https://github.com/scipy/scipy/blob/a2ffe09aa751749f2372aa13c19c61b2dec5266f/scipy/linalg/basic.py#L35-L39)), so maybe we can also only report extreme cases, e.g., `ferr > 1e-1`?

**Comment by sdrave** [comment]
Sounds like a reasonable compromise.
