### ISSUE TITLE
parametric input-output models

### ISSUE THREAD

**Issue by ftalbrecht** [pymor/pymor#531]
Dear all, I feel like collecting some parts of our discussion today. Feel free to add or disagree. This is somewhat based on @sdrave s proposal and includes some afterthought. So, what would an `InstationaryModel` look like, that is supposed to be a model for at least
* parameter-independent/parameter-dependent input-output LTI systems
* parameter-independent/parameter-dependent nonlinear input-output systems
* instationary discretizations of parametric PDEs, usually without input, possibly with output

What we came up with so far is:
* Stefans suggestion was to add `input` as an optional argument to `solve` and similar methods (such as `estimate`), so we would have `solve(self, mu=None, input=none)`.
* We already have the attribute `solution_space`, which specifies the `VectorSpace` of the `VectorArray` of the solution trajectory. I propose to add corresponding attributes `input_space` and `output_space`. To clarify: these `VectorSpace`s would specify the vector space of the input (output), evaluated at a specific time. So this is like `R^m`, not something like `L^2([0, T], R^m)`. Given these attributes we can check each model if it requires an input, and of what kind.
* Implications for the nonlinear case would be: if we have a time-varying but nonparametric nonlinearity
  ```
  d_t x = f(x, t, u)
  ```
  `f` would be implemented by an operator, mapping from `solution_space` to `solution_space`. At the end of the day, after time-discretization, we would need to evaluate `f` for something like `f(x_n, t_n, u_n)`, where `x_n = x(t_n)`, `u_n = u(t_n)`. Thus, we do not need to provide the full input `u`, but just its evaluation at some point in time, which lies in `input_space`, hence is some numpy-array. This we can put into the parameter, just like time. So in the end, `f` would be a parametric operator with parameter type `{"t_": 1, "input": input_space.dim}` (this is pseudocode now). The evaluation of the operator might thus look like `x_nplusone = f.apply(x_n, {'t_': t_n, 'input': u_n)`.
* If we have a parametric non-linearity `f(x, t, u, mu)` it work work as above, but the parameter would also contain `mu`.
* Do we want to accomodate parametric inputs? Then in general, the input that gets passed to `solve` should be somthing with a signature like `evaluate(t, mu=None)`.
* Implications for the LTI case: if we think of non-parametric LTI systems in the A, B, C, D, sense, then `B` could be an operator mapping from `input_space` to `solution_space`. In this case, the input is passed to the operator in the `apply` method as usual, something like `B.apply(u_n)`. Since we do state reduction currently, it should be detected that `B` should only be reduced w.r.t. `solution_space`.

This would have quite some implications regarding algorithms and reductors, of which @sdrave is most surely more aware than I am :)

Any thoughts, @pmli @renefritze @sdrave @gramian, @drittelhacker?

**Comment by pmli** [comment]
> - Stefans suggestion was to add `input` as an optional argument to `solve` and similar methods (such as `estimate`), so we would have `solve(self, mu=None, input=none)`.

It would be nice to also have the initial condition as an optional argument.
Many systems-theoretical MOR methods ignore the initial condition, so it doesn't really fit as an attribute of the `InputOutputSystem` (like it is done in the [`InstationaryDiscretization`](https://github.com/pymor/pymor/blob/e6f0960ccc9fba2f31cbb8dce3fe4da47c853886/src/pymor/discretizations/basic.py#L267-L269)). For methods that do take the initial condition into account, it could be given as an argument of `__init__` or `reduce` method of the reductor.

> - We already have the attribute `solution_space`, [...]

`InputStateOutputSystems` have a [`state_space`](https://github.com/pymor/pymor/blob/e6f0960ccc9fba2f31cbb8dce3fe4da47c853886/src/pymor/discretizations/iosys.py#L119-L129), so we should probably somehow unify `solution_space` and `state_space`. I'm ok with changing `state_space`, since `x(t)` is not necesserily the state of a system (see the discussion [here](https://github.com/pymor/pymor/pull/497)).

> - Implications for the nonlinear case would be: [...]
> - If we have a parametric non-linearity f(x, t, u, mu) [...]

Sounds good to me.

> - Do we want to accomodate parametric inputs? Then in general, the input that gets passed to `solve` should be somthing with a signature like `evaluate(t, mu=None)`.

I don't think I ever saw an input which depends on a parameter.

> - Implications for the LTI case: [...].

`LTISystem` already has the `input_space`, `state_space` and `output_space`, operators A, B, C, D, E are operators between these spaces, and `GenericPGReductor` (and `__add__`) looks at this when projecting the operators. Allowing the operators to be parametric is the subject of #487.

**Comment by sdrave** [comment]
One important thing to note: Having an `input` does not really make sense for stationary problems, IMHO. Thus, maybe not every `solve` method should accept an `input` argument. I guess the only problem with that would be that we have to refactor `greedy` to allow for arbitrary `solve` signatures. This should be doable, however.

**Comment by ftalbrecht** [comment]
Not sure if I agree. Think of your favorite PDE, and `m` different parts of the boundary with constant boundary condition. In an LTI system, `B` would be some discretization of these `m` boundary conditions, and the input `u` would be the (time-varying) values of the boundary condition.
The same argument could be applied to a stationary PDE. Since we allow for stationary outputs in stationary models, why not allow stationary inputs?

**Comment by drittelhacker** [comment]
I would be somewhat in-between here. I guess the question is whether one can influence the boundary condition, or also distributed source term. For an uncontrolled source, I would agree with @sdrave. In case this is controlled one could call it input, but in fact for the stationary case it is difficult to see, why one would not call it parameter. My whole point in the input versus parameter discussion was that one should use the language of the users here. I would guess there is no strong implication, here, in that respect, for a stationary model.

**Comment by pmli** [comment]
> - Stefans suggestion was to add `input` as an optional argument to `solve` and similar methods (such as `estimate`), so we would have `solve(self, mu=None, input=none)`.

I thought a bit more about this. For input-output models, it would make sense to have `solve(self, input, initial_condition, mu=None)`. This would also make it more similar to [`eval_tf`](https://github.com/pymor/pymor/blob/5ae4bcf7813b04731530d9b203da282e68475d6d/src/pymor/discretizations/iosys.py#L44) and [`apply`](https://github.com/pymor/pymor/blob/5ae4bcf7813b04731530d9b203da282e68475d6d/src/pymor/operators/interfaces.py#L64).

It would also make sense that the output trajectory `y(t)` is returned. There should also be an option to return `x(t)`, or maybe it should be the default behaviour.

**Comment by ftalbrecht** [comment]
> I thought a bit more about this. For input-output models, it would make sense to have solve(self, input, initial_condition, mu=None). This would also make it more similar to eval_tf and apply.

Here I would disagree for two reasons:
* (i) this would not make sense in the reduced setting. There, the `initial_condition` would have to be a reduced one already. Otherwise, the reduced instationary model would have to know how to handle high-dimensional initial conditions (and this is for the reductor to know, not the model). Requiring the user to project the initial conditions manually beforehand would feel awkward, or?
* (ii) we often have the case of parameter-dependent initial conditions, which not only need to be reduced but also sometimes have to be part of the reduced space for mathematical reasons. I do not see how this can work if they are not part of the model

> It would also make sense that the output trajectory y(t) is returned. There should also be an option to return x(t), or maybe it should be the default behaviour.

Here I would also like to disagree. pyMOR is all about state model order reduction (atm). While it might be an annoying fact sometimes that we have the state in between it is crucial for a lot of algorithms that we first solve for the state and then obtain the output. How about we add the methods `output` and `intpu_to_output` to instationary models for the following workflow:
*  evaluate the input-to-state map:
  `x = model.solve(mu, input=u)`
* evaluate the state-to-output map:
  `y = model.output(x, mu, input=u)`
* evaluate the input-to-output map:
  `y = model.input_to_output(mu, input=u)`

**Comment by sdrave** [comment]
To structure the discussion somewhat: would it make sense to try and come up with a definition of what in pyMOR is supposed to be a parameter and what an input? If yes, it might sense to discuss this in a separate issue.

**Comment by ftalbrecht** [comment]
How about the following. _Technically speaking_

* a parameter is what we currently have as a parameter in pyMOR. In particular (as it is already), time is a parameter. Thus: if something is time-dependent, it is parameter-dependent.
* an input is an optional argument to some of the methods of a model, that are required for a simulation.

_Mathematically speaking_ (at least a bit)

* a parameter is information that is required to determine _how_ and operator can be applied
* an input is _what_ an operator is applied on

Btw, I could also imagine the initial data being hidden in the input, if the model supports it: `x = model.solve(mu, input=(x_0, u))`. This would for instance allow 
* for parameter-dependent initial conditions (those have to be passed on on construction and can be handled by the reductor and put into the basis), something like
  ```
  model = discretize_to_obtain_my_model(some_data, parametric_initial_condition)
  x = model.solve(mu, input=u)
  ```
* and those passed on the fly
  ```
  model = discretize_to_obtain_my_model(some_data)
  x = model.solve(mu, input=(x_0, u))
  ```

The model should be able to detect this automatically and handle it accordingly.

**Comment by pmli** [comment]
I don't think it's possible to agree about an abstract mathematical definition of a parameter or input. On the one hand, for input-output systems (at some very high level), both `u` and `mu` could be thought of as inputs. On the other hand, for sampling-based methods, both `u` and `mu` could be thought of as parameters.

Technically speaking, I hope we can agree that using time as a parameter is a bit hacky. But, I would be fine with also using this hack with inputs (and later possibly with time-dependent parameters in parameter-varying systems and switching signals in switched systems), as long as what is visible to the user is what they would expect, e.g. `solve(input, initial_condition, mu)` for LTI systems. One way might be to fix the private function `_solve` to only accept a `dict` of parameters.

But, now that I think about it, the function `f(x, t, u, mu)` could be thought of as an operator mapping from `solution_space x time_space x input_space x parameter_space` to `solution_space` and we can represent the Cartesian product using the `BlockVectorSpace`. This could be a way to remove the "hack".

**Comment by pmli** [comment]
For the linear case, we might agree. But, consider a parameterized bilinear term

```
\sum_{i = 1}^m{N_i(mu) x(t, mu) u_i(t)}
```

where `m` is the number of inputs. Here, `N_i(mu)` is an operator applied to `x(t, mu)`, which is then multiplied by a scalar `u_i(t)`. For a general nonlinear system, it can be even more complicated. So, I'm not sure input can be simply defined as something an operator is applied to.

BTW, I would look at the "linear dynamical system that may be time and parameter dependent" as a parameterized LTV (linear time-varying) system. This would mean that, for any fixed value of the parameter `mu`, we would have an LTV system, for which again we can define Gramians (defined by differential matrix equations) and system norms. So, again, time `t` would be weird for me to call a parameter.

**Comment by sdrave** [comment]
Since we have by now formalized the notion of model input and output, I think this issue can now be closed. Re-open, if you feel there is still something missing. (What remains to do is to enable `solve` for system-theoretic models, which, however, is mainly intertwined with the ongoing re-design of our `Model` hierarchy, which might automatically yield this feature.
