### ISSUE TITLE
Document PR-only policy

### ISSUE THREAD

**Issue by sdrave** [pymor/pymor#535]
We decided at the developer meeting that every change to master should happen in the form of a pull request. Let's document this in `CONTRIBUTING.md`.

**Comment by renefritze** [comment]
I think we should not advertise any builds from that until I've integrated those into CI. That said, I've done work under a pyMOR [organization](https://anaconda.org/pymor). All @pymor/pymor-devs who want access should tell me their Anaconda credentials and I'll see how that works.

**Comment by sdrave** [comment]
The documentation part has been done already. I think we can close this ...

**Comment by renefritze** [comment]
Agreed
