### ISSUE TITLE
Use keywords in PR titles

### ISSUE THREAD

**Issue by sdrave** [pymor/pymor#536]
We decided at the dev meeting that each pull request should have one of the keywords from https://keepachangelog.com in it's title. This should be documented in `CONTRIBUTING.md`. It would be nice to have a bot which checks this automatically. @renefritze, maybe there is some generic github bot service we could use for that?

**Comment by renefritze** [comment]
Don't see any. What would that do? Check that one of the categories is in the PR title? First word?

**Comment by sdrave** [comment]
Yeah, the idea would be to have a bot complain when the keyword is missing. But we can probably live without that.

**Comment by sdrave** [comment]
BTW, wouldn't labels make more sense than having this in the title?

**Comment by renefritze** [comment]
I think that depends if the labels are harder to get programmatically, but for website display filterting labels would be better, yes.

**Comment by renefritze** [comment]
There's no readily available check integration for either option btw. Either way I'd have to create our own github app for this. Which imo should be rather way down on the priority list.

**Comment by pmli** [comment]
I would be for more labels in general, even if they need to be added manually. It could help potential contributors to look for interesting open issues, among other things. But, that's probably a separate issue from this one.

**Comment by sdrave** [comment]
+1 for labels. It is very easy to search issues or prs via 'label:label-name'. Also, labels eliminate the risk of types.

**Comment by sdrave** [comment]
Ok, so let's introduce the labels 'new-feature', 'change', 'deprecation', 'removal', 'fix'? Other proposals, @pymor/pymor-devs?

**Comment by sdrave** [comment]
I would like to keep the practice of adding [WIP] to the title instead of using a label to make it more visible.

**Comment by pmli** [comment]
> Ok, so let's introduce the labels 'new-feature', 'change', 'deprecation', 'removal', 'fix'? Other proposals, @pymor/pymor-devs?

Maybe it's beyond the topic of this issue, but how about also 'pymor.module_name', like [scipy is doing](https://github.com/scipy/scipy/labels?utf8=%E2%9C%93&q=scipy)? Then also 'pymortests', 'pymordemos', 'notebooks' and 'docs'. Maybe replace 'pep' with something which can't be confused with 'Python Enhancement Proposal', e.g. 'pymor-pep', or instead use 'proposal' or 'discussion'? [Sane GitHub labels](https://medium.com/@dave_lunny/sane-github-labels-c5d2e6004b63) might be interesting.

**Comment by renefritze** [comment]
I really like the category prefixes from that link, @pmli. I don't think we need priorities. I would then make


> the labels 'new-feature', 'change', 'deprecation', 'removal', 'fix'

into 
 - type: new-feature
 - type: change
 - type: deprecation
 - type: removal
 - type: fix

and additionally
 - type: pymor-pep (or ppep, or proposal)
 
I also somewhat like the scipy labels in the way that they describe the _target_ of the change. However, I feel like this would be too many categories for us. How about these?

 - target: infrastructure (buildsystem, CI, git-stuff)
 - target: demos
 - target: library (this needs a better word or be more fine grained)

**Comment by pmli** [comment]
> I don't think we need priorities.

I agree. Milestones are kind of fulfilling this purpose.

> I also somewhat like the scipy labels in the way that they describe the _target_ of the change.

NumPy has [categories](https://github.com/numpy/numpy/labels?utf8=%E2%9C%93&q=component), if that makes more sense, although I would prefer the shorter name.

> However, I feel like this would be too many categories for us.

I don't think there can be too many labels :) It would make the issue list easier to search (and also more colorful).

**Comment by sdrave** [comment]
Just had a chat with @renefritze: 

I believe we agreed on the 'type: XXX' labels. 

I would like to get rid of the 'PEP' label, as we have no established process how to treat PEPs, and with the new release cycle it should not be necessary. If we have a developer meeting after each release, we don't need any more formalism ATM, IMHO. 

Regarding 'target: ...' or 'category: ...' labels I am not convinced how useful they are for a project of pyMOR's size. Also, most PRs will touch many categories/modules (e.g. demos and library), so I don't really see the benefit. 'buildsystem' seems to be one exception which makes sense. Are there others? For me, one requirement for such a label would be that it is always obvious if a PR should have it or not.

Also, I propose to remove 'accepted', 'invalid', 'duplicate', 'wontfix', as we don't need them ATM.

**Comment by pmli** [comment]
> Just had a chat with @renefritze:
> 
> I believe we agreed on the 'type: XXX' labels.

Sounds good to me.

> I would like to get rid of the 'PEP' label, as we have no established process how to treat PEPs, and with the new release cycle it should not be necessary. If we have a developer meeting after each release, we don't need any more formalism ATM, IMHO.

Sounds good. How about also removing 'dev-meeting' or does it have a use I'm not aware of?

> Regarding 'target: ...' or 'category: ...' labels I am not convinced how useful they are for a project of pyMOR's size. Also, most PRs will touch many categories/modules (e.g. demos and library), so I don't really see the benefit. 'buildsystem' seems to be one exception which makes sense. Are there others? For me, one requirement for such a label would be that it is always obvious if a PR should have it or not.

I feel like there are also a lot of PRs which are about a specific module. E.g., I guess it would interesting to be able to see how many issues/PRs are about fixes to operators or vectorarrays.

> Also, I propose to remove 'accepted', 'invalid', 'duplicate', 'wontfix', as we don't need them ATM.

Agreed. Maybe also 'rejected'?

**Comment by sdrave** [comment]
I have just removed the mentioned labels (including 'rejected') and added the 'type:' labels. I also changed PR titles accordingly and added the corresponding labels. Furthermore I have remove the 'PEP' label.

I would like to keep the 'dev-meeting' label (as kind of the new 'PEP' label) as a documentation for what issues have been discussed during the last dev meeting. In particular, this seems helpful for judging whether or not the next release is on track.

Ok, so let's collect a few more useful keywords. Right now we have 'buildsystem' and 'sys-mor'. How about adding 'rb', 'linear algebra' (for stuff like pod, gram_schmidt), 'interfaces' (for changes to operator, vectorarray or discretization interfaces) and 'bindings'?

**Comment by sdrave** [comment]
I have just added these labels and attached them to all issues for the next release. There are still several issues left which do not fall into any of these categories. The remaining issues seem to be related to implementation improvements, testing or project governance. So we could add something like 'plumbing', 'testing', 'project' if we want to. (I am not sure about testing. Ideally all PRs that introduce something new should come with tests ..)

**Comment by pmli** [comment]
I'm also for 'testing'. I expect there will be (more than) a few issues/PRs dedicated to testing. Maybe also a label for notebooks/demos would be useful?

Just to be sure, are 'type: XXX' labels are meant only for PRs? If yes, I guess 'enhancement' label could be useful for issues, which would cover implementation improvements.

I would be for "management" instead of "governance". To me, "governance" sounds like, e.g., discussing if we should call @sdrave our BDFL.

**Comment by sdrave** [comment]
Ok, so how about adding 'testing', 'docs' and 'management'? 'docs' would apply to notebooks as well as other form of documentation?

Regarding the 'type: XXX' labels: I feel they are not really needed for issues, but could be applied there as well. Don't really have a strong opinion on this.

**Comment by sdrave** [comment]
Hmm, to get a consistent look, of the issues listing, I think it might be better to have a policy for this. Since it probably isn't clear for issues (at first at least) in which category they fall (what about issues with policy discussions?), I would vote for not applying them there.

**Comment by sdrave** [comment]
I forgot about the 'implementation' label. @pmli, I am not so sure about 'enhancement'. This sounds too generic to me. Instead of 'implementation', 'internal' might be another option?

**Comment by pmli** [comment]
I suggested 'enhancement' since it popular in [numpy](https://github.com/numpy/numpy/labels/01%20-%20Enhancement) and [scipy](https://github.com/scipy/scipy/labels/enhancement). Anyway, maybe it's ok to add some label, label some issues, and then rename the label...

**Comment by sdrave** [comment]
So I have added 'docs', 'testing', 'management' and 'internal' labels. I guess this can be closed now?

**Comment by sdrave** [comment]
Oh I see we haven't documented the pr keywords stuff in CONTRIBUTING.md yet. Should we do this?

**Comment by pmli** [comment]
Hm, can anybody except members of pymor organization add labels? Although, I guess either way it could be useful.

**Comment by sdrave** [comment]
I have just added the 'models' label for everything related to builtin models and discretizations.

**Comment by renefritze** [comment]
Just FYI: I now have a python code that can act as a GitHub app. Checking for or adding labels to PRs/issues is now trivial with it. Also commenting and whatnot.

**Comment by sdrave** [comment]
So, seems like labels can only be assigned to issues if you have the right permissions. Seems to make sense. Anyhow, I guess we do not need to document this policy. So I will close this issue now. @renefritze, cool! Still enforcing the labels is probably not worth the effort ATM.
