### ISSUE TITLE
Create ResearchGate project

### ISSUE THREAD

**Issue by sdrave** [pymor/pymor#537]
We decided at the dev meeting that it would be desirable to create a project page for pyMOR at ResearchGate.

**Comment by renefritze** [comment]
So I've created this on Friday during the session already. https://www.researchgate.net/project/pyMOR-Sustainable-Software-for-Model-Order-Reduction
I've added everyone I could think of too.

**Comment by sdrave** [comment]
Oh, I thought we were discussing a ResearchGate project for pyMOR, not the DFG project?

**Comment by renefritze** [comment]
Hah, I clearly did not. So which is it? Both? Also, @pmli already advised me that assigning contributors somewhat failed.

**Comment by sdrave** [comment]
So, as I understood the discussion, we want to have a ResearchGate project for pyMOR (the software), to advertise new releases, papers citing pyMOR and so on. I don't really see the need for a ResearchGate project for the DFG project ..

**Comment by renefritze** [comment]
https://www.researchgate.net/project/pyMOR-Model-Order-Reduction-with-Python

**Comment by sdrave** [comment]
I guess this can be closed?

**Comment by renefritze** [comment]
Right.
