### ISSUE TITLE
Officially support conda packages

### ISSUE THREAD

**Issue by sdrave** [pymor/pymor#538]
We kind of decided at the dev meeting that there should be conda packages for pyMOR. @renefritze already created some, but we do not advertise them yet.

**Comment by renefritze** [comment]
I think we should not advertise any builds from that until I've integrated those into CI. That said, I've done work under a pyMOR [organization](https://anaconda.org/pymor). All @pymor/pymor-devs who want access should tell me their Anaconda credentials and I'll see how that works.

**Comment by sdrave** [comment]
@renefritze, I have the impression that things are really moving towards conda-forge (e.g. https://twitter.com/teoliphant/status/729625025200984065). Before proceeding any further, we should really check if conda-forge might not be the better option.

**Comment by renefritze** [comment]
Not sure what this tweet means. It's also two plus years old.

**Comment by pmli** [comment]
Slycot 0.3.3 is in conda-forge, it that helps: https://anaconda.org/conda-forge/slycot

**Comment by sdrave** [comment]
Same is true for FEniCS. The download counts [here](https://anaconda.org/search?q=fenics) are quite interesting.

**Comment by renefritze** [comment]
And both are not available for Windows

**Comment by pmli** [comment]
It is possible for Slycot through a different channel: https://github.com/python-control/Slycot/issues/37

**Comment by sdrave** [comment]
@renefritze, granted. But looking at the downloads, conda-forge seems to be a very popular channel. And it seems promising, that packages from conda-forge are (kind of) compatible with each other.

**Comment by renefritze** [comment]
Packages in the default channel are also compatible with each other. And as it stands right now it seems that we cannot satisfy all of our (optional) dependencies from either default or conda-forge channels on linux and windows, which is somewhat required by the conda-forge process. So I guess I don't see the gain in trying to get into conda-forge right away.

**Comment by renefritze** [comment]
So apparently I was going by an outdated document on what "getting into conda-forge" entails. I thought this involved human council approval. Anyhow, now that I know better I'm still not convinced that we should target forge instead of default, because of the dependency issues. For example I just learned there's no scipy in forge on windows atm. What I am going to do though is prepare a feedstock for pymor to build conda packages from, and try to use that to build conda packages for linux(circle-ci), windows(appveyor) and macosx(travis) with it. When that works we can still decide to go for forge or continue in our own channel. The basic infrastructure with conda-smithy is the same.

**Comment by renefritze** [comment]
> Not sure what this tweet means. It's also two plus years old.

Anaconda forked the conda-forge recipes/feedstocks and started using them to build the official anaconda packages for those packages. It might also use the smithy.feedstock infra for all internal builds now, not sure.

**Comment by renefritze** [comment]
We're now in conda-forge: https://anaconda.org/conda-forge/pymor
Packages are still rebuilding, so check back if you only see windows as a listed platform. We _should_ get linux, osx and windows. 
The packages will have passed some rudimentary tests, but not our full suite: https://github.com/conda-forge/pymor-feedstock/blob/master/recipe/meta.yaml#L56

**Comment by renefritze** [comment]
I think there's nothing left to do here. Any issues with the conda package itself should go here: https://github.com/conda-forge/pymor-feedstock/issues
