### ISSUE TITLE
Double-check licensing issues with slycot

### ISSUE THREAD

**Issue by sdrave** [pymor/pymor#539]
At the dev meeting, @pmli was concerned that there might be licensing issues with slycot. Although the general opinion was that there aren't any problems, we should double-check.

**Comment by sdrave** [comment]
https://www.gnu.org/licenses/license-list.en.html#FreeBSD

**Comment by pmli** [comment]
So, as far as I understand, https://www.gnu.org/licenses/gpl-faq.html#IfLibraryIsGPL says that pyMOR can be licensed under FreeBSD (a GNU GPL compatible license), but a hypothetical "pyMOR + Slycot" package would have to be licensed under the GPL license version which Slycot uses.

It would seem https://www.gnu.org/licenses/gpl-faq.html#GPLWrapper also implies that it is legal to have a wrapper module licensed under a permissive license.

There is also https://www.gnu.org/licenses/gpl-faq.html#GPLPlugins, but I don't know how it applies to pyMOR and Slycot.

**Comment by renefritze** [comment]
This [here](https://opensource.stackexchange.com/questions/1487/how-does-the-gpls-linking-restriction-apply-when-using-a-proprietary-library-wi) seems was the most logical argument I could find.

My opinion is: we're only distributing pymor, nothing else. We're good.

**Comment by sdrave** [comment]
@renefritze, just to make sure: could there be any issue with our docker images?

**Comment by renefritze** [comment]
I think not. There's no derivative work, no recombination. Also source is available. If this was an issue, IMHO,  debian would have to be all gpl software.

**Comment by sdrave** [comment]
@pmli, are you convinced? Can we close this?

**Comment by pmli** [comment]
Well, I will probably only be 100% convinced if a lawyer says that what we are doing is ok, but since that doesn't seems likely, we can close this.
