### ISSUE TITLE
Bump minimum required Python version to 3.6

### ISSUE THREAD

**Issue by sdrave** [pymor/pymor#541]
We decided at the dev meeting that 2019.2 will require at least Python 3.6. If there are any benefits from that we might drop 3.6 as well.

**Comment by sdrave** [comment]
We should probably document [here](https://github.com/pymor/pymor#setting-up-an-environment-for-pymor-development) that master requires Python 3.6 or newer.

**Comment by renefritze** [comment]
Also, if there's declarative way to really tell pip/setuptools that we require python 3.6, we should think about putting our own runtime check into setup.py.
At least @sdrave and I were pretty sure that no tool actually obeys the trove classifiers.

**Comment by sdrave** [comment]
https://stackoverflow.com/questions/45778790/specifying-the-minimum-python-version-required-for-a-module-in-pip

Answer is from last year, so probably outdated and we need a new config file for that :wink:

**Comment by renefritze** [comment]
That ofc has the problem that everything in setup.py has.  If there's _any_ 3.6 feature "on the way" to running ```setuptools.setup``` we still fail horribly. 

The new config file actually wouldn't be bad, but AFAICT neither pep517/518 add a way to put a minimal python version into pyproject.toml, which is such a shame IMHO.

**Comment by sdrave** [comment]
Is there any problem with keeping setup.py compatible with Python 3.5? If no, using this feature might still be a good idea.

**Comment by renefritze** [comment]
One problem with keeping it compatible is we will never notice it if it becomes incompatible. As in there's no longer CI with 3.5.

**Comment by sdrave** [comment]
Also see #325.

**Comment by renefritze** [comment]
> Ok. So then let's just document it in the README ...

Well, I was thinking about adding an "importable check" for setup.py in CI for "older" pythons. If that's not simple I'll fall back on only documenting
