### ISSUE TITLE
Use f-strings throughout pyMOR

### ISSUE THREAD

**Issue by sdrave** [pymor/pymor#542]
At the dev meeting we decided to use the new f-string syntax in pyMOR.

Depends on #541.

**Comment by renefritze** [comment]
There's probably automation for that, right?

**Comment by renefritze** [comment]
> There's probably automation for that, right?

[Yes](https://github.com/asottile/pyupgrade)

Applied in 1e5632c5157c1c3e6d1d687c4276fc887c6c3fe6
This might have left out some corner cases:
> note: pyupgrade is intentionally timid and will not create an f-string if it would make the expression longer or if the substitution parameters are anything but simple names or dotted names (as this can decrease readability).

**Comment by sdrave** [comment]
Implemented in #553.
