### ISSUE TITLE
Should VectorArrays be thought of as column vectors?

### ISSUE THREAD

**Issue by sdrave** [pymor/pymor#545]
Currently, `VectorArrays` in pyMOR behave in some places like arrays of row vectors, which is in accordance with Numpy's conventions. At the dev meeting we had some heated discussions whether column vectors would be more appropriate. Possible implications:

- `NumpyVectorArray` would change it's storage format.
- The `to_numpy`/`from_numpy` methods would return/expect matrices of column vectors.
- The `dofs` method would return a 2d array of column vectors containing the selected dofs.

We decided that this should be discussed again after #544 has been implemented, which will allow to get rid of a lot of `from_numpy` calls.

**Comment by sdrave** [comment]
@pmli, #544 is now implemented. If you still fell, that we should transpose the arrays, we should discuss/implement this soon to have plenty of time for testing before the next release ..

**Comment by pmli** [comment]
Yes, I still feel that way, but I understand that it's nice to index vectors by `V[i]` instead of `V[:, i]`.

I think what I struggle with the most are `to_numpy`, `from_numpy`, `lincomb`, and `dofs` methods. Every time I use one of those, I need to think where and why to put `.T`. If we could change these methods, even if we keep vectors as rows in `NumpyVectorArray`, this would be quite helpful.

**Comment by sdrave** [comment]
- I do not care too much about the internal implementation of `NumpyVectorArray`. Nevertheless, it would be very surprising if `U.to_numpy()` was the transpose of `U._array`. So if we were to make the change, the internal storage format of `NumpyVectorArray` should change as well.

- The preferred memory layout of NumPy arrays is C contiguous. In particular, every array factory method will return a C contiguous array unless explicitly told otherwise. Hence, if we decide to use colum-vector arrays, vectors will be strided in memory. In particular, one cannot simply pass a `double *` to external libraries.

- Changing the interface will induce changes over the entire code base of pyMOR. So if we do this, there should be no work on other PRs for a week or so.

- I agree that column-vectors are what people are used to. But is there, apart from that, an argument why an interface with transposed arrays would be more useful?

**Comment by sdrave** [comment]
I did a quick benchmark to evaluate the implications of non-contiguous vector data. In general, I do not expect any performance hits in operations which take the entire array, so I decided to look at `gram_schmidt` which works on pairs of vectors:

```python
from pymor.basic import *
set_log_levels({'pymor': 'WARN'})
for e in range(6):
    print((100, 10**e)) 
    X = np.random.random((100, 10**e)) 
    XF = np.asfortranarray(X) 
    %timeit U = NumpyVectorSpace.from_numpy(X.copy('C')); gram_schmidt(U, copy=False) 
    %timeit UF = NumpyVectorSpace.from_numpy(XF.copy('F')); gram_schmidt(UF, copy=False) 
```
Passing `NumpyVectorSpace` a fortran-ordered array (without further copying it) would be equivalent to use C-ordered arrays of column vectors for data representation. On my machine (with `OMP_NUM_THREADS=1`) I get:

```
(100, 1)
11.5 ms ± 31.8 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
11.6 ms ± 33.9 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
(100, 10)
49.1 ms ± 220 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
55.2 ms ± 701 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
(100, 100)
234 ms ± 579 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)
269 ms ± 692 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)
(100, 1000)
254 ms ± 791 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)
333 ms ± 943 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)
(100, 10000)
398 ms ± 1.49 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
1.04 s ± 30.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
(100, 100000)
2.14 s ± 7.08 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
18.6 s ± 278 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

So the performance penalty can actually be quite severe for some use cases ...

**Comment by pmli** [comment]
I guess my issue is more about translating matrix operations and less about rows vs. columns. For example [`Br.apply_adjoint(Br.range.from_numpy(Q.T))`](https://github.com/pymor/pymor/blob/47598560d83a01b009ad8914ab7786abf28ee7a1/src/pymor/algorithms/sylvester.py#L109) looks more like `Br.T @ Q.T` than `Br.T @ Q`. Also in sylvester.py, [`W.lincomb(Q.conjugate())`](https://github.com/pymor/pymor/blob/47598560d83a01b009ad8914ab7786abf28ee7a1/src/pymor/algorithms/sylvester.py#L140) looks like `W @ Q.conjugate()`.

On the other hand, as [here](https://github.com/pymor/pymor/blob/47598560d83a01b009ad8914ab7786abf28ee7a1/src/pymor/bindings/pymess.py#L385-L388):
```python
if not trans:
    C = C.lincomb(Rci.T)  # C <- Rci^T * C = (C^T * Rci)^T
else:
    B = B.lincomb(Rci.T)  # B <- B * Rci
```
a vector array can sometimes be used to represent rows of an operator.

So, maybe the better approach is to try to make things more readable on a case by case basis. Later, we might decide to add more methods to the interface, as we did for `ones` and `random`.

**Comment by sdrave** [comment]
@pmli, I agree that the current interface is not idiomatic numerical linear algebra when it comes to transpositions. E.g. `Br.apply_adjoint(Br.range.from_numpy(Q.T))` is not as nice as `Br.apply_adjoint(Br.range.from_numpy(Q.T))`. On the other hand, if the behavior of `from_numpy` is changed to take an array of column vectors (i.e. `Br.range.from_numpy(Q)[i]` should correspond to `Q[:,i]`), then, to avoid unnecessary copies, the resulting `NumpyVectorArray` also has to store a matrix of column vectors with the consequences as described above.

I don't really see how to resolve this issue. Either we have to live with these transpositions, or we have to live with non-contiguous vectors.

You seem to propose to add additional interface methods. Do you have any concrete ideas how such methods would look like?

Regarding `lincomb`. If `U` is a matrix of row-vectors one want to take the linear combination of, then you would form `C @ U` where the coefficients would be the rows in `C` ..

Of course, one could also say that we think of `U` as a matrix of column-vectors even though its internal storage, the output of `to_numpy` and the imput of `from_numpy` is row-wise. Then `lincomb` and `dofs` could work with column-vectors. But I think that mixing both point of views is even more confusing.

**Comment by pmli** [comment]
> You seem to propose to add additional interface methods. Do you have any concrete ideas how such methods would look like?

No, nothing concrete right now.

`from_numpy` with `.T` actually doesn't appear as often as I expected.
```bash
$ grep -rn '\.from_numpy.*\.T' src/pymor
src/pymor/algorithms/sylvester.py:109:        BrTQ = Br.apply_adjoint(Br.range.from_numpy(Q.T))
src/pymor/algorithms/sylvester.py:128:        CrZ = Cr.apply(Cr.source.from_numpy(Z.T))
src/pymor/bindings/pymess.py:168:        return A.source.from_numpy(Z.T)
src/pymor/bindings/pymess.py:396:        return A.source.from_numpy(Z.T)
src/pymor/bindings/pymess.py:454:        return A.source.from_numpy(Z.T)
src/pymor/bindings/pymess.py:552:            y = self.a.source.from_numpy(y.T)
src/pymor/bindings/pymess.py:563:            y = self.a.source.from_numpy(y.T)
src/pymor/bindings/pymess.py:571:            y = self.a.source.from_numpy(y.T)
src/pymor/bindings/pymess.py:582:            y = self.a.source.from_numpy(y.T)
src/pymor/bindings/pymess.py:590:            y = self.a.source.from_numpy(y.T)
src/pymor/bindings/pymess.py:606:            y = self.a.source.from_numpy(y.T)
src/pymor/bindings/pymess.py:671:            y = self.a.source.from_numpy(y.T)
src/pymor/bindings/pymess.py:682:            y = self.a.source.from_numpy(y.T)
src/pymor/bindings/pymess.py:690:            y = self.a.source.from_numpy(y.T)
src/pymor/bindings/pymess.py:701:            y = self.a.source.from_numpy(y.T)
src/pymor/bindings/pymess.py:709:            y = self.a.source.from_numpy(y.T)
src/pymor/bindings/pymess.py:725:            y = self.a.source.from_numpy(y.T)
src/pymor/bindings/scipy.py:382:    return A.source.from_numpy(_chol(X).T)
src/pymor/bindings/scipy.py:518:    return A_source.from_numpy(_chol(X).T)
src/pymor/bindings/slycot.py:75:        return A.source.from_numpy(Z.T)
src/pymor/bindings/slycot.py:264:        return A_source.from_numpy(_chol(X).T)
```

`lincomb` is also not used so often.
```bash
$ grep -rn '\.lincomb(' src/pymor
src/pymor/algorithms/ei.py:209:            U_interpolated = collateral_basis[:len(interpolation_dofs)].lincomb(coefficients)
src/pymor/algorithms/basic.py:98:        return basis.lincomb(U.inner(basis, product))
src/pymor/algorithms/basic.py:103:        return basis.lincomb(coeffs)
src/pymor/algorithms/pod.py:106:        POD = A.lincomb(EVECS / SVALS[:, np.newaxis])
src/pymor/algorithms/sylvester.py:115:                    rhs -= A.apply(V.lincomb(TEr[i, :i:-1].conjugate()))
src/pymor/algorithms/sylvester.py:116:                rhs -= E.apply(V.lincomb(TAr[i, :i:-1].conjugate()))
src/pymor/algorithms/sylvester.py:121:        V = V.lincomb(Z.conjugate()[:, ::-1])
src/pymor/algorithms/sylvester.py:134:                    rhs -= A.apply_adjoint(W.lincomb(TEr[:i, i]))
src/pymor/algorithms/sylvester.py:135:                rhs -= E.apply_adjoint(W.lincomb(TAr[:i, i]))
src/pymor/algorithms/sylvester.py:140:        W = W.lincomb(Q.conjugate())
src/pymor/discretizers/fv.py:291:            return I.lincomb(U).to_numpy()
src/pymor/operators/basic.py:222:            UU = self.source_basis.lincomb(U.to_numpy())
src/pymor/operators/basic.py:239:            J = self.operator.jacobian(self.source_basis.lincomb(U.to_numpy()), mu=mu)
src/pymor/operators/basic.py:263:            V = self.range_basis.lincomb(V.to_numpy())
src/pymor/operators/constructions.py:562:            return self._array.lincomb(U.to_numpy())
src/pymor/operators/constructions.py:571:            return self._array.lincomb(V.to_numpy())
src/pymor/operators/ei.py:106:        return self.collateral_basis.lincomb(interpolation_coefficients)
src/pymor/operators/ei.py:136:            J = self.collateral_basis.lincomb(interpolation_coefficients)
src/pymor/operators/ei.py:164:        U_dofs = self.source_basis_dofs.lincomb(U.to_numpy())
src/pymor/operators/ei.py:174:        return self.projected_collateral_basis.lincomb(interpolation_coefficients)
src/pymor/operators/ei.py:185:        U_dofs = self.source_basis_dofs.lincomb(U.to_numpy()[0])
src/pymor/operators/ei.py:197:        M = self.projected_collateral_basis.lincomb(interpolation_coefficients)
src/pymor/operators/interfaces.py:251:            V.lincomb(U.to_numpy()) == self.apply(U, mu)
src/pymor/reductors/basic.py:126:        return self.bases[basis][:u.dim].lincomb(u.to_numpy())
src/pymor/reductors/basic.py:468:        U_proj_err = U - basis.lincomb(U.inner(basis, product))
src/pymor/reductors/residual.py:45:            == residual.apply(RB.lincomb(u), mu)
src/pymor/reductors/residual.py:110:            return self.residual_range[:u.dim].lincomb(u.to_numpy())
src/pymor/reductors/residual.py:200:            == riesz_residual.apply(RB.lincomb(u), RB.lincomb(u_old), mu)
src/pymor/reductors/residual.py:267:            return self.residual_range[:u.dim].lincomb(u.to_numpy())
src/pymor/reductors/bt.py:95:        self.V = cf.lincomb(sV[:r])
src/pymor/reductors/bt.py:96:        self.W = of.lincomb(sU[:r])
src/pymor/reductors/sobt.py:118:        return pcf.lincomb(Vp[:r]), vof.lincomb(Uv[:r]), sp
src/pymor/reductors/sobt.py:140:        return vcf.lincomb(Vv[:r]), vof.lincomb(Uv[:r]), sv
src/pymor/reductors/sobt.py:162:        return pcf.lincomb(Vpv[:r]), vof.lincomb(Upv[:r]), spv
src/pymor/reductors/sobt.py:186:        return vcf.lincomb(Vvp[:r]), vof.lincomb(Uv[:r]), svp
src/pymor/reductors/sobt.py:242:        self.V = pcf.lincomb(Vp[:r])
src/pymor/reductors/sobt.py:327:        self.V1 = pcf.lincomb(Vp[:r])
src/pymor/reductors/sobt.py:328:        self.W1 = pof.lincomb(Up[:r])
src/pymor/reductors/sobt.py:329:        self.V2 = vcf.lincomb(Vv[:r])
src/pymor/reductors/sobt.py:330:        self.W2 = vof.lincomb(Uv[:r])
src/pymor/reductors/sobt.py:358:                                           source_basis=self.V1.lincomb(W1TV1invW1TV2.T)),
src/pymor/reductors/sobt.py:364:                                            source_basis=self.V1.lincomb(W1TV1invW1TV2.T)),
src/pymor/vectorarrays/block.py:115:        lincombs = [block.lincomb(coefficients) for block in self._blocks]
src/pymor/vectorarrays/numpy.py:487:        return self.base.lincomb(coefficients, _ind=self.ind)
src/pymor/bindings/pymess.py:386:                    C = C.lincomb(Rci.T)  # C <- Rci^T * C = (C^T * Rci)^T
src/pymor/bindings/pymess.py:388:                    B = B.lincomb(Rci.T)  # B <- B * Rci
```

Anyway, I guess it should be expected that confusing things happen when interpreting a tall or short matrix (e.g. `B` and `C`) as a collection of vectors... I'm not sure how to resolve this.

**Comment by sdrave** [comment]
I think we need to come to a conclusion with this issue. I see two options:

1. Leave everything as is.

2. Use column vectors as storage format for `NumpyVectorArray` and make `to_numpy`, `from_numpy`, `lincomb`, `dofs` work with column vectors instead of row vectors. To prevent performance degradation, `NumpyVectorArray` should work with Fortran ordered arrays. If an array is passed which is C ordered, we emit a warning in case it is above a certain dimension.

Consequences of adopting 2:
- We will break all existing code that uses pyMOR.
- Since C ordering is the default in NumPy, warnings about missing Fortran ordering will not be too uncommon.
- The new convention would be in line with what most people new to pyMOR would expect. Since NumPy/SciPy uses column vectors for la routines itself, less transpositions will be needed in general.

If this is desired, I would be willing to test option 2 in a branch.

> Anyway, I guess it should be expected that confusing things happen when interpreting a tall or short matrix (e.g. B and C) as a collection of vectors... I'm not sure how to resolve this.

I am quite sure that there is no way to avoid transpositions for both B and C.

**Comment by pmli** [comment]
I'm getting around to the idea of thinking of vector arrays as lists of 1D vectors. So I'm for leaving it as is.
