### ISSUE TITLE
Further improve RuleTables

### ISSUE THREAD

**Issue by sdrave** [pymor/pymor#546]
As discussed at the dev meeting, the `RuleTable` implementation should be further improved to make debugging easier.

**Comment by renefritze** [comment]
Can you add an example of where debugging a RuleTable can/should be made easier? I would just step the evaluation in pdb and that works for me.

**Comment by renefritze** [comment]
So you're thinking of something like an automagic that ouputs a trace of an object through the rules it got handled by?

**Comment by sdrave** [comment]
Yeah, something like that. I guess, this is rather low priority, however.
