### ISSUE TITLE
Adopt dataclasses for instances of `ImmutableInterface`?

### ISSUE THREAD

**Issue by sdrave** [pymor/pymor#549]
At the dev meeting we discussed whether we want to make each instance of `ImmutableInterface` a dataclass. Apart from the benefit of having to write less boilerplate code in `__init__`, another advantage might be that `with_` might get a cleaner implementation which will always work.

We decided to experiment with this before we come to a decision.

**Comment by sdrave** [comment]
So I had a brief look how `LincombOperator` would look like as a `dataclass` and the result was not too promising. In particular, `dataclasses` perform no automatic argument conversion to the given type. In particular, for the `operators` and `coefficients` args, one still has to manually cast them into tuples.

**Comment by pmli** [comment]
> In particular, for the `operators` and `coefficients` args, one still has to manually cast them into tuples.

Does it make sense to only allow tuples everywhere, to avoid issues like #439?

**Comment by sdrave** [comment]
The two main benefits of dataclasses in my initial comment are implemented in #694 and #732, so I think we can close this issue.
