### ISSUE TITLE
flake8 ignore W503 or W504?

### ISSUE THREAD

**Issue by pmli** [pymor/pymor#554]
Relatively recently, flake8 plugin in my editor started reporting both W503 (line break before binary operator) and W504 (line break after binary operator). [1]

I guess now pyMOR can choose which one should be ignored. Thoughts @pymor/pymor-devs?

[1] https://pycodestyle.readthedocs.io/en/latest/intro.html#error-codes

**Comment by renefritze** [comment]
I'm fine with ignoring both, since they're not PEP8. I wonder how this is new behavior for you though.

**Comment by pmli** [comment]
It seems it used to be recommended to break after the binary operator and now it is only recommended to be consistent:
https://www.python.org/dev/peps/pep-0008/#should-a-line-break-before-or-after-a-binary-operator

I guess I noticed changes because of the addition of W504 to pycodestyle 2.4:
https://pycodestyle.readthedocs.io/en/latest/developer.html#changes

I see this as an opportunity to fix one style in pyMOR. I would vote for the more mathematical one (breaking before binary operators).

**Comment by sdrave** [comment]
I don't really care. Actually, I don't even care if it's consistent or not ..

**Comment by pmli** [comment]
Hm, I think I would find long if clauses (e.g. [this](https://github.com/pymor/pymor/blob/5ae4bcf7813b04731530d9b203da282e68475d6d/src/pymor/discretizations/iosys.py#L783-L790), [this](https://github.com/pymor/pymor/blob/5ae4bcf7813b04731530d9b203da282e68475d6d/src/pymor/operators/block.py#L393-L395) and [this](https://github.com/pymor/pymor/blob/5ae4bcf7813b04731530d9b203da282e68475d6d/src/pymor/operators/constructions.py#L595-L597)) and arithmetic expressions (e.g. [these](https://github.com/pymor/pymor/blob/5ae4bcf7813b04731530d9b203da282e68475d6d/src/pymor/operators/block.py#L480-L518)) easier to read if there were line breaks before binary operators. But, if you want to ignore both flake8 warnings, that's also fine.

**Comment by sdrave** [comment]
Just to clarify: I am not advocating ignoring W503 and W504. I am just saying that I will be fine with any policy regarding this question ..

**Comment by renefritze** [comment]
I'm ok with break before binary ops.
