### ISSUE TITLE
NonProjectedResidualOperator returns NaNs

### ISSUE THREAD

**Issue by andreasbuhr** [pymor/pymor#555]
Hi,

in pymor 0.4.x, I get NaN values when the residual should be zero because of the division by zero in
https://github.com/pymor/pymor/blob/a197ce03802af818ba329b505af03e8d79025a5b/src/pymor/reductors/residual.py#L174

best,
Andreas

**Comment by sdrave** [comment]
As discussed with @andreasbuhr, it should be fine to handle the norm zero separately. Apart from that, the implementation is broken for `len(U)` > 1.

**Comment by sdrave** [comment]
Fixed in #569.
