### ISSUE TITLE
Start testing against python 3.8

### ISSUE THREAD

**Issue by renefritze** [pymor/pymor#558]
This is a reminder for myself to add 3.8 to the docker ecosystem and start testing as allowed failing once Beta 1 is released. The current plan for that is end of may, with the final release end of october.

**Comment by renefritze** [comment]
For future reference: [PEP 569 -- Python 3.8 Release Schedule](https://www.python.org/dev/peps/pep-0569/)

**Comment by sdrave** [comment]
Python 3.8 has been released in December ..

**Comment by renefritze** [comment]
This has been blocked by waiting on a 3.8 compatible mpi4py release since I've readied the infrastructure at the last 3.8 rc.
