### ISSUE TITLE
Set cython language_level

### ISSUE THREAD

**Issue by renefritze** [pymor/pymor#562]
I've just discovered this in a build log

`
gcc -pthread -shared build/temp.linux-x86_64-3.7/src/pymor/grids/_unstructured.o -L/usr/local/lib -lpython3.7m -o /builds/pymor/pymor/src/pymor/grids/_unstructured.cpython-37m-x86_64-linux-gnu.so
/usr/local/lib/python3.7/site-packages/Cython/Compiler/Main.py:367: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /builds/pymor/pymor/src/pymor/tools/relations.pyx`

**Comment by sdrave** [comment]
I guess this is not really an issue, as the little Cython code we have should be compatible with both Python 2 and 3. Nevertheless, it would probably be prudent to set language_level to 3 ..

**Comment by renefritze** [comment]
Implemented in #586
