### ISSUE TITLE
More flake8 errors and warnings

### ISSUE THREAD

**Issue by pmli** [pymor/pymor#564]
Running on current master (7885b0cf1ddde4cc0f471a34d4f7e6ffc76f7a0b):

```bash
$ flake8 --version
3.7.0 (mccabe: 0.6.1, pycodestyle: 2.5.0, pyflakes: 2.1.0) CPython 3.6.8 on Linux
$ flake8 | wc -l
590
$ flake8 src/pymor/ | wc -l
77
$ flake8 src/pymortests/ | wc -l
293
$ flake8 src/pymordemos/ | wc -l
110
$ flake8 | grep E741 | wc -l
67
$ flake8 src/pymor/ | grep E741 | wc -l
47
$ flake8 src/pymor/ | grep -v E741
src/pymor/reductors/residual.py:93:121: E501 line too long (121 > 120 characters)
src/pymor/reductors/residual.py:244:121: E501 line too long (124 > 120 characters)
src/pymor/operators/mpi.py:9:1: F401 'pymor.vectorarrays.numpy.NumpyVectorSpace' imported but unused
src/pymor/operators/mpi.py:60:48: E711 comparison to None should be 'if cond is None:'
src/pymor/operators/numpy.py:165:12: F632 use ==/!= to compare str, bytes, and int literals
src/pymor/gui/qt.py:199:14: E401 multiple imports on one line
src/pymor/gui/qt.py:359:63: E127 continuation line over-indented for visual indent
src/pymor/core/pickle.py:25:1: F401 'sys' imported but unused
src/pymor/core/pickle.py:77:1: E303 too many blank lines (4)
src/pymor/core/cache.py:295:5: E731 do not assign a lambda expression, use a def
src/pymor/core/cache.py:408:13: E117 over-indented
src/pymor/core/cache.py:419:37: E117 over-indented (comment)
src/pymor/core/config.py:17:1: E302 expected 2 blank lines, found 1
src/pymor/tools/mpi.py:123:13: E722 do not use bare 'except'
src/pymor/tools/mpi.py:185:13: E722 do not use bare 'except'
src/pymor/tools/mpi.py:301:33: E127 continuation line over-indented for visual indent
src/pymor/tools/quadratures.py:236:13: E117 over-indented
src/pymor/algorithms/basic.py:56:9: E731 do not assign a lambda expression, use a def
src/pymor/algorithms/timestepping.py:160:15: E127 continuation line over-indented for visual indent
src/pymor/algorithms/timestepping.py:161:15: E127 continuation line over-indented for visual indent
src/pymor/algorithms/image.py:278:51: F821 undefined name 'image'
src/pymor/algorithms/gram_schmidt.py:75:57: F821 undefined name 'old_norm'
src/pymor/algorithms/gram_schmidt.py:90:17: F841 local variable 'old_norm' is assigned to but never used
src/pymor/algorithms/gram_schmidt.py:168:59: F821 undefined name 'old_norm'
src/pymor/algorithms/error.py:192:23: E128 continuation line under-indented for visual indent
src/pymor/parameters/functionals.py:114:9: E731 do not assign a lambda expression, use a def
src/pymor/parameters/spaces.py:98:9: E731 do not assign a lambda expression, use a def
src/pymor/discretizers/fv.py:144:19: F821 undefined name 'nonlinear_advection_upwind_operator'
src/pymor/discretizers/cg.py:287:87: E713 test for membership should be 'not in'
src/pymor/analyticalproblems/text.py:47:57: E117 over-indented (comment)
```

So, there are still plenty of code style issues. Most of them are not even in `src/pymor`. Of those in `src/pymor` most are about using `l` and `I` for variable names (E741), but there are still many other types.

@pymor/pymor-devs How do we decide which issues to ignore (by updating setup.cfg or just "mentally") and which to fix?

**Comment by renefritze** [comment]
"Mentally" definitely does not work for me, so I'd prefer formally in setup.cfg

**Comment by pmli** [comment]
I'm not sure I understand. Do we want `flake8 | wc -l` to output `0`? If not, how do we specify exceptions which do not enter setup.cfg and are not ignored using `# noqa`?

**Comment by sdrave** [comment]
I guess now would be a good time to decide what should be ignored. I would say:

E741 ambiguous variable name
E731 do not assign a lambda expression, use a def

Everything else should be fixed in general, IMHO.

**Comment by sdrave** [comment]
@pmli, we would just live with the fact that flake8 reports issues?

**Comment by pmli** [comment]
I agree about E741 and E731.

I guess doing all flake8 fixes in one PR would be too much and maybe it's better to set a policy to try not to introduce new flake8 issues in future PRs.

**Comment by pmli** [comment]
I tried running `pep8` to see what happens and got this

```bash
$ pep8
/.../site-packages/pep8.py:2124: UserWarning: 

pep8 has been renamed to pycodestyle (GitHub issue #466)
Use of the pep8 tool will be removed in a future release.
Please install and use `pycodestyle` instead.

$ pip install pycodestyle
$ pycodestyle ...
```

@renefritze @sdrave Should we remove `pep8` from setup.cfg, since `pycodestyle` is contained in flake8?

**Comment by renefritze** [comment]
> @renefritze @sdrave Should we remove `pep8` from setup.cfg, since `pycodestyle` is contained in flake8?

I'm actually quite unsure why there's duplicate sections now. Shouldn't pycodestyle run from flake8 use it's designated section for options? 

Either way, I would prefer if I can run pycodestyle stand-alone and it still uses the same options as when run by flake8. If that needs duplication (and section renaming) then I'm fine by that.

**Comment by pmli** [comment]
Few more things:

- Should we limit the line length for docstring, which is possible with option `max-doc-length` in `flake8` (similar to `max-line-length`)? [PEP8](https://www.python.org/dev/peps/pep-0008/#maximum-line-length) recommends 72 as the maximum line length.
- In `pymor.discretizers.fv`, `nonlinear_advection_upwind_operator` is used, but it is defined nowhere in pyMOR:
  ```bash
  $ grep -rn nonlinear_advection_upwind_operator
  src/pymor/discretizers/fv.py:144:            L += [nonlinear_advection_upwind_operator(grid, boundary_info, p.nonlinear_advection,
  ```

**Comment by sdrave** [comment]
@renefritze, I believe the PEP8 section was for the pep8 tool, and flake8 ignores this section. I have nothing against the duplication.

@pmli, I believe that 72 characters is very short. For normal code we allow 120 chars. I would go with 100 chars at least. Regarding  `nonlinear_advection_upwind_operator` I guess this code path actually belongs to a private branch which somehow ended up in master. This should be removed.

**Comment by pmli** [comment]
Yeah, 72 is probably too short:
```bash
$ flake8 --max-doc-length=72 | grep W505 | wc -l
2119
```
100 seems ok.
```bash
$ flake8 --max-doc-length=100 | grep W505 | wc -l
68
```
