### ISSUE TITLE
Auto generate scripts form jupyter notebooks

### ISSUE THREAD

**Issue by sdrave** [pymor/pymor#573]
It would be desirable if pyMOR would still ship demonstration scripts that work without jupyter. Auto generating such scripts from notebooks might be an option.

**Comment by renefritze** [comment]
So if we go with auto-synced jupytext scripts as proposed in #572 we would have to ensure that those actually execute without error. 

When you say "without jupyter" what do you mean precisely? Outside of a notebook server? Or without jupyter the package present in the python environment?

**Comment by sdrave** [comment]
At least outside of notebook server. If the jupyter package is needed, that would be ok. Of course it would be nicer if it could be avoided.

**Comment by renefritze** [comment]
IMO this would be covered if we let `nb2plots` also generate 'empty' python scripts alongside the 'full' jupyter notebooks.

**Comment by renefritze** [comment]
@sdrave agreed with me offline, with some additional discussion concerning new testing that should go into a separate issue.

**Comment by sdrave** [comment]
Closing in favor of #876, #877, #878.
