### ISSUE TITLE
Models containing a tuple of operators

### ISSUE THREAD

**Issue by pmli** [pymor/pymor#580]
`LinearDelayModel`, `LinearStochasticModel` and `BilinearModel` all have an attribute which is a tuple of operators. Creating these models fails, since `ModelBase.__init__` assumes there are no tuples when checking [linearity](https://github.com/pymor/pymor/blob/67097558e2e6d04dd5020c64743b3b0b509b973e/src/pymor/models/basic.py#L45). (This check is also wrong for the `BilinearModel`, which is nonlinear even though it only contains linear operators.)

Creating `special_operators` inside `...Model.__init__` and modifying `super().__init__(...)` can fix this. The issue arises when trying to use `with_`, which uses `with_arguments`, and I don't know if that can be modified in `...Model.__init__`.

@sdrave Is it possible to fix this by only modifying `pymor.models.iosys` or are bigger changes necessary?

**Comment by pmli** [comment]
> Sounds like this issue is also present in the current release?

Yes, it is.

**Comment by sdrave** [comment]
Ok, so there is actually no code shipped with pyMOR which actually uses these three classes?

**Comment by pmli** [comment]
True. It's not even in `pymor.basic`.

**Comment by pmli** [comment]
From what I understand, `with_` uses `with_arguments`, which in turn depends on `_init_arguments` from `UberMeta`. I guess this means that if `operators` cannot contain tuples, then also `...Model.__init__` cannot have tuples...

**Comment by sdrave** [comment]
Sounds like customizing `with_` might be the right approach (for now).

**Comment by sdrave** [comment]
@pmli, with #592 merged, this should be hopefully easy to fix?

**Comment by pmli** [comment]
I'd say it's already fixed, since `notebooks/delay.ipynb` works.

**Comment by sdrave** [comment]
All the better. Regarding the last release, maybe the easiest would be to just remove these classes?

**Comment by pmli** [comment]
Agreed.
