### ISSUE TITLE
Identity operator between vector spaces of different id

### ISSUE THREAD

**Issue by pmli** [pymor/pymor#581]
This could be useful, e.g. when the output of a system is equal to the state (`C = I` for an `LTIModel`).

**Comment by pmli** [comment]
I'm considering removing the constraint that the `input_space`, `state_space` and `output_space` need to be different and moving `__add__` from `InputStateOutputModel` to its subclasses (especially considering #580)...

**Comment by sdrave** [comment]
I agree that such an `Operator` would be useful.

@pmli, regarding your last comment: These spaces need to be different, at least `state_space` from the others, or `GenericPGReductor` will fail, as it uses the spaces to decided what gets projected with which basis. As I said in #580, I feel that the constraint that `GenericPGReductor` and `GenericRBReductor` should work automatically, is not really helpful.

**Comment by pmli** [comment]
Right. This (and also projection for general nonlinearities `f(t, x(t), u(t))`) would be my motivation for removing `GenericPGReductor`.

**Comment by sdrave** [comment]
What would be the issues with the nonlinearities? Anyhow, I guess we should start discussing a reductor overhaul in a separate issue.

In any case we should implement such an operator, however.

**Comment by pmli** [comment]
@sdrave With #589 and #592 merged, where are vector space IDs still used? I could find them in `as_vector` and `operators.mpi`.

**Comment by sdrave** [comment]
@pmli, I have made the mpi wrapping code less dependent on space ids in #608. Still ids can be used there to select which spaces require mpi wrapping. In case you want to get rid of `VectorSpace` ids, we should discuss this in a separate issue ..

**Comment by sdrave** [comment]
In view of #609, i think we do not really need this operator anymore. Shall we close this issue?

**Comment by pmli** [comment]
Yes, I think it's ok to close this.
