### ISSUE TITLE
RTD builds failing

### ISSUE THREAD

**Issue by sdrave** [pymor/pymor#583]
Since renaming Discretizations to Models, builds on RTD fail with an import error in
`"/home/docs/checkouts/readthedocs.org/user_builds/pymor/envs/latest/lib/python3.6/site-packages/pymor-0+untagged.176.g6709755-py3.6-linux-x86_64.egg/pymor/discretizations/iosys.py`.

@renefritze, any idea what is going on? The `discretizations` module no longer exists in master ...

**Comment by renefritze** [comment]
Build env on RTD needed a wipe again. Works now.
