### ISSUE TITLE
Model / Reductor simplifications

### ISSUE THREAD

**Issue by sdrave** [pymor/pymor#587]
As already discussed in #580, I would like to simplify the implementation of `Models` and the mechanics of the reduction process. The general idea is the following:

- `Models` loose their `operators` dict. (If really needed, `operators` could be made a property that automatically fetches all `Operators` from the instance dict. However, I am not convinced that we really need this dict.)
- There will be a generic `ProjectionBasedReductor` base class, which manages a dict of bases with strings as keys. Furthermore it has a dict of the form `{op: (range_basis, source_basis, product)}`, where `op` is a model attribute and `range_basis`, `source_basis` are keys in the basis dict. (Not sure how to exactly handle products and the case where operators should be projected to identity.) In `reduce`, the dict of projected `Operators` is computed, which is then passed to the abstract `build_rom` method.
- For instance, `CoerciveRBReductor` would derive from `ProjectionBasedReductor` and specify the projection dict according to a RB projection of a `StationaryModel`. `build_rom` is implemented by instantiating a `StationaryModel` holding the projected `Operators`.

Remarks:
- Today I had a longer discussion with @andreasbuhr about the usage of `with_`. My personal conclusion from it is that we should see `with_` similar to a constructor in the sense that it usually does not make a lot of sense to call `with_` in a polymorphic context. E.g., you might want to subclass `StationaryModel` to a `DuneModel` which gets the path of an ini file as only argument. Exchanging `operator` of such a model usually means to down-cast to `StationaryModel`. This is bothersome to implement and quite dubious to the user.
- Previously I have been using an `as_generic_type` method, which performs the down-cast before calling `with_`. However, what is the right generic type? Think of using `ParabolicRBReductor` on a `DuneLTIModel`. In that case, the right generic type would be `InstationaryModel`, but for a BT reductor the right generic type would be `LTIModel` (once they derive from each other...)
- By not relying on `with_` in reductors and not using `operators`, the implementation of `Models` should be much less convoluted.
- The RB reduction of a `DuneModel` would work right out of the box. Applying `ParabolicRBReductor` to a `DuneLTIModel` would lead to an `InstationaryModel`. To automatically arrive at an `LTIModel`, one would have to subclass `ParabolicRBReductor` as `ParabolicLTIRBReductor` and perform an upcast to `LTIModel` in `build_rom`. I would hope there are only few instances where such a special treatment would be required.
- By explicitly stating the reduction rules, space ids become irrelevant for the reduction process. In particular, input, output and state space ids could agree in `LTIModel`. 

What do you think, @pymor/pymor-devs? If we agree that this is generally the right approach, I will start hacking on this.

**Comment by pmli** [comment]
> * There will be a generic `ProjectionBasedReductor` base class, which manages a dict of bases with strings as keys. Furthermore it has a dict of the form `{op: (range_basis, source_basis, product)}`, where `op` is a model attribute and `range_basis`, `source_basis` are keys in the basis dict. (Not sure how to exactly handle products and the case where operators should be projected to identity.) In `reduce`, the dict of projected `Operators` is computed, which is then passed to the abstract `build_rom` method.

What would `product` be here? Is it again something only used for the initial condition? Or would it mean "`range_basis` and `source_basis` are orthogonal in the inner product `product`"?

> * Today I had a longer discussion with @andreasbuhr about the usage of `with_`. My personal conclusion from it is that we should see `with_` similar to a constructor in the sense that it usually does not make a lot of sense to call `with_` in a polymorphic context. E.g., you might want to subclass `StationaryModel` to a `DuneModel` which gets the path of an ini file as only argument. Exchanging `operator` of such a model usually means to down-cast to `StationaryModel`. This is bothersome to implement and quite dubious to the user.

I don't understand the example with `DuneModel`. Couldn't `StationaryModel` have `from_dune_ini` method which would create a `StationaryModel` instance? And similarly for `DuneLTIModel` and `LTIModel`?

**Comment by sdrave** [comment]
> What would product be here? Is it again something only used for the initial condition? Or would it mean "range_basis and source_basis are orthogonal in the inner product product"?

The former. It's basically the signature of the `project` method. - Nobody said that this is only intended for initial conditions. But yes, for the currently available builtin models, it's only used for the initial condition. For the latter, a different specification is required. (As I said, I haven't flushed out all of the details yet.)

> I don't understand the example with DuneModel. Couldn't StationaryModel have from_dune_ini method which would create a StationaryModel instance? And similarly for DuneLTIModel and LTIModel?

When integrating external sovlers, you usually have two options: Either, you use a generic `Model` class like `StationaryModel`, or you derive from this class. The latter is usually preferred when you need to have something like a discretization object in the solver you require a reference to or when you want to override `solve` to use the solver's impl. Also, you might want to expose solver specific features as methods of the pyMOR `Model`. Obvioulsy, a `from_dune_ini` makes no sense, as you would have to provide such a method for each possible solver code that might ever be used. That's what inheritance is for. - Anyhow, I am not quite sure what exactly you don't understand in the example.

**Comment by pmli** [comment]
Aha, ok, I thought the "path of an ini file" would be an "operator" for `DuneModel`, not that one would also want different methods for the model.

Concerning up/down-casting, I would say it's better not to make it overly complicated right now, since we might be changing the inheritance structure. Discussing how `ParabolicRBReductor` is supposed to work on an `LTIModel`, which doesn't have a working `solve` method and can have an arbitrary input `u(t)` (i.e. `rhs`), is too abstract for me right now. I guess, for now it's ok to have `to_lti` and `to_instationary` to change the type of FOM and ROM. Also, it makes sense to interpret an `LTIModel` as a `StationaryModel` with `s` as a parameter, use `CoerciveRBReductor`, and convert the ROM into an `LTIModel`.
