### ISSUE TITLE
Add links to gitlab ci builds

### ISSUE THREAD

**Issue by sdrave** [pymor/pymor#601]
It would be nice if there could be links to the running gitlab ci builds in the PR check summaries like we had for travis.

**Comment by renefritze** [comment]
Not sure what you want that isn't the 'Details' link.

**Comment by sdrave** [comment]
Which only becomes available *after* the build completes, not while it is still running.

**Comment by renefritze** [comment]
Uhm, no?

![screenshot-github](https://user-images.githubusercontent.com/47802/53249990-bed52480-36b9-11e9-930d-c6d80125a832.png)

**Comment by sdrave** [comment]
Not in https://github.com/pymor/pymor/pull/592

**Comment by renefritze** [comment]
Lets hope that that's due to that PR having been opened before I merged the CI stuff to master then. The two new PRs from today are fine. And also have actual icons.

**Comment by sdrave** [comment]
After a rebase on master, the PR behaves as expected ..
