### ISSUE TITLE
0.6.0rc0 tag missing?

### ISSUE THREAD

**Issue by renefritze** [pymor/pymor#605]
Did we just forgot about it?

**Comment by sdrave** [comment]
I guess we haven't created one. Could you remind me why we needed one?

**Comment by renefritze** [comment]
Master builds carry a 0.5.1-something version now, which isn't too nice for ordering requirements.

**Comment by sdrave** [comment]
A so this is relevant for the wheel building? Otherwise I would no longer care ..

**Comment by sdrave** [comment]
BTW, shouldn't it be a 2019.2rc0 tag?

**Comment by renefritze** [comment]
> A so this is relevant for the wheel building? Otherwise I would no longer care ..

Yes. Also RTD.

> BTW, shouldn't it be a 2019.2rc0 tag?

Right.

**Comment by renefritze** [comment]
Pushed
