### ISSUE TITLE
Automatic PR closing

### ISSUE THREAD

**Issue by renefritze** [pymor/pymor#610]
Would the @pymor/pymor-devs like to able to automatically merge PRs when all checks are ready and you've either put a certain label or comment on the PR? I've found myself looking way too often on PR status where I know it's ready to merge once CI clears. I would like to comment 'Ready to merge' once I'm done with changes and a bot comes in and pushes the button for me once CI is green.

**Comment by sdrave** [comment]
I think I would prefer to keep modifying master a manual process ..

**Comment by renefritze** [comment]
The solution I have in mind only pushes the Button on Github though it does not modify master on it's own.

**Comment by sdrave** [comment]
Doesn't pushing the button modify master?

**Comment by renefritze** [comment]
Your concern sounded targeted towards the application doing something untowards with the merge when it handles git itself. 
This is the GitHub app src btw: https://github.com/palantir/bulldozer/
It would run in the same space as the Gitlab bridge.

**Comment by pmli** [comment]
> I've found myself looking way too often on PR status where I know it's ready to merge once CI clears.

I don't think I've ever been in such a situation... But, I often add @sdrave as a reviewer, so maybe approved reviews can also be made required for merging?

**Comment by renefritze** [comment]
Bulldozer relies on Github's branch protection rules telling when it can merge the PR. The only thing configurable in bulldozer is when it should merge. So a merge only happens it should and can. 
AFAICT the only option in Github's branch protection rules wrt reviews is to require a total number of them before you can merge. It's not enforceable there that a review is only required iff requested. 
I definitely do not want mandatory reviews atm.

**Comment by renefritze** [comment]
After talking offline @sdrave is not opposed to me setting this up, but would not want to use it in his own PRs. Sound good for the other @pymor/pymor-devs too?

**Comment by renefritze** [comment]
This is now finally live for the repos under the pymor org. Once a "merge when ready" comment is added the next successful CI run will trigger the auto merge.
