### ISSUE TITLE
Incorrect adjoint of LincombOperator in case of complex coefficients

### ISSUE THREAD

**Issue by sdrave** [pymor/pymor#643]
`LincombOperator.coefficients` are not conjugated in `H`, `apply_adjoint` and `apply_inverse_adjoint`. Unfortunately, to correctly implement this we will need a `ConjugateParameterFunctional` ..

**Comment by pmli** [comment]
Can parameter functionals be complex-valued?

**Comment by sdrave** [comment]
Why not?

**Comment by pmli** [comment]
I would guess that if operators are usually real, then the same is true for functionals. But, then there are shifted operators...
