### ISSUE TITLE
state_space issues

### ISSUE THREAD

**Issue by pmli** [pymor/pymor#645]
Right now, `ModelInterface` has a [`solution_space`](https://github.com/pymor/pymor/blob/443fe97d9e0351deaed6c9ea63b76ada39c85dc5/src/pymor/models/interfaces.py#L21-L22) attribute, while input-output models define it and the [`state_space`](https://github.com/pymor/pymor/blob/443fe97d9e0351deaed6c9ea63b76ada39c85dc5/src/pymor/models/iosys.py#L126) with the same value ([`LTIModel`](https://github.com/pymor/pymor/blob/443fe97d9e0351deaed6c9ea63b76ada39c85dc5/src/pymor/models/iosys.py#L236), [`SecondOrderModel`](https://github.com/pymor/pymor/blob/443fe97d9e0351deaed6c9ea63b76ada39c85dc5/src/pymor/models/iosys.py#L1024), [`LinearDelaySystem`](https://github.com/pymor/pymor/blob/443fe97d9e0351deaed6c9ea63b76ada39c85dc5/src/pymor/models/iosys.py#L1578)).

It does not make too much sense to have two attributes with the same value. Additionally, the state of a system is not necessarily the x variable (the state for second order systems is position and velocity, for time-delay systems it is x over a time interval; basically the initial condition).

Since `solution_space` is clearly defined and I'm not aware of systems theory terminology for x, I would be for removing the `state_space` attribute or modifying it in a way that fits with the established terminology (which might be useful when defining the initial condition and in a time-stepper). I'm not sure how to change the `InputStateOutputModel` if the `state_space` is removed, but I would still like `order` to mean 'the number of equations' and not 'the dimension of the actual state space'.

@pymor/pymor-devs Thoughts?

**Comment by sdrave** [comment]
In view of #531, it would be clearly be a good first step to unify these notions. I do not care too much about the name, so `state_space` would be fine for me as well. In general it should be the `VectorSpace` to which the arrays belong that come out of `solve` (or however it will be called in the future) and from which the output trajectory is computed.

BTW, in the RB world one usually says that RB is a state-space projection method. I guess renaming `solution_space` to `state_space` would be fine as well, even when it is somewhat mathematically incorrect for a `SecondOrderModel`.

**Comment by pmli** [comment]
@sdrave What do you think about separating the concepts for "`VectorSpace` for the output of `solve`" and "`VectorSpace` for the initial condition"? (I guess `solution_space` represents both in the `InstationaryModel`.) Or should each model have its own concept of `initial_data` and time-stepping?

**Comment by sdrave** [comment]
What are the use cases for a `VectorSpace` attribute for the initial data?

**Comment by pmli** [comment]
I guess for a generic time-stepper. But, maybe it makes more sense to have separate time-steppers for second-order and time-delay systems?

**Comment by sdrave** [comment]
ATM time steppers get called with the initial data, so they don't need a `VectorSpace` for anything. I am quite sure that we would need different time steppers for these kinds of systems.

The only situation I could imagine a `initial_data_space` being useful would be for an initial data argument to `solve`. However, I am not a fan of having such an argument for `solve` ...

**Comment by pmli** [comment]
I'm fine with the initial condition being a part of the model and not an argument to `solve`, with the idea that the initial condition is projected by the reductor and `with_` can be used to change the initial condition.

I guess then the question is do we want to rename `solution_space`. I like that it is related to `solve` in the name, so maybe replacing both at the same time makes sense. How about first we remove `state_space` and discuss later if and how to rename `solution_space` and `solve`, and what to call state to output and input to output mappings?

**Comment by sdrave** [comment]
Agreed.
