### ISSUE TITLE
The norm of NumpyVectorArrays can be complex. 

### ISSUE THREAD

**Issue by deneick** [pymor/pymor#667]
Example: 
`import numpy as np`
`from pymor.basic import NumpyMatrixOperator`
`product = NumpyMatrixOperator(np.array([[3,2],[2,3]]))`
`v = product.source.random(seed=0)+1j*product.source.random(seed=1)`
`print(v.norm(product)[0])`

Output:
 `(2.699627279099872-8.22500967611599e-17j)`

**Comment by pmli** [comment]
Can confirm the issue.

@deneick Are you willing to open a PR to fix this? It should be enough to add `.real` [here](https://github.com/pymor/pymor/blob/707c30aadc5e846ecdc8304ac2fa7602826a4b38/src/pymor/vectorarrays/interfaces.py#L395).

**Comment by renefritze** [comment]
It would also be great if that code was added as a test.

**Comment by pmli** [comment]
@renefritze I guess that's the topic of #461...

**Comment by deneick** [comment]
@pmli Yes, I will open a PR

**Comment by pmli** [comment]
Fixed in #668.
