### ISSUE TITLE
Add contribution guideline?

### ISSUE THREAD

**Issue by renemilk** [pymor/pymor#67]
See https://github.com/tiimgreen/github-cheat-sheet#contributing-guidelines and
https://github.com/tiimgreen/github-cheat-sheet#decreasing-contributor-friction

**Comment by ftalbrecht** [comment]
* We decided to flesh out what we think a _Core Developer_ should be (regarding rights and duties) and to document this (once #125 is done).
* We decided to work mostly with pull requests for new features, while minor changes can becommited directly.

**Comment by ftalbrecht** [comment]
We can draft this out once #126 is decided...

**Comment by sdrave** [comment]
@renemilk, @ftalbrecht, I have started writing CONTRIBUTING.md in the copyright branch. Please take a look and extend it if necessary.

**Comment by sdrave** [comment]
The changes are now in master: 3285677.
