### ISSUE TITLE
Performance issue with solve_lyap_lrcf

### ISSUE THREAD

**Issue by lbalicki** [pymor/pymor#677]
The `solve_lyap_lrcf` function from `pymor.algorithms.lradi` seems to perform a lot worse when Py-M.E.S.S. is available. Running the following lines works as expected when Py-M.E.S.S. is not installed:
```
import timeit
import scipy.sparse as sps
import numpy as np
from pymor.algorithms.lradi import solve_lyap_lrcf
from pymor.operators.numpy import NumpyMatrixOperator


def init_operators(n):
    diagonals = [-2 * (n + 1) ** 2 * np.ones((n,)),
                 ((n + 1) ** 2 + (n + 1) / 2) * np.ones((n - 1,)),
                 ((n + 1) ** 2 - (n + 1) / 2) * np.ones((n - 1,))]
    A = sps.diags(diagonals, [0, -1, 1], format='csc')
    B = np.ones((n,))
    Aop = NumpyMatrixOperator(A)
    return Aop, Aop.source.from_numpy(B)


Aop, Bop = init_operators(100000)
time = timeit.timeit(
        stmt="""solve_lyap_lrcf(Aop, None, Bop)""",
        globals=locals(), number=1
    )
print(time)
```
But if Py-M.E.S.S. is installed, the above lines need about twice as much time to compute the solution. If you add something like this to the very top of the code above
```
from pymor.core.config import config
config.HAVE_PYMESS = False
```
you get the expected run time again, just like in the case where Py-M.E.S.S. is not installed.

**Comment by sdrave** [comment]
So, any idea why pymess is slower, @lbalicki, @pmli?

**Comment by sdrave** [comment]
Oh sorry, I didn't read the issue properly. So basically the speed depends on whether or not pymess is imported?

**Comment by pmli** [comment]
Yes, something like that.

**Comment by sdrave** [comment]
I cannot reproduce the issue. Could you check the `ldd` output of the pymess C extension? Maybe it causes some different library versions to be loaded on your machines? See [here](https://github.com/pymor/pymor/issues/412#issuecomment-410763812).
Maybe the pymess import could also mess with the OpenMP settings?

**Comment by lbalicki** [comment]
I did some profiling and found out that the slowdown is happening (mainly) because `scipy.sparse.linalg.splu` needs more time to solve the linear systems. When I use the pymess bindings, exactly the same method is used for solving the linear systems, but I get the (expected) normal speed, although pymess is imported. So I assume that different library versions can't really be the issue here. But I still don't know what else could be the problem.

**Comment by pmli** [comment]
I tried it also and can confirm that `splu` is slower, but I also got that `numpy.dot` is much more slower. Below are the results when running `python -m cProfile -s tottime example.py` without and with pymess.
```
5.543027689000155
         287381 function calls (281082 primitive calls) in 6.113 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
       67    4.133    0.062    4.133    0.062 {built-in method scipy.sparse.linalg.dsolve._superlu.gstrf}
       67    0.269    0.004    0.269    0.004 {built-in method scipy.sparse._sparsetools.csc_plus_csc}
    67/56    0.259    0.004    0.271    0.005 {built-in method _imp.exec_dynamic}
       67    0.215    0.003    0.215    0.003 {built-in method scipy.sparse._sparsetools.csr_sort_indices}
       67    0.199    0.003    0.199    0.003 {method 'solve' of 'SuperLU' objects}
       67    0.150    0.002    5.311    0.079 constructions.py:154(apply_inverse)
       68    0.061    0.001    0.133    0.002 dia.py:322(tocsc)
      326    0.044    0.000    0.044    0.000 {built-in method marshal.loads}
       68    0.040    0.001    0.040    0.001 {built-in method scipy.sparse._sparsetools.csc_matvec}
       67    0.037    0.001    0.037    0.001 {built-in method scipy.sparse._sparsetools.csr_sum_duplicates}
      397    0.036    0.000    0.036    0.000 {method 'copy' of 'numpy.ndarray' objects}
      678    0.030    0.000    0.030    0.000 {method 'reduce' of 'numpy.ufunc' objects}
       68    0.028    0.000    0.028    0.000 {method 'cumsum' of 'numpy.ndarray' objects}
    67/65    0.026    0.000    0.030    0.000 {built-in method _imp.create_dynamic}
       67    0.021    0.000    0.022    0.000 numpy.py:102(append)
      273    0.015    0.000    0.015    0.000 {method 'dot' of 'numpy.ndarray' objects}
...
```
```
17.926605561000542
         289502 function calls (283119 primitive calls) in 18.507 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
       67    7.244    0.108    7.244    0.108 {built-in method scipy.sparse.linalg.dsolve._superlu.gstrf}
      273    6.485    0.024    6.485    0.024 {method 'dot' of 'numpy.ndarray' objects}
       67    2.040    0.030    2.040    0.030 {built-in method scipy.sparse._sparsetools.csc_plus_csc}
       67    0.647    0.010    0.647    0.010 {built-in method scipy.sparse._sparsetools.csr_sort_indices}
    67/56    0.261    0.004    0.270    0.005 {built-in method _imp.exec_dynamic}
       67    0.189    0.003    0.189    0.003 {built-in method scipy.sparse._sparsetools.csr_sum_duplicates}
       67    0.156    0.002    0.156    0.002 {method 'solve' of 'SuperLU' objects}
       67    0.113    0.002   11.255    0.168 constructions.py:154(apply_inverse)
       68    0.110    0.002    0.174    0.003 dia.py:322(tocsc)
  459/187    0.088    0.000    9.364    0.050 defaults.py:251(wrapper)
    18457    0.051    0.000    0.103    0.000 {built-in method builtins.isinstance}
...
```

**Comment by sdrave** [comment]
@lbalicki, @pmli, can you confirm that this has nothing to do with the number of used processor cores? (E.g. importing some C extension could change the default number of threads used by OpenMP.)

**Comment by pmli** [comment]
Running both with `OMP_NUM_THREADS=1` makes both versions equally fast and even faster than the version without pymess...

**Comment by lbalicki** [comment]
I got the same results as @pmli. So I guess the OpenMP settings are at least a part of the issue. Is there any way I can check in which way importing a certain C extension affects the OpenMP settings?

**Comment by sdrave** [comment]
The easiest way I could find:

`openmp_config.c`:
```c
#include <omp.h>

int get() {
        return omp_get_max_threads();
}

void set(int num) {
        return omp_set_num_threads(num);
}
```

```bash
gcc openmp_config.c  -o openmp_config.so --shared  -fopenmp
```

then

```python
import ctypes
openmp_config = ctypes.CDLL('./openmp_config.so')
print(openmp_config.get())
openmp_config.set(3)
print(openmp_config.get())
```

**Comment by lbalicki** [comment]
I ran the code above and replaced `omp_get_max_threads()` with all of the other OpenMP functions that return the environment variables as well. What I got as a result is that before the pymess import `omp_get_num_procs()` returns 4 on my machine and after the import it changes to 1. So I would assume that this is the issue, but I am not sure how it can be fixed.

**Comment by drittelhacker** [comment]
After talking to the MESS core deveolpers, this may be related to BLAS issues. Can you double check that all imports link against the same BLAS!? Should be OpenBLAS in the case of pymess.

**Comment by sdrave** [comment]
How shall we proceed with this issue?

**Comment by pmli** [comment]
Installing from source seems to fix the issue for me, by doing it either for NumPy/SciPy (`pip install --no-binary :all: numpy scipy`) or pymess (https://gitlab.mpi-magdeburg.mpg.de/mess/cmess-releases). Installing both NumPy/SciPy and pymess from source doesn't seem to be necessary...

How about adding a recommendation in `README.md` to install pymess from source? C-M.E.S.S. developers also recommend installing pymess from source to use already installed BLAS.

**Comment by lbalicki** [comment]
What @pmli suggested also works for me. I also think that adding a recommendation for the pymess installation to the `README.md` is a good idea.

**Comment by renefritze** [comment]
I think adding a note in README here is fine since upstream also suggests source install.

What about the num threads changing though? That could be a potential issue source in other circumstances.

**Comment by lbalicki** [comment]
Installing from source also fixes the issue with the changing num threads for me. So, I think there should not be any further problems related to that.
