### ISSUE TITLE
Replace manual gmsh file parsing

### ISSUE THREAD

**Issue by renefritze** [pymor/pymor#680]
Our current implementation can only handle gmsh in version 2.2. My machine now has 4.1 -> tests fail. I'm introducing xfail mechanics for mismatched installs like mine in #675, but we need something better. 

It should be possible to parse gmsh files with [meshio](https://github.com/nschloe/meshio) and 
use their intermediate representation to construct an UnstructedTriangleGrid. 
This would a) solve the gmsh problem and b) allows to use a wide variety of input formats too.

**Comment by sdrave** [comment]
There is also `pygmsh`.

**Comment by renefritze** [comment]
> There is also `pygmsh`.

[Yup](https://github.com/pymor/pymor/blob/4b84e02b7a43d10d3f60d018521749f9ddb865fe/src/pymortests/demos.py#L176), [indeed](https://github.com/pymor/pymor/blob/master/dependencies.py#L26)

**Comment by sdrave** [comment]
Can meshio handle boundary types?

pygmsh could be used not only for reading the mesh but also generating it (see `domaindiscretizers/gmsh).

**Comment by renefritze** [comment]
> Can meshio handle boundary types?

Yes. This is mapped in tags.

> 
> pygmsh could be used not only for reading the mesh but also generating it (see `domaindiscretizers/gmsh).

That's actually a separate issue, but sure.

**Comment by sdrave** [comment]
Ok, then I agree that `meshio` is probably preferable. Some work might be involved ..
