### ISSUE TITLE
Model outputs

### ISSUE THREAD

**Issue by sdrave** [pymor/pymor#698]
@pmli, @ftalbrecht, to solve a simpler sub-problem of #531, I would like to first try to unify what the output of a `Model` should be.

Currently, `StationaryModel` and `InstationaryModel` define `outputs` dicts of functional `Operators` which map from `m.solution_space` to numbers. In `models.iosys` there is no common notion of an output `Operator`. For `LTIModel` it would be `m.C` for `SecondOrderModel` we have `m.Cp` and `m.Cv`.

Questions:
- Do we actually want a unified definition of what the output of a `Model` is? - I think that would be a good idea.)
- In case there are multiple outputs: Do we want to have a dict of outputs or should the output always be a single `Operator` - I think having a single (vector-valued) output `Operator` might have conceptual benefits, but one would always have to remember, which meaning is assigned to which output component. (This could be handled by an additional dict, however.)
- In case of time-dependent `Models`. Should the output be always a mapping from `solution_space` (or however it might be called) to numbers, or do we also want to consider mappings from solution-time-space to numbers (E.g. a functional of the state at the final simulation time)? - The latter should definitely be handled by pyMOR as well, but this could also be a functional of the output time-series.

**Comment by pmli** [comment]
> For `LTIModel` it would be `m.C` for `SecondOrderModel` we have `m.Cp` and `m.Cv`.

There is also `m.D`.

> Questions:
> 
> * Do we actually want a unified definition of what the output of a `Model` is? - I think that would be a good idea.)

I guess it would be good to have something like `solve` which would return the output.

> * In case there are multiple outputs: Do we want to have a dict of outputs or should the output always be a single `Operator` - I think having a single (vector-valued) output `Operator` might have conceptual benefits, but one would always have to remember, which meaning is assigned to which output component. (This could be handled by an additional dict, however.)

Working with operators is convenient, so I would be against dicts. Also, models could have many inputs (`C` could even be the identity operator).

Naming input and output components could be interesting for [connecting systems](https://www.mathworks.com/help/control/ref/connect.html), but I haven't thought about it much so far.

> * In case of time-dependent `Models`. Should the output be always a mapping from `solution_space` (or however it might be called) to numbers, or do we also want to consider mappings from solution-time-space to numbers (E.g. a functional of the state at the final simulation time)? - The latter should definitely be handled by pyMOR as well, but this could also be a functional of the output time-series.

As mentioned, the output could also depend on the input directly (operator `D`).

I saw RB people using a functional of the state at the final simulation time as the output, so pyMOR should probably handle this. On the other hand, I've never seen anything like that in the systems theory community.

**Comment by pmli** [comment]
> I am also thinking about the MOR algorithms. If I want to evaluate the output in the ROM, I will have to project something responible for computing the output.

The projection-based reductor can do the projection. The ROM would then have its method for computing the output. Right?

> Also, for RB methods, for getting an efficient a posterior error indicator for the output, I need to solve a dual problem with the output as RHS. So I need to know what functional computes the output.

How about adding a `solve_dual` method? Or `.H` for models?

> > Working with operators is convenient, so I would be against dicts. Also, models could have many inputs (C could even be the identity operator).
> 
> Ok. This sounds like we should consider allowing the output to lie in an arbitrary `VectorSpace` (FEniCS, etc.). Are there any downsides to this?

Where is this not allowed?

> > As mentioned, the output could also depend on the input directly (operator D).
> 
> This is really inconvenient. Do you have cases where the such a decomposition in `C` and `D` is not possible? (For nonlinear problems?)

I don't think I've seen such an example. But, I mostly work with linear systems...

> > I saw RB people using a functional of the state at the final simulation time as the output, so pyMOR should probably handle this. On the other hand, I've never seen anything like that in the systems theory community.
> 
> I would expect this to be a common error functional when you are doing optimal control?

Right. I just haven't seen a system-theoretic method which would minimize this type of error (time-limited methods would be the closest).

**Comment by sdrave** [comment]
I have thought about this some more. Maybe having output-associated `Operators` in `ModelInterface` is not the right approach? In particular, right now `ModelInterface` does not require any `Operator` to be included in the object, so it feels somewhat strange to require `Operators` for the output.

This leaves us with adding an `output_space` attribute and a method for computing the output. I think there are two possible situations: We have a parameter (and an input) and want to compute the output trajectory (possibly in addition to the `solution_space` trajectory), or we already have a `solution_space` trajectory coming from somewhere (and an input) and want to compute an output trajectory. What should be included in the interface?

Maybe

```python
def solve(self, mu=None, return_solution=True, return_output=False):
```

and

```python
def output(self, U, mu=None):
```

**Comment by pmli** [comment]
The `TransferFunction` model has no solution space, so it should be possible to only ask for output given some parameter and/or input.

**Comment by sdrave** [comment]
This case would be covered by the first method.

I think we could also consider to start with a completely new terminology and deprecate `solve`. E.g., we could have methods like `input_to_output`, `input_to_state` (or whatever the right word is instead of `state`), `state_to_output`.

**Comment by pmli** [comment]
Matlab's [Control System Toolbox](https://www.mathworks.com/help/control/ref/lsim.html) and [scipy.signal](https://github.com/scipy/scipy/blob/3478f52a4c72dac32ad76a0c6e201b2255497352/scipy/signal/ltisys.py#L1870) have `lsim`, which stands for "linear system simulation" (I guess), for LTI systems which can return both the state and output. [python-control](https://github.com/python-control/python-control/blob/e2346cd6e528880a5ae712016d3500f949b11164/control/timeresp.py#L187) has `forced_response` which behaves similarly ("response" comes from "time response"; there is also "frequency response").

I would be fine with having a single method which takes parameters/inputs and returns state (or whatever we call it in general) and output. For `TransferFunction` it would make sense to only return the output, but the state could also be returned as `None`. I'm not sure if specific methods for `input_to_state` and `state_to_output` are necessary.

**Comment by sdrave** [comment]
It's a good point that sometimes we may want to compute the state and the output. This should be possible with a single method call. So maybe we really should go with an extension of `solve` and an additional method which computes the output from the state?

**Comment by pmli** [comment]
Seems like a good approach.

**Comment by sdrave** [comment]
Ok, let's do that. Shall we use the exact same signatures as proposed above or should there be some changes?

**Comment by pmli** [comment]
For `StationaryModel` and `InstationaryModel`, I guess this is fine. For input-output systems, it would be nice to also have the input `u(t)` as a separate argument.

**Comment by sdrave** [comment]
Sure, the input is still missing and needs discussion (whether it should be somehow contained in the parameter or if it becomes a separate argument to `solve`).

So the consequences would be:

- Add `output_space` as an attribute to `ModelInterface`.
- Extend `solve` as given above.
- Add an `output` method to `ModelInterface`.
- In `StationaryModel` / `InstationaryModel` the `outputs` dict becomes an `output` `Operator`.

**Comment by sdrave** [comment]
@pymor/pymor-devs, do we really need a separate `output` method in the interface? While I surely sometimes want to compute the output for some given state vector, I probably do not want to do this in some generic code that knows nothing about the given model. Also, as discussed in #728, there are cases, where it might not be completely obvious how to define the `output` method.

So I am currently thinking about sticking with the approach above, but to leave out the `output` method from `ModelInterface` (which would also allow renaming `output_operator` to `output` in `(In)StationaryModel`).

**Comment by pmli** [comment]
Right, as I mentioned a bit late in https://github.com/pymor/pymor/pull/728#issuecomment-508790687, I don't know where would the `output` method be used. But, I rarely do any time-domain simulations.

**Comment by sdrave** [comment]
Well, I think that `output` would be mostly relevant for interactive use when experiment with the model. 
But in these cases it should be fine to evaluate the output manually.

I am still a bit unsure if we really want a single `solve` method with optional arguments for choosing the returned value. Feels kind of clumsy to write `solve(mu, return_solution=False, return_output=True)`. Any other ideas, @pymor/pymor-devs?

**Comment by pmli** [comment]
I feel like `solve` should always return a solution and optionally an output. I'm unsure about having a method which only returns the output (AFAICT, it wouldn't make things faster or use less memory).

**Comment by sdrave** [comment]
@pmli, only returning the output can reduce memory usage substantially since you do not need to keep the entire state space trajectory in memory.

Also, if you actually want to use a model for something, you probably will only be interested in the parameter/intput to output mapping, so I think something shorter than `solve(mu, return_solution=False, return_output=True)` would be nice. So maybe

```python
def foo(mu=None, return_output=False):
```

which always returns the state and optionally the output and

```python
def bar(mu=None):
```

which only returns the output? I would also like three separate methods. However, I am still unsure what better names than `foo` and `bar` would be. If we were to speak of state space instead of solution space, I could imagine `solve_for_state`, `solve_for_output`, `solve_for_state_output`.

**Comment by pmli** [comment]
> @pmli, only returning the output can reduce memory usage substantially since you do not need to keep the entire state space trajectory in memory.

Right, of course... Then it makes sense to have a separate method which only returns the output.

> I would also like three separate methods. However, I am still unsure what better names than `foo` and `bar` would be. If we were to speak of state space instead of solution space, I could imagine `solve_for_state`, `solve_for_output`, `solve_for_state_output`.

What do you think about using `simulate` or `sim`, e.g., `sim_sol`, `sim_out`, `sim_sol_out`?

**Comment by ftalbrecht** [comment]
`simulate` does not really fit the stationary PDE case well and we currently have `solve`, so I would support something like `solve_for_output`, `solve_for_state`. We should also think about `estimate_state` and `estimate_output`...

**Comment by sdrave** [comment]
@pmli, @ftalbrecht, to cite Wikipedia:

> A simulation is an approximate imitation of the operation of a process or system; the act of simulating first requires a model is developed. This model is a well-defined description of the simulated subject, and represents its key characteristics, such as its behaviour, functions and abstract or physical properties. The model represents the system itself, whereas the simulation represents its operation over time. 

In other words, you do not simulate the model but the process or system it imitates. So I am not sure if `simulate` is actually a good name for a method of a `Model`, in particular as `Models` in pyMOR are completely detached from any possible system they might imitate.

What do you think of `compute`?  Overall I see the following options:

1. `solve` with parameters which select the returned quantities
2. `solve_for_state`, `solve_for_output`, `solve_for_state_output`
3. `simulate_state`, `simulate_output`, `simulate_state_output`
4. `simulate_solution`, `simulate_output`, `simulate_solution_output`
5. `compute_state`, `compute_output`, `compute_state_output`
6. `compute_solution`, `compute_output`, `compute_solution_output`

Preferences?

@pmli, do you still think that it is better to speak of `solution_space` instead of `state_space`? I understand that `state` may have some special meaning for some physical models, but my impression is that people in the MOR community very often use `state` when they mean `solution`.

**Comment by pmli** [comment]
In systems and control theory, "state" has a specific meaning. To cite Sontag's [Mathematical Control Theory book](https://doi.org/10.1007/978-1-4612-0577-7), chapter 2, page 27:
> At each instant, the state `x` summarizes all of the information needed in order to know the future evolution of the system.

and Polderman, Willems, [Introduction to Mathematical Systems Theory: A Behavioral Approach](https://doi.org/10.1007/978-1-4757-2953-5), page 119, remark 4.3.4:
> The state property expresses that `l` splits the past and the future of `w`. All the information needed to decide whether or not two trajectories `w1` and `w2` can be concatenated within `B` at time `t0` is contained in the values of the corresponding states at time `t0`.

I like to think of "state" as the initial condition in an initial value problem. For second-order systems, this would be initial position and velocity. For time-delay systems, this would be `x(t)` over some time interval.

In both books, I only saw "solution" used when referring to solving a system of ODEs, i.e. nothing specific to systems and control theory.

As far as I'm aware, there is no standard terminology in time-delay systems literature for `x(t)` at specific time, e.g. [Krylov-Based Model Order Reduction of Time-delay Systems](https://doi.org/10.1137/100797436) uses "state variable" and [Model reduction of time-delay systems using position balancing and delay Lyapunov equations](https://doi.org/10.1007/s00498-012-0096-9) uses "position".

For these reasons, I would prefer to use `solution` when referring to the trajectory `x(t)` (or `u(t, mu)`) and `state` for what can be used as an initial condition.

Now, I'm not sure if we decided what would time-domain simulation of a `SecondOrderModel` return. I guess position (without velocity) is enough for POD?

**Comment by sdrave** [comment]
I agree with this definition of state.

I also agree that position without velocity will usually be enough for POD. I am saying usually, as I assume that this depends on the chosen time stepping method and that there might be fancy methods out there where the velocity is not in the span of the positions.

Overall the consequence seems to be that we stick with `solution_space`. Thus, the options, as I see it, would be:

1. `solve` with parameters which select the returned quantities
2. `solve`, `solve_for_output` (the later with an `return_solution=False` parameter)
3. `simulate_solution`, `simulate_output`, `simulate_solution_output`
4. `compute_solution`, `compute_output`, `compute_solution_output`

So, what shall it be @pymor/pymor-devs? Note that these are important interface methods which we should not rename anytime soon.

**Comment by renefritze** [comment]
I like `compute_*` the best.

**Comment by ftalbrecht** [comment]
2 or 4

**Comment by pmli** [comment]
I also like 4 the most.

**Comment by gramian** [comment]
Not a dev, but I would go with 1.

**Comment by pmli** [comment]
Maybe writing it explicitly can help

1. `solve`, `solve(return_solution=False, return_output=True)`, `solve(return_output=True)`
2. `solve`, `solve_for_output`, `solve_for_output(return_solution=True)`
3. `simulate_solution`, `simulate_output`, `simulate_solution_output`
4. `compute_solution`, `compute_output`, `compute_solution_output`

Personally, I find option 1 too long (unless we can come up with better names), since I expect returning output without a solution would be useful for input-output systems.
I was confused a bit with option 2, I would have expected:

5. `solve`, `solve_for_output`, `solve(return_output=True)`

since returning only the output is a more special method (it doesn't have to store the whole solution of an instationary model).
I still find the name `solve_for_output` a bit weird. Maybe `solve_output` is enough? Or `compute_output`?

**Comment by ftalbrecht** [comment]
How about

* `solve` and `compute_output(return_solution=False)`

**Comment by pmli** [comment]
I like the idea of merging `compute_solution_output` with `solve`/`compute_solution` or `solve_for_output`/`compute_output`, but I'm not really sure what is the best way. I guess I'm fine with both

6. `solve` and `compute_output(return_solution=False)`

and

7. `solve(return_output=False)` and `compute_output`.

**Comment by sdrave** [comment]
There certainly would be a benefit in keeping `solve` and just adding a method/parameters. I agree with @pmli that `solve_for_output` is a bit weird.

How about:

8. `solve(return_output=False)` and `output`

**Comment by ftalbrecht** [comment]
I like `8`.

**Comment by pmli** [comment]
I also like 8. I guess you would then use `output_operator` for the solution-to-output operator in `models.basic`?

**Comment by sdrave** [comment]
Yeah, `output_operator` or maybe `output_functional` (even though the thing may map to multiple numbers). Seems like 8 is a good compromise. I will work on a new PR.

**Comment by ftalbrecht** [comment]
On 25.07.19 12:02, Stephan Rave wrote:
> Yeah, `output_operator` or maybe `output_functional` (even though the thing may map to multiple numbers). Seems like 8 is a good compromise. I will work on a new PR.
> 

Given the current implementation of most discretizers, when specifying
an 'output' functional in a problem, the resulting discretized model
will have an 'output_functional' operator in the operators dict. So
'output_functional' seems like a good name ...
