### ISSUE TITLE
Discontinue wheels.pymor.org?

### ISSUE THREAD

**Issue by renefritze** [pymor/pymor#712]
I just realized that I did not really communicate that I stopped uploading wheels there since the move to gitlab-ci, where the wheels are stored internally with a limited lifetime. 
I don't really see a use for the page any more, but it wouldn't be hard to re-add uploading from gitlab-ci. 
Any @pymor/pymor-devs who is pro keeping the page?

**Comment by sdrave** [comment]
Not sure if we really need to provide wheels for anything except releases. So I guess it is ok to remove the page.

**Comment by renefritze** [comment]
Once DNS refresh hits clients will see wheels.pymor.org redirecting to pymor.org
