### ISSUE TITLE
POD for Energy Model 

### ISSUE THREAD

**Issue by quyenanh98** [pymor/pymor#713]
I want to apply POD for my Energy model in python. The model is originally from another simulation software called EnergyPlus. I have used a python package called PyFMI to convert it to a .fmu file for model exchange so that I could run the simulation in python. The python code is really simple, I just have to import the libraries, locate the .fmu file, set the simulation time and some parameters and it will give the results exactly as running with the original software.

I guess because there's no explicit matrix in my python code so it is reasonable to apply POD and do the snapshots. However, I really don't know how to apply the POD algorithm to my model. 

Please give me some advice as I am still new to this topic.

**Comment by pmli** [comment]
Hi @quyenanh98. I'm not familiar with PyFMI, so what I can say is that in case you can only access the snapshots and not the model, the approach would be to use a data-driven method. Unfortunately, so far, there are no time domain data-driven methods implemented in pyMOR (see #390).

If you can somehow access the model, then POD is a valid approach. The details depend on the type of model (parametric or non-parametric, linear or non-linear).

**Comment by sdrave** [comment]
Closing since inactive and mainly a support question.
