### ISSUE TITLE
Guide for writing new solver bindings

### ISSUE THREAD

**Issue by renefritze** [pymor/pymor#719]
Judging from a couple recent maillinglist interactions I think it's clear we should provide a better document on what's necessary to write new bindings, what level of integration is necessary for what methods...

Lets collect ideas here first.

**Comment by sdrave** [comment]
I would suggest to make a tutorial style document out of the minimal_cpp_demo and add it to the sphinx docs.

**Comment by renefritze** [comment]
Tutorial entered 2020.1
