### ISSUE TITLE
Known Jupyter Visualization issues

### ISSUE THREAD

**Issue by renefritze** [pymor/pymor#801]
Current known issues I plan to address after my vacation:

 - dynamic resizing of plot widgets with the parent
 - general layouting improvements with multiple plots/colorbars
 - hopefully identify what's happening with disappearing plots like @TiKeil has experienced.

Please leave a comment if you find anything unexpected happening after #759 is merged.

**Comment by ftalbrecht** [comment]
On current master, plotting multiple solutions as timeline does not work anymore (only shows the first). I.e., after

```python
from pymor.analyticalproblems.thermalblock import thermal_block_problem
from pymor.discretizers.builtin import discretize_stationary_cg

problem = thermal_block_problem(num_blocks=(2, 1))
fom, _ = discretize_stationary_cg(problem)

U = fom.solution_space.empty()
for mu in (0.1, 1, 10):
    mu = fom.parse_parameter({'diffusion': (mu, 1.)})
    fom.visualize(fom.solve(mu=mu))
    U.append(fom.solve(mu=mu))
fom.visualize(U)
```

I get three different plots and a widget indicating three timesteps (showing the first), but moving the slider does not change a thing ....

**Comment by TiKeil** [comment]
There is no obvious way of increasing the font size of the plots (since I need them for a paper and for slides) 
I changed the number in https://github.com/pymor/pymor/blob/7b8682458543c3a6b4dfacaa7076a8f85a2e77cd/src/pymor/discretizers/builtin/gui/jupyter/threejs.py#L213
but that did not work for me. Perhaps there is something that I need to reset after changing the font size there? 

My dream would be to give the font size to the visualize function but that probably depends on the backend?

**Comment by TiKeil** [comment]
When I increased the number of DoFs in a structured mesh to approx 500.000 it happened to me that the plot did not pop up at all. Only the colorbar existed. Is the resolution too high or what is happening there?

**Comment by renefritze** [comment]
> On current master, plotting multiple solutions as timeline does not work anymore (only shows the first). I.e., after

I just checked on master with mybinder and this works atm.

**Comment by renefritze** [comment]
Currently one get a static representation via `PYMOR_NBCONVERT=1 jupyter nbconvert --execute  test_visualization.ipynb`. Problem is play controls do not update the vis in the loaded html then.

**Comment by renefritze** [comment]
IIRC @TiKeil had some issue with the readability of colorbars. Using https://ipyscales.readthedocs.io/en/latest/examples/colormaps.html instead of my own rendering code might be a good option there.

**Comment by TiKeil** [comment]
Yes, you are totally right. I think the main problem was that it sometimes wrote 5.00000 e-2 instead of just taking 0.05 or 5e-2 which would be way less space. 

The colorbars in the link look very good but I am not sure how this would look in the described case above.

**Comment by ftalbrecht** [comment]
Not sure if this is the right place, but on current master with supposedly all desp installed, when I try to `m.visualize(U)` in a jupyter notebook, nothing happens, but the log of the notebook server shows
```
[W 16:15:56.485 NotebookApp] 404 GET /static/jupyter-threejs.js (172.17.0.1) 5.14ms referer=http://127.0.0.1:18157/notebooks/thermalblock_dune.md
```

**Comment by renefritze** [comment]
The nothing happening is not causally connected with that message AFAICT. The js loader actually only _tries_ to load that locally and falls back to the NPM CDN afterwards. So the thing gets loaded in the end. 

If you do `jupyter nbextension list`, is pythreejs there?

**Comment by ftalbrecht** [comment]
> If you do `jupyter nbextension list`, is pythreejs there?

Yes. Other ideas how to debug this?

**Comment by renefritze** [comment]
Unless you want to dig into the Javascript debugger I'd say your best option is to leave that to me. 
Otherwise, if you open your JS Console, you will see that pythree.js cannot load a model/child view. If you find out why, we're done :wink:

**Comment by renefritze** [comment]
@ftalbrecht please try to run your jupyter server with `PYMOR_NBCONVERT=1` in process environment and see if that fixes the problem

**Comment by ftalbrecht** [comment]
> @ftalbrecht please try to run your jupyter server with `PYMOR_NBCONVERT=1` in process environment and see if that fixes the problem

I did not need to try that, since the issue was resolved otherwise: I've had an old venv (resulting from an old `pip freeze`ed `requirements.txt` and simply changed the pyMOR branch (possibly without `pip install -e`ing afterwards, don't recall), leading to the above error.
Deleting the venv and starting from scratch using `pip install -e . && pip install -r requirements-optional.txt` lead to the visualization working again. If you are interested I can provide the diff of the old an new `pip freeze`...

**Comment by renefritze** [comment]
That would be great, thanks!

**Comment by ftalbrecht** [comment]
```
commit cb1d6179a956dd72a55c3c778d8e071560405740
Author: Felix Schindler <felix.schindler@wwu.de>
Date:   Thu Jun 25 11:19:10 2020 +0200

update requirements

diff --git a/requirements.txt b/requirements.txt
index 27eba95..17b3c43 100644
--- a/requirements.txt
+++ b/requirements.txt
@@ -1,101 +1,151 @@
alabaster==0.7.12
-atomicwrites==1.3.0
+apipkg==1.5
+appdirs==1.4.4
attrs==19.3.0
-Babel==2.7.0
-backcall==0.1.0
-bleach==3.1.0
-certifi==2019.9.11
+Babel==2.8.0
+backcall==0.2.0
+bleach==3.1.5
+certifi==2020.6.20
+cffi==1.14.0
chardet==3.0.4
-coverage==4.5.4
+check-manifest==0.42
+cmarkgfm==0.4.2
+codecov==2.1.7
+colorama==0.4.3
+coverage==5.1
+cryptography==2.9.2
cycler==0.10.0
-Cython==0.29.14
-decorator==4.4.1
+Cython==0.29.20
+decorator==4.4.2
defusedxml==0.6.0
diskcache==4.1.0
-docker==4.1.0
+distlib==0.3.0
docopt-ng==0.7.2
-docutils==0.15.2
+docutils==0.16
entrypoints==0.3
-envparse==0.2.0
-idna==2.8
-imagesize==1.1.0
-importlib-metadata==0.23
-ipdb==0.12.3
-ipykernel==5.1.3
-ipyparallel==6.2.4
-ipython==7.9.0
+execnet==1.7.1
+filelock==3.0.12
+future==0.18.2
+idna==2.9
+imagesize==1.2.0
+importlib-metadata==1.6.1
+ipydatawidgets==4.0.1
+ipykernel==5.3.0
+ipyparallel==6.3.0
+ipython==7.15.0
ipython-genutils==0.2.0
ipywidgets==7.5.1
-jedi==0.15.1
-Jinja2==2.10.3
-jsonschema==3.1.1
-jupyter-client==5.3.4
-jupyter-core==4.6.1
-jupytext==1.2.4
-kiwisolver==1.1.0
+jedi==0.17.1
+jeepney==0.4.3
+Jinja2==2.11.2
+jsonschema==3.2.0
+jupyter==1.0.0
+jupyter-client==6.1.3
+jupyter-console==6.1.0
+jupyter-contrib-core==0.3.3
+jupyter-contrib-nbextensions==0.5.1
+jupyter-core==4.6.3
+jupyter-highlight-selected-word==0.2.0
+jupyter-latex-envs==1.4.6
+jupyter-nbextensions-configurator==0.4.1
+jupytext==1.5.0
+keyring==21.2.1
+kiwisolver==1.2.0
+lxml==4.5.1
MarkupSafe==1.1.1
-matplotlib==3.1.1
-meshio==3.2.8
+matplotlib==3.2.2
+meshio==3.3.1
mistune==0.8.4
-more-itertools==7.2.0
+more-itertools==8.4.0
mpi4py==3.0.3
mpmath==1.1.0
nbconvert==5.6.1
-nbformat==4.4.0
+nbformat==5.0.7
+nbresuse==0.3.6
notebook==6.0.3
-numpy==1.17.3
-packaging==19.2
+numpy==1.19.0
+packaging==20.4
pandocfilters==1.4.2
-parso==0.5.1
-pexpect==4.7.0
+parso==0.7.0
+pep517==0.8.2
+pexpect==4.8.0
pickleshare==0.7.5
-Pillow==6.2.1
+Pillow==7.1.2
+pkginfo==1.5.0.1
pkg-resources==0.0.0
-pluggy==0.13.0
-prometheus-client==0.7.1
-prompt-toolkit==2.0.10
+pluggy==0.13.1
+prometheus-client==0.8.0
+prompt-toolkit==3.0.5
+properties==0.6.1
+psutil==5.7.0
ptyprocess==0.6.0
-py==1.8.0
+py==1.8.2
pyamg==4.0.0
-pybind11==2.4.3
+pybind11==2.5.0
+pycparser==2.20
pyevtk==1.1.1
-Pygments==2.4.2
+Pygments==2.6.1
pygmsh==6.0.2
-PyOpenGL==3.1.0
-pyparsing==2.4.4
-PyQt5==5.13.2
-PyQt5-sip==12.7.0
-pyrsistent==0.15.5
-pytest==5.2.2
-pytest-cov==2.8.1
+pymor-nb2plots==0.7
+PyOpenGL==3.1.5
+pyparsing==2.4.7
+pypi-oldest-requirements==2020.4.1
+pyrsistent==0.16.0
+PySide2==5.15.0
+pytest==5.4.3
+pytest-cov==2.10.0
+pytest-forked==1.1.3
+pytest-memprof==0.2.0
+pytest-parallel==0.1.0
pytest-runner==5.2
+pytest-timeout==1.4.1
+pytest-xdist==1.32.0
python-dateutil==2.8.1
-pytz==2019.3
-PyYAML==5.1.2
-pyzmq==18.1.0
-Qt.py==1.2.1
-requests==2.22.0
-scipy==1.3.1
+pythreejs==2.2.0
+pytz==2020.1
+PyYAML==5.3.1
+pyzmq==19.0.1
+qtconsole==4.7.5
+Qt.py==1.2.5
+QtPy==1.9.0
+readme-renderer==26.0
+requests==2.24.0
+requests-toolbelt==0.9.1
+requirements-parser==0.2.0
+rfc3986==1.4.0
+rstcheck==3.3.1
+scipy==1.5.0
+SecretStorage==3.1.2
Send2Trash==1.5.0
-sh==1.12.14
-six==1.13.0
+shiboken2==5.15.0
+six==1.15.0
+slycot==0.3.3
snowballstemmer==2.0.0
-Sphinx==2.2.1
-sphinxcontrib-applehelp==1.0.1
-sphinxcontrib-devhelp==1.0.1
-sphinxcontrib-htmlhelp==1.0.2
+Sphinx==3.1.1
+sphinxcontrib-applehelp==1.0.2
+sphinxcontrib-devhelp==1.0.2
+sphinxcontrib-htmlhelp==1.0.3
sphinxcontrib-jsmath==1.0.1
-sphinxcontrib-qthelp==1.0.2
-sphinxcontrib-serializinghtml==1.1.3
-sympy==1.4
-terminado==0.8.2
+sphinxcontrib-qthelp==1.0.3
+sphinxcontrib-serializinghtml==1.1.4
+sphinx-qt-documentation==0.2
+sphinxtesters==0.2.3
+sympy==1.6
+tblib==1.6.0
+terminado==0.8.3
+testipynb==0.0.2
testpath==0.4.4
-tornado==6.0.3
+texext==0.6.6
+toml==0.10.1
+tornado==6.0.4
+tqdm==4.46.1
traitlets==4.3.3
-urllib3==1.25.6
-wcwidth==0.1.7
+traittypes==0.2.1
+twine==3.2.0
+urllib3==1.25.9
+virtualenv==20.0.25
+wcwidth==0.2.5
webencodings==0.5.1
-websocket-client==0.56.0
widgetsnbextension==3.5.1
wurlitzer==2.0.0
-zipp==0.6.0
+zipp==3.1.0
```

**Comment by renefritze** [comment]
[Closing](https://github.com/pymor/pymor/issues/647#issuecomment-900903370)
