### ISSUE TITLE
Switch default jupyter visualization backend in 2019.2 release branch

### ISSUE THREAD

**Issue by sdrave** [pymor/pymor#816]
We have decided to keep the matplotlib-based backend as a default for 2019.2. The default in master is the new pythreejs-based backend.

**Comment by renefritze** [comment]
Will cherry-pick https://github.com/pymor/pymor/commit/2d232fb3f78ec6686222115898991dc941ffe96d to the release branch once it's up.

**Comment by renefritze** [comment]
Done: https://github.com/pymor/pymor/commits/2019.2.x
