### ISSUE TITLE
[algorithms.greedy] drop default for extension_algorithm

### ISSUE THREAD

**Issue by ftalbrecht** [pymor/pymor#82]
I ran into a situation where I was stupid enough to not give any extension algorithm to the greedy algorithm (thus ending up with the default `trivial_basis_extension`) which led to hard-to-interpret results. We discussed that defaulting to `gram_schmidt_basis_extension` might also not be a good idead (since one often wants to specify the product). Thus I propose to drop the default and force the user to explicitely set the basis extension algorithm.

**Comment by sdrave** [comment]
Done in 1dd463287b9ad41bb4a866385043e5d9e8a41438.
