### ISSUE TITLE
Get rid of state ids and simplify caching

### ISSUE THREAD

**Issue by sdrave** [pymor/pymor#838]
I think that, in the end, state ids are a complicated, error-prone concept that we actually do not really need. Their only use case is the generation of keys for caching which are stable over multiple runs of a given script. The same could be achieved by making persistent disk caching more explicit.

In detail, I propose the following changes:

- To identify the `Cacheable` object on which a `cached` method is a called, we currently use to object's `uid` for non-persistent regions and the object`s `sid` for persistent regions. The latter will be replaced by the new `cache_id` attribute of `Cacheable` objects which will have to be provided by the user to enable persistent caching.

- Possible arguments of a `cached` method are restricted to some basic types (numbers, strings, bools, `Parameters`, NumPy arrays) and tuples/dicts/sets thereof, which we can easily serialize deterministically. Other arguments will raise an error. 

- Remove the cache_region argument from `__init__` methods and rely of setting a default in the class `__dict__` and `enable_caching`/`disable_caching`. `enable_caching` will get an optional argument for specifying the `cache_id`.

- pyMOR's `DefaultContainer` will keep track of the number of changes made to it. The current change count will be stored along the cached value. If the change count has increased when a value is retrieved from the cache, a warning will be issued.

- The concept of state ids is removed.

Any comments, @pymor/pymor-devs?

**Comment by renefritze** [comment]
I'm in favor of the proposal. We should reconsider https://github.com/pymor/pymor/issues/129 in light of your second point.

**Comment by pmli** [comment]
This is all fine with me.

**Comment by sdrave** [comment]
> We should reconsider #129 in light of your second point.
@renefritze, can you elaborate? Not sure what you mean by this.

**Comment by renefritze** [comment]
That new cache decorator function could be a good place to experiment with DBC for example
