### ISSUE TITLE
Rename BasicInterface and ImmutableInterface?

### ISSUE THREAD

**Issue by sdrave** [pymor/pymor#854]
I would like to discuss whether we should rename our base classes to something like `Object` and `ImmutableObject` (I am open to other suggestions). I think that the word `Interface` should only refer to classes that define an interface that needs to be implemented. As a new user, I would be quite confused by the name `BasicInterface`. Other opinions, @pymor/pymor-devs?

**Comment by pmli** [comment]
I would prefer `BasicObject` (or similar) over `Object`, to avoid confusion with `object`. But, I'm also fine with `BasicInterface` and `ImmutableInterface`. From the inheritance structures and the names `Basic` and `Immutable`, I found it more or less clear that they are only used to define more specific interfaces.

Although, I would also be for removing `Interface` everywhere (e.g., `OperatorInterface` -> `Operator`), which would make it more similar to, e.g., [`collections.abc`](https://docs.python.org/3/library/collections.abc.html).

**Comment by sdrave** [comment]
I am ok with `BasicObject`.

> I found it more or less clear that they are only used to define more specific interfaces.

The point is that `BasicInterface` and `ImmutableInterface` *do not define any interface*. If I name somthing `FooInterface` or `IFoo` (I guess more common in other languages) then I look for an interface I need to implement. `BasicInterface` and `ImmutableInterface` are typical base classes, however, which provide some functionality. (Purists might probably say that the real interface classes like `OperatorInterface` should not inherit from anything, and that, say, `NumpyMatrixOperator` should inherit from `ImmutableObject` *and* `OperatorInterface`. However, I would prefer sparing users from multiple inheritance.)

> Although, I would also be for removing Interface everywhere (e.g., OperatorInterface -> Operator), which would make it more similar to, e.g., collections.abc.

That is certainly a possibility, but since pyMOR is all about interfaces (or at least to a big extent) I would prefer to clearly mark those interfaces.

**Comment by sdrave** [comment]
Also note that there are classes in pyMOR which directly derive from `BasicInterface` or `ImmutableInterface` and not from any `FooInterface`.

**Comment by sdrave** [comment]
Ok, a completely different idea: Remove `Interface` from the names, and move all these classes to a top-level module `pymor.interfaces`?

**Comment by sdrave** [comment]
FYI, at the moment we have the following classes with `Interface` in it:

`TimeStepperInterface, DomainDescriptionInterface, FunctionInterface, CacheableInterface, BasicInterface, ImmutableInterface, NumericalConvectiveFluxInterface, ConfromalTopologicalGridInterface, ReferenceElementInterface, AffineGridInterface, AffineGridWithOrthogonalCentersInterface, BoundaryInfoInterface, ModelInterface, OperatorInterface, WorkerPoolInterface, ParameterSpaceInterface, ParameterFunctionalInterface, VectorArrayInterface, VectorSpaceInterface`

When it comes to pyMOR's advertised interfaces, only
`ModelInterface, OperatorInterface, VectorArrayInterface, VectorSpaceInterface` are really relevant and should be advertised. So I am actually starting to like my last proposal to remove `Interface` from all class names and move these latter classes to `pymor.interfaces`.

**Comment by ftalbrecht** [comment]
Not sure about implications yet, but sounds like a decent idea!

**Comment by pmli** [comment]
I like the idea.
On a somewhat related note, I'm wondering whether `OperatorBase` and `ModelBase` should be removed and their implementations added to respectively `OperatorInterface` and `ModelInterface` since no concrete operators or model inherit directly from interfaces.

**Comment by sdrave** [comment]
See #859.
