### ISSUE TITLE
Make parameter handling less surprising

### ISSUE THREAD

**Issue by sdrave** [pymor/pymor#869]
At the moment one might pass `Parameters`, dicts of (NumPy) arrays, lists/tuples/arrays of numbers or single numbers as `mu` into a parametric method.

When lucky/unlucky, this method calls `parse_parameter` or not. The following can happen:
1. `parse_parameter` is not called.
    1. The method accesses a parameter component:
        - The user passes a number,list,tuple or array -> error at some point
        - The user passes a dict with the requested key missing -> error at some point
        - The user passes a dict with the requested key but wrong shape -> error at some point
        - The user passes a dict with the requested key and good shape -> success
    2. The method does not access a parameter component -> no error (in this) method
2. `parse_parameter` is called.
    - The user passes a number,list,tuple, array or dict which can be interpreted as a `Parameter` of the exact `parameter_type` the parametric object has -> success
    - The user passes a number,list,tuple, array which cannot be interpreted as a `Parameter` of the exact `parameter_type` the parametric object has -> error in `parse_parameter`
    - The user passes a dict of arrays which contains all keys of the object's `parameter_type` with correct shapes as a proper subset -> error in `parse_parameter`
    - The user passes a `Parameter` which contains all keys of the object's `parameter_type` with correct shapes as a proper subset -> success

This is all a mess and often bites users when an object which passes as `mu` for `Model.solve` is plugged into the `apply` method of an `Operator`.

I would propose the following change:

1. `parse_parameter` should be called in a methods which directly access the components of a `Parameter`.
2. The behavior of `parse_parameter` is changed as follows:
    1. The user passes a number,list or array:
        - The `parameter_type` has more than one component -> error
        - The `np.array(mu).shape` does not match the shape of the single parameter component -> error
        - Otherwise convert to `Parameter` of the object's `parameter_type` -> success
    2. The user passes a dict:
        - Convert to `Parameter` (converting all values of the dict to NumPy arrays).
        - Proceed with iii.
    3. The user passes a `Parameter`
        - The `Parameter` has all components of the object's `ParameterType` with matching shape -> success
        - One component is missing or has the wrong shape -> error

This approach should guarantee that if a `mu` can be passed to a parametric object, it can also be passed to sub-objects used to build the object's `parameter_type`. At the same time, it is still possible to pass single numbers/arrays to objects which only depend on a single parameter component.

Further options:
- Getting rid of `parse_parameter` and always passing a dict: I think it is desirable to keep the possibility to write `m.solve([1,2,3])` for interactive use. I also prefer to fail early when the passed parameter is incorrect.
- Removing `Parameter` and always using `dicts`: If we keep `parse_parameter` there is no real benefit in dropping `Parameter` except for maybe a little less confusion for the user what a parameter is. However, `Parameter` has nice methods like `copy` (performing a deep copy on all contained arrays) or `allclose` I would like to keep available.

Regarding `parse_paramter` and `Parametric` object in general we might think about an even more radical change: I think we already came across situations where it does not make sense to have a single `parameter_type` for an entire parametric object. So it might actually be an option to get rid of the entire `Paramteric` class and instead have a `parametric` decorator which might be used as follows:

```python
@parametric('operators', 'coefficients', additonal_parameter=(3,2))
def apply(self, U, mu=None):
    pass
```

So every method could have its own `parameter_type` where the arguments of `build_parameter_type` are passed to the function decorator. I haven't fully thought about the consequences yet, and I assume that there might be various difficulties with this approach I am not seeing right now.

What do you think, @pymor/pymor-devs, @TiKeil?

**Comment by TiKeil** [comment]
I agree that it handling parameters is a little bit surprising sometimes. However, in my case, being surprised often means that I did something wrong which eventually helped me to write less buggy code. I also agree that your suggestions would make since from a usability perspective, though.

In my case, giving a dict of type [ [2 , 1 ] , 1 ] when I actually mean a parameter type { a: (2,) , b: (1,) } is very useful and I would really like to keep this. Dropping this functionality would mean for me that I need an additional pre_parse_parameter since I am always switching between dicts and np.arrays.

**Comment by pmli** [comment]
There are a couple more things I find surprising about parameters:

- `Parameters` are not "symbols", but "parameter values",
- `parameter_space` is separate from `Parameter` (e.g., `parameter_space` does not have to be specified in a model, as far as I know).

I feel like `Parameters` should just have the attributes `name` and `space` (e.g., `'diffusion'` and `CubicParameterSpace`). Then methods such as `solve` and `apply` would accept a keyword argument `diffusion=[1, 2, 3]`, check that `'diffusion'` is the `name` of one of the parameters of the model/operator and that `[1, 2, 3]` is contained in the parameter's `space`. There could still be a `mu` attribute that would accept a `dict` of names and values.
What do you think about this?

**Comment by sdrave** [comment]
@pmli,

> Then methods such as solve and apply would accept a keyword argument diffusion=[1, 2, 3]

This would mean that basically every second method in pyMOR would have to take `**kwargs` which might be parameters. Note that most constructions in pyMOR are aware of a possible parametrization without knowing statically which parameters to expect. I am pretty sure that this is not a feasible approach from a technical point of view. (And I actually do not see much benefit for the user.)

If I interpret your criticism correctly you would say that a pyMOR `Parameter` is acutally a collection of parameters (which we officially call components). To that would tend to agree. When I speak about parameters in pyMOR I always have to take special care to say 'parameter *component*'. So what I would be willing to discuss would be to change this terminology. For instance we could speak of a `ParameterSet` (which might be confused with 'training set') or (maybe a bit mysterious ) `Mu`.

Regarding spaces, I agree that the current concept is probably is over-engineered and that it would be sufficient to specify allowed intervals for each parameter component. I would be willing to discuss getting rid of a separate space object and attach that information to the `parameter_type` (component-wise). That would be a pretty big change, I would rather discuss in a separate issue, however.

I had some offline discussion with @TiKeil and @ftalbrecht, which both emphasized that they are using the full functionality of `parse_parameter`. So here is a new proposal (which probably needs further discussion):

1. Rename `Parameter` to `Mu`.
2. Each `mu` passed to a parametric function must be either `None` or an instance of `Mu`.
3. Instead of `mu = self.parse_parameter(mu)` everywhere we write `assert mu in self.parameter_type`. (Or some similar idiom.)
4. `Mu.__init__` has a standard `dict` constructor signature, where values are converted to NumPy arrays.
5. In addition, one can write `Mu(fom, 3)` or, e.g., `Mu(fom, 3, [1, 2, 3])` to get the current `parse_parameter` functionality.

Thus, assuming we have a `Model` taking a `diffusions` parameter of shape `(3,)` and a scalar `reaction`, one now would write:

```python
fom.solve(Mu(diffusions=[1,2,3], reaction=0.1))
```

or

```python
fom.solve(Mu(fom, [1,2,3], 0.1)
```

So, you see, that I am using `Mu` as a class name mainly to keep notation short.

I have to admit that this is looking complicated. So maybe we should rather ditch `Parameter`/`Mu` and use vaniila dicts. Downsides:
- We loose automatic deep copy via the `copy` method. However, ATM we only change entire components, so a shallow copy would be sufficient.
- We loose the `allclose` method which isn't used anywhere.
- Printing a `mu` will not give alphabetical ordering.

The examples would change to:
```python
fom.solve({'diffusions': [1,2,3], 'reaction': 0.1})
fom.solve(dict(diffusions=[1,2,3], reaction=0.1))
fom.solve(fom.parse_parameter([1,2,3], 0.1))
```

**Comment by pmli** [comment]
> This would mean that basically every second method in pyMOR would have to take `**kwargs` which might be parameters. [...] I am pretty sure that this is not a feasible approach from a technical point of view.

Right, agreed.

> If I interpret your criticism correctly you would say that a pyMOR `Parameter` is acutally a collection of parameters (which we officially call components).

Yeah, I guess that was one part of my confusion. The other is "symbols" vs. "values". I was thinking whether pyMOR parameters can be (something like) SymPy symbols and the symbols replaced with values using SymPy's `subs` method. Does it make sense to add a `subs` method (maybe with a different name) to `Parametric` objects and remove `mu` from `apply` and `solve`? Then your example would look like

```python
fom.subs(diffusions=[1,2,3], reaction=0.1).solve()
```

**Comment by sdrave** [comment]
I do not really see the benefit:

```python
fom.subs(diffusions=[1,2,3], reaction=0.1).solve()
fom.solve(dict(diffusions=[1,2,3], reaction=0.1))
fom.solve(Mu(diffusions=[1,2,3], reaction=0.1))
```

So your approach requires the most characters, and it is not clear to me how to implement it. If you do not want to have the parameter (values) in the signature of `apply` or `solve`, you would probably have to have a `mu` attribute which would be `None` before calling `subs`. Calling `subs` would have to produce a new instance with this attribute set to the right value. Thus, we would need to add `mu` to all constructors at the very least. Maybe doable, but I do not see what would be gained. Also note that your notion of parameter seems to be precisely what the `parameter_type` of the object is. I am open to changing nomenclature, e.g. replace `parameter_type` by `params` .. Finally, for `Operators`, `assemble` is basically what you want `subs` to do ..

**Comment by pmli** [comment]
I see...
Right now, I don't have a preference between the `dict` and `Mu` options.
