### ISSUE TITLE
Auto generate scripts from tutorials

### ISSUE THREAD

**Issue by sdrave** [pymor/pymor#876]
and them into an easily discoverable directory (`docs/scripts`?).

Supersedes #573.

**Comment by renefritze** [comment]
This now translates in adding `:jupyter-download:script:` alongside  `:jupyter-download:notebook:` in the tutorials, right?

**Comment by renefritze** [comment]
> This now translates in adding `:jupyter-download:script:` alongside `:jupyter-download:notebook:` in the tutorials, right?

Or not, since that's already there. So you want to ship those scripts in the pymor source?

**Comment by sdrave** [comment]
> > This now translates in adding `:jupyter-download:script:` alongside `:jupyter-download:notebook:` in the tutorials, right?
> 
> Or not, since that's already there. So you want to ship those scripts in the pymor source?

I think the meaning of this still needs discussion .. Are you at the office this afternoon?

**Comment by renefritze** [comment]
We decided to try to extract the runnable code from the tutorial RST without executing it first (ie no jupyter-sphinx) and using that result in pytest.
