### ISSUE TITLE
Integrate tutorial scripts into pytest

### ISSUE THREAD

**Issue by sdrave** [pymor/pymor#877]
Find a way to keep the `check_results` functionality of current demo tests. (Eg. by an additional rst directive or a dedicated test function.)

**Comment by renefritze** [comment]
Intent here is to make sure `make test` executes the tutorials.

**Comment by renefritze** [comment]
With current myst-nb setup it is trivial to have hidden cells in generated tutorials that do these checks. Pretty sure we already use that too (with asserts, not `check_results`). And since we're not converting the demo tests to tutorials (any more?) I think this issue is no longer needed.

**Comment by sdrave** [comment]
Agreed.
