### ISSUE TITLE
Parametrize tutorials?

### ISSUE THREAD

**Issue by sdrave** [pymor/pymor#878]
It would be nice to support some basic form of parametrization for the tutorial documents, in particular to make them more useful for testing. However, it is completely unclear how to do that. (In particular, what would we expect for the static html version of the tutorial?)

**Comment by renefritze** [comment]
As I mentioned offline, integrating parameterization (in the sense of multiple code paths) into the nbplots directive is not a good idea as the processing in nbplots is already too complex. 
We would need to come up with another solution, maybe along the line of generating multiple rst documents from a text template.

**Comment by sdrave** [comment]
So after having some experience with writing tutorials, I do not think it makes much sense to add any form of parametrization. I think that, overall, we should keep the demo scripts for parametrized system test, even if it means some code duplication. What do you think, @pymor/pymor-devs?

**Comment by renefritze** [comment]
Completely agree. Any solution that will hide the parameterization in docs output, but execute it from tests is likely to end in  overengineering.

**Comment by pmli** [comment]
The tutorials can already be converted to notebooks. How much work would it be to run papermill on them for testing? As far as I see, it's enough to add a "parameters" tag to a cell to [parameterize a notebook](https://papermill.readthedocs.io/en/latest/usage-parameterize.html).

If this wouldn't work, I would still prefer to have notebooks instead of scripts as demos.

**Comment by renefritze** [comment]
> How much work would it be to run papermill on them for testing? 

1. AFAICS jupyter-sphinx does not support generating tagged cells, so you'd first have to implement that and get it merged. 
2. Notebooks are generated in the docs job currently. This would need to be duplicated/moved into/before the test jobs. 
3. The actual parameterization needs to be saved into a config (pytest script?) and papermill execution hooked into pytest
4. Results comparison needs to happen somehow?

As an aside, parameter cells don't make for a nice to read tutorial IMO.

**Comment by sdrave** [comment]
@pmli, in view of  #1160, #1166 and our discussion at the last dev meeting that we want to keep the demos for testing purposes, this can be closed, right?

**Comment by pmli** [comment]
Right.
