### ISSUE TITLE
NumpyVectorArray.__init__ does no checks

### ISSUE THREAD

**Issue by pmli** [pymor/pymor#879]
There are no dimension checks in `NumpyVectorArray.__init__`. This causes issues if vectors are given as columns of a matrix as in

```python
import numpy as np
from pymor.operators.numpy import NumpyMatrixOperator
from pymor.vectorarrays.numpy import NumpyVectorArray

A = NumpyMatrixOperator(np.eye(5))
V = NumpyVectorArray(np.zeros((5, 2)), A.source)
print(V.dim)
print(len(V))
print(V in A.source)
print(A.apply(V))
```

which results in

```
5
5
True
Traceback (most recent call last):
  [...]
ValueError: shapes (5,5) and (2,5) not aligned: 5 (dim 1) != 2 (dim 0)
```

**Comment by sdrave** [comment]
You should never directly instantiate a `NumpyVectorArray`. `VectorSpaces` are for creating new `VectorArrays`, so you should write

```python
A.source.make_array(np.zeros((5, 2))
```

which *will* produce an error.

**Comment by pmli** [comment]
> You should never directly instantiate a `NumpyVectorArray`.

Should this be documented somewhere?

**Comment by sdrave** [comment]
Probalby ... I would hope, that this also explained in the technical overview.
