### ISSUE TITLE
Playground's future

### ISSUE THREAD

**Issue by sdrave** [pymor/pymor#890]
It just came to my attention that it has been quite a while that we have added something to the `playground`. I see two options for the future: Remove it from pyMOR completely or keep it and actually encourage putting preliminary code there which is of some value but does not meet our general quality standards. Should code in the `playground` be tested?

Opinions, @pymor/pymor-devs?

**Comment by renefritze** [comment]
I like the second option. Maybe also rename to "staging", cause that is really what you just described.
I would propose limited testing (only most current python), separately from the rest of the pytest suite, so as to potentially allow failing the entire step w/o failing the entire pipeline.

**Comment by pmli** [comment]
I'm not sure. I don't think I ever used the `playground`.

**Comment by sdrave** [comment]
I think, this might also be a good discussion point for the next dev meeting?

**Comment by pmli** [comment]
Agreed.

**Comment by sdrave** [comment]
pyMOR dev meeting: Remove it.
