### ISSUE TITLE
Re-enable tests for python 3.8

### ISSUE THREAD

**Issue by renefritze** [pymor/pymor#891]
Currently there are no Pymess wheels for that version. I've already asked about it upstream.
Revert e7ebcada09af489f7329d9c0f4b78e6496d8fd42 afterwards.

**Comment by renefritze** [comment]
Ipyparallel also fails on 3.8: https://github.com/ipython/ipyparallel/issues/396
Revert 6c1cc9f4246358cf641f4171f274184077aa7404 when that's fixed.

**Comment by kinglionsz** [comment]
```
import sys
import os

print(os.path)
print(sys.version,sys.version_info)
print(sys.executable)

import ipyparallel as ipp
c=ipp.Client()
print(ipp)
print(ipp.__version__)
print(c[:].apply_sync(lambda : "Hello, World"))
```

<module 'ntpath' from 'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.8_3.8.752.0_x64__qbz5n2kfra8p0\\lib\\ntpath.py'>
3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)] sys.version_info(major=3, minor=8, micro=2, releaselevel='final', serial=0)
C:\Users\lyl\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\python.exe
<module 'ipyparallel' from 'C:\\Users\\lyl\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\ipyparallel\\__init__.py'>
6.2.4
['Hello, World', 'Hello, World', 'Hello, World', 'Hello, World']


```
import sys
import os

print(os.path)
print(sys.version,sys.version_info)
print(sys.executable)
```

<module 'ntpath' from 'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.8_3.8.752.0_x64__qbz5n2kfra8p0\\lib\\ntpath.py'>
3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)] sys.version_info(major=3, minor=8, micro=2, releaselevel='final', serial=0)
C:\Users\lyl\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\python.exe

14 hours ago. @renefritze 😊👍

**Comment by renefritze** [comment]
Not sure what you are saying, @kinglionsz. Could you please elaborate?

**Comment by renefritze** [comment]
It's only the Pymess tests that are still disabled now.
