### ISSUE TITLE
CI speedup ideas

### ISSUE THREAD

**Issue by renefritze** [pymor/pymor#892]
I'm currently investigating ways to reduce the total time our test pipeline uses:
 1. reduce time to failure if something's broken:
    1. first step here was to introduce a "sanity" stage at the start of the pipeline which checks if all docker images used further down the pipe are actually available, if out setup.py can be executed, ...
    1. maybe separate running unit and system/integration tests, so we can run unit first. That assumes unit is actually faster to execute, which I'd have to check

1. Split pytest execution into more jobs on gitlab:
   This involves a simple pytest plugin and the gitlab 'parallel' setting for jobs. Config/usage is trivial, coverage submit might be a bit tricky. Impact depends on job setup vs actual pytest execution time, which I have to examine again.

1. Variability reduction with hypothesis:
    "Everyday" CI jobs could run a limited amount of data sets, while "some other" could run full. "Some other" could be weekly pipelines on certain branches, first pipeline on a new branch, ...

1. Reduce setup time for jobs (i.e. everything that's not executing pytest):
    - Provisioning fixed pypi mirrors for the pipeline already cut down on this
    - Next step will be (automatically) pre-seeding these + test images on the autoscaling builders VM in WWU IT Openstack. This needs Adrian. 

Open for comments, @pymor/pymor-devs

**Comment by renefritze** [comment]
5. Most intrusive measure: Select tests to run from effected code changes wit testmon: https://testmon.org/determining-affected-tests.html

**Comment by renefritze** [comment]
6. reduce complexity via hypothesis. I'll tackle this first by re-setting the vectorarray setup I had back before the complex value changes.
 7. generally investigate where test size/complexity reduction would might be possible

**Comment by renefritze** [comment]
For reference I extracted some runtimes of a complete test suite on my workstation. All test classes (= source files in pymortests) with less than 1s runtime are left out.
 [Here's the script](https://gist.github.com/renefritze/14c5f2d79694ff746e7b0905a773e03c)

| class name                             |   cumulative time (s) |
|----------------------------------------|-----------------------|
| src.pymortests.affine_grid             |                85.513 |
| src.pymortests.demos                   |               736.037 |
| src.pymortests.grid                    |               385.281 |
| src.pymortests.gui                     |                 1.521 |
| src.pymortests.lyapunov                |                 7.694 |
| src.pymortests.model                   |                17.231 |
| src.pymortests.operators               |                45.882 |
| src.pymortests.riccati                 |                58.857 |
| src.pymortests.sylvester               |                 1.982 |
| src.pymortests.tools                   |                 1.076 |
| src.pymortests.vectorarray             |               575.950 |
| src.pymortests.algorithms.basic        |               163.982 |
| src.pymortests.algorithms.gram_schmidt |                33.929 |
| src.pymortests.algorithms.pod          |                 9.975 |
| src.pymortests.algorithms.svd_va       |                10.292 |

**Comment by renefritze** [comment]
After some more processing:

Showing tests that build the top 90 percentile in total runtime


| class name       |   cumulative (s) |   % total |
|------------------|------------------|-----------|
| demos            |          736.037 |     34.44 |
| vectorarray      |          575.950 |     26.95 |
| grid             |          385.281 |     18.03 |
| algorithms.basic |          163.982 |      7.67 |
| affine_grid      |           85.513 |      4    |


| case name                                            |   cumulative (s) |   % total |
|------------------------------------------------------|------------------|-----------|
| demos__test_demos                                    |          401.192 |     18.77 |
| vectorarray__test_axpy_one_x                         |          243.328 |     11.39 |
| demos__test_thermalblock_ipython                     |          164.592 |      7.7  |
| algorithms.basic__test_almost_equal_self             |          112.159 |      5.25 |
| grid__test_neighbours_each_neighbour_has_entry       |           77.742 |      3.64 |
| demos__test_burgers_ei_result                        |           77.464 |      3.62 |
| grid__test_neighbours_each_entry_neighbour           |           67.087 |      3.14 |
| vectorarray__test_axpy                               |           62.821 |      2.94 |
| riccati__test_ricc_lrcf                              |           56.257 |      2.63 |
| grid__test_neighbours_entry_values_unique            |           55.052 |      2.58 |
| grid__test_neighbours_dtype                          |           46.049 |      2.15 |
| grid__test_neighbours_shape                          |           45.961 |      2.15 |
| grid__test_neighbours_entry_value_range              |           45.938 |      2.15 |
| demos__test_thermalblock_results                     |           42.621 |      1.99 |
| vectorarray__test_dot                                |           37.249 |      1.74 |
| demos__test_parabolic_mor_result                     |           30.883 |      1.45 |
| vectorarray__test_dot_self                           |           28.068 |      1.31 |
| affine_grid__test_jacobian_inverse_transposed_values |           24.385 |      1.14 |
| vectorarray__test_append                             |           21.684 |      1.01 |
| vectorarray__test_axpy_self                          |           21.546 |      1.01 |
| algorithms.basic__test_almost_equal                  |           20.763 |      0.97 |
| grid__test_neighbours_not_neighbour_of_itself        |           20.359 |      0.95 |
| affine_grid__test_embeddings_transitivity            |           19.358 |      0.91 |
| demos__test_analyze_pickle                           |           19.285 |      0.9  |
| vectorarray__test_gramian                            |           18.821 |      0.88 |
| algorithms.basic__test_almost_equal_self_product     |           14.733 |      0.69 |
| vectorarray__test_axpy_wrong_ind                     |           14.652 |      0.69 |
| algorithms.gram_schmidt__test_gram_schmidt_with_R    |           13.042 |      0.61 |
| algorithms.basic__test_almost_equal_wrong_ind        |           12.578 |      0.59 |
| vectorarray__test_getitem_repeated                   |           12.444 |      0.58 |
| algorithms.gram_schmidt__test_gram_schmidt           |           12.374 |      0.58 |
| vectorarray__test_scal                               |           11.462 |      0.54 |
| vectorarray__test_random_normal                      |           11.416 |      0.53 |
| vectorarray__test_dofs                               |           10.005 |      0.47 |
| operators__test_apply_inverse_adjoint                |            9.980 |      0.47 |
| operators__test_apply_inverse                        |            9.955 |      0.47 |
| affine_grid__test_unit_outer_normals_neighbours      |            9.488 |      0.44 |
| model__test_pickle_by_solving                        |            9.427 |      0.44 |
| algorithms.svd_va__test_method_of_snapshots          |            8.822 |      0.41 |
| algorithms.pod__test_pod                             |            8.457 |      0.4  |

**Comment by sdrave** [comment]
Judging by the last table, it would definetely make sense to look at individual tests first. `vectorarray__test_axpy_one_x` for instance seems to take way too much time. Also, why does `demos__test_thermalblock_ipython` have to take so much time. For testing out the the parallelization, a small test case should be sufficient. I think there are some low-hanging fruits there.

**Comment by renefritze** [comment]
And now with the current state in the hypothesis2 branch:

| class name   |   cumulative (s) |   % total |
|--------------|------------------|-----------|
| demos        |          708.709 |     78.73 |
| grid         |           46.128 |      5.12 |
| operators    |           35.921 |      3.99 |
| riccati      |           33.624 |      3.74 |


| case name                                        |   cumulative (s) |   % total |
|--------------------------------------------------|------------------|-----------|
| demos__test_demos                                |          386.969 |     42.99 |
| demos__test_thermalblock_ipython                 |          160.838 |     17.87 |
| demos__test_burgers_ei_result                    |           71.538 |      7.95 |
| demos__test_thermalblock_results                 |           41.960 |      4.66 |
| riccati__test_ricc_lrcf                          |           31.998 |      3.55 |
| demos__test_parabolic_mor_result                 |           28.017 |      3.11 |
| demos__test_analyze_pickle                       |           19.387 |      2.15 |
| algorithms.basic__test_almost_equal_self_product |           11.247 |      1.25 |
| grid__test_neighbours_each_neighbour_has_entr    |            9.586 |      1.06 |
| model__test_pickle_by_solving                    |            9.500 |      1.06 |
| operators__test_apply_inverse                    |            8.606 |      0.96 |
| grid__test_neighbours_dtyp                       |            7.763 |      0.86 |
| grid__test_neighbours_each_entry_neighbou        |            7.621 |      0.85 |
| operators__test_apply_inverse_adjoint            |            7.535 |      0.84 |
| grid__test_neighbours_shap                       |            6.679 |      0.74 |
| lyapunov__test_lrcf                              |            5.154 |      0.57 |

In this (the default, controlled in our conftest.py) profile hypothesis produces 10 data points as input for a test function. I've already setup a weekly cron-triggered CI pipeline that bumps that to 5000 and the everyday CI pipeline is set to 100 examples. Numbers for that incoming.

**Comment by renefritze** [comment]
And here the numbers for 100 examples (which already found failures that 10 did not):

| class name              |   cumulative (s) |   % total |
|-------------------------|------------------|-----------|
| demos                   |          724.189 |     40.07 |
| grid                    |          352.070 |     19.48 |
| vectorarray             |          206.090 |     11.4  |
| affine_grid             |          184.724 |     10.22 |
| algorithms.gram_schmidt |          149.592 |      8.28 |
| algorithms.basic        |           61.944 |      3.43 |


| case name                                           |   cumulative (s) |   % total |
|-----------------------------------------------------|------------------|-----------|
| demos__test_demos                                   |          398.970 |     22.08 |
| demos__test_thermalblock_ipython                    |          160.761 |      8.9  |
| algorithms.gram_schmidt__test_gram_schmid           |          130.025 |      7.19 |
| demos__test_burgers_ei_result                       |           75.703 |      4.19 |
| vectorarray__test_axpy_one_                         |           63.065 |      3.49 |
| grid__test_neighbours_entry_values_uniqu            |           60.811 |      3.36 |
| grid__test_neighbours_each_neighbour_has_entr       |           55.134 |      3.05 |
| grid__test_neighbours_entry_value_rang              |           47.968 |      2.65 |
| grid__test_neighbours_each_entry_neighbou           |           47.916 |      2.65 |
| demos__test_thermalblock_results                    |           42.069 |      2.33 |
| grid__test_neighbours_dtyp                          |           39.363 |      2.18 |
| grid__test_neighbours_shap                          |           35.277 |      1.95 |
| algorithms.basic__test_almost_equal_sel             |           32.357 |      1.79 |
| riccati__test_ricc_lrcf                             |           31.978 |      1.77 |
| affine_grid__test_embeddings_transitivit            |           31.429 |      1.74 |
| affine_grid__test_unit_outer_normals_neighbour      |           30.152 |      1.67 |
| demos__test_parabolic_mor_result                    |           27.547 |      1.52 |
| affine_grid__test_unit_outer_normals_shap           |           26.469 |      1.46 |
| affine_grid__test_jacobian_inverse_transposed_value |           25.769 |      1.43 |
| stateful.TestBasis__runTes                          |           21.559 |      1.19 |
| affine_grid__test_orthogonal_center                 |           20.914 |      1.16 |
| demos__test_analyze_pickle                          |           19.139 |      1.06 |
| algorithms.gram_schmidt__test_gram_schmidt_biort    |           11.021 |      0.61 |
| grid__test_neighbours_not_neighbour_of_itsel        |           10.914 |      0.6  |
| algorithms.basic__test_almost_equal_self_product    |           10.623 |      0.59 |
| vectorarray__test_axp                               |           10.536 |      0.58 |
| model__test_pickle_by_solving                       |            9.175 |      0.51 |
| algorithms.basic__test_almost_equal_wrong_in        |            9.175 |      0.51 |
| affine_grid__test_jacobian_inverse_transposed_shap  |            8.580 |      0.47 |
| operators__test_apply_inverse                       |            8.432 |      0.47 |
| affine_grid__test_unit_outer_normals_norma          |            7.776 |      0.43 |
| operators__test_apply_inverse_adjoint               |            7.427 |      0.41 |
| affine_grid__test_unit_outer_normals_norme          |            7.284 |      0.4  |
| algorithms.gram_schmidt__test_gram_schmidt_with_    |            6.489 |      0.36 |
| grid__test_subentities_entry_values_uniqu           |            5.397 |      0.3  |
| lyapunov__test_lrcf                                 |            5.253 |      0.29 |
| vectorarray__test_appen                             |            5.244 |      0.29 |
| grid__test_boundary_mask_entries_codim              |            5.117 |      0.28 |
| vectorarray__test_axpy_wrong_in                     |            5.079 |      0.28 |
| grid__test_visualiz                                 |            4.982 |      0.28 |
| grid__test_superentities_each_entry_superentit      |            4.951 |      0.27 |
| vectorarray__test_axpy_wrong_coefficient            |            4.276 |      0.24 |
| vectorarray__test_dot_sel                           |            4.070 |      0.23 |
| grid__test_superentities_each_superentity_has_entr  |            3.973 |      0.22 |
| vectorarray__test_random_norma                      |            3.883 |      0.21 |
| model__test_pickle                                  |            3.873 |      0.21 |
| operators__test_apply2                              |            3.849 |      0.21 |
| model__test_pickle_without_dumps_function           |            3.729 |      0.21 |
| vectorarray__test_ad                                |            3.666 |      0.2  |
| affine_grid__test_quadrature_points_value           |            3.639 |      0.2  |
| affine_grid__test_integration_elements_value        |            3.474 |      0.19 |
| algorithms.basic__test_almost_equa                  |            3.424 |      0.19 |
| vectorarray__test_pairwise_do                       |            3.346 |      0.19 |
| vectorarray__test_imu                               |            3.214 |      0.18 |
| vectorarray__test_pairwise_dot_wrong_in             |            3.188 |      0.18 |
| vectorarray__test_isu                               |            3.175 |      0.18 |
| grid__test_superentity_indices_valid_entrie         |            3.156 |      0.17 |
| vectorarray__test_append_incompatibl                |            2.975 |      0.16 |

**Comment by renefritze** [comment]
8. Let draft pull request no longer trigger a PR build
 9. Normal branch pushed CI pipelines and the PR CI pipeline could have differently sized hypothesis profiles. In combination with 8. this would reduce total CI waiting time until one deems the PR "ready" to merge.

**Comment by renefritze** [comment]
Dev Meeting: I'll implement point 9 as suggested for the 2020.1 milestone in #910 in addition to 3 and 6 which are already there for certain tests.

**Comment by renefritze** [comment]
> Dev Meeting: I'll implement point 9 as suggested for the 2020.1 milestone in #910 in addition to 3 and 6 which are already there for certain tests.

This is now implemented, therefore I'm moving the rest to next release.

**Comment by sdrave** [comment]
I think it would really pay off to look at the demo tests and see if the parametrization is reasonable. At least for a quick test, all demos can run with small basis sizes and small grids. I am not sure if this is the case.

**Comment by renefritze** [comment]
with #1147 I'm moving this to 2021

**Comment by renefritze** [comment]
This needs to be split into actually actionable issues at some point after the next release.

**Comment by renefritze** [comment]
Important for the next release is #1665

**Comment by renefritze** [comment]
I think this can actually be closed now.
