### ISSUE TITLE
Thermalblock demo fails with parameters FEnics + without estimator

### ISSUE THREAD

**Issue by pbuchfink** [pymor/pymor#893]
The `thermalblock.py` demo throws an error with the parameters `--greedy-without-estimator` and `--fenics` at the same time. MWE: 
`python3 thermalblock.py --greedy-without-estimator --fenics 1 1 1 1`
Full error log: [err.log](https://github.com/pymor/pymor/files/4305938/err.log). The error is:

> TypeError: can't pickle dolfin.cpp.la.PETScVector objects

The problem is that, in `RBSurrogate.extend`, a deepcopy of `self.reductor` is created which carries the reduced basis as class attribute. This happens when `self.reductor` is pushed to the pool with
`self.remote_reductor = self.pool.push(self.reductor)`
The problematic attributes of the reductor are:
- `bases['RB']`
- `residual_reductor.residual_range`
- `residual_reductor.RB`

Is there a conceptual work arround or something that should be implemented in the future?

**Comment by sdrave** [comment]
Hi @pbuchfink, this should be fixed by #895.

**Comment by pbuchfink** [comment]
Thanks @sdrave. The fix works for me.
