### ISSUE TITLE
Should CI test a virtualenv install?

### ISSUE THREAD

**Issue by renefritze** [pymor/pymor#897]
The (ex) "PIP_ONLY" step would be a good candidate to install pymor and dependencies in a venv instead of system/user wide.
However, this would mean we'd need to mark tests that use external solvers to exclude them in this job. 

Two potential pros:
 1. Actually try to install and use pymor in a Venv, which we tell people to do in our README
 2. Try running code w/o the assumption of the fully stocked docker image. 

Cons:
 1. Marking tests potentially messy

Opinions, @pymor/pymor-devs ?

**Comment by ftalbrecht** [comment]
I like testing in a virtualenv, this is how I usually work. However, I am against complicating CI...

**Comment by pmli** [comment]
I'm not sure I understand why additional marking is necessary. If the external solver is not installed, the corresponding test is skipped, right?

**Comment by renefritze** [comment]
In the demos test for example missing solvers are a failure if running in the docker environment. Which is good for all other tests in CI since we want to be alerted when the supposedly installed solver is not available, but which would have to be handled differently for my proposed venv job here.

**Comment by pmli** [comment]
It might be good to test pyMOR installed in a virtual environment with external solvers installed globally. Is this possible?

**Comment by renefritze** [comment]
Well, one can create the venv with `--system-site-packages` but in our case here that imo would defeat the purpose as I feel the real test here would mimic a new setting up a pymor install.

**Comment by pmli** [comment]
Ok, then what about installing external solvers locally? I'm not sure if it's possible for all, but I usually build FEniCS/Dolfin from source and add it to the venv with `cd dolfin/python && pip install .`.

**Comment by renefritze** [comment]
That's not really practical IMO as I would have to keep the build directories of all the solvers in the CI image. Currently those are discarded by several Multi-Stage build elements, reducing the final image size to 1.2GB from around 3GB.

**Comment by pmli** [comment]
Ok, I see...

**Comment by sdrave** [comment]
I'm not sure if testing in a venv really is that helpful to justify the extra CI complexities. I always use pyMOR in a venv and never encountered any issues.

**Comment by renefritze** [comment]
I also feel like this has been much more of an issue with older versions of pip/virtualenv. 
I'd say if we ever come across a real venv-only issue we can put in the work to enable testing then. Script wise that's trivial: https://github.com/pymor/pymor/blob/master/.ci/gitlab/test_pip_installed.bash#L10
Only the failure masking stuff would be some work. 

Closing until then.
