### ISSUE TITLE
AssertionError for parametric NumpyMatrixOperators in apply2 and pairwise_apply2

### ISSUE THREAD

**Issue by pbuchfink** [pymor/pymor#898]
Calling `apply2` or `pairwise_apply2` for a parametric `NumpyMatrixOperator` raises an `AssertionError` ([mwe.zip](https://github.com/pymor/pymor/files/4324042/mwe.zip) attached). The problem is that in `Operator` it is not checked, if the operator is `parametric` before `parse_parameter` is called (cf. `apply` operation in `NumpyMatrixOperator`).
This could be fixed in `Operator` or in `NumpyMatrixOperator`.

**Comment by sdrave** [comment]
Here's the MWE:

```python
'''MWE to demonstrate problems with parametric NumpyMatrixOperators and apply2'''
import numpy as np
from pymor.operators.numpy import NumpyMatrixOperator
from pymor.operators.constructions import LincombOperator
from pymor.parameters.functionals import ExpressionParameterFunctional

M = np.eye(2)
param = ExpressionParameterFunctional('alpha', {'alpha': 0})
op = NumpyMatrixOperator(M)
B = LincombOperator([op], [param])

space = op.source
V = space.make_array([1, 1])
mu = {'alpha': 1.}
# apply works, since parametric is checked
B.apply(V, mu=mu)
# apply2 does not work, since parametric is not checked
B.apply2(V, V, mu=mu)
# same problem for pairwise_apply2
B.pairwise_apply2(V, V, mu=mu)
```

Unfortunately, this is expected behavior (#869). The code can be fixed, by making mu a proper `Parameter` by writing
```python
mu = Parameter({'alpha': 1.})
```

The next pyMOR release should include a change in parameter handling which will prevent such errors.
