### ISSUE TITLE
RemoteObject self-loop

### ISSUE THREAD

**Issue by pmli** [pymor/pymor#899]
By accident, #859 caused:

https://github.com/pymor/pymor/blob/1e5eaf72879a1b2915f19a2bbcf72f6917fbfd99/src/pymor/parallel/basic.py#L98

**Comment by renefritze** [comment]
I wonder how this not an error in any test. Any clue, @pmli ?

**Comment by pmli** [comment]
No idea. I found it by seeing a literal self-loop in a class diagram I made.

**Comment by sdrave** [comment]
The trick is that we import `RemoteObject` from `pymor.parallel.interfaces`. So `pymor.parallel.basic.RemoteObject` inherits from a different class with the same name. I think this is all correct, but we *might* consider doing some renaming ...

**Comment by pmli** [comment]
Is it possible to remove `pymor.parallel.basic.RemoteObject` and move its methods to `pymor.parallel.interfaces.RemoteObject`?

**Comment by sdrave** [comment]
Merging does not really make sense. `pymor.parallel.basic.RemoteObject` is a complete implementation used in combination with `WorkerPoolBase`. I think we should just rename it.
