### ISSUE TITLE
add an unstructured grid

### ISSUE THREAD

**Issue by sdrave** [pymor/pymor#9]

**Comment by ftalbrecht** [comment]
There already exits an implementation of a gmsh reader in the playground: https://github.com/pymor/pymor/blob/master/src/pymor/playground/grids/gmsh.py

Maybe you could comment on what is working/missing at some point?, @sdrave

**Comment by sdrave** [comment]
The idea is to make this implementation actually usable. Main issues:

1. The code hasn't been tested for quite a while.
2. I believe there were some performance issues.
3. We need a standardized way to obtain a `BoundaryInfo` from the gmsh data as well.
4. Nice to have: Implement a domain discretizer which creates gmsh input files from `DomainDescriptions` (also add a `PolygonalDomain`, or something like that), runs gmsh and then loads the output into pyMOR.

Currently plans are that @michaellaier will work a bit on this in the not so distant future.

**Comment by sdrave** [comment]
@michaellaier, in case you haven't started working on it yet: It might also be a good option to use triangle instead of gmsh. There is a nice Python wrapper which also builds triangle itself for you if you run `pip install triangle`.

Here is a basic example to get started:

```python
import numpy as np
import triangle
import matplotlib
from matplotlib.pyplot import *

angles = np.linspace(0, 1.75*np.pi, 20)
vertices = np.array([np.cos(angles), np.sin(angles)]).T
vertices = np.vstack([vertices, [0., 0.]])
segments = np.array([np.arange(len(vertices)), np.arange(1, len(vertices)+1)]).T
segments[-1, -1] = 0
segment_markers = np.arange(1, len(segments) + 1)
R = triangle.triangulate({'vertices': vertices, 'segments': segments, 'segment_markers': segment_markers}, 'pqa0.01')
segment_coords = R['vertices'][R['segments']]
gca().tripcolor(R['vertices'][:, 0], R['vertices'][:, 1], R['triangles'], facecolors=np.arange(len(R['triangles'])))
cmap = matplotlib.cm.get_cmap()
for l, m in zip(segment_coords, R['segment_markers']):
    plot(l[:, 0], l[:, 1], color=cmap(float(m)/len(segments)), linewidth=3)
show()
```
![figure_1](https://cloud.githubusercontent.com/assets/2648288/9679167/65c5188c-52ec-11e5-8681-80979ba9f1ab.png)

**Comment by sdrave** [comment]
There is a problem with passing floats to triangle in the option string, however. If localization support in libc is activated (as it happens when you use matplotlib, but triangle does not activate it!), the float is parsed according to `LC_NUMERIC`. So if `LC_NUMERIC=de`, you would have to write `0,1` instead of `0.1`. The wrong format will crash trianagle (and thus the whole process), since `atof` will incorrectly parse the string as `0`.

For development, I would simply `unset LC_NUMERIC`, and worry about this issue later.

**Comment by sdrave** [comment]
Regarding the implementation of the grid, it would probably wise, to implement a grid satisfying the interface, which uses a vertex array and a triangle array of vertex indices as input. This could be used for gmsh output as well as triangle output.
