### ISSUE TITLE
Decide future of manylinux1 wheels

### ISSUE THREAD

**Issue by renefritze** [pymor/pymor#900]
For some reason I do not understand yet the manylinux1 toolchain broke. I will disable building manylinux1 wheels on our CI for the time being since I really have to finish up with the fixed pypi mirror and python 3.8 setup. 
The manylinux2010 toolchain is still fine, so we might also decide to just drop manylinux1. 2010 support landed in pip with version 19.

**Comment by sdrave** [comment]
I did some research: buster still ships pip 18.1, which is also what you get when you use the venv module of the Python 3 standard lib. On the other hand, virtualenv downloads a recent pip from the internet. Assuming that virtually nobody uses the venv module, dropping manylinux1 wheels mainly breaks 'pip3 install (--user) pymor'. Ubuntu also seems to ship pip 18, so quite a few people might be affected.

So, I would say for the releases this years it would still be nice to have manylinux1 wheels. However, if it should turn out difficult to get them building again, I think a warning in the README might also be acceptable.

**Comment by renefritze** [comment]
The wheelbuilder part of the problem wasn't as bad as I initially thought. Testing actually building wheels with it tonight.
