### ISSUE TITLE
Start testing against python 3.9

### ISSUE THREAD

**Issue by renefritze** [pymor/pymor#903]
RC1 is due 2020-08-10 and final 2020-10-05.

I've already setup building the docker images for 3.9, which are still [allowed to fail](https://zivgitlab.uni-muenster.de/pymor/docker-all/-/jobs/316484) to build.

**Comment by renefritze** [comment]
Remember to add 3.9 to trove classifiers afterwards

**Comment by renefritze** [comment]
Currently Petsc fails configuring with 3.9: https://github.com/pymor/docker-all/pull/11

**Comment by renefritze** [comment]
> Currently Petsc fails configuring with 3.9: [pymor/docker-all#11](https://github.com/pymor/docker-all/pull/11)

Fixed with petsc 3.14.

Now waiting on https://github.com/lxml/lxml/pull/311

**Comment by renefritze** [comment]
Also waiting for: https://github.com/python-pillow/Pillow/issues/4953

Pytorch apparently will not ship python 3.9 binaries until they release version 1.8 with 1.7 being the upcoming release.

**Comment by hugovk** [comment]
Pillow 8.0.0 supporting Python 3.9 is now out!

* https://pillow.readthedocs.io/en/stable/releasenotes/8.0.0.html
* https://pypi.org/project/Pillow/8.0.0/
* https://twitter.com/PythonPillow/status/1316452445824921602

**Comment by renefritze** [comment]
> Pillow 8.0.0 supporting Python 3.9 is now out!

Great! Thanks for the heads up @hugovk !

**Comment by renefritze** [comment]
The pytorch install for python 3.9 I do segfaults on interpreter shutdown. I think our best option to still include 3.9 support for the next release would be to skip CI with torch and 3.9. 

If nobody opposes this until Monday, I will make the changes accordingly  in the pytest setup.
