### ISSUE TITLE
Initial guess parameter for `apply_inverse`

### ISSUE THREAD

**Issue by HenKlei** [pymor/pymor#924]
In an instationary equation I tried to solve using the FEniCS bindings in pyMOR, I ran into problems when the operator, resulting from the equation, was applied to 0. In the equation, one divides by one of the unknown quantities, thus the operator can not be applied to the 0 element. The Newton method, as implemented in pyMOR, uses 0 when no initial guess is provided. As @sdrave pointed out, this is the case if the Newton method is called in the `apply_inverse` method. However, when solving instationary problems, it would make sense to use the solution of the former time step as initial guess. Hence, @sdrave suggested to introduce an `initial_guess`-parameter in the `apply_inverse` method.

**Comment by sdrave** [comment]
Any arguments against this, @pymor/pymor-devs, @TiKeil? This might as well be helpful for iterative linear solvers. However, one would probably have to add quite a few `initial_guess=intial_guess`s to `apply_inverse` implementations ..

**Comment by ftalbrecht** [comment]
We definitely need a means to provide an initial guess, no objections.

**Comment by pmli** [comment]
I agree, it makes sense to add `initial_guess` for iterative solvers and the use-case with solving instationary problems sounds reasonable.

**Comment by sdrave** [comment]
Ok, I will prepare a PR once #923 has been merged.
