### ISSUE TITLE
Residual norm of exactly 0 in Newton throws error

### ISSUE THREAD

**Issue by HenKlei** [pymor/pymor#927]
While designing a test case for #925, I played around with the Newton algorithm and ran into the following problem: When the norm of the residual is exactly 0, i.e. the Newton hits exactly the root of the function under consideration, the Newton produces an error due to a division by 0.

Certainly, in almost all realistic cases, hitting the exact solution is almost infeasible and my example was just a toy scenario. However, consider the following case: the 0 element could indeed be a solution to the problem the Newton is solving. In this case, when no other initial guess is provided, the Newton uses 0 as initial guess, and thus, hits the exact solution.

If there aren't any objections, I would go ahead and create a PR including the necessary checks.

**Comment by sdrave** [comment]
That would be great!
