### ISSUE TITLE
Add more tutorials

### ISSUE THREAD

**Issue by sdrave** [pymor/pymor#929]
- [x] building a reduced basis / working with `VectorArrays` (@sdrave)
- [ ] ~manually projecting a `Model` onto an RB space (@sdrave)~
- [x] creating bindings for an external solver (@renefritze)
- [x] Balanced truncation (@pmli)
- [x] MOR with ANNs (@HenKlei)

**Comment by renefritze** [comment]
At one of the last dev meetings we decided to name the rst files like "tutorial_NUMBER_SOME-TITLE". Should we just go ahead and use the listing in the first comment here to do the numbering (Starting with 2, since there is one present in master currently)? Currently concerns #984, #1001, #1007

**Comment by HenKlei** [comment]
From my point of view, the ordering above makes sense from a teaching perspective. Thus, I'm fine with the numbering.

**Comment by pmli** [comment]
I'm not sure about using numbers. I expect we would want to later add tutorials that fit somewhere in the middle, and then we would have to adjust a bunch of numbers.

Also, how about having one "Tutorial" section and each tutorial as its subsection (instead of each tutorial as a separate section)?

**Comment by sdrave** [comment]
I would say we give the documents just some name for now and fix these and their ordering in a separate PR. I guess it would also make sense to speak about the tutorials at the next dev meeting.
