### ISSUE TITLE
order of mu vector in thermal_block_problem

### ISSUE THREAD

**Issue by LeErnst** [pymor/pymor#933]
Hello,
i have implemented the error estimator from [Gianluigi Rozza et. al: Certified Reduced Basis Methods for Parametrized Partial Differential Equations, page 53] and test case was the thermal block problem. Therefore i set up the analytical problem with the `thermal_block_problem` function and I run into an issue, which has cost me days and the reason was: the order of the `mu_ij` do not coincide with the order of `fom.operator.operators[1:]` 
e.g.: `mu = {'diffusion': [[1, 2], [3, 4]]}`, `fom.operator.operators[1:][0] ` is associated with `mu_ij=3`, `fom.operator.operators[1:][1] ` is associated with `mu_ij=1`, `fom.operator.operators[1:][2] ` is associated with `mu_ij=4`, `fom.operator.operators[1:][3] ` is associated with `mu_ij=2`
It is not a big issue, but if someone wants to implement his own algorithms upon the pyMOR framework it is a surprising behavior.

**Comment by sdrave** [comment]
Hi @LeErnst, thanks for the feedback. You are right, this is unnecessarily counterintuitive and should be easy to fix. Will do that for the next release.
