### ISSUE TITLE
Generalize Max-theta approach 

### ISSUE THREAD

**Issue by TiKeil** [pymor/pymor#935]
I would like to generalize the `MaxThetaParameterFunctional` approach in order to also have an upper bound for the derivatives of the bilinear (or linear) forms. Currently we are using the  `MaxThetaParameterFunctional` for evaluating the functional

gamma_UB(mu) =  gamma_mu_bar * max{q = 1}^Q theta_q(mu)/theta_q(mu_bar)

which is used as an upper bound for the continuity of e.g.  a( u, v, mu) = sum_q theta_q(mu) a_q( u, v). We can also derive an upper bound on the continuity of the derivative 
d_mu a(u, v, mu) = sum_q (d_mu theta_q)(mu) a_q(u, v). This upper bound reads 

gamma_UB(mu) =  gamma_mu_bar * max{q = 1}^Q (d_mu theta_q)(mu)/theta_q(mu_bar).

Thus, only the numerator in the fraction is different to the above functional. With the current code, it is not possible to derive this functional from `MaxThetaParameterFunctional`. So I would like to add it and in my opinion there are two easy possibilities to incorporate it: 

1. Introduce a `BaseMaxThetaParameterFunctional(theta_denominator, theta_numerator, ... )` which enables to choose a different theta for the denominator as well as for the numerator of gamma_UB. Then, `MaxThetaParameterFunctional` would inherit from `BaseMaxThetaParameterFunctional`, but called with the same theta twice. Also, the `BaseMaxThetaParameterFunctional' could be used for any possible theta_q in the numerator and not only for the derivative of the bilinear or linear form.

2. One could hide the above described case in the `d_mu` method of `MaxThetaParameterFunctional` in the way that for each component of 'mu' a new functional with exchanged numerator is returned. However, this could potentially lead to confusion because this is not the true derivative of the functional but rather an easy way to implement the desired upper bound.

So, I would like to ask you whether this makes sense to incorporate and if, in which way. 
I prefer item 1. but I wanted to ask before I open the PR. If there exists an even better way, I am open for suggestions. @sdrave  and @ftalbrecht  , do you have thoughts on that? 

Cheers, Tim

**Comment by sdrave** [comment]
I would perfer 1. as well. BTW, could there also be a `BaseMinMaxThetaParameterFunctional`?

**Comment by TiKeil** [comment]
Yes this is ofc doable. But I don't know whether that would help too much. Probably would reduce lines of code but one has to be careful in terms of conditions for the thetas and also some mechanism for the different evaluation of the max or min would be required.
Moreover, I think that exchanging numerator for `MinThetaParameterFunctional ` is not really of interest.

**Comment by sdrave** [comment]
Agreed.

**Comment by ftalbrecht** [comment]
agreed, go ahead with 1

**Comment by TiKeil** [comment]
Done in #952
