### ISSUE TITLE
General "Log_once" facility?

### ISSUE THREAD

**Issue by renefritze** [pymor/pymor#951]
I want to warn the user that need to manually save the widget state via notebook UI for the 2js visualization to work after a kernel restart. I feel like printing a message on every display of a plot would be a too much. I'd rather only do that once an interpreter session.

One (somewhat hacky) solution would be to just log unconditionally in the module, so it gets executed (once) on import.

Or we'd implement a more general and controllable solution via the logger module.

Anybody think that would be useful?

**Comment by sdrave** [comment]
Not sure if there are other places we would need this. We use `warnings` in a few places for similar functionality.

For your use case: Maybe it would be an option, to display the text in the widget when the state has not been saved?

**Comment by renefritze** [comment]
I cannot seem to be able to tell from python whether the state has been saved. Alternatively if I had a way to check whether the notebook is trusted, that would suffice as well. I did manage to r[eliably make the widget state be saved ](https://github.com/pymor/pymor/commit/733dbefcec6e4b7cba64958d98c95d3cf6957571) after a visualization is "ready", but that ofc only works if the notebook is trusted (ie. injected JS is executed).
