### ISSUE TITLE
apply_inverse of BlockOperator

### ISSUE THREAD

**Issue by lbalicki** [pymor/pymor#957]
I am currently working with a 2x2 `BlockOperator` where every block is a `NumpyMatrixOperator`. When calling `apply_inverse` on the block operator the `lgmres` method is called. However, executing `NumpyMatrixOperator(to_matrix(block_operator)).apply_inverse` is a bit faster, which makes me think that it might be of interest to implement a different approach for the `apply_inverse` method of a `BlockOperator`. I have the following approaches in mind:
1. Implement `class NumpyBlockOperator(BlockOperator)` where the block matrix is essentially treated as a regular `NumpyMatrixOperator`
2. Implement `class NumpyBlockOperator(BlockOperator)` where `apply_inverse` uses an external (e.g. [HSL](http://www.hsl.rl.ac.uk/) based) library
3. Implement a generic `apply_inverse` for `BlockOperator` based on the Schur complement (might be very inefficient for most structures)
4. Stick to `lgmres` and implement a block preconditioner (probably difficult to outperform first option with this)

I assume 1. will yield the best results, however I would be interested in hearing some other opinions. Is there maybe a better approach and would it be of interest to have this in pyMOR?

**Comment by renefritze** [comment]
I'm not familiar with HSL, but generally approach 2. sounds to me as a good way to experiment with different preconditioners/solvers w/o having to implement them yourself. And I guess it would contain option 1 as a special case.

**Comment by drittelhacker** [comment]
"2." seems like a very good choice for specializations. I guess the case you have in mind is  (Navier-)Stokes or KKT type saddle point systems (due to the HSL mention) 
Other 2x2 structures that come to mind are companion form linearizations of second order ODEs or explicit representations of error systems in the LTI case. They would require rather different treatment. In that sense "1." would be more generic and, thus, better suited for the general case.
"3." would be good for the error system case, i.e. when one diagonal block is far larger than the other, i.e. one is FOM sized and one ROM sized. Then the Schur-complement is actually a low-rank update and could be treated by Sherman-Morrison.
"4." can be very powerful when you have a good preconditioner. Again NSE with block diagonal preconditoners with a Schur-complement approximation  in the lower-right have been shown to be good and especially give grid independent peformance (i.e. essentially constant iteration numbers)

**Comment by drittelhacker** [comment]
In case of "2." also [SyLVER](https://github.com/NLAFET/Sylver) should be a rather fast option. In presentations, the [NLAFET team](http://www.nlafet.eu/) (See also [here](https://github.com/NLAFET/)) claims it is around 2x faster than the fastest HSL routines.Also SyLVER is BSD (3-clause) licensed while most of HSL is proprietary with an "academic free" option.

**Comment by lbalicki** [comment]
I will try to implement "1." and "2." then and try to see what backends work well in my case. The reason i suggested something based on HSL is because they have some methods for [saddle point systems](http://www.hsl.rl.ac.uk/catalogue/hsl_mi27.html). Also I will check which preconditioners work well, maybe there is something that can be added to pyMOR in the future.

**Comment by pmli** [comment]
I'm worried about adding dependencies. Which licenses do these projects use? When I tried to download the HSL code, it asks if I want a personal academic or a commercial license, which doesn't sound like it would be easy to integrate here. On the other hand, SyLVER uses a BSD 3-clause license. There is also the question of the maintenance burden and if it's worth it for a non-generic solver. It doesn't seem like these projects provide Python wrappers.

Something like 1. would be good to have. In particular, if the blocks are `NumpyOperators` with dense NumPy arrays, then forming the bigger NumPy array is probably the best option. Things get more complicated when some blocks are sparse or special operators such as `IdentityOperator` or `ZeroOperator`. The question is whether to have a new class for this or handle everything in `BlockOperator.apply_inverse` (or something else I can't think of).

Concerning the second-order model use case, it would be nice to have something generic like 3. to remove `SecondOrderModelOperator` and `ShiftedSecondOrderModelOperator`. I had been thinking about it, but I'm not sure if it can be done as efficiently.

@drittelhacker What do you mean by error system case? Those are just block-diagonal matrices, right? Right now, they are (more or less) nicely handled with the `BlockDiagonalOperator`.

**Comment by drittelhacker** [comment]
Then ignore my comment about that.

**Comment by lbalicki** [comment]
@pmli I agree that it looks tricky to use these external solvers due to their licenses and the lack of Python interfaces. One option could also be to check the structure and types of the blocks in `BlockOperator.__init__` and then return an instance of a specialization of `BlockOperator` which is able to handle `apply_inverse` efficiently with respect to the underlying block structure. Maybe this would make things a bit too complicated though.

**Comment by sdrave** [comment]
So, I am no expert here, but a few comments:

- Before thinking about adding some fancy algorithm, we should think about the actual use cases for the algorithm. For instance, for large sparse systems, e.g. NSE, I would expect an efficient solver to be available in the backend from where the blocks of the operator are coming.

- For blocks of dense `NumpyOperators`, we should first have an application in mind where 1. isn't good enough.

- Option 4 might be interesting in view of solving problems with complex shift as as real system, independent from the backend the blocks are coming from. So this would be most interesting to me, and hopefully to the Magdeburg guys as well ..

- Regarding 1. I would consider implementing `apply_inverse` of `BlockOperator` and treating this as a special case. If you subclass, you need to ensure that the right class is used everywhere, and I do not see a lot of benefit in having a specialized class at the moment.

- Regarding lgmres, be aware that the default tolerance for `lgrmes` is only 1e-5.

**Comment by pmli** [comment]
Was this fixed in #1662?

**Comment by lbalicki** [comment]
Yes, #1662 fixes this (at least for the scenario which I was interested in originally).
