### ISSUE TITLE
[jupyter-visualization] Document how to store widget states

### ISSUE THREAD

**Issue by TiKeil** [pymor/pymor#958]
If one wants to store a jupyter-notebook including all figures, it is currently not trivially possible to do it with the new visualization because the widget state gets lost. According to @renefritze this is easy to achieve.

Thus, we discussed that we should document how this is possible.

**Comment by renefritze** [comment]
Isn't this included in  #951 already?

**Comment by TiKeil** [comment]
True ! Sorry
