### ISSUE TITLE
Check tolerance in `gram_schmidt_biorth`

### ISSUE THREAD

**Issue by renefritze** [pymor/pymor#964]
So hypothesis just generated a failing case for the `test_gram_schmidt_biorth` function (`@reproduce_failure('5.10.5', b'AXicE2ZAAr8AAhIBDg==')`).  The difference array of `np.eye` and the dot of the orthogonalized vectors had values outside `np.allclose` default `atol=1e-8`. I've changed the test in 9166cafd6e3cc58ad8bd52099e59b738b4987cc6 to use the default `check_tol=1e-3` of `test_gram_schmidt_biorth`, but since this seems a rather high tolerance to me, I wanted to make sure this isn't fishy.

**Comment by pmli** [comment]
I would expect `gram_schmidt_biorth` to be inaccurate when `V.inner(W, product)` is close to being singular. Could you extract the data that fails the test?

**Comment by renefritze** [comment]
If you run the test after adding the `reproduce_failure` decorator (in the hypothesis2 branch only currently, with hypothesis 5.10.5 installed) you'll get the exact setup.

**Comment by pmli** [comment]
Thanks, here is the data (real, 19x19 matrices): [V.txt](https://github.com/pymor/pymor/files/4818689/V.txt), [W.txt](https://github.com/pymor/pymor/files/4818690/W.txt)

Here are the condition numbers of `V`, `W`, and `V.inner(W)`:
```python
>>> import numpy as np
>>> from pymor.basic import *
>>> V = NumpyVectorSpace(19).from_numpy(np.loadtxt('V.txt'))
>>> W = NumpyVectorSpace(19).from_numpy(np.loadtxt('W.txt'))
>>> np.linalg.cond(V.to_numpy())
424.99194473780267
>>> np.linalg.cond(W.to_numpy())
447.20371185057945
>>> np.linalg.cond(V.inner(W))
17274.62305715314
```

It seems like the condition number of `V` and `W` gets multipied by the condition number of `V.inner(W)` after `gram_schmidt_biorth`:
```python
>>> V2, W2 = gram_schmidt_biorth(V, W)
01:19 gram_schmidt_biorth: Projecting vector W[14] again
>>> np.linalg.cond(V2.to_numpy())
4361612.0617999025
>>> np.linalg.cond(W2.to_numpy())
4361613.670242904
>>> np.max(np.abs(V2.inner(W2) - np.eye(19)))
6.004121063953887e-06
```

The accuracy of the order `1e-6` is consistent with the condition number of `V2` (or `W2`).

On the other hand, first orthonormalizing doesn't seem to help:

```python
>>> V0 = gram_schmidt(V)
11:33 gram_schmidt: Orthonormalizing vector 17 again
>>> W0 = gram_schmidt(W)
11:39 gram_schmidt: Orthonormalizing vector 14 again
11:39 gram_schmidt: Orthonormalizing vector 15 again
>>> np.linalg.cond(V0.to_numpy())
1.000000000000002
>>> np.linalg.cond(W0.to_numpy())
1.0000000000000013
>>> np.linalg.cond(V0.inner(W0))
1.000000000000002
>>> V02, W02 = gram_schmidt_biorth(V0, W0)
>>> np.linalg.cond(V02.to_numpy())
4361614.732212511
>>> np.linalg.cond(W02.to_numpy())
4361612.424933026
>>> np.max(np.abs(V02.inner(W02) - np.eye(19)))
5.252089384176379e-06
```

It looks like the issue can still be detected when looking at condition numbers of submatrices of `V0.inner(W0)`:
```python
>>> for i in range(1, 20):
...     print(f'{i:2d}, {np.linalg.cond(V0.inner(W0)[:i, :i]):.3e}, {np.max(np.abs(V02.inner(W02)[:i, :i] - np.eye(i))):.3e}')
... 
 1, 1.000e+00, 4.441e-16
 2, 1.586e+00, 1.123e-15
 3, 1.576e+00, 1.673e-15
 4, 1.859e+00, 1.673e-15
 5, 1.755e+00, 1.673e-15
 6, 2.141e+00, 2.187e-15
 7, 1.946e+00, 2.187e-15
 8, 1.668e+00, 3.346e-15
 9, 1.787e+00, 3.346e-15
10, 1.944e+00, 3.346e-15
11, 2.048e+00, 4.587e-15
12, 3.196e+00, 4.587e-15
13, 3.605e+00, 4.587e-15
14, 2.229e+00, 4.587e-15
15, 3.969e+00, 4.587e-15
16, 5.015e+00, 4.587e-15
17, 1.558e+06, 2.535e-10
18, 5.935e+00, 2.535e-10
19, 1.000e+00, 5.252e-06
```

Maybe it makes sense to use `np.linalg.cond(V2.to_numpy())` when choosing the tolerance, but I'm not aware of an error analysis that would justify this...

**Comment by renefritze** [comment]
I guess somewhat related, at least in the direction of near singular input, this fails the `test_method_of_snapshots`:
`
pytest_1        | Falsifying example: test_method_of_snapshots(
pytest_1        |     vector_array=NumpyVectorArray(
pytest_1        |         [[2.50355282e-06 1.00142117e-13]
pytest_1        |          [1.00142117e-13 1.00142117e-13]],
pytest_1        |         NumpyVectorSpace(2)),
pytest_1        |     method=<function pymor.algorithms.svd_va.method_of_snapshots>,
pytest_1        | )

@reproduce_failure('5.10.5', b'AAACAAIBAAAAAAKgCtb9AAAAAAAAAAHDAA==')
`
I've switched the input for now: https://github.com/pymor/pymor/pull/910/commits/8833bd1080dbac1b7988551e266b22c63c51ca0f

**Comment by pmli** [comment]
I wanted to check my suspicion about subspace angles. Indeed, the following code

```python
import numpy as np
import scipy.linalg as spla
import matplotlib.pyplot as plt

V = np.loadtxt('V.txt').T
W = np.loadtxt('W.txt').T
n = V.shape[1]
angles = np.array([np.rad2deg(spla.subspace_angles(V[:, :k], W[:, :k]).max())
                   for k in range(1, n)])
print(list(zip(range(1, n), angles)))

fig, ax = plt.subplots()
ax.plot(range(1, n), angles, '.-')
ax.plot([1, n - 1], [90, 90])
ax.set_xlabel('$k$')
ax.set_xticks(range(1, n))
ax.set_title('The largest angle between the first $k$ columns of $V$ and $W$')
plt.show()
```

gives

```python
[(1, 86.5911951932524),
 (2, 65.78033310145457),
 (3, 56.29827163702535),
 (4, 60.8877933563386),
 (5, 58.32815919159246),
 (6, 64.47586812735175),
 (7, 59.453172569681364),
 (8, 53.5432624407251),
 (9, 55.983344538097555),
 (10, 59.050921680560265),
 (11, 60.765554728747745),
 (12, 71.7688593691452),
 (13, 73.89655433381843),
 (14, 63.33772774424632),
 (15, 75.40517278182455),
 (16, 78.49867606399204),
 (17, 89.99996323812871),
 (18, 80.30029768968369)]

```

and

![angles](https://user-images.githubusercontent.com/1268421/97617752-74738180-1a1e-11eb-90f6-7729466eb40f.png)

**Comment by pmli** [comment]
I think, if we decide to test `gram_schmidt_biorth` in some clever way using `hypothesis`, the same should be done for [linear solver tests](https://github.com/pymor/pymor/blob/53aabbfe0cd3eb418510277461264117ac29ddd1/src/pymortests/solver.py).

**Comment by renefritze** [comment]
What did we decide to do for this ticket and the impending release?

**Comment by pmli** [comment]
We could discuss between accepting the fix you mentioned in the first comment of this issue (using the same tolerance for the (bi)orthogonality check as in `gram_schmidt(_biorth`)) or adapting the tolerance based on error analysis (which doesn't exist, AFAIK). Either way, I guess we should postpone this.

**Comment by pmli** [comment]
Another option could be not testing `gram_schmidt_biorth` with `hypothesis`, but with a few fixed examples, because the error analysis still doesn't exist.

**Comment by sdrave** [comment]
I think the very least we should do is to add some documentation which discusses the accuracy of the algorithm. It is clear that the input has to satisfy some property for the algorithm to succeed (orthogonal spaces won't work). So we could have an informal discussion that the accuracy of the algorithm will depend on the angles between the spaces. - Would it be possible to compute the angles only using the `VectorArray` interface? If yes (and I would think so), this might be a heuristic we might want to add to the algorithm in order to generate accuracy warnings.
