### ISSUE TITLE
Add a policy for deprecations

### ISSUE THREAD

**Issue by renefritze** [pymor/pymor#967]
I just stumbled over https://github.com/pymor/pymor/blob/master/src/pymor/algorithms/pod.py#L71

This (and others, haven't looked) clearly should not be in the library forever. I think we should document a clear target for removal (at the time of adding!) and run these down as part of our (post) release checklist.

**Comment by sdrave** [comment]
I would say:

- All deprecations need to be mentioned in the release notes.
- Directly after each release all deprecated features are removed.

**Comment by sdrave** [comment]
@renefritze, add an entry to the release checklist and then close this?
