### ISSUE TITLE
New Sphinx theme

### ISSUE THREAD

**Issue by renefritze** [pymor/pymor#971]
You can see the theme we talked about in the meeting here: https://gh-docs.pymor.org/sphinx-theme/

Everybody should have a look and see if there are things left to tweak.

**Comment by renefritze** [comment]
1. Get rid of the the Github info line
 2. Wider 1st col in Method/Attrib lists
 3. Replace the wrench icon. With what though?

**Comment by HenKlei** [comment]
>     3. Replace the wrench icon. With what though?

What about the pyMOR logo?

**Comment by HenKlei** [comment]
This "Show Source" on the right at the top is very counterintuitive, I think. When clicking on that one, I would assume that I get redirected to some folder or file in the GitHub repository. What do you think about removing that one? I think it does not really help anyone that is looking at the documentation.

**Comment by renefritze** [comment]
> What about the pyMOR logo?

Heh, forgot about that. Good point!



> This "Show Source"

Yeah, I would've expected this to work like "edit on GitHub". Which I think can be useful, but wouldn't need to be featured that prominently.

**Comment by sdrave** [comment]
>  Get rid of the the Github info line

I think it would be nice to keep the Github icon to quickly get to the repo.

> Wider 1st col in Method/Attrib lists

Yes.

>  Replace the wrench icon. With what though?

I agree to put the logo there.

>   >  This "Show Source"

> Yeah, I would've expected this to work like "edit on GitHub". Which I think can be useful, but wouldn't need to be featured that prominently.

Yes.

Futhermore:

- Should the text column be a little bit wider? At least this would make the code in tutorial 1 more readable.

- I really dislike that in the API docs Parameters/Returns/Methods/Attributes is more strongly highlighted than the functions/classes they belong to. This is already a problem with our current theme but here it is more pronounced. Not sure how to solve this though. At least one could try increaseing the font size or making it bold.

**Comment by renefritze** [comment]
> * I really dislike that in the API docs Parameters/Returns/Methods/Attributes is more strongly highlighted than the functions/classes they belong to. This is already a problem with our current theme but here it is more pronounced. Not sure how to solve this though. At least one could try increaseing the font size or making it bold.

That's referencing the box's header text, right? Then I agree, that's disproportionate with the rest.

**Comment by sdrave** [comment]
> That's referencing the box's header text, right? Then I agree, that's disproportionate with the rest.

Not sure what you mean by 'box'. Let's take the `adaptivegreedy` module. Here I would assume that
```
class pymor.algorithms.adaptivegreedy.AdaptiveSampleSet(parameter_space)
```
has more visual highlight than `Methods`.

**Comment by renefritze** [comment]
![Screenshot_20200630_121549](https://user-images.githubusercontent.com/47802/86115026-a2c26e00-bacb-11ea-91c7-dc17003c2f0b.png)
 That's the box I mean.

**Comment by sdrave** [comment]
Yes, but even if you make the header of the box smaller, the entire box still looks very prominent. I would go with trying to make the class/function signatures more prominent.

**Comment by pmli** [comment]
I would add two more issues:

4. It is more difficult to distinguish between section, subsections, and subsubsection in this style

![sphinx_sections](https://user-images.githubusercontent.com/1268421/86123291-7d3c6100-bad9-11ea-8b77-57c16f2fce3b.png)

5. When looking at the API documentation of a pyMOR subpackage (e.g., `pymor.algorithms`), this style does not show the submodules on the left

![sphinx_toc](https://user-images.githubusercontent.com/1268421/86123135-48c8a500-bad9-11ea-8568-2d3b23a5ef15.png)

**Comment by sdrave** [comment]
> 4. It is more difficult to distinguish between section, subsections, and subsubsection in this style

I find that acceptable.

> 5. When looking at the API documentation of a pyMOR subpackage (e.g., pymor.algorithms), this style does not show the submodules on the left

I think that really needs fixing.

**Comment by sdrave** [comment]
So we need the new theme to have a version picker on github pages. So I would vote for merging this once the most pressing issues have been fixed. From my point of view this would be the listing of subpackages (which is probably controlled by some sphinx option) and the column widths.

**Comment by sdrave** [comment]
Regarding '5.', setting `globaltoc_depth` to 5 seems like a good compromise (although I did not test on mobile ..)

**Comment by sdrave** [comment]
So I tried to adust the widths of the tables via CSS, but it doesn't work: on page load, the layout is as desired for a fraction of a second but then seems to get reset (by some javascript?). I am giving up now, as I don't even know where to start looking for relevant documentation. Is anybody else willing to look into it? Otherwise should look for another theme.

**Comment by renefritze** [comment]
@HenKlei managed to do the adjustments live in browser and sent me what he did. I didn't have time to try those adjustments yet though. 

I don't think we should be looking for another theme either way. If adjustment via custom templates doesn't work we can still hard fork the theme.

**Comment by sdrave** [comment]
> @HenKlei managed to do the adjustments live in browser and sent me what he did. I didn't have time to try those adjustments yet though.

This works for me as well. Only when I write them in a css file, it doesn't work. I am not saying that I really understand what is going on, but it feels like somewhere the widths of the table is dynamically reset and I have no idea what cases it and how to customize it.

> I don't think we should be looking for another theme either way. If adjustment via custom templates doesn't work we can still hard fork the theme.

Yes, but even then I would have no idea what to do.

**Comment by renefritze** [comment]
This is not live for release + master
