### ISSUE TITLE
Remove labels

### ISSUE THREAD

**Issue by sdrave** [pymor/pymor#975]
As discussed during the last dev meeting, most labels are never used or are used for personal issue collections. Furthermore, for many labels there are diverging definitions of how they should be applied. Thus, I propose to remove most labels:

* Remove:
  * algorithms
  * bindings
  * builtin-models
  * dev-meeting
  * docs
  * generic-objects
  * implementation
  * interfaces
  * rb
  * sys-mor
  * testing

* Keep:
  * automerge
  * backport
  * bug
  * management
  * type:change
  * type:fix
  * type:new-feature
  * type:removal

Furthermore, I would drop the `type:` prefix. The `bug` label should be applied to issues whereas all the `type:...` labels should only be applied to PRs.

Other opinions, @pymor/pymor-devs?

**Comment by pmli** [comment]
The remove/keep lists look good to me. I guess only the `buildsystem` and `type:deprecation` labels are missing?

I like that `type:` labels are grouped together when sorted alphabetically in the labels dropdown menu. How about replacing `type:` with `pr:` to make it more explicit where it should be used?

**Comment by renefritze** [comment]
Rather than dropping the `type` prefix why not make it explicit that those only get applied to PR and use a `pr` prefix instead?

**Comment by ftalbrecht** [comment]
sounds good

**Comment by sdrave** [comment]
Ok, so we seem to agree on the following labels:

-  automerge
-  backport
-  buildsystem
-  bug
-  management
-  pr:change
-  pr:fix
-  pr:new-feature
-  pr:removal
-  pr:deprecation

Maybe 'buildsystem' should be renamed to something which includes ci?

**Comment by renefritze** [comment]
I didn't read @pmli as wanting to keep buildsystem. I do not.

**Comment by sdrave** [comment]
Ok, maybe not 'buildsystem', but maybe 'ci'? The idea would be that 'management' and 'ci' issues/prs usually should not got into the release notes. Or we could remove both.

**Comment by renefritze** [comment]
If we're keeping it, how about calling it infrastructure?

**Comment by sdrave** [comment]
Ok, so I will rename buildsystem to infrastructure and keep it along with management. Any objections?

**Comment by pmli** [comment]
Sounds good to me.

**Comment by sdrave** [comment]
Done.

**Comment by renefritze** [comment]
Should we still document label usage (in CONTRIBUTING.md)?
