### ISSUE TITLE
Move defaultimpl.py into interfaces.py in discretizers/builtin/grids?

### ISSUE THREAD

**Issue by pmli** [pymor/pymor#987]
It seems that `ConformalTopologicalGridDefaultImplementations`/`ReferenceElementDefaultImplementations`/`AffineGridDefaultImplementations` could be merged into `ConformalTopologicalGrid`/`ReferenceElement`/`AffineGrid` without issues.

**Comment by sdrave** [comment]
I think the idea was to make the interface classes more readable. But I agree, merging these classes will make everything easier to understand.
