### ISSUE TITLE
Inconsistencies in class naming

### ISSUE THREAD

**Issue by pmli** [pymor/pymor#989]
Here are examples of classes inheriting from `SomeInterface` and not called `...SomeInterface` (except `Operator` -> `Functional` and `VectorArray` -> `VectorArrayView`):

- `VectorSpace` (similar for `VectorArray`)
    - [`MPIVectorSpaceNoComm`](https://github.com/pymor/pymor/blob/c38840e05206990ba807887eeb10494f03b73453/src/pymor/vectorarrays/mpi.py#L252)
    - [`MPIVectorSpaceAutoComm`](https://github.com/pymor/pymor/blob/c38840e05206990ba807887eeb10494f03b73453/src/pymor/vectorarrays/mpi.py#L312)
- `Operator`
    - [`LinearAdvectionLaxFriedrichs`](https://github.com/pymor/pymor/blob/c38840e05206990ba807887eeb10494f03b73453/src/pymor/discretizers/builtin/fv.py#L448)
    - [`Concatenation`](https://github.com/pymor/pymor/blob/c38840e05206990ba807887eeb10494f03b73453/src/pymor/operators/constructions.py#L275)
    - [`ComponentProjection`](https://github.com/pymor/pymor/blob/c38840e05206990ba807887eeb10494f03b73453/src/pymor/operators/constructions.py#L629)

Should we rename some of them?

**Comment by HenKlei** [comment]
I remember that @sdrave planned (or at least mentioned that it would be a good idea) to change the operator names to be more consistent.

**Comment by pmli** [comment]
Yes, this continues the discussion from @sdrave's comment https://github.com/pymor/pymor/pull/923#issuecomment-633632873

**Comment by sdrave** [comment]
I believe, we haven't come to a conclusion so far?

**Comment by pmli** [comment]
Yes, we didn't.

**Comment by HenKlei** [comment]
Personally, I would prefer to append `Operator` to each of these names. To me, that makes it a bit more clear what kind of object one is dealing with.

**Comment by sdrave** [comment]
I would keep the names of the `VectorSpaces` append `Operator` to the few ones that don't have it in their name. Agreed, @pymor/pymor-devs?

**Comment by pmli** [comment]
Sounds good to me.
